; Problem description
; This file describes the example input from the problem statement
(define (problem pb1)
  (:metric minimize (total-cost))
  (:domain CS170)
(:objects TA_X_b_i_r_t_h_d_a_y TA_X_f_e_a_r_l_e_s_s TA_X_a_b_s_o_r_b TA_X_n_i_m_b_l_e TA_X_u_s_e TA_X_t_e_n_t TA_X_w_o_r_s_h_i_p TA_X_u_n_u_s_e_d TA_X_s_p_r_e_a_d TA_X_k_n_o_t TA_X_d_i_f_f_e_r TA_X_s_e_l_f_i_s_h TA_X_s_p_i_l_l TA_X_v_o_l_l_e_y_b_a_l_l TA_X_a_n_g_r_y TA_X_a_t_t_a_c_k TA_X_i_m_p_e_n_d TA_X_s_e_p_a_r_a_t_e TA_X_i_m_i_t_a_t_e TA_X_s_c_i_e_n_t_i_f_i_c TA_X_t_e_e_n_y TA_X_b_a_n_g TA_X_j_o_k_e TA_X_c_o_m_p_e_t_e TA_X_a_i_r_p_l_a_n_e X_b_i_r_t_h_d_a_y X_f_e_a_r_l_e_s_s X_a_b_s_o_r_b X_n_i_m_b_l_e X_u_s_e X_t_e_n_t X_w_o_r_s_h_i_p X_u_n_u_s_e_d X_s_p_r_e_a_d X_k_n_o_t X_d_i_f_f_e_r X_s_e_l_f_i_s_h X_s_p_i_l_l X_v_o_l_l_e_y_b_a_l_l X_a_n_g_r_y X_a_t_t_a_c_k X_i_m_p_e_n_d X_s_e_p_a_r_a_t_e X_i_m_i_t_a_t_e X_s_c_i_e_n_t_i_f_i_c X_t_e_e_n_y X_b_a_n_g X_j_o_k_e X_c_o_m_p_e_t_e X_a_i_r_p_l_a_n_e X_b_a_d_g_e X_c_o_n_s_o_r_t X_p_h_y_s_i_c_a_l X_p_e_r_i_s_h X_a_b_s_e_n_t X_m_u_t_e X_b_o_u_n_d_l_e_s_s X_o_c_e_a_n_i_c X_d_o_g X_n_e_e_d X_g_a_i_n_f_u_l X_e_v_a_n_e_s_c_e_n_t X_i_n_q_u_i_r_e X_l_i_n_e X_z_i_p_p_e_r X_h_i X_b_y_e X_y_o_u X_a_r_e X_a_m_a_z_i_n_g X_w_h_y X_t_h_e_r_e X_i_s X_t_o_p X_b_o_t_t_o_m )
(:init(= (total-cost) 0)
( Car_At X_b_i_r_t_h_d_a_y )
(InCar TA_X_b_i_r_t_h_d_a_y)
(InCar TA_X_f_e_a_r_l_e_s_s)
(InCar TA_X_a_b_s_o_r_b)
(InCar TA_X_n_i_m_b_l_e)
(InCar TA_X_u_s_e)
(InCar TA_X_t_e_n_t)
(InCar TA_X_w_o_r_s_h_i_p)
(InCar TA_X_u_n_u_s_e_d)
(InCar TA_X_s_p_r_e_a_d)
(InCar TA_X_k_n_o_t)
(InCar TA_X_d_i_f_f_e_r)
(InCar TA_X_s_e_l_f_i_s_h)
(InCar TA_X_s_p_i_l_l)
(InCar TA_X_v_o_l_l_e_y_b_a_l_l)
(InCar TA_X_a_n_g_r_y)
(InCar TA_X_a_t_t_a_c_k)
(InCar TA_X_i_m_p_e_n_d)
(InCar TA_X_s_e_p_a_r_a_t_e)
(InCar TA_X_i_m_i_t_a_t_e)
(InCar TA_X_s_c_i_e_n_t_i_f_i_c)
(InCar TA_X_t_e_e_n_y)
(InCar TA_X_b_a_n_g)
(InCar TA_X_j_o_k_e)
(InCar TA_X_c_o_m_p_e_t_e)
(InCar TA_X_a_i_r_p_l_a_n_e)
(Path X_b_i_r_t_h_d_a_y X_f_e_a_r_l_e_s_s )
(Path X_f_e_a_r_l_e_s_s X_b_i_r_t_h_d_a_y )
(= (Distance X_b_i_r_t_h_d_a_y X_f_e_a_r_l_e_s_s )2)
(= (Distance X_f_e_a_r_l_e_s_s X_b_i_r_t_h_d_a_y )2)

(Path X_f_e_a_r_l_e_s_s X_a_b_s_o_r_b )
(Path X_a_b_s_o_r_b X_f_e_a_r_l_e_s_s )
(= (Distance X_f_e_a_r_l_e_s_s X_a_b_s_o_r_b )3)
(= (Distance X_a_b_s_o_r_b X_f_e_a_r_l_e_s_s )3)

(Path X_a_b_s_o_r_b X_n_i_m_b_l_e )
(Path X_n_i_m_b_l_e X_a_b_s_o_r_b )
(= (Distance X_a_b_s_o_r_b X_n_i_m_b_l_e )1)
(= (Distance X_n_i_m_b_l_e X_a_b_s_o_r_b )1)

(Path X_n_i_m_b_l_e X_u_s_e )
(Path X_u_s_e X_n_i_m_b_l_e )
(= (Distance X_n_i_m_b_l_e X_u_s_e )1)
(= (Distance X_u_s_e X_n_i_m_b_l_e )1)

(Path X_u_s_e X_t_e_n_t )
(Path X_t_e_n_t X_u_s_e )
(= (Distance X_u_s_e X_t_e_n_t )2)
(= (Distance X_t_e_n_t X_u_s_e )2)

(Path X_t_e_n_t X_w_o_r_s_h_i_p )
(Path X_w_o_r_s_h_i_p X_t_e_n_t )
(= (Distance X_t_e_n_t X_w_o_r_s_h_i_p )2)
(= (Distance X_w_o_r_s_h_i_p X_t_e_n_t )2)

(Path X_w_o_r_s_h_i_p X_u_n_u_s_e_d )
(Path X_u_n_u_s_e_d X_w_o_r_s_h_i_p )
(= (Distance X_w_o_r_s_h_i_p X_u_n_u_s_e_d )5)
(= (Distance X_u_n_u_s_e_d X_w_o_r_s_h_i_p )5)

(Path X_u_n_u_s_e_d X_s_p_r_e_a_d )
(Path X_s_p_r_e_a_d X_u_n_u_s_e_d )
(= (Distance X_u_n_u_s_e_d X_s_p_r_e_a_d )4)
(= (Distance X_s_p_r_e_a_d X_u_n_u_s_e_d )4)

(Path X_s_p_r_e_a_d X_k_n_o_t )
(Path X_k_n_o_t X_s_p_r_e_a_d )
(= (Distance X_s_p_r_e_a_d X_k_n_o_t )1)
(= (Distance X_k_n_o_t X_s_p_r_e_a_d )1)

(Path X_k_n_o_t X_d_i_f_f_e_r )
(Path X_d_i_f_f_e_r X_k_n_o_t )
(= (Distance X_k_n_o_t X_d_i_f_f_e_r )1)
(= (Distance X_d_i_f_f_e_r X_k_n_o_t )1)

(Path X_d_i_f_f_e_r X_s_e_l_f_i_s_h )
(Path X_s_e_l_f_i_s_h X_d_i_f_f_e_r )
(= (Distance X_d_i_f_f_e_r X_s_e_l_f_i_s_h )1)
(= (Distance X_s_e_l_f_i_s_h X_d_i_f_f_e_r )1)

(Path X_s_e_l_f_i_s_h X_s_p_i_l_l )
(Path X_s_p_i_l_l X_s_e_l_f_i_s_h )
(= (Distance X_s_e_l_f_i_s_h X_s_p_i_l_l )1)
(= (Distance X_s_p_i_l_l X_s_e_l_f_i_s_h )1)

(Path X_s_p_i_l_l X_v_o_l_l_e_y_b_a_l_l )
(Path X_v_o_l_l_e_y_b_a_l_l X_s_p_i_l_l )
(= (Distance X_s_p_i_l_l X_v_o_l_l_e_y_b_a_l_l )1)
(= (Distance X_v_o_l_l_e_y_b_a_l_l X_s_p_i_l_l )1)

(Path X_v_o_l_l_e_y_b_a_l_l X_a_n_g_r_y )
(Path X_a_n_g_r_y X_v_o_l_l_e_y_b_a_l_l )
(= (Distance X_v_o_l_l_e_y_b_a_l_l X_a_n_g_r_y )1)
(= (Distance X_a_n_g_r_y X_v_o_l_l_e_y_b_a_l_l )1)

(Path X_a_n_g_r_y X_a_t_t_a_c_k )
(Path X_a_t_t_a_c_k X_a_n_g_r_y )
(= (Distance X_a_n_g_r_y X_a_t_t_a_c_k )3)
(= (Distance X_a_t_t_a_c_k X_a_n_g_r_y )3)

(Path X_a_t_t_a_c_k X_i_m_p_e_n_d )
(Path X_i_m_p_e_n_d X_a_t_t_a_c_k )
(= (Distance X_a_t_t_a_c_k X_i_m_p_e_n_d )2)
(= (Distance X_i_m_p_e_n_d X_a_t_t_a_c_k )2)

(Path X_i_m_p_e_n_d X_s_e_p_a_r_a_t_e )
(Path X_s_e_p_a_r_a_t_e X_i_m_p_e_n_d )
(= (Distance X_i_m_p_e_n_d X_s_e_p_a_r_a_t_e )2)
(= (Distance X_s_e_p_a_r_a_t_e X_i_m_p_e_n_d )2)

(Path X_s_e_p_a_r_a_t_e X_i_m_i_t_a_t_e )
(Path X_i_m_i_t_a_t_e X_s_e_p_a_r_a_t_e )
(= (Distance X_s_e_p_a_r_a_t_e X_i_m_i_t_a_t_e )1)
(= (Distance X_i_m_i_t_a_t_e X_s_e_p_a_r_a_t_e )1)

(Path X_i_m_i_t_a_t_e X_s_c_i_e_n_t_i_f_i_c )
(Path X_s_c_i_e_n_t_i_f_i_c X_i_m_i_t_a_t_e )
(= (Distance X_i_m_i_t_a_t_e X_s_c_i_e_n_t_i_f_i_c )4)
(= (Distance X_s_c_i_e_n_t_i_f_i_c X_i_m_i_t_a_t_e )4)

(Path X_s_c_i_e_n_t_i_f_i_c X_t_e_e_n_y )
(Path X_t_e_e_n_y X_s_c_i_e_n_t_i_f_i_c )
(= (Distance X_s_c_i_e_n_t_i_f_i_c X_t_e_e_n_y )2)
(= (Distance X_t_e_e_n_y X_s_c_i_e_n_t_i_f_i_c )2)

(Path X_t_e_e_n_y X_b_a_n_g )
(Path X_b_a_n_g X_t_e_e_n_y )
(= (Distance X_t_e_e_n_y X_b_a_n_g )5)
(= (Distance X_b_a_n_g X_t_e_e_n_y )5)

(Path X_b_a_n_g X_j_o_k_e )
(Path X_j_o_k_e X_b_a_n_g )
(= (Distance X_b_a_n_g X_j_o_k_e )2)
(= (Distance X_j_o_k_e X_b_a_n_g )2)

(Path X_j_o_k_e X_c_o_m_p_e_t_e )
(Path X_c_o_m_p_e_t_e X_j_o_k_e )
(= (Distance X_j_o_k_e X_c_o_m_p_e_t_e )8)
(= (Distance X_c_o_m_p_e_t_e X_j_o_k_e )8)

(Path X_c_o_m_p_e_t_e X_a_i_r_p_l_a_n_e )
(Path X_a_i_r_p_l_a_n_e X_c_o_m_p_e_t_e )
(= (Distance X_c_o_m_p_e_t_e X_a_i_r_p_l_a_n_e )4)
(= (Distance X_a_i_r_p_l_a_n_e X_c_o_m_p_e_t_e )4)

(Path X_a_i_r_p_l_a_n_e X_b_a_d_g_e )
(Path X_b_a_d_g_e X_a_i_r_p_l_a_n_e )
(= (Distance X_a_i_r_p_l_a_n_e X_b_a_d_g_e )3)
(= (Distance X_b_a_d_g_e X_a_i_r_p_l_a_n_e )3)

(Path X_b_a_d_g_e X_c_o_n_s_o_r_t )
(Path X_c_o_n_s_o_r_t X_b_a_d_g_e )
(= (Distance X_b_a_d_g_e X_c_o_n_s_o_r_t )2)
(= (Distance X_c_o_n_s_o_r_t X_b_a_d_g_e )2)

(Path X_c_o_n_s_o_r_t X_p_h_y_s_i_c_a_l )
(Path X_p_h_y_s_i_c_a_l X_c_o_n_s_o_r_t )
(= (Distance X_c_o_n_s_o_r_t X_p_h_y_s_i_c_a_l )1)
(= (Distance X_p_h_y_s_i_c_a_l X_c_o_n_s_o_r_t )1)

(Path X_p_h_y_s_i_c_a_l X_p_e_r_i_s_h )
(Path X_p_e_r_i_s_h X_p_h_y_s_i_c_a_l )
(= (Distance X_p_h_y_s_i_c_a_l X_p_e_r_i_s_h )2)
(= (Distance X_p_e_r_i_s_h X_p_h_y_s_i_c_a_l )2)

(Path X_p_e_r_i_s_h X_a_b_s_e_n_t )
(Path X_a_b_s_e_n_t X_p_e_r_i_s_h )
(= (Distance X_p_e_r_i_s_h X_a_b_s_e_n_t )3)
(= (Distance X_a_b_s_e_n_t X_p_e_r_i_s_h )3)

(Path X_a_b_s_e_n_t X_m_u_t_e )
(Path X_m_u_t_e X_a_b_s_e_n_t )
(= (Distance X_a_b_s_e_n_t X_m_u_t_e )4)
(= (Distance X_m_u_t_e X_a_b_s_e_n_t )4)

(Path X_m_u_t_e X_b_o_u_n_d_l_e_s_s )
(Path X_b_o_u_n_d_l_e_s_s X_m_u_t_e )
(= (Distance X_m_u_t_e X_b_o_u_n_d_l_e_s_s )5)
(= (Distance X_b_o_u_n_d_l_e_s_s X_m_u_t_e )5)

(Path X_b_o_u_n_d_l_e_s_s X_o_c_e_a_n_i_c )
(Path X_o_c_e_a_n_i_c X_b_o_u_n_d_l_e_s_s )
(= (Distance X_b_o_u_n_d_l_e_s_s X_o_c_e_a_n_i_c )5)
(= (Distance X_o_c_e_a_n_i_c X_b_o_u_n_d_l_e_s_s )5)

(Path X_o_c_e_a_n_i_c X_d_o_g )
(Path X_d_o_g X_o_c_e_a_n_i_c )
(= (Distance X_o_c_e_a_n_i_c X_d_o_g )7)
(= (Distance X_d_o_g X_o_c_e_a_n_i_c )7)

(Path X_d_o_g X_n_e_e_d )
(Path X_n_e_e_d X_d_o_g )
(= (Distance X_d_o_g X_n_e_e_d )8)
(= (Distance X_n_e_e_d X_d_o_g )8)

(Path X_n_e_e_d X_g_a_i_n_f_u_l )
(Path X_g_a_i_n_f_u_l X_n_e_e_d )
(= (Distance X_n_e_e_d X_g_a_i_n_f_u_l )5)
(= (Distance X_g_a_i_n_f_u_l X_n_e_e_d )5)

(Path X_g_a_i_n_f_u_l X_e_v_a_n_e_s_c_e_n_t )
(Path X_e_v_a_n_e_s_c_e_n_t X_g_a_i_n_f_u_l )
(= (Distance X_g_a_i_n_f_u_l X_e_v_a_n_e_s_c_e_n_t )5)
(= (Distance X_e_v_a_n_e_s_c_e_n_t X_g_a_i_n_f_u_l )5)

(Path X_e_v_a_n_e_s_c_e_n_t X_i_n_q_u_i_r_e )
(Path X_i_n_q_u_i_r_e X_e_v_a_n_e_s_c_e_n_t )
(= (Distance X_e_v_a_n_e_s_c_e_n_t X_i_n_q_u_i_r_e )5)
(= (Distance X_i_n_q_u_i_r_e X_e_v_a_n_e_s_c_e_n_t )5)

(Path X_i_n_q_u_i_r_e X_l_i_n_e )
(Path X_l_i_n_e X_i_n_q_u_i_r_e )
(= (Distance X_i_n_q_u_i_r_e X_l_i_n_e )5)
(= (Distance X_l_i_n_e X_i_n_q_u_i_r_e )5)

(Path X_l_i_n_e X_z_i_p_p_e_r )
(Path X_z_i_p_p_e_r X_l_i_n_e )
(= (Distance X_l_i_n_e X_z_i_p_p_e_r )5)
(= (Distance X_z_i_p_p_e_r X_l_i_n_e )5)

(Path X_z_i_p_p_e_r X_h_i )
(Path X_h_i X_z_i_p_p_e_r )
(= (Distance X_z_i_p_p_e_r X_h_i )5)
(= (Distance X_h_i X_z_i_p_p_e_r )5)

(Path X_h_i X_b_y_e )
(Path X_b_y_e X_h_i )
(= (Distance X_h_i X_b_y_e )3)
(= (Distance X_b_y_e X_h_i )3)

(Path X_b_y_e X_y_o_u )
(Path X_y_o_u X_b_y_e )
(= (Distance X_b_y_e X_y_o_u )2)
(= (Distance X_y_o_u X_b_y_e )2)

(Path X_y_o_u X_a_r_e )
(Path X_a_r_e X_y_o_u )
(= (Distance X_y_o_u X_a_r_e )2)
(= (Distance X_a_r_e X_y_o_u )2)

(Path X_a_r_e X_a_m_a_z_i_n_g )
(Path X_a_m_a_z_i_n_g X_a_r_e )
(= (Distance X_a_r_e X_a_m_a_z_i_n_g )6)
(= (Distance X_a_m_a_z_i_n_g X_a_r_e )6)

(Path X_a_m_a_z_i_n_g X_w_h_y )
(Path X_w_h_y X_a_m_a_z_i_n_g )
(= (Distance X_a_m_a_z_i_n_g X_w_h_y )4)
(= (Distance X_w_h_y X_a_m_a_z_i_n_g )4)

(Path X_w_h_y X_t_h_e_r_e )
(Path X_t_h_e_r_e X_w_h_y )
(= (Distance X_w_h_y X_t_h_e_r_e )2)
(= (Distance X_t_h_e_r_e X_w_h_y )2)

(Path X_t_h_e_r_e X_i_s )
(Path X_i_s X_t_h_e_r_e )
(= (Distance X_t_h_e_r_e X_i_s )1)
(= (Distance X_i_s X_t_h_e_r_e )1)

(Path X_i_s X_t_o_p )
(Path X_t_o_p X_i_s )
(= (Distance X_i_s X_t_o_p )1)
(= (Distance X_t_o_p X_i_s )1)

(Path X_t_o_p X_b_o_t_t_o_m )
(Path X_b_o_t_t_o_m X_t_o_p )
(= (Distance X_t_o_p X_b_o_t_t_o_m )1)
(= (Distance X_b_o_t_t_o_m X_t_o_p )1)

(EmptyHome X_b_i_r_t_h_d_a_y)
(EmptyHome X_f_e_a_r_l_e_s_s)
(EmptyHome X_a_b_s_o_r_b)
(EmptyHome X_n_i_m_b_l_e)
(EmptyHome X_u_s_e)
(EmptyHome X_t_e_n_t)
(EmptyHome X_w_o_r_s_h_i_p)
(EmptyHome X_u_n_u_s_e_d)
(EmptyHome X_s_p_r_e_a_d)
(EmptyHome X_k_n_o_t)
(EmptyHome X_d_i_f_f_e_r)
(EmptyHome X_s_e_l_f_i_s_h)
(EmptyHome X_s_p_i_l_l)
(EmptyHome X_v_o_l_l_e_y_b_a_l_l)
(EmptyHome X_a_n_g_r_y)
(EmptyHome X_a_t_t_a_c_k)
(EmptyHome X_i_m_p_e_n_d)
(EmptyHome X_s_e_p_a_r_a_t_e)
(EmptyHome X_i_m_i_t_a_t_e)
(EmptyHome X_s_c_i_e_n_t_i_f_i_c)
(EmptyHome X_t_e_e_n_y)
(EmptyHome X_b_a_n_g)
(EmptyHome X_j_o_k_e)
(EmptyHome X_c_o_m_p_e_t_e)
(EmptyHome X_a_i_r_p_l_a_n_e)
)

  ; The goal state describe what we desire to achieve
  (:goal (and
( Car_At X_b_i_r_t_h_d_a_y )
(not (EmptyHome X_b_i_r_t_h_d_a_y))
(not (EmptyHome X_f_e_a_r_l_e_s_s))
(not (EmptyHome X_a_b_s_o_r_b))
(not (EmptyHome X_n_i_m_b_l_e))
(not (EmptyHome X_u_s_e))
(not (EmptyHome X_t_e_n_t))
(not (EmptyHome X_w_o_r_s_h_i_p))
(not (EmptyHome X_u_n_u_s_e_d))
(not (EmptyHome X_s_p_r_e_a_d))
(not (EmptyHome X_k_n_o_t))
(not (EmptyHome X_d_i_f_f_e_r))
(not (EmptyHome X_s_e_l_f_i_s_h))
(not (EmptyHome X_s_p_i_l_l))
(not (EmptyHome X_v_o_l_l_e_y_b_a_l_l))
(not (EmptyHome X_a_n_g_r_y))
(not (EmptyHome X_a_t_t_a_c_k))
(not (EmptyHome X_i_m_p_e_n_d))
(not (EmptyHome X_s_e_p_a_r_a_t_e))
(not (EmptyHome X_i_m_i_t_a_t_e))
(not (EmptyHome X_s_c_i_e_n_t_i_f_i_c))
(not (EmptyHome X_t_e_e_n_y))
(not (EmptyHome X_b_a_n_g))
(not (EmptyHome X_j_o_k_e))
(not (EmptyHome X_c_o_m_p_e_t_e))
(not (EmptyHome X_a_i_r_p_l_a_n_e))
  ))
)