; Problem description
; This file describes the example input from the problem statement
(define (problem pb1)
  (:metric minimize (total-cost))
  (:domain CS170)
(:objects TA_XB TA_XD TA_XE TA_XF TA_XG TA_XH TA_XI TA_XJ TA_XK TA_XL TA_XM TA_XN TA_XP TA_XS TA_XT TA_XY XA XB XC XD XE XF XG XH XI XJ XK XL XM XN XO XP XQ XR XS XT XU XV XW XX XY XZ )
(:init(= (total-cost) 0)
( Car_At XA )
(InCar TA_XB)
(InCar TA_XD)
(InCar TA_XE)
(InCar TA_XF)
(InCar TA_XG)
(InCar TA_XH)
(InCar TA_XI)
(InCar TA_XJ)
(InCar TA_XK)
(InCar TA_XL)
(InCar TA_XM)
(InCar TA_XN)
(InCar TA_XP)
(InCar TA_XS)
(InCar TA_XT)
(InCar TA_XY)
(Path XA XC )
(Path XC XA )
(= (Distance XA XC )1)
(= (Distance XC XA )1)

(Path XA XF )
(Path XF XA )
(= (Distance XA XF )1)
(= (Distance XF XA )1)

(Path XA XK )
(Path XK XA )
(= (Distance XA XK )2)
(= (Distance XK XA )2)

(Path XA XM )
(Path XM XA )
(= (Distance XA XM )1)
(= (Distance XM XA )1)

(Path XA XP )
(Path XP XA )
(= (Distance XA XP )1)
(= (Distance XP XA )1)

(Path XA XR )
(Path XR XA )
(= (Distance XA XR )1)
(= (Distance XR XA )1)

(Path XA XU )
(Path XU XA )
(= (Distance XA XU )2)
(= (Distance XU XA )2)

(Path XA XW )
(Path XW XA )
(= (Distance XA XW )2)
(= (Distance XW XA )2)

(Path XA XZ )
(Path XZ XA )
(= (Distance XA XZ )1)
(= (Distance XZ XA )1)

(Path XB XE )
(Path XE XB )
(= (Distance XB XE )1)
(= (Distance XE XB )1)

(Path XB XH )
(Path XH XB )
(= (Distance XB XH )1)
(= (Distance XH XB )1)

(Path XB XJ )
(Path XJ XB )
(= (Distance XB XJ )1)
(= (Distance XJ XB )1)

(Path XB XN )
(Path XN XB )
(= (Distance XB XN )3)
(= (Distance XN XB )3)

(Path XB XS )
(Path XS XB )
(= (Distance XB XS )2)
(= (Distance XS XB )2)

(Path XB XU )
(Path XU XB )
(= (Distance XB XU )1)
(= (Distance XU XB )1)

(Path XB XY )
(Path XY XB )
(= (Distance XB XY )2)
(= (Distance XY XB )2)

(Path XC XD )
(Path XD XC )
(= (Distance XC XD )2)
(= (Distance XD XC )2)

(Path XC XF )
(Path XF XC )
(= (Distance XC XF )1)
(= (Distance XF XC )1)

(Path XC XM )
(Path XM XC )
(= (Distance XC XM )1)
(= (Distance XM XC )1)

(Path XC XP )
(Path XP XC )
(= (Distance XC XP )1)
(= (Distance XP XC )1)

(Path XC XV )
(Path XV XC )
(= (Distance XC XV )2)
(= (Distance XV XC )2)

(Path XC XW )
(Path XW XC )
(= (Distance XC XW )1)
(= (Distance XW XC )1)

(Path XD XE )
(Path XE XD )
(= (Distance XD XE )1)
(= (Distance XE XD )1)

(Path XD XH )
(Path XH XD )
(= (Distance XD XH )1)
(= (Distance XH XD )1)

(Path XD XI )
(Path XI XD )
(= (Distance XD XI )1)
(= (Distance XI XD )1)

(Path XD XM )
(Path XM XD )
(= (Distance XD XM )1)
(= (Distance XM XD )1)

(Path XD XO )
(Path XO XD )
(= (Distance XD XO )2)
(= (Distance XO XD )2)

(Path XD XP )
(Path XP XD )
(= (Distance XD XP )1)
(= (Distance XP XD )1)

(Path XD XW )
(Path XW XD )
(= (Distance XD XW )1)
(= (Distance XW XD )1)

(Path XD XZ )
(Path XZ XD )
(= (Distance XD XZ )1)
(= (Distance XZ XD )1)

(Path XE XH )
(Path XH XE )
(= (Distance XE XH )1)
(= (Distance XH XE )1)

(Path XE XM )
(Path XM XE )
(= (Distance XE XM )1)
(= (Distance XM XE )1)

(Path XE XP )
(Path XP XE )
(= (Distance XE XP )1)
(= (Distance XP XE )1)

(Path XE XT )
(Path XT XE )
(= (Distance XE XT )2)
(= (Distance XT XE )2)

(Path XE XW )
(Path XW XE )
(= (Distance XE XW )1)
(= (Distance XW XE )1)

(Path XE XZ )
(Path XZ XE )
(= (Distance XE XZ )1)
(= (Distance XZ XE )1)

(Path XF XG )
(Path XG XF )
(= (Distance XF XG )2)
(= (Distance XG XF )2)

(Path XF XI )
(Path XI XF )
(= (Distance XF XI )2)
(= (Distance XI XF )2)

(Path XF XL )
(Path XL XF )
(= (Distance XF XL )2)
(= (Distance XL XF )2)

(Path XF XM )
(Path XM XF )
(= (Distance XF XM )1)
(= (Distance XM XF )1)

(Path XF XP )
(Path XP XF )
(= (Distance XF XP )1)
(= (Distance XP XF )1)

(Path XF XW )
(Path XW XF )
(= (Distance XF XW )1)
(= (Distance XW XF )1)

(Path XF XZ )
(Path XZ XF )
(= (Distance XF XZ )1)
(= (Distance XZ XF )1)

(Path XG XH )
(Path XH XG )
(= (Distance XG XH )1)
(= (Distance XH XG )1)

(Path XG XI )
(Path XI XG )
(= (Distance XG XI )1)
(= (Distance XI XG )1)

(Path XG XM )
(Path XM XG )
(= (Distance XG XM )1)
(= (Distance XM XG )1)

(Path XG XP )
(Path XP XG )
(= (Distance XG XP )1)
(= (Distance XP XG )1)

(Path XG XW )
(Path XW XG )
(= (Distance XG XW )1)
(= (Distance XW XG )1)

(Path XG XY )
(Path XY XG )
(= (Distance XG XY )2)
(= (Distance XY XG )2)

(Path XH XJ )
(Path XJ XH )
(= (Distance XH XJ )2)
(= (Distance XJ XH )2)

(Path XH XL )
(Path XL XH )
(= (Distance XH XL )2)
(= (Distance XL XH )2)

(Path XH XM )
(Path XM XH )
(= (Distance XH XM )1)
(= (Distance XM XH )1)

(Path XH XP )
(Path XP XH )
(= (Distance XH XP )1)
(= (Distance XP XH )1)

(Path XH XS )
(Path XS XH )
(= (Distance XH XS )2)
(= (Distance XS XH )2)

(Path XH XT )
(Path XT XH )
(= (Distance XH XT )2)
(= (Distance XT XH )2)

(Path XH XW )
(Path XW XH )
(= (Distance XH XW )1)
(= (Distance XW XH )1)

(Path XH XZ )
(Path XZ XH )
(= (Distance XH XZ )1)
(= (Distance XZ XH )1)

(Path XI XM )
(Path XM XI )
(= (Distance XI XM )1)
(= (Distance XM XI )1)

(Path XI XN )
(Path XN XI )
(= (Distance XI XN )1)
(= (Distance XN XI )1)

(Path XI XP )
(Path XP XI )
(= (Distance XI XP )1)
(= (Distance XP XI )1)

(Path XI XW )
(Path XW XI )
(= (Distance XI XW )1)
(= (Distance XW XI )1)

(Path XJ XK )
(Path XK XJ )
(= (Distance XJ XK )1)
(= (Distance XK XJ )1)

(Path XJ XM )
(Path XM XJ )
(= (Distance XJ XM )2)
(= (Distance XM XJ )2)

(Path XJ XN )
(Path XN XJ )
(= (Distance XJ XN )2)
(= (Distance XN XJ )2)

(Path XJ XP )
(Path XP XJ )
(= (Distance XJ XP )2)
(= (Distance XP XJ )2)

(Path XJ XS )
(Path XS XJ )
(= (Distance XJ XS )2)
(= (Distance XS XJ )2)

(Path XJ XW )
(Path XW XJ )
(= (Distance XJ XW )1)
(= (Distance XW XJ )1)

(Path XJ XZ )
(Path XZ XJ )
(= (Distance XJ XZ )1)
(= (Distance XZ XJ )1)

(Path XK XM )
(Path XM XK )
(= (Distance XK XM )1)
(= (Distance XM XK )1)

(Path XK XN )
(Path XN XK )
(= (Distance XK XN )2)
(= (Distance XN XK )2)

(Path XK XP )
(Path XP XK )
(= (Distance XK XP )1)
(= (Distance XP XK )1)

(Path XK XS )
(Path XS XK )
(= (Distance XK XS )2)
(= (Distance XS XK )2)

(Path XK XT )
(Path XT XK )
(= (Distance XK XT )2)
(= (Distance XT XK )2)

(Path XK XW )
(Path XW XK )
(= (Distance XK XW )1)
(= (Distance XW XK )1)

(Path XK XZ )
(Path XZ XK )
(= (Distance XK XZ )1)
(= (Distance XZ XK )1)

(Path XL XM )
(Path XM XL )
(= (Distance XL XM )2)
(= (Distance XM XL )2)

(Path XL XP )
(Path XP XL )
(= (Distance XL XP )1)
(= (Distance XP XL )1)

(Path XL XR )
(Path XR XL )
(= (Distance XL XR )2)
(= (Distance XR XL )2)

(Path XL XV )
(Path XV XL )
(= (Distance XL XV )2)
(= (Distance XV XL )2)

(Path XL XW )
(Path XW XL )
(= (Distance XL XW )1)
(= (Distance XW XL )1)

(Path XL XZ )
(Path XZ XL )
(= (Distance XL XZ )1)
(= (Distance XZ XL )1)

(Path XM XN )
(Path XN XM )
(= (Distance XM XN )1)
(= (Distance XN XM )1)

(Path XM XO )
(Path XO XM )
(= (Distance XM XO )1)
(= (Distance XO XM )1)

(Path XM XP )
(Path XP XM )
(= (Distance XM XP )1)
(= (Distance XP XM )1)

(Path XM XQ )
(Path XQ XM )
(= (Distance XM XQ )1)
(= (Distance XQ XM )1)

(Path XM XR )
(Path XR XM )
(= (Distance XM XR )1)
(= (Distance XR XM )1)

(Path XM XS )
(Path XS XM )
(= (Distance XM XS )1)
(= (Distance XS XM )1)

(Path XM XT )
(Path XT XM )
(= (Distance XM XT )1)
(= (Distance XT XM )1)

(Path XM XU )
(Path XU XM )
(= (Distance XM XU )1)
(= (Distance XU XM )1)

(Path XM XV )
(Path XV XM )
(= (Distance XM XV )1)
(= (Distance XV XM )1)

(Path XM XW )
(Path XW XM )
(= (Distance XM XW )1)
(= (Distance XW XM )1)

(Path XM XX )
(Path XX XM )
(= (Distance XM XX )1)
(= (Distance XX XM )1)

(Path XM XY )
(Path XY XM )
(= (Distance XM XY )2)
(= (Distance XY XM )2)

(Path XM XZ )
(Path XZ XM )
(= (Distance XM XZ )1)
(= (Distance XZ XM )1)

(Path XN XP )
(Path XP XN )
(= (Distance XN XP )1)
(= (Distance XP XN )1)

(Path XN XW )
(Path XW XN )
(= (Distance XN XW )1)
(= (Distance XW XN )1)

(Path XN XZ )
(Path XZ XN )
(= (Distance XN XZ )1)
(= (Distance XZ XN )1)

(Path XO XP )
(Path XP XO )
(= (Distance XO XP )1)
(= (Distance XP XO )1)

(Path XO XW )
(Path XW XO )
(= (Distance XO XW )1)
(= (Distance XW XO )1)

(Path XO XZ )
(Path XZ XO )
(= (Distance XO XZ )1)
(= (Distance XZ XO )1)

(Path XP XQ )
(Path XQ XP )
(= (Distance XP XQ )1)
(= (Distance XQ XP )1)

(Path XP XR )
(Path XR XP )
(= (Distance XP XR )1)
(= (Distance XR XP )1)

(Path XP XS )
(Path XS XP )
(= (Distance XP XS )1)
(= (Distance XS XP )1)

(Path XP XT )
(Path XT XP )
(= (Distance XP XT )1)
(= (Distance XT XP )1)

(Path XP XU )
(Path XU XP )
(= (Distance XP XU )1)
(= (Distance XU XP )1)

(Path XP XV )
(Path XV XP )
(= (Distance XP XV )1)
(= (Distance XV XP )1)

(Path XP XW )
(Path XW XP )
(= (Distance XP XW )1)
(= (Distance XW XP )1)

(Path XP XX )
(Path XX XP )
(= (Distance XP XX )1)
(= (Distance XX XP )1)

(Path XP XY )
(Path XY XP )
(= (Distance XP XY )1)
(= (Distance XY XP )1)

(Path XP XZ )
(Path XZ XP )
(= (Distance XP XZ )1)
(= (Distance XZ XP )1)

(Path XQ XV )
(Path XV XQ )
(= (Distance XQ XV )2)
(= (Distance XV XQ )2)

(Path XQ XW )
(Path XW XQ )
(= (Distance XQ XW )1)
(= (Distance XW XQ )1)

(Path XQ XZ )
(Path XZ XQ )
(= (Distance XQ XZ )1)
(= (Distance XZ XQ )1)

(Path XR XU )
(Path XU XR )
(= (Distance XR XU )2)
(= (Distance XU XR )2)

(Path XR XW )
(Path XW XR )
(= (Distance XR XW )1)
(= (Distance XW XR )1)

(Path XR XZ )
(Path XZ XR )
(= (Distance XR XZ )1)
(= (Distance XZ XR )1)

(Path XS XT )
(Path XT XS )
(= (Distance XS XT )2)
(= (Distance XT XS )2)

(Path XS XW )
(Path XW XS )
(= (Distance XS XW )1)
(= (Distance XW XS )1)

(Path XT XW )
(Path XW XT )
(= (Distance XT XW )1)
(= (Distance XW XT )1)

(Path XT XZ )
(Path XZ XT )
(= (Distance XT XZ )1)
(= (Distance XZ XT )1)

(Path XU XW )
(Path XW XU )
(= (Distance XU XW )1)
(= (Distance XW XU )1)

(Path XU XZ )
(Path XZ XU )
(= (Distance XU XZ )1)
(= (Distance XZ XU )1)

(Path XV XW )
(Path XW XV )
(= (Distance XV XW )1)
(= (Distance XW XV )1)

(Path XW XX )
(Path XX XW )
(= (Distance XW XX )1)
(= (Distance XX XW )1)

(Path XW XY )
(Path XY XW )
(= (Distance XW XY )1)
(= (Distance XY XW )1)

(Path XW XZ )
(Path XZ XW )
(= (Distance XW XZ )1)
(= (Distance XZ XW )1)

(Path XY XZ )
(Path XZ XY )
(= (Distance XY XZ )1)
(= (Distance XZ XY )1)

(EmptyHome XB)
(EmptyHome XD)
(EmptyHome XE)
(EmptyHome XF)
(EmptyHome XG)
(EmptyHome XH)
(EmptyHome XI)
(EmptyHome XJ)
(EmptyHome XK)
(EmptyHome XL)
(EmptyHome XM)
(EmptyHome XN)
(EmptyHome XP)
(EmptyHome XS)
(EmptyHome XT)
(EmptyHome XY)
)

  ; The goal state describe what we desire to achieve
  (:goal (and
( Car_At XA )
(not (EmptyHome XB))
(not (EmptyHome XD))
(not (EmptyHome XE))
(not (EmptyHome XF))
(not (EmptyHome XG))
(not (EmptyHome XH))
(not (EmptyHome XI))
(not (EmptyHome XJ))
(not (EmptyHome XK))
(not (EmptyHome XL))
(not (EmptyHome XM))
(not (EmptyHome XN))
(not (EmptyHome XP))
(not (EmptyHome XS))
(not (EmptyHome XT))
(not (EmptyHome XY))
  ))
)