; Problem description
; This file describes the example input from the problem statement
(define (problem pb1)
  (:metric minimize (total-cost))
  (:domain CS170)
(:objects TA_X0 TA_X1 TA_X2 TA_X5 TA_X6 X0 X1 X2 X3 X4 X5 X6 )
(:init(= (total-cost) 0)
( Car_At X3 )
(InCar TA_X0)
(InCar TA_X1)
(InCar TA_X2)
(InCar TA_X5)
(InCar TA_X6)
(Path X0 X1 )
(Path X1 X0 )
(= (Distance X0 X1 )1)
(= (Distance X1 X0 )1)

(Path X0 X3 )
(Path X3 X0 )
(= (Distance X0 X3 )1)
(= (Distance X3 X0 )1)

(Path X1 X2 )
(Path X2 X1 )
(= (Distance X1 X2 )1)
(= (Distance X2 X1 )1)

(Path X2 X3 )
(Path X3 X2 )
(= (Distance X2 X3 )1)
(= (Distance X3 X2 )1)

(Path X3 X4 )
(Path X4 X3 )
(= (Distance X3 X4 )1)
(= (Distance X4 X3 )1)

(Path X4 X5 )
(Path X5 X4 )
(= (Distance X4 X5 )100)
(= (Distance X5 X4 )100)

(Path X4 X6 )
(Path X6 X4 )
(= (Distance X4 X6 )100)
(= (Distance X6 X4 )100)

(EmptyHome X0)
(EmptyHome X1)
(EmptyHome X2)
(EmptyHome X5)
(EmptyHome X6)
)

  ; The goal state describe what we desire to achieve
  (:goal (and
( Car_At X3 )
(not (EmptyHome X0))
(not (EmptyHome X1))
(not (EmptyHome X2))
(not (EmptyHome X5))
(not (EmptyHome X6))
  ))
)