; Problem description
; This file describes the example input from the problem statement
(define (problem pb1)
  (:metric minimize (total-cost))
  (:domain CS170)
(:objects TA_XL_i_a_m TA_XN_o_a_h TA_XW_i_l_l_i_a_m TA_XJ_a_m_e_s TA_XL_o_g_a_n TA_XB_e_n_j_a_m_i_n TA_XM_a_s_o_n TA_XE_l_i_j_a_h TA_XO_l_i_v_e_r TA_XJ_a_c_o_b TA_XL_u_c_a_s TA_XM_i_c_h_a_e_l TA_XA_l_e_x_a_n_d_e_r TA_XE_t_h_a_n TA_XD_a_n_i_e_l TA_XM_a_t_t_h_e_w TA_XA_i_d_e_n TA_XH_e_n_r_y TA_XJ_o_s_e_p_h TA_XJ_a_c_k_s_o_n TA_XS_a_m_u_e_l TA_XS_e_b_a_s_t_i_a_n TA_XD_a_v_i_d TA_XC_a_r_t_e_r TA_XW_y_a_t_t XL_i_a_m XN_o_a_h XW_i_l_l_i_a_m XJ_a_m_e_s XL_o_g_a_n XB_e_n_j_a_m_i_n XM_a_s_o_n XE_l_i_j_a_h XO_l_i_v_e_r XJ_a_c_o_b XL_u_c_a_s XM_i_c_h_a_e_l XA_l_e_x_a_n_d_e_r XE_t_h_a_n XD_a_n_i_e_l XM_a_t_t_h_e_w XA_i_d_e_n XH_e_n_r_y XJ_o_s_e_p_h XJ_a_c_k_s_o_n XS_a_m_u_e_l XS_e_b_a_s_t_i_a_n XD_a_v_i_d XC_a_r_t_e_r XW_y_a_t_t XJ_a_y_d_e_n XJ_o_h_n XO_w_e_n XD_y_l_a_n XL_u_k_e XG_a_b_r_i_e_l XA_n_t_h_o_n_y XI_s_a_a_c XG_r_a_y_s_o_n XJ_a_c_k XJ_u_l_i_a_n XL_e_v_i XC_h_r_i_s_t_o_p_h_e_r XJ_o_s_h_u_a XA_n_d_r_e_w XL_i_n_c_o_l_n XM_a_t_e_o XR_y_a_n XJ_a_x_o_n XN_a_t_h_a_n XA_a_r_o_n XI_s_a_i_a_h XT_h_o_m_a_s XC_h_a_r_l_e_s XC_a_l_e_b )
(:init(= (total-cost) 0)
( Car_At XL_i_a_m )
(InCar TA_XL_i_a_m)
(InCar TA_XN_o_a_h)
(InCar TA_XW_i_l_l_i_a_m)
(InCar TA_XJ_a_m_e_s)
(InCar TA_XL_o_g_a_n)
(InCar TA_XB_e_n_j_a_m_i_n)
(InCar TA_XM_a_s_o_n)
(InCar TA_XE_l_i_j_a_h)
(InCar TA_XO_l_i_v_e_r)
(InCar TA_XJ_a_c_o_b)
(InCar TA_XL_u_c_a_s)
(InCar TA_XM_i_c_h_a_e_l)
(InCar TA_XA_l_e_x_a_n_d_e_r)
(InCar TA_XE_t_h_a_n)
(InCar TA_XD_a_n_i_e_l)
(InCar TA_XM_a_t_t_h_e_w)
(InCar TA_XA_i_d_e_n)
(InCar TA_XH_e_n_r_y)
(InCar TA_XJ_o_s_e_p_h)
(InCar TA_XJ_a_c_k_s_o_n)
(InCar TA_XS_a_m_u_e_l)
(InCar TA_XS_e_b_a_s_t_i_a_n)
(InCar TA_XD_a_v_i_d)
(InCar TA_XC_a_r_t_e_r)
(InCar TA_XW_y_a_t_t)
(Path XL_i_a_m XB_e_n_j_a_m_i_n )
(Path XB_e_n_j_a_m_i_n XL_i_a_m )
(= (Distance XL_i_a_m XB_e_n_j_a_m_i_n )3)
(= (Distance XB_e_n_j_a_m_i_n XL_i_a_m )3)

(Path XL_i_a_m XO_l_i_v_e_r )
(Path XO_l_i_v_e_r XL_i_a_m )
(= (Distance XL_i_a_m XO_l_i_v_e_r )13)
(= (Distance XO_l_i_v_e_r XL_i_a_m )13)

(Path XL_i_a_m XJ_a_c_o_b )
(Path XJ_a_c_o_b XL_i_a_m )
(= (Distance XL_i_a_m XJ_a_c_o_b )11)
(= (Distance XJ_a_c_o_b XL_i_a_m )11)

(Path XL_i_a_m XL_u_c_a_s )
(Path XL_u_c_a_s XL_i_a_m )
(= (Distance XL_i_a_m XL_u_c_a_s )19)
(= (Distance XL_u_c_a_s XL_i_a_m )19)

(Path XL_i_a_m XA_i_d_e_n )
(Path XA_i_d_e_n XL_i_a_m )
(= (Distance XL_i_a_m XA_i_d_e_n )4)
(= (Distance XA_i_d_e_n XL_i_a_m )4)

(Path XL_i_a_m XS_a_m_u_e_l )
(Path XS_a_m_u_e_l XL_i_a_m )
(= (Distance XL_i_a_m XS_a_m_u_e_l )14)
(= (Distance XS_a_m_u_e_l XL_i_a_m )14)

(Path XL_i_a_m XL_u_k_e )
(Path XL_u_k_e XL_i_a_m )
(= (Distance XL_i_a_m XL_u_k_e )21)
(= (Distance XL_u_k_e XL_i_a_m )21)

(Path XL_i_a_m XJ_o_s_h_u_a )
(Path XJ_o_s_h_u_a XL_i_a_m )
(= (Distance XL_i_a_m XJ_o_s_h_u_a )21)
(= (Distance XJ_o_s_h_u_a XL_i_a_m )21)

(Path XL_i_a_m XJ_a_x_o_n )
(Path XJ_a_x_o_n XL_i_a_m )
(= (Distance XL_i_a_m XJ_a_x_o_n )3)
(= (Distance XJ_a_x_o_n XL_i_a_m )3)

(Path XL_i_a_m XA_a_r_o_n )
(Path XA_a_r_o_n XL_i_a_m )
(= (Distance XL_i_a_m XA_a_r_o_n )18)
(= (Distance XA_a_r_o_n XL_i_a_m )18)

(Path XL_i_a_m XT_h_o_m_a_s )
(Path XT_h_o_m_a_s XL_i_a_m )
(= (Distance XL_i_a_m XT_h_o_m_a_s )23)
(= (Distance XT_h_o_m_a_s XL_i_a_m )23)

(Path XN_o_a_h XL_o_g_a_n )
(Path XL_o_g_a_n XN_o_a_h )
(= (Distance XN_o_a_h XL_o_g_a_n )12)
(= (Distance XL_o_g_a_n XN_o_a_h )12)

(Path XN_o_a_h XM_a_s_o_n )
(Path XM_a_s_o_n XN_o_a_h )
(= (Distance XN_o_a_h XM_a_s_o_n )7)
(= (Distance XM_a_s_o_n XN_o_a_h )7)

(Path XN_o_a_h XJ_o_s_e_p_h )
(Path XJ_o_s_e_p_h XN_o_a_h )
(= (Distance XN_o_a_h XJ_o_s_e_p_h )10)
(= (Distance XJ_o_s_e_p_h XN_o_a_h )10)

(Path XN_o_a_h XJ_a_y_d_e_n )
(Path XJ_a_y_d_e_n XN_o_a_h )
(= (Distance XN_o_a_h XJ_a_y_d_e_n )30)
(= (Distance XJ_a_y_d_e_n XN_o_a_h )30)

(Path XN_o_a_h XD_y_l_a_n )
(Path XD_y_l_a_n XN_o_a_h )
(= (Distance XN_o_a_h XD_y_l_a_n )8)
(= (Distance XD_y_l_a_n XN_o_a_h )8)

(Path XN_o_a_h XG_a_b_r_i_e_l )
(Path XG_a_b_r_i_e_l XN_o_a_h )
(= (Distance XN_o_a_h XG_a_b_r_i_e_l )4)
(= (Distance XG_a_b_r_i_e_l XN_o_a_h )4)

(Path XN_o_a_h XJ_o_s_h_u_a )
(Path XJ_o_s_h_u_a XN_o_a_h )
(= (Distance XN_o_a_h XJ_o_s_h_u_a )8)
(= (Distance XJ_o_s_h_u_a XN_o_a_h )8)

(Path XN_o_a_h XN_a_t_h_a_n )
(Path XN_a_t_h_a_n XN_o_a_h )
(= (Distance XN_o_a_h XN_a_t_h_a_n )12)
(= (Distance XN_a_t_h_a_n XN_o_a_h )12)

(Path XN_o_a_h XA_a_r_o_n )
(Path XA_a_r_o_n XN_o_a_h )
(= (Distance XN_o_a_h XA_a_r_o_n )23)
(= (Distance XA_a_r_o_n XN_o_a_h )23)

(Path XN_o_a_h XC_a_l_e_b )
(Path XC_a_l_e_b XN_o_a_h )
(= (Distance XN_o_a_h XC_a_l_e_b )31)
(= (Distance XC_a_l_e_b XN_o_a_h )31)

(Path XW_i_l_l_i_a_m XM_a_s_o_n )
(Path XM_a_s_o_n XW_i_l_l_i_a_m )
(= (Distance XW_i_l_l_i_a_m XM_a_s_o_n )1)
(= (Distance XM_a_s_o_n XW_i_l_l_i_a_m )1)

(Path XW_i_l_l_i_a_m XE_l_i_j_a_h )
(Path XE_l_i_j_a_h XW_i_l_l_i_a_m )
(= (Distance XW_i_l_l_i_a_m XE_l_i_j_a_h )2)
(= (Distance XE_l_i_j_a_h XW_i_l_l_i_a_m )2)

(Path XW_i_l_l_i_a_m XA_l_e_x_a_n_d_e_r )
(Path XA_l_e_x_a_n_d_e_r XW_i_l_l_i_a_m )
(= (Distance XW_i_l_l_i_a_m XA_l_e_x_a_n_d_e_r )6)
(= (Distance XA_l_e_x_a_n_d_e_r XW_i_l_l_i_a_m )6)

(Path XW_i_l_l_i_a_m XE_t_h_a_n )
(Path XE_t_h_a_n XW_i_l_l_i_a_m )
(= (Distance XW_i_l_l_i_a_m XE_t_h_a_n )14)
(= (Distance XE_t_h_a_n XW_i_l_l_i_a_m )14)

(Path XW_i_l_l_i_a_m XM_a_t_t_h_e_w )
(Path XM_a_t_t_h_e_w XW_i_l_l_i_a_m )
(= (Distance XW_i_l_l_i_a_m XM_a_t_t_h_e_w )19)
(= (Distance XM_a_t_t_h_e_w XW_i_l_l_i_a_m )19)

(Path XW_i_l_l_i_a_m XC_a_r_t_e_r )
(Path XC_a_r_t_e_r XW_i_l_l_i_a_m )
(= (Distance XW_i_l_l_i_a_m XC_a_r_t_e_r )1)
(= (Distance XC_a_r_t_e_r XW_i_l_l_i_a_m )1)

(Path XW_i_l_l_i_a_m XJ_a_y_d_e_n )
(Path XJ_a_y_d_e_n XW_i_l_l_i_a_m )
(= (Distance XW_i_l_l_i_a_m XJ_a_y_d_e_n )22)
(= (Distance XJ_a_y_d_e_n XW_i_l_l_i_a_m )22)

(Path XW_i_l_l_i_a_m XO_w_e_n )
(Path XO_w_e_n XW_i_l_l_i_a_m )
(= (Distance XW_i_l_l_i_a_m XO_w_e_n )18)
(= (Distance XO_w_e_n XW_i_l_l_i_a_m )18)

(Path XW_i_l_l_i_a_m XD_y_l_a_n )
(Path XD_y_l_a_n XW_i_l_l_i_a_m )
(= (Distance XW_i_l_l_i_a_m XD_y_l_a_n )16)
(= (Distance XD_y_l_a_n XW_i_l_l_i_a_m )16)

(Path XW_i_l_l_i_a_m XG_r_a_y_s_o_n )
(Path XG_r_a_y_s_o_n XW_i_l_l_i_a_m )
(= (Distance XW_i_l_l_i_a_m XG_r_a_y_s_o_n )4)
(= (Distance XG_r_a_y_s_o_n XW_i_l_l_i_a_m )4)

(Path XW_i_l_l_i_a_m XJ_a_c_k )
(Path XJ_a_c_k XW_i_l_l_i_a_m )
(= (Distance XW_i_l_l_i_a_m XJ_a_c_k )10)
(= (Distance XJ_a_c_k XW_i_l_l_i_a_m )10)

(Path XW_i_l_l_i_a_m XL_i_n_c_o_l_n )
(Path XL_i_n_c_o_l_n XW_i_l_l_i_a_m )
(= (Distance XW_i_l_l_i_a_m XL_i_n_c_o_l_n )30)
(= (Distance XL_i_n_c_o_l_n XW_i_l_l_i_a_m )30)

(Path XW_i_l_l_i_a_m XN_a_t_h_a_n )
(Path XN_a_t_h_a_n XW_i_l_l_i_a_m )
(= (Distance XW_i_l_l_i_a_m XN_a_t_h_a_n )20)
(= (Distance XN_a_t_h_a_n XW_i_l_l_i_a_m )20)

(Path XW_i_l_l_i_a_m XI_s_a_i_a_h )
(Path XI_s_a_i_a_h XW_i_l_l_i_a_m )
(= (Distance XW_i_l_l_i_a_m XI_s_a_i_a_h )15)
(= (Distance XI_s_a_i_a_h XW_i_l_l_i_a_m )15)

(Path XJ_a_m_e_s XL_o_g_a_n )
(Path XL_o_g_a_n XJ_a_m_e_s )
(= (Distance XJ_a_m_e_s XL_o_g_a_n )12)
(= (Distance XL_o_g_a_n XJ_a_m_e_s )12)

(Path XJ_a_m_e_s XM_a_s_o_n )
(Path XM_a_s_o_n XJ_a_m_e_s )
(= (Distance XJ_a_m_e_s XM_a_s_o_n )11)
(= (Distance XM_a_s_o_n XJ_a_m_e_s )11)

(Path XJ_a_m_e_s XE_l_i_j_a_h )
(Path XE_l_i_j_a_h XJ_a_m_e_s )
(= (Distance XJ_a_m_e_s XE_l_i_j_a_h )12)
(= (Distance XE_l_i_j_a_h XJ_a_m_e_s )12)

(Path XJ_a_m_e_s XO_l_i_v_e_r )
(Path XO_l_i_v_e_r XJ_a_m_e_s )
(= (Distance XJ_a_m_e_s XO_l_i_v_e_r )14)
(= (Distance XO_l_i_v_e_r XJ_a_m_e_s )14)

(Path XJ_a_m_e_s XM_i_c_h_a_e_l )
(Path XM_i_c_h_a_e_l XJ_a_m_e_s )
(= (Distance XJ_a_m_e_s XM_i_c_h_a_e_l )24)
(= (Distance XM_i_c_h_a_e_l XJ_a_m_e_s )24)

(Path XJ_a_m_e_s XA_i_d_e_n )
(Path XA_i_d_e_n XJ_a_m_e_s )
(= (Distance XJ_a_m_e_s XA_i_d_e_n )5)
(= (Distance XA_i_d_e_n XJ_a_m_e_s )5)

(Path XJ_a_m_e_s XS_a_m_u_e_l )
(Path XS_a_m_u_e_l XJ_a_m_e_s )
(= (Distance XJ_a_m_e_s XS_a_m_u_e_l )7)
(= (Distance XS_a_m_u_e_l XJ_a_m_e_s )7)

(Path XJ_a_m_e_s XD_a_v_i_d )
(Path XD_a_v_i_d XJ_a_m_e_s )
(= (Distance XJ_a_m_e_s XD_a_v_i_d )5)
(= (Distance XD_a_v_i_d XJ_a_m_e_s )5)

(Path XJ_a_m_e_s XJ_o_h_n )
(Path XJ_o_h_n XJ_a_m_e_s )
(= (Distance XJ_a_m_e_s XJ_o_h_n )15)
(= (Distance XJ_o_h_n XJ_a_m_e_s )15)

(Path XJ_a_m_e_s XO_w_e_n )
(Path XO_w_e_n XJ_a_m_e_s )
(= (Distance XJ_a_m_e_s XO_w_e_n )16)
(= (Distance XO_w_e_n XJ_a_m_e_s )16)

(Path XJ_a_m_e_s XL_u_k_e )
(Path XL_u_k_e XJ_a_m_e_s )
(= (Distance XJ_a_m_e_s XL_u_k_e )20)
(= (Distance XL_u_k_e XJ_a_m_e_s )20)

(Path XJ_a_m_e_s XJ_a_c_k )
(Path XJ_a_c_k XJ_a_m_e_s )
(= (Distance XJ_a_m_e_s XJ_a_c_k )22)
(= (Distance XJ_a_c_k XJ_a_m_e_s )22)

(Path XJ_a_m_e_s XA_n_d_r_e_w )
(Path XA_n_d_r_e_w XJ_a_m_e_s )
(= (Distance XJ_a_m_e_s XA_n_d_r_e_w )11)
(= (Distance XA_n_d_r_e_w XJ_a_m_e_s )11)

(Path XJ_a_m_e_s XJ_a_x_o_n )
(Path XJ_a_x_o_n XJ_a_m_e_s )
(= (Distance XJ_a_m_e_s XJ_a_x_o_n )4)
(= (Distance XJ_a_x_o_n XJ_a_m_e_s )4)

(Path XJ_a_m_e_s XN_a_t_h_a_n )
(Path XN_a_t_h_a_n XJ_a_m_e_s )
(= (Distance XJ_a_m_e_s XN_a_t_h_a_n )18)
(= (Distance XN_a_t_h_a_n XJ_a_m_e_s )18)

(Path XJ_a_m_e_s XC_a_l_e_b )
(Path XC_a_l_e_b XJ_a_m_e_s )
(= (Distance XJ_a_m_e_s XC_a_l_e_b )13)
(= (Distance XC_a_l_e_b XJ_a_m_e_s )13)

(Path XL_o_g_a_n XM_a_s_o_n )
(Path XM_a_s_o_n XL_o_g_a_n )
(= (Distance XL_o_g_a_n XM_a_s_o_n )19)
(= (Distance XM_a_s_o_n XL_o_g_a_n )19)

(Path XL_o_g_a_n XE_t_h_a_n )
(Path XE_t_h_a_n XL_o_g_a_n )
(= (Distance XL_o_g_a_n XE_t_h_a_n )15)
(= (Distance XE_t_h_a_n XL_o_g_a_n )15)

(Path XL_o_g_a_n XA_i_d_e_n )
(Path XA_i_d_e_n XL_o_g_a_n )
(= (Distance XL_o_g_a_n XA_i_d_e_n )15)
(= (Distance XA_i_d_e_n XL_o_g_a_n )15)

(Path XL_o_g_a_n XW_y_a_t_t )
(Path XW_y_a_t_t XL_o_g_a_n )
(= (Distance XL_o_g_a_n XW_y_a_t_t )23)
(= (Distance XW_y_a_t_t XL_o_g_a_n )23)

(Path XL_o_g_a_n XJ_a_y_d_e_n )
(Path XJ_a_y_d_e_n XL_o_g_a_n )
(= (Distance XL_o_g_a_n XJ_a_y_d_e_n )20)
(= (Distance XJ_a_y_d_e_n XL_o_g_a_n )20)

(Path XL_o_g_a_n XJ_o_h_n )
(Path XJ_o_h_n XL_o_g_a_n )
(= (Distance XL_o_g_a_n XJ_o_h_n )8)
(= (Distance XJ_o_h_n XL_o_g_a_n )8)

(Path XL_o_g_a_n XO_w_e_n )
(Path XO_w_e_n XL_o_g_a_n )
(= (Distance XL_o_g_a_n XO_w_e_n )28)
(= (Distance XO_w_e_n XL_o_g_a_n )28)

(Path XL_o_g_a_n XL_u_k_e )
(Path XL_u_k_e XL_o_g_a_n )
(= (Distance XL_o_g_a_n XL_u_k_e )15)
(= (Distance XL_u_k_e XL_o_g_a_n )15)

(Path XL_o_g_a_n XG_a_b_r_i_e_l )
(Path XG_a_b_r_i_e_l XL_o_g_a_n )
(= (Distance XL_o_g_a_n XG_a_b_r_i_e_l )8)
(= (Distance XG_a_b_r_i_e_l XL_o_g_a_n )8)

(Path XL_o_g_a_n XI_s_a_a_c )
(Path XI_s_a_a_c XL_o_g_a_n )
(= (Distance XL_o_g_a_n XI_s_a_a_c )37)
(= (Distance XI_s_a_a_c XL_o_g_a_n )37)

(Path XL_o_g_a_n XL_e_v_i )
(Path XL_e_v_i XL_o_g_a_n )
(= (Distance XL_o_g_a_n XL_e_v_i )30)
(= (Distance XL_e_v_i XL_o_g_a_n )30)

(Path XL_o_g_a_n XC_h_r_i_s_t_o_p_h_e_r )
(Path XC_h_r_i_s_t_o_p_h_e_r XL_o_g_a_n )
(= (Distance XL_o_g_a_n XC_h_r_i_s_t_o_p_h_e_r )12)
(= (Distance XC_h_r_i_s_t_o_p_h_e_r XL_o_g_a_n )12)

(Path XL_o_g_a_n XL_i_n_c_o_l_n )
(Path XL_i_n_c_o_l_n XL_o_g_a_n )
(= (Distance XL_o_g_a_n XL_i_n_c_o_l_n )31)
(= (Distance XL_i_n_c_o_l_n XL_o_g_a_n )31)

(Path XL_o_g_a_n XM_a_t_e_o )
(Path XM_a_t_e_o XL_o_g_a_n )
(= (Distance XL_o_g_a_n XM_a_t_e_o )18)
(= (Distance XM_a_t_e_o XL_o_g_a_n )18)

(Path XL_o_g_a_n XJ_a_x_o_n )
(Path XJ_a_x_o_n XL_o_g_a_n )
(= (Distance XL_o_g_a_n XJ_a_x_o_n )14)
(= (Distance XJ_a_x_o_n XL_o_g_a_n )14)

(Path XL_o_g_a_n XC_h_a_r_l_e_s )
(Path XC_h_a_r_l_e_s XL_o_g_a_n )
(= (Distance XL_o_g_a_n XC_h_a_r_l_e_s )22)
(= (Distance XC_h_a_r_l_e_s XL_o_g_a_n )22)

(Path XB_e_n_j_a_m_i_n XO_l_i_v_e_r )
(Path XO_l_i_v_e_r XB_e_n_j_a_m_i_n )
(= (Distance XB_e_n_j_a_m_i_n XO_l_i_v_e_r )16)
(= (Distance XO_l_i_v_e_r XB_e_n_j_a_m_i_n )16)

(Path XB_e_n_j_a_m_i_n XM_i_c_h_a_e_l )
(Path XM_i_c_h_a_e_l XB_e_n_j_a_m_i_n )
(= (Distance XB_e_n_j_a_m_i_n XM_i_c_h_a_e_l )29)
(= (Distance XM_i_c_h_a_e_l XB_e_n_j_a_m_i_n )29)

(Path XB_e_n_j_a_m_i_n XJ_o_s_e_p_h )
(Path XJ_o_s_e_p_h XB_e_n_j_a_m_i_n )
(= (Distance XB_e_n_j_a_m_i_n XJ_o_s_e_p_h )19)
(= (Distance XJ_o_s_e_p_h XB_e_n_j_a_m_i_n )19)

(Path XB_e_n_j_a_m_i_n XW_y_a_t_t )
(Path XW_y_a_t_t XB_e_n_j_a_m_i_n )
(= (Distance XB_e_n_j_a_m_i_n XW_y_a_t_t )8)
(= (Distance XW_y_a_t_t XB_e_n_j_a_m_i_n )8)

(Path XB_e_n_j_a_m_i_n XJ_o_h_n )
(Path XJ_o_h_n XB_e_n_j_a_m_i_n )
(= (Distance XB_e_n_j_a_m_i_n XJ_o_h_n )25)
(= (Distance XJ_o_h_n XB_e_n_j_a_m_i_n )25)

(Path XB_e_n_j_a_m_i_n XJ_o_s_h_u_a )
(Path XJ_o_s_h_u_a XB_e_n_j_a_m_i_n )
(= (Distance XB_e_n_j_a_m_i_n XJ_o_s_h_u_a )24)
(= (Distance XJ_o_s_h_u_a XB_e_n_j_a_m_i_n )24)

(Path XB_e_n_j_a_m_i_n XN_a_t_h_a_n )
(Path XN_a_t_h_a_n XB_e_n_j_a_m_i_n )
(= (Distance XB_e_n_j_a_m_i_n XN_a_t_h_a_n )8)
(= (Distance XN_a_t_h_a_n XB_e_n_j_a_m_i_n )8)

(Path XB_e_n_j_a_m_i_n XC_a_l_e_b )
(Path XC_a_l_e_b XB_e_n_j_a_m_i_n )
(= (Distance XB_e_n_j_a_m_i_n XC_a_l_e_b )23)
(= (Distance XC_a_l_e_b XB_e_n_j_a_m_i_n )23)

(Path XM_a_s_o_n XE_l_i_j_a_h )
(Path XE_l_i_j_a_h XM_a_s_o_n )
(= (Distance XM_a_s_o_n XE_l_i_j_a_h )1)
(= (Distance XE_l_i_j_a_h XM_a_s_o_n )1)

(Path XM_a_s_o_n XE_t_h_a_n )
(Path XE_t_h_a_n XM_a_s_o_n )
(= (Distance XM_a_s_o_n XE_t_h_a_n )13)
(= (Distance XE_t_h_a_n XM_a_s_o_n )13)

(Path XM_a_s_o_n XS_a_m_u_e_l )
(Path XS_a_m_u_e_l XM_a_s_o_n )
(= (Distance XM_a_s_o_n XS_a_m_u_e_l )4)
(= (Distance XS_a_m_u_e_l XM_a_s_o_n )4)

(Path XM_a_s_o_n XS_e_b_a_s_t_i_a_n )
(Path XS_e_b_a_s_t_i_a_n XM_a_s_o_n )
(= (Distance XM_a_s_o_n XS_e_b_a_s_t_i_a_n )27)
(= (Distance XS_e_b_a_s_t_i_a_n XM_a_s_o_n )27)

(Path XM_a_s_o_n XJ_o_h_n )
(Path XJ_o_h_n XM_a_s_o_n )
(= (Distance XM_a_s_o_n XJ_o_h_n )14)
(= (Distance XJ_o_h_n XM_a_s_o_n )14)

(Path XM_a_s_o_n XI_s_a_a_c )
(Path XI_s_a_a_c XM_a_s_o_n )
(= (Distance XM_a_s_o_n XI_s_a_a_c )29)
(= (Distance XI_s_a_a_c XM_a_s_o_n )29)

(Path XM_a_s_o_n XL_e_v_i )
(Path XL_e_v_i XM_a_s_o_n )
(= (Distance XM_a_s_o_n XL_e_v_i )11)
(= (Distance XL_e_v_i XM_a_s_o_n )11)

(Path XM_a_s_o_n XL_i_n_c_o_l_n )
(Path XL_i_n_c_o_l_n XM_a_s_o_n )
(= (Distance XM_a_s_o_n XL_i_n_c_o_l_n )29)
(= (Distance XL_i_n_c_o_l_n XM_a_s_o_n )29)

(Path XM_a_s_o_n XR_y_a_n )
(Path XR_y_a_n XM_a_s_o_n )
(= (Distance XM_a_s_o_n XR_y_a_n )9)
(= (Distance XR_y_a_n XM_a_s_o_n )9)

(Path XM_a_s_o_n XI_s_a_i_a_h )
(Path XI_s_a_i_a_h XM_a_s_o_n )
(= (Distance XM_a_s_o_n XI_s_a_i_a_h )16)
(= (Distance XI_s_a_i_a_h XM_a_s_o_n )16)

(Path XE_l_i_j_a_h XM_i_c_h_a_e_l )
(Path XM_i_c_h_a_e_l XE_l_i_j_a_h )
(= (Distance XE_l_i_j_a_h XM_i_c_h_a_e_l )21)
(= (Distance XM_i_c_h_a_e_l XE_l_i_j_a_h )21)

(Path XE_l_i_j_a_h XE_t_h_a_n )
(Path XE_t_h_a_n XE_l_i_j_a_h )
(= (Distance XE_l_i_j_a_h XE_t_h_a_n )14)
(= (Distance XE_t_h_a_n XE_l_i_j_a_h )14)

(Path XE_l_i_j_a_h XM_a_t_t_h_e_w )
(Path XM_a_t_t_h_e_w XE_l_i_j_a_h )
(= (Distance XE_l_i_j_a_h XM_a_t_t_h_e_w )17)
(= (Distance XM_a_t_t_h_e_w XE_l_i_j_a_h )17)

(Path XE_l_i_j_a_h XA_n_t_h_o_n_y )
(Path XA_n_t_h_o_n_y XE_l_i_j_a_h )
(= (Distance XE_l_i_j_a_h XA_n_t_h_o_n_y )26)
(= (Distance XA_n_t_h_o_n_y XE_l_i_j_a_h )26)

(Path XE_l_i_j_a_h XM_a_t_e_o )
(Path XM_a_t_e_o XE_l_i_j_a_h )
(= (Distance XE_l_i_j_a_h XM_a_t_e_o )10)
(= (Distance XM_a_t_e_o XE_l_i_j_a_h )10)

(Path XO_l_i_v_e_r XA_l_e_x_a_n_d_e_r )
(Path XA_l_e_x_a_n_d_e_r XO_l_i_v_e_r )
(= (Distance XO_l_i_v_e_r XA_l_e_x_a_n_d_e_r )8)
(= (Distance XA_l_e_x_a_n_d_e_r XO_l_i_v_e_r )8)

(Path XO_l_i_v_e_r XC_a_r_t_e_r )
(Path XC_a_r_t_e_r XO_l_i_v_e_r )
(= (Distance XO_l_i_v_e_r XC_a_r_t_e_r )11)
(= (Distance XC_a_r_t_e_r XO_l_i_v_e_r )11)

(Path XO_l_i_v_e_r XL_u_k_e )
(Path XL_u_k_e XO_l_i_v_e_r )
(= (Distance XO_l_i_v_e_r XL_u_k_e )10)
(= (Distance XL_u_k_e XO_l_i_v_e_r )10)

(Path XO_l_i_v_e_r XG_r_a_y_s_o_n )
(Path XG_r_a_y_s_o_n XO_l_i_v_e_r )
(= (Distance XO_l_i_v_e_r XG_r_a_y_s_o_n )6)
(= (Distance XG_r_a_y_s_o_n XO_l_i_v_e_r )6)

(Path XO_l_i_v_e_r XN_a_t_h_a_n )
(Path XN_a_t_h_a_n XO_l_i_v_e_r )
(= (Distance XO_l_i_v_e_r XN_a_t_h_a_n )18)
(= (Distance XN_a_t_h_a_n XO_l_i_v_e_r )18)

(Path XO_l_i_v_e_r XA_a_r_o_n )
(Path XA_a_r_o_n XO_l_i_v_e_r )
(= (Distance XO_l_i_v_e_r XA_a_r_o_n )5)
(= (Distance XA_a_r_o_n XO_l_i_v_e_r )5)

(Path XO_l_i_v_e_r XC_h_a_r_l_e_s )
(Path XC_h_a_r_l_e_s XO_l_i_v_e_r )
(= (Distance XO_l_i_v_e_r XC_h_a_r_l_e_s )1)
(= (Distance XC_h_a_r_l_e_s XO_l_i_v_e_r )1)

(Path XO_l_i_v_e_r XC_a_l_e_b )
(Path XC_a_l_e_b XO_l_i_v_e_r )
(= (Distance XO_l_i_v_e_r XC_a_l_e_b )19)
(= (Distance XC_a_l_e_b XO_l_i_v_e_r )19)

(Path XJ_a_c_o_b XH_e_n_r_y )
(Path XH_e_n_r_y XJ_a_c_o_b )
(= (Distance XJ_a_c_o_b XH_e_n_r_y )19)
(= (Distance XH_e_n_r_y XJ_a_c_o_b )19)

(Path XJ_a_c_o_b XJ_o_s_e_p_h )
(Path XJ_o_s_e_p_h XJ_a_c_o_b )
(= (Distance XJ_a_c_o_b XJ_o_s_e_p_h )6)
(= (Distance XJ_o_s_e_p_h XJ_a_c_o_b )6)

(Path XJ_a_c_o_b XJ_a_y_d_e_n )
(Path XJ_a_y_d_e_n XJ_a_c_o_b )
(= (Distance XJ_a_c_o_b XJ_a_y_d_e_n )22)
(= (Distance XJ_a_y_d_e_n XJ_a_c_o_b )22)

(Path XJ_a_c_o_b XD_y_l_a_n )
(Path XD_y_l_a_n XJ_a_c_o_b )
(= (Distance XJ_a_c_o_b XD_y_l_a_n )24)
(= (Distance XD_y_l_a_n XJ_a_c_o_b )24)

(Path XJ_a_c_o_b XL_e_v_i )
(Path XL_e_v_i XJ_a_c_o_b )
(= (Distance XJ_a_c_o_b XL_e_v_i )25)
(= (Distance XL_e_v_i XJ_a_c_o_b )25)

(Path XJ_a_c_o_b XL_i_n_c_o_l_n )
(Path XL_i_n_c_o_l_n XJ_a_c_o_b )
(= (Distance XJ_a_c_o_b XL_i_n_c_o_l_n )29)
(= (Distance XL_i_n_c_o_l_n XJ_a_c_o_b )29)

(Path XJ_a_c_o_b XN_a_t_h_a_n )
(Path XN_a_t_h_a_n XJ_a_c_o_b )
(= (Distance XJ_a_c_o_b XN_a_t_h_a_n )22)
(= (Distance XN_a_t_h_a_n XJ_a_c_o_b )22)

(Path XJ_a_c_o_b XC_h_a_r_l_e_s )
(Path XC_h_a_r_l_e_s XJ_a_c_o_b )
(= (Distance XJ_a_c_o_b XC_h_a_r_l_e_s )22)
(= (Distance XC_h_a_r_l_e_s XJ_a_c_o_b )22)

(Path XL_u_c_a_s XJ_a_c_k_s_o_n )
(Path XJ_a_c_k_s_o_n XL_u_c_a_s )
(= (Distance XL_u_c_a_s XJ_a_c_k_s_o_n )6)
(= (Distance XJ_a_c_k_s_o_n XL_u_c_a_s )6)

(Path XL_u_c_a_s XS_e_b_a_s_t_i_a_n )
(Path XS_e_b_a_s_t_i_a_n XL_u_c_a_s )
(= (Distance XL_u_c_a_s XS_e_b_a_s_t_i_a_n )32)
(= (Distance XS_e_b_a_s_t_i_a_n XL_u_c_a_s )32)

(Path XL_u_c_a_s XJ_a_y_d_e_n )
(Path XJ_a_y_d_e_n XL_u_c_a_s )
(= (Distance XL_u_c_a_s XJ_a_y_d_e_n )29)
(= (Distance XJ_a_y_d_e_n XL_u_c_a_s )29)

(Path XL_u_c_a_s XI_s_a_a_c )
(Path XI_s_a_a_c XL_u_c_a_s )
(= (Distance XL_u_c_a_s XI_s_a_a_c )31)
(= (Distance XI_s_a_a_c XL_u_c_a_s )31)

(Path XL_u_c_a_s XJ_u_l_i_a_n )
(Path XJ_u_l_i_a_n XL_u_c_a_s )
(= (Distance XL_u_c_a_s XJ_u_l_i_a_n )3)
(= (Distance XJ_u_l_i_a_n XL_u_c_a_s )3)

(Path XL_u_c_a_s XJ_o_s_h_u_a )
(Path XJ_o_s_h_u_a XL_u_c_a_s )
(= (Distance XL_u_c_a_s XJ_o_s_h_u_a )22)
(= (Distance XJ_o_s_h_u_a XL_u_c_a_s )22)

(Path XL_u_c_a_s XA_n_d_r_e_w )
(Path XA_n_d_r_e_w XL_u_c_a_s )
(= (Distance XL_u_c_a_s XA_n_d_r_e_w )4)
(= (Distance XA_n_d_r_e_w XL_u_c_a_s )4)

(Path XL_u_c_a_s XJ_a_x_o_n )
(Path XJ_a_x_o_n XL_u_c_a_s )
(= (Distance XL_u_c_a_s XJ_a_x_o_n )16)
(= (Distance XJ_a_x_o_n XL_u_c_a_s )16)

(Path XL_u_c_a_s XA_a_r_o_n )
(Path XA_a_r_o_n XL_u_c_a_s )
(= (Distance XL_u_c_a_s XA_a_r_o_n )13)
(= (Distance XA_a_r_o_n XL_u_c_a_s )13)

(Path XM_i_c_h_a_e_l XJ_o_s_e_p_h )
(Path XJ_o_s_e_p_h XM_i_c_h_a_e_l )
(= (Distance XM_i_c_h_a_e_l XJ_o_s_e_p_h )12)
(= (Distance XJ_o_s_e_p_h XM_i_c_h_a_e_l )12)

(Path XM_i_c_h_a_e_l XS_a_m_u_e_l )
(Path XS_a_m_u_e_l XM_i_c_h_a_e_l )
(= (Distance XM_i_c_h_a_e_l XS_a_m_u_e_l )18)
(= (Distance XS_a_m_u_e_l XM_i_c_h_a_e_l )18)

(Path XM_i_c_h_a_e_l XC_a_r_t_e_r )
(Path XC_a_r_t_e_r XM_i_c_h_a_e_l )
(= (Distance XM_i_c_h_a_e_l XC_a_r_t_e_r )18)
(= (Distance XC_a_r_t_e_r XM_i_c_h_a_e_l )18)

(Path XM_i_c_h_a_e_l XO_w_e_n )
(Path XO_w_e_n XM_i_c_h_a_e_l )
(= (Distance XM_i_c_h_a_e_l XO_w_e_n )20)
(= (Distance XO_w_e_n XM_i_c_h_a_e_l )20)

(Path XM_i_c_h_a_e_l XL_u_k_e )
(Path XL_u_k_e XM_i_c_h_a_e_l )
(= (Distance XM_i_c_h_a_e_l XL_u_k_e )5)
(= (Distance XL_u_k_e XM_i_c_h_a_e_l )5)

(Path XM_i_c_h_a_e_l XA_n_t_h_o_n_y )
(Path XA_n_t_h_o_n_y XM_i_c_h_a_e_l )
(= (Distance XM_i_c_h_a_e_l XA_n_t_h_o_n_y )6)
(= (Distance XA_n_t_h_o_n_y XM_i_c_h_a_e_l )6)

(Path XM_i_c_h_a_e_l XJ_u_l_i_a_n )
(Path XJ_u_l_i_a_n XM_i_c_h_a_e_l )
(= (Distance XM_i_c_h_a_e_l XJ_u_l_i_a_n )12)
(= (Distance XJ_u_l_i_a_n XM_i_c_h_a_e_l )12)

(Path XM_i_c_h_a_e_l XL_i_n_c_o_l_n )
(Path XL_i_n_c_o_l_n XM_i_c_h_a_e_l )
(= (Distance XM_i_c_h_a_e_l XL_i_n_c_o_l_n )11)
(= (Distance XL_i_n_c_o_l_n XM_i_c_h_a_e_l )11)

(Path XM_i_c_h_a_e_l XA_a_r_o_n )
(Path XA_a_r_o_n XM_i_c_h_a_e_l )
(= (Distance XM_i_c_h_a_e_l XA_a_r_o_n )10)
(= (Distance XA_a_r_o_n XM_i_c_h_a_e_l )10)

(Path XA_l_e_x_a_n_d_e_r XH_e_n_r_y )
(Path XH_e_n_r_y XA_l_e_x_a_n_d_e_r )
(= (Distance XA_l_e_x_a_n_d_e_r XH_e_n_r_y )1)
(= (Distance XH_e_n_r_y XA_l_e_x_a_n_d_e_r )1)

(Path XA_l_e_x_a_n_d_e_r XS_a_m_u_e_l )
(Path XS_a_m_u_e_l XA_l_e_x_a_n_d_e_r )
(= (Distance XA_l_e_x_a_n_d_e_r XS_a_m_u_e_l )1)
(= (Distance XS_a_m_u_e_l XA_l_e_x_a_n_d_e_r )1)

(Path XA_l_e_x_a_n_d_e_r XJ_a_y_d_e_n )
(Path XJ_a_y_d_e_n XA_l_e_x_a_n_d_e_r )
(= (Distance XA_l_e_x_a_n_d_e_r XJ_a_y_d_e_n )28)
(= (Distance XJ_a_y_d_e_n XA_l_e_x_a_n_d_e_r )28)

(Path XA_l_e_x_a_n_d_e_r XO_w_e_n )
(Path XO_w_e_n XA_l_e_x_a_n_d_e_r )
(= (Distance XA_l_e_x_a_n_d_e_r XO_w_e_n )17)
(= (Distance XO_w_e_n XA_l_e_x_a_n_d_e_r )17)

(Path XA_l_e_x_a_n_d_e_r XG_r_a_y_s_o_n )
(Path XG_r_a_y_s_o_n XA_l_e_x_a_n_d_e_r )
(= (Distance XA_l_e_x_a_n_d_e_r XG_r_a_y_s_o_n )10)
(= (Distance XG_r_a_y_s_o_n XA_l_e_x_a_n_d_e_r )10)

(Path XA_l_e_x_a_n_d_e_r XJ_u_l_i_a_n )
(Path XJ_u_l_i_a_n XA_l_e_x_a_n_d_e_r )
(= (Distance XA_l_e_x_a_n_d_e_r XJ_u_l_i_a_n )7)
(= (Distance XJ_u_l_i_a_n XA_l_e_x_a_n_d_e_r )7)

(Path XA_l_e_x_a_n_d_e_r XA_n_d_r_e_w )
(Path XA_n_d_r_e_w XA_l_e_x_a_n_d_e_r )
(= (Distance XA_l_e_x_a_n_d_e_r XA_n_d_r_e_w )12)
(= (Distance XA_n_d_r_e_w XA_l_e_x_a_n_d_e_r )12)

(Path XA_l_e_x_a_n_d_e_r XM_a_t_e_o )
(Path XM_a_t_e_o XA_l_e_x_a_n_d_e_r )
(= (Distance XA_l_e_x_a_n_d_e_r XM_a_t_e_o )4)
(= (Distance XM_a_t_e_o XA_l_e_x_a_n_d_e_r )4)

(Path XA_l_e_x_a_n_d_e_r XJ_a_x_o_n )
(Path XJ_a_x_o_n XA_l_e_x_a_n_d_e_r )
(= (Distance XA_l_e_x_a_n_d_e_r XJ_a_x_o_n )12)
(= (Distance XJ_a_x_o_n XA_l_e_x_a_n_d_e_r )12)

(Path XA_l_e_x_a_n_d_e_r XI_s_a_i_a_h )
(Path XI_s_a_i_a_h XA_l_e_x_a_n_d_e_r )
(= (Distance XA_l_e_x_a_n_d_e_r XI_s_a_i_a_h )13)
(= (Distance XI_s_a_i_a_h XA_l_e_x_a_n_d_e_r )13)

(Path XA_l_e_x_a_n_d_e_r XT_h_o_m_a_s )
(Path XT_h_o_m_a_s XA_l_e_x_a_n_d_e_r )
(= (Distance XA_l_e_x_a_n_d_e_r XT_h_o_m_a_s )22)
(= (Distance XT_h_o_m_a_s XA_l_e_x_a_n_d_e_r )22)

(Path XE_t_h_a_n XM_a_t_t_h_e_w )
(Path XM_a_t_t_h_e_w XE_t_h_a_n )
(= (Distance XE_t_h_a_n XM_a_t_t_h_e_w )17)
(= (Distance XM_a_t_t_h_e_w XE_t_h_a_n )17)

(Path XE_t_h_a_n XH_e_n_r_y )
(Path XH_e_n_r_y XE_t_h_a_n )
(= (Distance XE_t_h_a_n XH_e_n_r_y )15)
(= (Distance XH_e_n_r_y XE_t_h_a_n )15)

(Path XE_t_h_a_n XJ_o_s_e_p_h )
(Path XJ_o_s_e_p_h XE_t_h_a_n )
(= (Distance XE_t_h_a_n XJ_o_s_e_p_h )12)
(= (Distance XJ_o_s_e_p_h XE_t_h_a_n )12)

(Path XE_t_h_a_n XJ_a_c_k_s_o_n )
(Path XJ_a_c_k_s_o_n XE_t_h_a_n )
(= (Distance XE_t_h_a_n XJ_a_c_k_s_o_n )16)
(= (Distance XJ_a_c_k_s_o_n XE_t_h_a_n )16)

(Path XE_t_h_a_n XJ_a_y_d_e_n )
(Path XJ_a_y_d_e_n XE_t_h_a_n )
(= (Distance XE_t_h_a_n XJ_a_y_d_e_n )26)
(= (Distance XJ_a_y_d_e_n XE_t_h_a_n )26)

(Path XE_t_h_a_n XJ_o_h_n )
(Path XJ_o_h_n XE_t_h_a_n )
(= (Distance XE_t_h_a_n XJ_o_h_n )23)
(= (Distance XJ_o_h_n XE_t_h_a_n )23)

(Path XE_t_h_a_n XJ_u_l_i_a_n )
(Path XJ_u_l_i_a_n XE_t_h_a_n )
(= (Distance XE_t_h_a_n XJ_u_l_i_a_n )7)
(= (Distance XJ_u_l_i_a_n XE_t_h_a_n )7)

(Path XE_t_h_a_n XL_i_n_c_o_l_n )
(Path XL_i_n_c_o_l_n XE_t_h_a_n )
(= (Distance XE_t_h_a_n XL_i_n_c_o_l_n )26)
(= (Distance XL_i_n_c_o_l_n XE_t_h_a_n )26)

(Path XE_t_h_a_n XR_y_a_n )
(Path XR_y_a_n XE_t_h_a_n )
(= (Distance XE_t_h_a_n XR_y_a_n )22)
(= (Distance XR_y_a_n XE_t_h_a_n )22)

(Path XE_t_h_a_n XN_a_t_h_a_n )
(Path XN_a_t_h_a_n XE_t_h_a_n )
(= (Distance XE_t_h_a_n XN_a_t_h_a_n )13)
(= (Distance XN_a_t_h_a_n XE_t_h_a_n )13)

(Path XE_t_h_a_n XT_h_o_m_a_s )
(Path XT_h_o_m_a_s XE_t_h_a_n )
(= (Distance XE_t_h_a_n XT_h_o_m_a_s )22)
(= (Distance XT_h_o_m_a_s XE_t_h_a_n )22)

(Path XE_t_h_a_n XC_h_a_r_l_e_s )
(Path XC_h_a_r_l_e_s XE_t_h_a_n )
(= (Distance XE_t_h_a_n XC_h_a_r_l_e_s )17)
(= (Distance XC_h_a_r_l_e_s XE_t_h_a_n )17)

(Path XD_a_n_i_e_l XJ_o_s_e_p_h )
(Path XJ_o_s_e_p_h XD_a_n_i_e_l )
(= (Distance XD_a_n_i_e_l XJ_o_s_e_p_h )27)
(= (Distance XJ_o_s_e_p_h XD_a_n_i_e_l )27)

(Path XD_a_n_i_e_l XC_a_r_t_e_r )
(Path XC_a_r_t_e_r XD_a_n_i_e_l )
(= (Distance XD_a_n_i_e_l XC_a_r_t_e_r )38)
(= (Distance XC_a_r_t_e_r XD_a_n_i_e_l )38)

(Path XD_a_n_i_e_l XW_y_a_t_t )
(Path XW_y_a_t_t XD_a_n_i_e_l )
(= (Distance XD_a_n_i_e_l XW_y_a_t_t )27)
(= (Distance XW_y_a_t_t XD_a_n_i_e_l )27)

(Path XD_a_n_i_e_l XJ_a_y_d_e_n )
(Path XJ_a_y_d_e_n XD_a_n_i_e_l )
(= (Distance XD_a_n_i_e_l XJ_a_y_d_e_n )19)
(= (Distance XJ_a_y_d_e_n XD_a_n_i_e_l )19)

(Path XD_a_n_i_e_l XJ_o_s_h_u_a )
(Path XJ_o_s_h_u_a XD_a_n_i_e_l )
(= (Distance XD_a_n_i_e_l XJ_o_s_h_u_a )32)
(= (Distance XJ_o_s_h_u_a XD_a_n_i_e_l )32)

(Path XD_a_n_i_e_l XL_i_n_c_o_l_n )
(Path XL_i_n_c_o_l_n XD_a_n_i_e_l )
(= (Distance XD_a_n_i_e_l XL_i_n_c_o_l_n )21)
(= (Distance XL_i_n_c_o_l_n XD_a_n_i_e_l )21)

(Path XD_a_n_i_e_l XM_a_t_e_o )
(Path XM_a_t_e_o XD_a_n_i_e_l )
(= (Distance XD_a_n_i_e_l XM_a_t_e_o )30)
(= (Distance XM_a_t_e_o XD_a_n_i_e_l )30)

(Path XD_a_n_i_e_l XN_a_t_h_a_n )
(Path XN_a_t_h_a_n XD_a_n_i_e_l )
(= (Distance XD_a_n_i_e_l XN_a_t_h_a_n )34)
(= (Distance XN_a_t_h_a_n XD_a_n_i_e_l )34)

(Path XM_a_t_t_h_e_w XJ_o_s_e_p_h )
(Path XJ_o_s_e_p_h XM_a_t_t_h_e_w )
(= (Distance XM_a_t_t_h_e_w XJ_o_s_e_p_h )5)
(= (Distance XJ_o_s_e_p_h XM_a_t_t_h_e_w )5)

(Path XM_a_t_t_h_e_w XD_a_v_i_d )
(Path XD_a_v_i_d XM_a_t_t_h_e_w )
(= (Distance XM_a_t_t_h_e_w XD_a_v_i_d )9)
(= (Distance XD_a_v_i_d XM_a_t_t_h_e_w )9)

(Path XM_a_t_t_h_e_w XG_a_b_r_i_e_l )
(Path XG_a_b_r_i_e_l XM_a_t_t_h_e_w )
(= (Distance XM_a_t_t_h_e_w XG_a_b_r_i_e_l )18)
(= (Distance XG_a_b_r_i_e_l XM_a_t_t_h_e_w )18)

(Path XM_a_t_t_h_e_w XC_h_r_i_s_t_o_p_h_e_r )
(Path XC_h_r_i_s_t_o_p_h_e_r XM_a_t_t_h_e_w )
(= (Distance XM_a_t_t_h_e_w XC_h_r_i_s_t_o_p_h_e_r )14)
(= (Distance XC_h_r_i_s_t_o_p_h_e_r XM_a_t_t_h_e_w )14)

(Path XM_a_t_t_h_e_w XJ_a_x_o_n )
(Path XJ_a_x_o_n XM_a_t_t_h_e_w )
(= (Distance XM_a_t_t_h_e_w XJ_a_x_o_n )8)
(= (Distance XJ_a_x_o_n XM_a_t_t_h_e_w )8)

(Path XM_a_t_t_h_e_w XI_s_a_i_a_h )
(Path XI_s_a_i_a_h XM_a_t_t_h_e_w )
(= (Distance XM_a_t_t_h_e_w XI_s_a_i_a_h )13)
(= (Distance XI_s_a_i_a_h XM_a_t_t_h_e_w )13)

(Path XA_i_d_e_n XJ_o_s_e_p_h )
(Path XJ_o_s_e_p_h XA_i_d_e_n )
(= (Distance XA_i_d_e_n XJ_o_s_e_p_h )14)
(= (Distance XJ_o_s_e_p_h XA_i_d_e_n )14)

(Path XA_i_d_e_n XG_r_a_y_s_o_n )
(Path XG_r_a_y_s_o_n XA_i_d_e_n )
(= (Distance XA_i_d_e_n XG_r_a_y_s_o_n )17)
(= (Distance XG_r_a_y_s_o_n XA_i_d_e_n )17)

(Path XA_i_d_e_n XJ_a_x_o_n )
(Path XJ_a_x_o_n XA_i_d_e_n )
(= (Distance XA_i_d_e_n XJ_a_x_o_n )1)
(= (Distance XJ_a_x_o_n XA_i_d_e_n )1)

(Path XA_i_d_e_n XN_a_t_h_a_n )
(Path XN_a_t_h_a_n XA_i_d_e_n )
(= (Distance XA_i_d_e_n XN_a_t_h_a_n )14)
(= (Distance XN_a_t_h_a_n XA_i_d_e_n )14)

(Path XA_i_d_e_n XA_a_r_o_n )
(Path XA_a_r_o_n XA_i_d_e_n )
(= (Distance XA_i_d_e_n XA_a_r_o_n )16)
(= (Distance XA_a_r_o_n XA_i_d_e_n )16)

(Path XA_i_d_e_n XC_h_a_r_l_e_s )
(Path XC_h_a_r_l_e_s XA_i_d_e_n )
(= (Distance XA_i_d_e_n XC_h_a_r_l_e_s )10)
(= (Distance XC_h_a_r_l_e_s XA_i_d_e_n )10)

(Path XH_e_n_r_y XO_w_e_n )
(Path XO_w_e_n XH_e_n_r_y )
(= (Distance XH_e_n_r_y XO_w_e_n )18)
(= (Distance XO_w_e_n XH_e_n_r_y )18)

(Path XH_e_n_r_y XJ_u_l_i_a_n )
(Path XJ_u_l_i_a_n XH_e_n_r_y )
(= (Distance XH_e_n_r_y XJ_u_l_i_a_n )8)
(= (Distance XJ_u_l_i_a_n XH_e_n_r_y )8)

(Path XH_e_n_r_y XA_n_d_r_e_w )
(Path XA_n_d_r_e_w XH_e_n_r_y )
(= (Distance XH_e_n_r_y XA_n_d_r_e_w )13)
(= (Distance XA_n_d_r_e_w XH_e_n_r_y )13)

(Path XH_e_n_r_y XA_a_r_o_n )
(Path XA_a_r_o_n XH_e_n_r_y )
(= (Distance XH_e_n_r_y XA_a_r_o_n )14)
(= (Distance XA_a_r_o_n XH_e_n_r_y )14)

(Path XH_e_n_r_y XI_s_a_i_a_h )
(Path XI_s_a_i_a_h XH_e_n_r_y )
(= (Distance XH_e_n_r_y XI_s_a_i_a_h )14)
(= (Distance XI_s_a_i_a_h XH_e_n_r_y )14)

(Path XH_e_n_r_y XC_h_a_r_l_e_s )
(Path XC_h_a_r_l_e_s XH_e_n_r_y )
(= (Distance XH_e_n_r_y XC_h_a_r_l_e_s )10)
(= (Distance XC_h_a_r_l_e_s XH_e_n_r_y )10)

(Path XJ_o_s_e_p_h XC_a_r_t_e_r )
(Path XC_a_r_t_e_r XJ_o_s_e_p_h )
(= (Distance XJ_o_s_e_p_h XC_a_r_t_e_r )19)
(= (Distance XC_a_r_t_e_r XJ_o_s_e_p_h )19)

(Path XJ_o_s_e_p_h XJ_o_h_n )
(Path XJ_o_h_n XJ_o_s_e_p_h )
(= (Distance XJ_o_s_e_p_h XJ_o_h_n )29)
(= (Distance XJ_o_h_n XJ_o_s_e_p_h )29)

(Path XJ_o_s_e_p_h XJ_u_l_i_a_n )
(Path XJ_u_l_i_a_n XJ_o_s_e_p_h )
(= (Distance XJ_o_s_e_p_h XJ_u_l_i_a_n )19)
(= (Distance XJ_u_l_i_a_n XJ_o_s_e_p_h )19)

(Path XJ_o_s_e_p_h XJ_o_s_h_u_a )
(Path XJ_o_s_h_u_a XJ_o_s_e_p_h )
(= (Distance XJ_o_s_e_p_h XJ_o_s_h_u_a )5)
(= (Distance XJ_o_s_h_u_a XJ_o_s_e_p_h )5)

(Path XJ_o_s_e_p_h XA_n_d_r_e_w )
(Path XA_n_d_r_e_w XJ_o_s_e_p_h )
(= (Distance XJ_o_s_e_p_h XA_n_d_r_e_w )13)
(= (Distance XA_n_d_r_e_w XJ_o_s_e_p_h )13)

(Path XJ_o_s_e_p_h XM_a_t_e_o )
(Path XM_a_t_e_o XJ_o_s_e_p_h )
(= (Distance XJ_o_s_e_p_h XM_a_t_e_o )9)
(= (Distance XM_a_t_e_o XJ_o_s_e_p_h )9)

(Path XJ_o_s_e_p_h XI_s_a_i_a_h )
(Path XI_s_a_i_a_h XJ_o_s_e_p_h )
(= (Distance XJ_o_s_e_p_h XI_s_a_i_a_h )18)
(= (Distance XI_s_a_i_a_h XJ_o_s_e_p_h )18)

(Path XJ_o_s_e_p_h XC_a_l_e_b )
(Path XC_a_l_e_b XJ_o_s_e_p_h )
(= (Distance XJ_o_s_e_p_h XC_a_l_e_b )27)
(= (Distance XC_a_l_e_b XJ_o_s_e_p_h )27)

(Path XJ_a_c_k_s_o_n XS_e_b_a_s_t_i_a_n )
(Path XS_e_b_a_s_t_i_a_n XJ_a_c_k_s_o_n )
(= (Distance XJ_a_c_k_s_o_n XS_e_b_a_s_t_i_a_n )38)
(= (Distance XS_e_b_a_s_t_i_a_n XJ_a_c_k_s_o_n )38)

(Path XJ_a_c_k_s_o_n XO_w_e_n )
(Path XO_w_e_n XJ_a_c_k_s_o_n )
(= (Distance XJ_a_c_k_s_o_n XO_w_e_n )15)
(= (Distance XO_w_e_n XJ_a_c_k_s_o_n )15)

(Path XJ_a_c_k_s_o_n XG_a_b_r_i_e_l )
(Path XG_a_b_r_i_e_l XJ_a_c_k_s_o_n )
(= (Distance XJ_a_c_k_s_o_n XG_a_b_r_i_e_l )12)
(= (Distance XG_a_b_r_i_e_l XJ_a_c_k_s_o_n )12)

(Path XJ_a_c_k_s_o_n XA_n_t_h_o_n_y )
(Path XA_n_t_h_o_n_y XJ_a_c_k_s_o_n )
(= (Distance XJ_a_c_k_s_o_n XA_n_t_h_o_n_y )27)
(= (Distance XA_n_t_h_o_n_y XJ_a_c_k_s_o_n )27)

(Path XJ_a_c_k_s_o_n XL_e_v_i )
(Path XL_e_v_i XJ_a_c_k_s_o_n )
(= (Distance XJ_a_c_k_s_o_n XL_e_v_i )21)
(= (Distance XL_e_v_i XJ_a_c_k_s_o_n )21)

(Path XJ_a_c_k_s_o_n XC_h_r_i_s_t_o_p_h_e_r )
(Path XC_h_r_i_s_t_o_p_h_e_r XJ_a_c_k_s_o_n )
(= (Distance XJ_a_c_k_s_o_n XC_h_r_i_s_t_o_p_h_e_r )8)
(= (Distance XC_h_r_i_s_t_o_p_h_e_r XJ_a_c_k_s_o_n )8)

(Path XJ_a_c_k_s_o_n XN_a_t_h_a_n )
(Path XN_a_t_h_a_n XJ_a_c_k_s_o_n )
(= (Distance XJ_a_c_k_s_o_n XN_a_t_h_a_n )4)
(= (Distance XN_a_t_h_a_n XJ_a_c_k_s_o_n )4)

(Path XS_a_m_u_e_l XS_e_b_a_s_t_i_a_n )
(Path XS_e_b_a_s_t_i_a_n XS_a_m_u_e_l )
(= (Distance XS_a_m_u_e_l XS_e_b_a_s_t_i_a_n )31)
(= (Distance XS_e_b_a_s_t_i_a_n XS_a_m_u_e_l )31)

(Path XS_a_m_u_e_l XJ_a_y_d_e_n )
(Path XJ_a_y_d_e_n XS_a_m_u_e_l )
(= (Distance XS_a_m_u_e_l XJ_a_y_d_e_n )27)
(= (Distance XJ_a_y_d_e_n XS_a_m_u_e_l )27)

(Path XS_a_m_u_e_l XJ_o_h_n )
(Path XJ_o_h_n XS_a_m_u_e_l )
(= (Distance XS_a_m_u_e_l XJ_o_h_n )18)
(= (Distance XJ_o_h_n XS_a_m_u_e_l )18)

(Path XS_a_m_u_e_l XG_a_b_r_i_e_l )
(Path XG_a_b_r_i_e_l XS_a_m_u_e_l )
(= (Distance XS_a_m_u_e_l XG_a_b_r_i_e_l )15)
(= (Distance XG_a_b_r_i_e_l XS_a_m_u_e_l )15)

(Path XS_a_m_u_e_l XA_n_t_h_o_n_y )
(Path XA_n_t_h_o_n_y XS_a_m_u_e_l )
(= (Distance XS_a_m_u_e_l XA_n_t_h_o_n_y )24)
(= (Distance XA_n_t_h_o_n_y XS_a_m_u_e_l )24)

(Path XS_a_m_u_e_l XJ_u_l_i_a_n )
(Path XJ_u_l_i_a_n XS_a_m_u_e_l )
(= (Distance XS_a_m_u_e_l XJ_u_l_i_a_n )6)
(= (Distance XJ_u_l_i_a_n XS_a_m_u_e_l )6)

(Path XS_a_m_u_e_l XR_y_a_n )
(Path XR_y_a_n XS_a_m_u_e_l )
(= (Distance XS_a_m_u_e_l XR_y_a_n )12)
(= (Distance XR_y_a_n XS_a_m_u_e_l )12)

(Path XS_a_m_u_e_l XC_h_a_r_l_e_s )
(Path XC_h_a_r_l_e_s XS_a_m_u_e_l )
(= (Distance XS_a_m_u_e_l XC_h_a_r_l_e_s )10)
(= (Distance XC_h_a_r_l_e_s XS_a_m_u_e_l )10)

(Path XS_e_b_a_s_t_i_a_n XI_s_a_a_c )
(Path XI_s_a_a_c XS_e_b_a_s_t_i_a_n )
(= (Distance XS_e_b_a_s_t_i_a_n XI_s_a_a_c )10)
(= (Distance XI_s_a_a_c XS_e_b_a_s_t_i_a_n )10)

(Path XS_e_b_a_s_t_i_a_n XR_y_a_n )
(Path XR_y_a_n XS_e_b_a_s_t_i_a_n )
(= (Distance XS_e_b_a_s_t_i_a_n XR_y_a_n )32)
(= (Distance XR_y_a_n XS_e_b_a_s_t_i_a_n )32)

(Path XS_e_b_a_s_t_i_a_n XJ_a_x_o_n )
(Path XJ_a_x_o_n XS_e_b_a_s_t_i_a_n )
(= (Distance XS_e_b_a_s_t_i_a_n XJ_a_x_o_n )27)
(= (Distance XJ_a_x_o_n XS_e_b_a_s_t_i_a_n )27)

(Path XD_a_v_i_d XA_n_t_h_o_n_y )
(Path XA_n_t_h_o_n_y XD_a_v_i_d )
(= (Distance XD_a_v_i_d XA_n_t_h_o_n_y )25)
(= (Distance XA_n_t_h_o_n_y XD_a_v_i_d )25)

(Path XD_a_v_i_d XL_i_n_c_o_l_n )
(Path XL_i_n_c_o_l_n XD_a_v_i_d )
(= (Distance XD_a_v_i_d XL_i_n_c_o_l_n )29)
(= (Distance XL_i_n_c_o_l_n XD_a_v_i_d )29)

(Path XD_a_v_i_d XR_y_a_n )
(Path XR_y_a_n XD_a_v_i_d )
(= (Distance XD_a_v_i_d XR_y_a_n )14)
(= (Distance XR_y_a_n XD_a_v_i_d )14)

(Path XD_a_v_i_d XJ_a_x_o_n )
(Path XJ_a_x_o_n XD_a_v_i_d )
(= (Distance XD_a_v_i_d XJ_a_x_o_n )1)
(= (Distance XJ_a_x_o_n XD_a_v_i_d )1)

(Path XD_a_v_i_d XC_a_l_e_b )
(Path XC_a_l_e_b XD_a_v_i_d )
(= (Distance XD_a_v_i_d XC_a_l_e_b )16)
(= (Distance XC_a_l_e_b XD_a_v_i_d )16)

(Path XC_a_r_t_e_r XJ_o_h_n )
(Path XJ_o_h_n XC_a_r_t_e_r )
(= (Distance XC_a_r_t_e_r XJ_o_h_n )16)
(= (Distance XJ_o_h_n XC_a_r_t_e_r )16)

(Path XC_a_r_t_e_r XL_u_k_e )
(Path XL_u_k_e XC_a_r_t_e_r )
(= (Distance XC_a_r_t_e_r XL_u_k_e )13)
(= (Distance XL_u_k_e XC_a_r_t_e_r )13)

(Path XC_a_r_t_e_r XG_a_b_r_i_e_l )
(Path XG_a_b_r_i_e_l XC_a_r_t_e_r )
(= (Distance XC_a_r_t_e_r XG_a_b_r_i_e_l )13)
(= (Distance XG_a_b_r_i_e_l XC_a_r_t_e_r )13)

(Path XC_a_r_t_e_r XJ_a_c_k )
(Path XJ_a_c_k XC_a_r_t_e_r )
(= (Distance XC_a_r_t_e_r XJ_a_c_k )11)
(= (Distance XJ_a_c_k XC_a_r_t_e_r )11)

(Path XC_a_r_t_e_r XJ_u_l_i_a_n )
(Path XJ_u_l_i_a_n XC_a_r_t_e_r )
(= (Distance XC_a_r_t_e_r XJ_u_l_i_a_n )12)
(= (Distance XJ_u_l_i_a_n XC_a_r_t_e_r )12)

(Path XC_a_r_t_e_r XM_a_t_e_o )
(Path XM_a_t_e_o XC_a_r_t_e_r )
(= (Distance XC_a_r_t_e_r XM_a_t_e_o )11)
(= (Distance XM_a_t_e_o XC_a_r_t_e_r )11)

(Path XC_a_r_t_e_r XN_a_t_h_a_n )
(Path XN_a_t_h_a_n XC_a_r_t_e_r )
(= (Distance XC_a_r_t_e_r XN_a_t_h_a_n )21)
(= (Distance XN_a_t_h_a_n XC_a_r_t_e_r )21)

(Path XC_a_r_t_e_r XI_s_a_i_a_h )
(Path XI_s_a_i_a_h XC_a_r_t_e_r )
(= (Distance XC_a_r_t_e_r XI_s_a_i_a_h )16)
(= (Distance XI_s_a_i_a_h XC_a_r_t_e_r )16)

(Path XC_a_r_t_e_r XC_a_l_e_b )
(Path XC_a_l_e_b XC_a_r_t_e_r )
(= (Distance XC_a_r_t_e_r XC_a_l_e_b )26)
(= (Distance XC_a_l_e_b XC_a_r_t_e_r )26)

(Path XW_y_a_t_t XO_w_e_n )
(Path XO_w_e_n XW_y_a_t_t )
(= (Distance XW_y_a_t_t XO_w_e_n )10)
(= (Distance XO_w_e_n XW_y_a_t_t )10)

(Path XW_y_a_t_t XD_y_l_a_n )
(Path XD_y_l_a_n XW_y_a_t_t )
(= (Distance XW_y_a_t_t XD_y_l_a_n )3)
(= (Distance XD_y_l_a_n XW_y_a_t_t )3)

(Path XW_y_a_t_t XN_a_t_h_a_n )
(Path XN_a_t_h_a_n XW_y_a_t_t )
(= (Distance XW_y_a_t_t XN_a_t_h_a_n )16)
(= (Distance XN_a_t_h_a_n XW_y_a_t_t )16)

(Path XW_y_a_t_t XT_h_o_m_a_s )
(Path XT_h_o_m_a_s XW_y_a_t_t )
(= (Distance XW_y_a_t_t XT_h_o_m_a_s )22)
(= (Distance XT_h_o_m_a_s XW_y_a_t_t )22)

(Path XJ_a_y_d_e_n XJ_o_h_n )
(Path XJ_o_h_n XJ_a_y_d_e_n )
(= (Distance XJ_a_y_d_e_n XJ_o_h_n )12)
(= (Distance XJ_o_h_n XJ_a_y_d_e_n )12)

(Path XJ_a_y_d_e_n XD_y_l_a_n )
(Path XD_y_l_a_n XJ_a_y_d_e_n )
(= (Distance XJ_a_y_d_e_n XD_y_l_a_n )37)
(= (Distance XD_y_l_a_n XJ_a_y_d_e_n )37)

(Path XJ_a_y_d_e_n XA_n_d_r_e_w )
(Path XA_n_d_r_e_w XJ_a_y_d_e_n )
(= (Distance XJ_a_y_d_e_n XA_n_d_r_e_w )25)
(= (Distance XA_n_d_r_e_w XJ_a_y_d_e_n )25)

(Path XJ_a_y_d_e_n XR_y_a_n )
(Path XR_y_a_n XJ_a_y_d_e_n )
(= (Distance XJ_a_y_d_e_n XR_y_a_n )27)
(= (Distance XR_y_a_n XJ_a_y_d_e_n )27)

(Path XJ_a_y_d_e_n XI_s_a_i_a_h )
(Path XI_s_a_i_a_h XJ_a_y_d_e_n )
(= (Distance XJ_a_y_d_e_n XI_s_a_i_a_h )18)
(= (Distance XI_s_a_i_a_h XJ_a_y_d_e_n )18)

(Path XJ_a_y_d_e_n XT_h_o_m_a_s )
(Path XT_h_o_m_a_s XJ_a_y_d_e_n )
(= (Distance XJ_a_y_d_e_n XT_h_o_m_a_s )13)
(= (Distance XT_h_o_m_a_s XJ_a_y_d_e_n )13)

(Path XJ_a_y_d_e_n XC_a_l_e_b )
(Path XC_a_l_e_b XJ_a_y_d_e_n )
(= (Distance XJ_a_y_d_e_n XC_a_l_e_b )33)
(= (Distance XC_a_l_e_b XJ_a_y_d_e_n )33)

(Path XJ_o_h_n XA_n_t_h_o_n_y )
(Path XA_n_t_h_o_n_y XJ_o_h_n )
(= (Distance XJ_o_h_n XA_n_t_h_o_n_y )11)
(= (Distance XA_n_t_h_o_n_y XJ_o_h_n )11)

(Path XJ_o_h_n XG_r_a_y_s_o_n )
(Path XG_r_a_y_s_o_n XJ_o_h_n )
(= (Distance XJ_o_h_n XG_r_a_y_s_o_n )19)
(= (Distance XG_r_a_y_s_o_n XJ_o_h_n )19)

(Path XJ_o_h_n XI_s_a_i_a_h )
(Path XI_s_a_i_a_h XJ_o_h_n )
(= (Distance XJ_o_h_n XI_s_a_i_a_h )24)
(= (Distance XI_s_a_i_a_h XJ_o_h_n )24)

(Path XJ_o_h_n XC_a_l_e_b )
(Path XC_a_l_e_b XJ_o_h_n )
(= (Distance XJ_o_h_n XC_a_l_e_b )27)
(= (Distance XC_a_l_e_b XJ_o_h_n )27)

(Path XO_w_e_n XA_n_d_r_e_w )
(Path XA_n_d_r_e_w XO_w_e_n )
(= (Distance XO_w_e_n XA_n_d_r_e_w )5)
(= (Distance XA_n_d_r_e_w XO_w_e_n )5)

(Path XO_w_e_n XM_a_t_e_o )
(Path XM_a_t_e_o XO_w_e_n )
(= (Distance XO_w_e_n XM_a_t_e_o )21)
(= (Distance XM_a_t_e_o XO_w_e_n )21)

(Path XO_w_e_n XN_a_t_h_a_n )
(Path XN_a_t_h_a_n XO_w_e_n )
(= (Distance XO_w_e_n XN_a_t_h_a_n )17)
(= (Distance XN_a_t_h_a_n XO_w_e_n )17)

(Path XO_w_e_n XC_h_a_r_l_e_s )
(Path XC_h_a_r_l_e_s XO_w_e_n )
(= (Distance XO_w_e_n XC_h_a_r_l_e_s )8)
(= (Distance XC_h_a_r_l_e_s XO_w_e_n )8)

(Path XD_y_l_a_n XJ_u_l_i_a_n )
(Path XJ_u_l_i_a_n XD_y_l_a_n )
(= (Distance XD_y_l_a_n XJ_u_l_i_a_n )25)
(= (Distance XJ_u_l_i_a_n XD_y_l_a_n )25)

(Path XD_y_l_a_n XJ_o_s_h_u_a )
(Path XJ_o_s_h_u_a XD_y_l_a_n )
(= (Distance XD_y_l_a_n XJ_o_s_h_u_a )16)
(= (Distance XJ_o_s_h_u_a XD_y_l_a_n )16)

(Path XD_y_l_a_n XA_n_d_r_e_w )
(Path XA_n_d_r_e_w XD_y_l_a_n )
(= (Distance XD_y_l_a_n XA_n_d_r_e_w )18)
(= (Distance XA_n_d_r_e_w XD_y_l_a_n )18)

(Path XD_y_l_a_n XL_i_n_c_o_l_n )
(Path XL_i_n_c_o_l_n XD_y_l_a_n )
(= (Distance XD_y_l_a_n XL_i_n_c_o_l_n )29)
(= (Distance XL_i_n_c_o_l_n XD_y_l_a_n )29)

(Path XL_u_k_e XJ_u_l_i_a_n )
(Path XJ_u_l_i_a_n XL_u_k_e )
(= (Distance XL_u_k_e XJ_u_l_i_a_n )7)
(= (Distance XJ_u_l_i_a_n XL_u_k_e )7)

(Path XL_u_k_e XJ_a_x_o_n )
(Path XJ_a_x_o_n XL_u_k_e )
(= (Distance XL_u_k_e XJ_a_x_o_n )18)
(= (Distance XJ_a_x_o_n XL_u_k_e )18)

(Path XL_u_k_e XA_a_r_o_n )
(Path XA_a_r_o_n XL_u_k_e )
(= (Distance XL_u_k_e XA_a_r_o_n )5)
(= (Distance XA_a_r_o_n XL_u_k_e )5)

(Path XL_u_k_e XT_h_o_m_a_s )
(Path XT_h_o_m_a_s XL_u_k_e )
(= (Distance XL_u_k_e XT_h_o_m_a_s )18)
(= (Distance XT_h_o_m_a_s XL_u_k_e )18)

(Path XL_u_k_e XC_h_a_r_l_e_s )
(Path XC_h_a_r_l_e_s XL_u_k_e )
(= (Distance XL_u_k_e XC_h_a_r_l_e_s )11)
(= (Distance XC_h_a_r_l_e_s XL_u_k_e )11)

(Path XG_a_b_r_i_e_l XG_r_a_y_s_o_n )
(Path XG_r_a_y_s_o_n XG_a_b_r_i_e_l )
(= (Distance XG_a_b_r_i_e_l XG_r_a_y_s_o_n )11)
(= (Distance XG_r_a_y_s_o_n XG_a_b_r_i_e_l )11)

(Path XG_a_b_r_i_e_l XJ_a_c_k )
(Path XJ_a_c_k XG_a_b_r_i_e_l )
(= (Distance XG_a_b_r_i_e_l XJ_a_c_k )5)
(= (Distance XJ_a_c_k XG_a_b_r_i_e_l )5)

(Path XG_a_b_r_i_e_l XC_h_r_i_s_t_o_p_h_e_r )
(Path XC_h_r_i_s_t_o_p_h_e_r XG_a_b_r_i_e_l )
(= (Distance XG_a_b_r_i_e_l XC_h_r_i_s_t_o_p_h_e_r )4)
(= (Distance XC_h_r_i_s_t_o_p_h_e_r XG_a_b_r_i_e_l )4)

(Path XG_a_b_r_i_e_l XJ_o_s_h_u_a )
(Path XJ_o_s_h_u_a XG_a_b_r_i_e_l )
(= (Distance XG_a_b_r_i_e_l XJ_o_s_h_u_a )12)
(= (Distance XJ_o_s_h_u_a XG_a_b_r_i_e_l )12)

(Path XG_a_b_r_i_e_l XA_n_d_r_e_w )
(Path XA_n_d_r_e_w XG_a_b_r_i_e_l )
(= (Distance XG_a_b_r_i_e_l XA_n_d_r_e_w )17)
(= (Distance XA_n_d_r_e_w XG_a_b_r_i_e_l )17)

(Path XG_a_b_r_i_e_l XN_a_t_h_a_n )
(Path XN_a_t_h_a_n XG_a_b_r_i_e_l )
(= (Distance XG_a_b_r_i_e_l XN_a_t_h_a_n )16)
(= (Distance XN_a_t_h_a_n XG_a_b_r_i_e_l )16)

(Path XA_n_t_h_o_n_y XT_h_o_m_a_s )
(Path XT_h_o_m_a_s XA_n_t_h_o_n_y )
(= (Distance XA_n_t_h_o_n_y XT_h_o_m_a_s )15)
(= (Distance XT_h_o_m_a_s XA_n_t_h_o_n_y )15)

(Path XA_n_t_h_o_n_y XC_h_a_r_l_e_s )
(Path XC_h_a_r_l_e_s XA_n_t_h_o_n_y )
(= (Distance XA_n_t_h_o_n_y XC_h_a_r_l_e_s )22)
(= (Distance XC_h_a_r_l_e_s XA_n_t_h_o_n_y )22)

(Path XI_s_a_a_c XJ_u_l_i_a_n )
(Path XJ_u_l_i_a_n XI_s_a_a_c )
(= (Distance XI_s_a_a_c XJ_u_l_i_a_n )28)
(= (Distance XJ_u_l_i_a_n XI_s_a_a_c )28)

(Path XI_s_a_a_c XC_h_r_i_s_t_o_p_h_e_r )
(Path XC_h_r_i_s_t_o_p_h_e_r XI_s_a_a_c )
(= (Distance XI_s_a_a_c XC_h_r_i_s_t_o_p_h_e_r )37)
(= (Distance XC_h_r_i_s_t_o_p_h_e_r XI_s_a_a_c )37)

(Path XI_s_a_a_c XJ_o_s_h_u_a )
(Path XJ_o_s_h_u_a XI_s_a_a_c )
(= (Distance XI_s_a_a_c XJ_o_s_h_u_a )29)
(= (Distance XJ_o_s_h_u_a XI_s_a_a_c )29)

(Path XI_s_a_a_c XM_a_t_e_o )
(Path XM_a_t_e_o XI_s_a_a_c )
(= (Distance XI_s_a_a_c XM_a_t_e_o )26)
(= (Distance XM_a_t_e_o XI_s_a_a_c )26)

(Path XI_s_a_a_c XR_y_a_n )
(Path XR_y_a_n XI_s_a_a_c )
(= (Distance XI_s_a_a_c XR_y_a_n )38)
(= (Distance XR_y_a_n XI_s_a_a_c )38)

(Path XI_s_a_a_c XA_a_r_o_n )
(Path XA_a_r_o_n XI_s_a_a_c )
(= (Distance XI_s_a_a_c XA_a_r_o_n )33)
(= (Distance XA_a_r_o_n XI_s_a_a_c )33)

(Path XI_s_a_a_c XI_s_a_i_a_h )
(Path XI_s_a_i_a_h XI_s_a_a_c )
(= (Distance XI_s_a_a_c XI_s_a_i_a_h )31)
(= (Distance XI_s_a_i_a_h XI_s_a_a_c )31)

(Path XI_s_a_a_c XC_h_a_r_l_e_s )
(Path XC_h_a_r_l_e_s XI_s_a_a_c )
(= (Distance XI_s_a_a_c XC_h_a_r_l_e_s )35)
(= (Distance XC_h_a_r_l_e_s XI_s_a_a_c )35)

(Path XG_r_a_y_s_o_n XJ_a_c_k )
(Path XJ_a_c_k XG_r_a_y_s_o_n )
(= (Distance XG_r_a_y_s_o_n XJ_a_c_k )6)
(= (Distance XJ_a_c_k XG_r_a_y_s_o_n )6)

(Path XG_r_a_y_s_o_n XJ_u_l_i_a_n )
(Path XJ_u_l_i_a_n XG_r_a_y_s_o_n )
(= (Distance XG_r_a_y_s_o_n XJ_u_l_i_a_n )8)
(= (Distance XJ_u_l_i_a_n XG_r_a_y_s_o_n )8)

(Path XG_r_a_y_s_o_n XA_n_d_r_e_w )
(Path XA_n_d_r_e_w XG_r_a_y_s_o_n )
(= (Distance XG_r_a_y_s_o_n XA_n_d_r_e_w )10)
(= (Distance XA_n_d_r_e_w XG_r_a_y_s_o_n )10)

(Path XG_r_a_y_s_o_n XN_a_t_h_a_n )
(Path XN_a_t_h_a_n XG_r_a_y_s_o_n )
(= (Distance XG_r_a_y_s_o_n XN_a_t_h_a_n )19)
(= (Distance XN_a_t_h_a_n XG_r_a_y_s_o_n )19)

(Path XJ_a_c_k XJ_u_l_i_a_n )
(Path XJ_u_l_i_a_n XJ_a_c_k )
(= (Distance XJ_a_c_k XJ_u_l_i_a_n )11)
(= (Distance XJ_u_l_i_a_n XJ_a_c_k )11)

(Path XJ_a_c_k XC_h_r_i_s_t_o_p_h_e_r )
(Path XC_h_r_i_s_t_o_p_h_e_r XJ_a_c_k )
(= (Distance XJ_a_c_k XC_h_r_i_s_t_o_p_h_e_r )1)
(= (Distance XC_h_r_i_s_t_o_p_h_e_r XJ_a_c_k )1)

(Path XJ_a_c_k XL_i_n_c_o_l_n )
(Path XL_i_n_c_o_l_n XJ_a_c_k )
(= (Distance XJ_a_c_k XL_i_n_c_o_l_n )30)
(= (Distance XL_i_n_c_o_l_n XJ_a_c_k )30)

(Path XJ_a_c_k XR_y_a_n )
(Path XR_y_a_n XJ_a_c_k )
(= (Distance XJ_a_c_k XR_y_a_n )12)
(= (Distance XR_y_a_n XJ_a_c_k )12)

(Path XJ_a_c_k XN_a_t_h_a_n )
(Path XN_a_t_h_a_n XJ_a_c_k )
(= (Distance XJ_a_c_k XN_a_t_h_a_n )13)
(= (Distance XN_a_t_h_a_n XJ_a_c_k )13)

(Path XJ_u_l_i_a_n XL_e_v_i )
(Path XL_e_v_i XJ_u_l_i_a_n )
(= (Distance XJ_u_l_i_a_n XL_e_v_i )12)
(= (Distance XL_e_v_i XJ_u_l_i_a_n )12)

(Path XJ_u_l_i_a_n XC_h_r_i_s_t_o_p_h_e_r )
(Path XC_h_r_i_s_t_o_p_h_e_r XJ_u_l_i_a_n )
(= (Distance XJ_u_l_i_a_n XC_h_r_i_s_t_o_p_h_e_r )12)
(= (Distance XC_h_r_i_s_t_o_p_h_e_r XJ_u_l_i_a_n )12)

(Path XJ_u_l_i_a_n XT_h_o_m_a_s )
(Path XT_h_o_m_a_s XJ_u_l_i_a_n )
(= (Distance XJ_u_l_i_a_n XT_h_o_m_a_s )15)
(= (Distance XT_h_o_m_a_s XJ_u_l_i_a_n )15)

(Path XL_e_v_i XR_y_a_n )
(Path XR_y_a_n XL_e_v_i )
(= (Distance XL_e_v_i XR_y_a_n )20)
(= (Distance XR_y_a_n XL_e_v_i )20)

(Path XL_e_v_i XI_s_a_i_a_h )
(Path XI_s_a_i_a_h XL_e_v_i )
(= (Distance XL_e_v_i XI_s_a_i_a_h )21)
(= (Distance XI_s_a_i_a_h XL_e_v_i )21)

(Path XC_h_r_i_s_t_o_p_h_e_r XM_a_t_e_o )
(Path XM_a_t_e_o XC_h_r_i_s_t_o_p_h_e_r )
(= (Distance XC_h_r_i_s_t_o_p_h_e_r XM_a_t_e_o )20)
(= (Distance XM_a_t_e_o XC_h_r_i_s_t_o_p_h_e_r )20)

(Path XC_h_r_i_s_t_o_p_h_e_r XT_h_o_m_a_s )
(Path XT_h_o_m_a_s XC_h_r_i_s_t_o_p_h_e_r )
(= (Distance XC_h_r_i_s_t_o_p_h_e_r XT_h_o_m_a_s )27)
(= (Distance XT_h_o_m_a_s XC_h_r_i_s_t_o_p_h_e_r )27)

(Path XC_h_r_i_s_t_o_p_h_e_r XC_h_a_r_l_e_s )
(Path XC_h_a_r_l_e_s XC_h_r_i_s_t_o_p_h_e_r )
(= (Distance XC_h_r_i_s_t_o_p_h_e_r XC_h_a_r_l_e_s )10)
(= (Distance XC_h_a_r_l_e_s XC_h_r_i_s_t_o_p_h_e_r )10)

(Path XC_h_r_i_s_t_o_p_h_e_r XC_a_l_e_b )
(Path XC_a_l_e_b XC_h_r_i_s_t_o_p_h_e_r )
(= (Distance XC_h_r_i_s_t_o_p_h_e_r XC_a_l_e_b )28)
(= (Distance XC_a_l_e_b XC_h_r_i_s_t_o_p_h_e_r )28)

(Path XJ_o_s_h_u_a XJ_a_x_o_n )
(Path XJ_a_x_o_n XJ_o_s_h_u_a )
(= (Distance XJ_o_s_h_u_a XJ_a_x_o_n )18)
(= (Distance XJ_a_x_o_n XJ_o_s_h_u_a )18)

(Path XJ_o_s_h_u_a XN_a_t_h_a_n )
(Path XN_a_t_h_a_n XJ_o_s_h_u_a )
(= (Distance XJ_o_s_h_u_a XN_a_t_h_a_n )20)
(= (Distance XN_a_t_h_a_n XJ_o_s_h_u_a )20)

(Path XJ_o_s_h_u_a XA_a_r_o_n )
(Path XA_a_r_o_n XJ_o_s_h_u_a )
(= (Distance XJ_o_s_h_u_a XA_a_r_o_n )25)
(= (Distance XA_a_r_o_n XJ_o_s_h_u_a )25)

(Path XJ_o_s_h_u_a XT_h_o_m_a_s )
(Path XT_h_o_m_a_s XJ_o_s_h_u_a )
(= (Distance XJ_o_s_h_u_a XT_h_o_m_a_s )30)
(= (Distance XT_h_o_m_a_s XJ_o_s_h_u_a )30)

(Path XJ_o_s_h_u_a XC_h_a_r_l_e_s )
(Path XC_h_a_r_l_e_s XJ_o_s_h_u_a )
(= (Distance XJ_o_s_h_u_a XC_h_a_r_l_e_s )21)
(= (Distance XC_h_a_r_l_e_s XJ_o_s_h_u_a )21)

(Path XA_n_d_r_e_w XN_a_t_h_a_n )
(Path XN_a_t_h_a_n XA_n_d_r_e_w )
(= (Distance XA_n_d_r_e_w XN_a_t_h_a_n )14)
(= (Distance XN_a_t_h_a_n XA_n_d_r_e_w )14)

(Path XA_n_d_r_e_w XC_h_a_r_l_e_s )
(Path XC_h_a_r_l_e_s XA_n_d_r_e_w )
(= (Distance XA_n_d_r_e_w XC_h_a_r_l_e_s )3)
(= (Distance XC_h_a_r_l_e_s XA_n_d_r_e_w )3)

(Path XA_n_d_r_e_w XC_a_l_e_b )
(Path XC_a_l_e_b XA_n_d_r_e_w )
(= (Distance XA_n_d_r_e_w XC_a_l_e_b )15)
(= (Distance XC_a_l_e_b XA_n_d_r_e_w )15)

(Path XL_i_n_c_o_l_n XM_a_t_e_o )
(Path XM_a_t_e_o XL_i_n_c_o_l_n )
(= (Distance XL_i_n_c_o_l_n XM_a_t_e_o )27)
(= (Distance XM_a_t_e_o XL_i_n_c_o_l_n )27)

(Path XL_i_n_c_o_l_n XT_h_o_m_a_s )
(Path XT_h_o_m_a_s XL_i_n_c_o_l_n )
(= (Distance XL_i_n_c_o_l_n XT_h_o_m_a_s )4)
(= (Distance XT_h_o_m_a_s XL_i_n_c_o_l_n )4)

(Path XL_i_n_c_o_l_n XC_h_a_r_l_e_s )
(Path XC_h_a_r_l_e_s XL_i_n_c_o_l_n )
(= (Distance XL_i_n_c_o_l_n XC_h_a_r_l_e_s )26)
(= (Distance XC_h_a_r_l_e_s XL_i_n_c_o_l_n )26)

(Path XM_a_t_e_o XN_a_t_h_a_n )
(Path XN_a_t_h_a_n XM_a_t_e_o )
(= (Distance XM_a_t_e_o XN_a_t_h_a_n )13)
(= (Distance XN_a_t_h_a_n XM_a_t_e_o )13)

(Path XM_a_t_e_o XC_h_a_r_l_e_s )
(Path XC_h_a_r_l_e_s XM_a_t_e_o )
(= (Distance XM_a_t_e_o XC_h_a_r_l_e_s )13)
(= (Distance XC_h_a_r_l_e_s XM_a_t_e_o )13)

(Path XR_y_a_n XT_h_o_m_a_s )
(Path XT_h_o_m_a_s XR_y_a_n )
(= (Distance XR_y_a_n XT_h_o_m_a_s )33)
(= (Distance XT_h_o_m_a_s XR_y_a_n )33)

(Path XJ_a_x_o_n XI_s_a_i_a_h )
(Path XI_s_a_i_a_h XJ_a_x_o_n )
(= (Distance XJ_a_x_o_n XI_s_a_i_a_h )5)
(= (Distance XI_s_a_i_a_h XJ_a_x_o_n )5)

(Path XJ_a_x_o_n XC_h_a_r_l_e_s )
(Path XC_h_a_r_l_e_s XJ_a_x_o_n )
(= (Distance XJ_a_x_o_n XC_h_a_r_l_e_s )9)
(= (Distance XC_h_a_r_l_e_s XJ_a_x_o_n )9)

(Path XJ_a_x_o_n XC_a_l_e_b )
(Path XC_a_l_e_b XJ_a_x_o_n )
(= (Distance XJ_a_x_o_n XC_a_l_e_b )17)
(= (Distance XC_a_l_e_b XJ_a_x_o_n )17)

(Path XN_a_t_h_a_n XA_a_r_o_n )
(Path XA_a_r_o_n XN_a_t_h_a_n )
(= (Distance XN_a_t_h_a_n XA_a_r_o_n )23)
(= (Distance XA_a_r_o_n XN_a_t_h_a_n )23)

(Path XA_a_r_o_n XT_h_o_m_a_s )
(Path XT_h_o_m_a_s XA_a_r_o_n )
(= (Distance XA_a_r_o_n XT_h_o_m_a_s )16)
(= (Distance XT_h_o_m_a_s XA_a_r_o_n )16)

(Path XA_a_r_o_n XC_h_a_r_l_e_s )
(Path XC_h_a_r_l_e_s XA_a_r_o_n )
(= (Distance XA_a_r_o_n XC_h_a_r_l_e_s )6)
(= (Distance XC_h_a_r_l_e_s XA_a_r_o_n )6)

(Path XI_s_a_i_a_h XT_h_o_m_a_s )
(Path XT_h_o_m_a_s XI_s_a_i_a_h )
(= (Distance XI_s_a_i_a_h XT_h_o_m_a_s )26)
(= (Distance XT_h_o_m_a_s XI_s_a_i_a_h )26)

(Path XI_s_a_i_a_h XC_h_a_r_l_e_s )
(Path XC_h_a_r_l_e_s XI_s_a_i_a_h )
(= (Distance XI_s_a_i_a_h XC_h_a_r_l_e_s )4)
(= (Distance XC_h_a_r_l_e_s XI_s_a_i_a_h )4)

(Path XT_h_o_m_a_s XC_h_a_r_l_e_s )
(Path XC_h_a_r_l_e_s XT_h_o_m_a_s )
(= (Distance XT_h_o_m_a_s XC_h_a_r_l_e_s )22)
(= (Distance XC_h_a_r_l_e_s XT_h_o_m_a_s )22)

(Path XC_h_a_r_l_e_s XC_a_l_e_b )
(Path XC_a_l_e_b XC_h_a_r_l_e_s )
(= (Distance XC_h_a_r_l_e_s XC_a_l_e_b )18)
(= (Distance XC_a_l_e_b XC_h_a_r_l_e_s )18)

(EmptyHome XL_i_a_m)
(EmptyHome XN_o_a_h)
(EmptyHome XW_i_l_l_i_a_m)
(EmptyHome XJ_a_m_e_s)
(EmptyHome XL_o_g_a_n)
(EmptyHome XB_e_n_j_a_m_i_n)
(EmptyHome XM_a_s_o_n)
(EmptyHome XE_l_i_j_a_h)
(EmptyHome XO_l_i_v_e_r)
(EmptyHome XJ_a_c_o_b)
(EmptyHome XL_u_c_a_s)
(EmptyHome XM_i_c_h_a_e_l)
(EmptyHome XA_l_e_x_a_n_d_e_r)
(EmptyHome XE_t_h_a_n)
(EmptyHome XD_a_n_i_e_l)
(EmptyHome XM_a_t_t_h_e_w)
(EmptyHome XA_i_d_e_n)
(EmptyHome XH_e_n_r_y)
(EmptyHome XJ_o_s_e_p_h)
(EmptyHome XJ_a_c_k_s_o_n)
(EmptyHome XS_a_m_u_e_l)
(EmptyHome XS_e_b_a_s_t_i_a_n)
(EmptyHome XD_a_v_i_d)
(EmptyHome XC_a_r_t_e_r)
(EmptyHome XW_y_a_t_t)
)

  ; The goal state describe what we desire to achieve
  (:goal (and
( Car_At XL_i_a_m )
(not (EmptyHome XL_i_a_m))
(not (EmptyHome XN_o_a_h))
(not (EmptyHome XW_i_l_l_i_a_m))
(not (EmptyHome XJ_a_m_e_s))
(not (EmptyHome XL_o_g_a_n))
(not (EmptyHome XB_e_n_j_a_m_i_n))
(not (EmptyHome XM_a_s_o_n))
(not (EmptyHome XE_l_i_j_a_h))
(not (EmptyHome XO_l_i_v_e_r))
(not (EmptyHome XJ_a_c_o_b))
(not (EmptyHome XL_u_c_a_s))
(not (EmptyHome XM_i_c_h_a_e_l))
(not (EmptyHome XA_l_e_x_a_n_d_e_r))
(not (EmptyHome XE_t_h_a_n))
(not (EmptyHome XD_a_n_i_e_l))
(not (EmptyHome XM_a_t_t_h_e_w))
(not (EmptyHome XA_i_d_e_n))
(not (EmptyHome XH_e_n_r_y))
(not (EmptyHome XJ_o_s_e_p_h))
(not (EmptyHome XJ_a_c_k_s_o_n))
(not (EmptyHome XS_a_m_u_e_l))
(not (EmptyHome XS_e_b_a_s_t_i_a_n))
(not (EmptyHome XD_a_v_i_d))
(not (EmptyHome XC_a_r_t_e_r))
(not (EmptyHome XW_y_a_t_t))
  ))
)