; Problem description
; This file describes the example input from the problem statement
(define (problem pb1)
  (:metric minimize (total-cost))
  (:domain CS170)
(:objects TA_XB_e_r_k_e_l_e_yM_u_s_e_u_m TA_XB_e_r_k_e_l_e_yW_e_s_t TA_XB_i_r_g_eH_a_l_l TA_XB_l_a_c_k_w_e_l_lH_a_l_l TA_XB_l_u_mH_a_l_l TA_XB_o_a_l_tH_a_l_l TA_XB_o_t_a_nG_a_r_d_e_n TA_XI_m_a_g_i_n_gC_e_n_t_e_r TA_XS_t_a_r_rL_i_b_r_a_r_y TA_XC_a_l_i_f_o_r_n_i_aH_a_l_l TA_XC_a_l_i_f_o_r_n_i_aS_t_a_d_i_u_m TA_XC_a_l_v_i_nL_a_b_o_r_a_t_o_r_y TA_XC_a_m_p_b_e_l_lH_a_l_l TA_XC_a_r_e_e_rC_e_n_t_e_r TA_XC_h_a_nA_u_d_i_t_o_r_i_u_m TA_XC_h_a_v_e_zC_e_n_t_e_r TA_XC_h_e_i_tH_a_l_l TA_XC_h_o_uH_a_l_l TA_XC_l_a_r_kC_a_m_p_u_s TA_XC_l_a_s_sF_o_u_n_t_a_i_n TA_XC_l_a_s_sG_a_t_e TA_XCNMAT TA_XC_o_r_yH_a_l_l TA_XC_y_c_l_o_t_r_o_nR_d TA_XD_a_v_i_sH_a_l_l TA_XD_o_eL_i_b_r_a_r_y TA_XD_o_n_n_e_rL_a_b TA_XD_u_r_a_n_tH_a_l_l TA_XD_u_r_h_a_mT_h_e_a_t_r_e TA_XD_w_i_n_e_l_l_eA_n_n_e_x TA_XD_w_i_n_e_l_l_eH_a_l_l TA_XE_a_s_tG_a_t_e TA_XE_d_w_a_r_d_sS_t_a_d_i_u_m TA_XE_n_e_r_g_yB_u_i_l_d_i_n_g TA_XE_s_h_l_e_m_a_nH_a_l_l TA_XE_t_c_h_e_v_e_r_r_yH_a_l_l TA_XE_v_a_n_sD_i_a_m_o_n_d TA_XE_v_a_n_sH_a_l_l TA_XE_y_eC_e_n_t_e_r TA_XF_a_c_u_l_t_yC_l_u_b TA_XF_a_c_u_l_t_yG_l_a_d_e TA_XF_o_u_n_d_e_r_sR_o_c_k TA_XF_o_xC_o_t_t_a_g_e TA_XF_r_a_n_kW_a_y TA_XG_a_y_l_e_yR_d TA_XG_e_n_e_t_i_c_sP_l_a_n_tB_l_d_g TA_XG_i_a_n_n_i_n_iH_a_l_l TA_XH_e_r_t_zH_a_l_l TA_XC_a_f_e3 TA_X_u_n_i_t3 XG_r_e_e_n_h_o_u_s_e XH_i_l_g_a_r_dH_a_l_l XI_n_s_e_c_t_a_r_y X_iH_o_u_s_e XI_s_h_iC_o_u_r_t XJ_a_c_o_b_sH_a_l_l XJ_o_n_e_sS_t_u_d_yC_e_n_t XK_l_e_bF_i_e_l_dH_o_u_s_e XK_o_s_h_l_a_n_dH_a_l_l XK_r_o_e_b_e_rH_a_l_l XK_r_u_t_c_hT_h_e_a_t_e_r XL_a_t_i_m_e_rH_a_l_l X_l_a_w_r_e_n_c_e XL_a_w_r_e_n_c_eH_a_l_l XL_eC_o_n_t_eH_a_l_l XA_q_u_a_t_i_cC_e_n_t_e_r XL_e_vF_r_i_cF_i_e_l_d XL_e_w_i_sH_a_l_l XS_c_i_e_n_c_e_sA_d_d_i_t_i_o_n XL_s_p_r_o_u_l X_m_l_k XM_a_t_hS_c_i_e_n_c_e_sR_e_s X_m_a_x_w_e_l_l XM_cC_o_n_eH_a_l_l XM_cE_n_e_r_n_e_yH_a_l_l XM_cL_a_u_g_h_l_i_n X_m_e_m_o_r_i_a_l_p_o_o_l XM_i_n_o_rH_a_l_l XM_i_n_o_rH_a_l_lA_d_d X_m_o_f_f_i_t XM_o_r_g_a_nH_a_l_l XM_o_r_r_i_s_o_nH_a_l_l XM_o_s_e_sH_a_l_l XM_u_l_f_o_r_dH_a_l_l X_n_r_l XN_o_r_t_hF_i_e_l_d XN_o_r_t_hG_a_t_eH_a_l_l XNA_n_i_m_a_lF_a_c_i_l XOB_r_i_e_nH_a_l_l XO_b_s_e_r_vH_i_l_l XA_l_u_m_n_iH_o_u_s_e XA_n_d_e_r_s_e_nA_u_d XA_n_t_h_o_n_yH_a_l_l XA_r_c_h_sE_n_g_i_n_e_e_r_s XB_a_n_c_r_o_f_tL_i_b_r_a_r_y XB_a_n_w_a_yB_l_d_g XB_a_r_k_e_rH_a_l_l XB_a_r_r_o_wL_a_n_e XB_a_r_r_o_w_sH_a_l_l XBARTS_t_a_t_i_o_n XB_e_c_h_t_e_lE_n_g_i_n_e_e_r_i_n_g XB_e_r_k_e_l_e_yM_u_s_e_u_m XB_e_r_k_e_l_e_yW_e_s_t XB_i_r_g_eH_a_l_l XB_l_a_c_k_w_e_l_lH_a_l_l XB_l_u_mH_a_l_l XB_o_a_l_tH_a_l_l XB_o_t_a_nG_a_r_d_e_n XI_m_a_g_i_n_gC_e_n_t_e_r XS_t_a_r_rL_i_b_r_a_r_y XC_a_l_i_f_o_r_n_i_aH_a_l_l XC_a_l_i_f_o_r_n_i_aS_t_a_d_i_u_m XC_a_l_v_i_nL_a_b_o_r_a_t_o_r_y XC_a_m_p_b_e_l_lH_a_l_l XC_a_r_e_e_rC_e_n_t_e_r XC_h_a_nA_u_d_i_t_o_r_i_u_m XC_h_a_v_e_zC_e_n_t_e_r XC_h_e_i_tH_a_l_l XC_h_o_uH_a_l_l XC_l_a_r_kC_a_m_p_u_s XC_l_a_s_sF_o_u_n_t_a_i_n XC_l_a_s_sG_a_t_e XCNMAT XC_o_r_yH_a_l_l XC_y_c_l_o_t_r_o_nR_d XD_a_v_i_sH_a_l_l XD_o_eL_i_b_r_a_r_y XD_o_n_n_e_rL_a_b XD_u_r_a_n_tH_a_l_l XD_u_r_h_a_mT_h_e_a_t_r_e XD_w_i_n_e_l_l_eA_n_n_e_x XD_w_i_n_e_l_l_eH_a_l_l XE_a_s_tG_a_t_e XE_d_w_a_r_d_sS_t_a_d_i_u_m XE_n_e_r_g_yB_u_i_l_d_i_n_g XE_s_h_l_e_m_a_nH_a_l_l XE_t_c_h_e_v_e_r_r_yH_a_l_l XE_v_a_n_sD_i_a_m_o_n_d XE_v_a_n_sH_a_l_l XE_y_eC_e_n_t_e_r XF_a_c_u_l_t_yC_l_u_b XF_a_c_u_l_t_yG_l_a_d_e XF_o_u_n_d_e_r_sR_o_c_k XF_o_xC_o_t_t_a_g_e XF_r_a_n_kW_a_y XG_a_y_l_e_yR_d XG_e_n_e_t_i_c_sP_l_a_n_tB_l_d_g XG_i_a_n_n_i_n_iH_a_l_l XH_e_r_t_zH_a_l_l XC_a_f_e3 X_u_n_i_t3 )
(:init(= (total-cost) 0)
( Car_At XG_r_e_e_n_h_o_u_s_e )
(InCar TA_XB_e_r_k_e_l_e_yM_u_s_e_u_m)
(InCar TA_XB_e_r_k_e_l_e_yW_e_s_t)
(InCar TA_XB_i_r_g_eH_a_l_l)
(InCar TA_XB_l_a_c_k_w_e_l_lH_a_l_l)
(InCar TA_XB_l_u_mH_a_l_l)
(InCar TA_XB_o_a_l_tH_a_l_l)
(InCar TA_XB_o_t_a_nG_a_r_d_e_n)
(InCar TA_XI_m_a_g_i_n_gC_e_n_t_e_r)
(InCar TA_XS_t_a_r_rL_i_b_r_a_r_y)
(InCar TA_XC_a_l_i_f_o_r_n_i_aH_a_l_l)
(InCar TA_XC_a_l_i_f_o_r_n_i_aS_t_a_d_i_u_m)
(InCar TA_XC_a_l_v_i_nL_a_b_o_r_a_t_o_r_y)
(InCar TA_XC_a_m_p_b_e_l_lH_a_l_l)
(InCar TA_XC_a_r_e_e_rC_e_n_t_e_r)
(InCar TA_XC_h_a_nA_u_d_i_t_o_r_i_u_m)
(InCar TA_XC_h_a_v_e_zC_e_n_t_e_r)
(InCar TA_XC_h_e_i_tH_a_l_l)
(InCar TA_XC_h_o_uH_a_l_l)
(InCar TA_XC_l_a_r_kC_a_m_p_u_s)
(InCar TA_XC_l_a_s_sF_o_u_n_t_a_i_n)
(InCar TA_XC_l_a_s_sG_a_t_e)
(InCar TA_XCNMAT)
(InCar TA_XC_o_r_yH_a_l_l)
(InCar TA_XC_y_c_l_o_t_r_o_nR_d)
(InCar TA_XD_a_v_i_sH_a_l_l)
(InCar TA_XD_o_eL_i_b_r_a_r_y)
(InCar TA_XD_o_n_n_e_rL_a_b)
(InCar TA_XD_u_r_a_n_tH_a_l_l)
(InCar TA_XD_u_r_h_a_mT_h_e_a_t_r_e)
(InCar TA_XD_w_i_n_e_l_l_eA_n_n_e_x)
(InCar TA_XD_w_i_n_e_l_l_eH_a_l_l)
(InCar TA_XE_a_s_tG_a_t_e)
(InCar TA_XE_d_w_a_r_d_sS_t_a_d_i_u_m)
(InCar TA_XE_n_e_r_g_yB_u_i_l_d_i_n_g)
(InCar TA_XE_s_h_l_e_m_a_nH_a_l_l)
(InCar TA_XE_t_c_h_e_v_e_r_r_yH_a_l_l)
(InCar TA_XE_v_a_n_sD_i_a_m_o_n_d)
(InCar TA_XE_v_a_n_sH_a_l_l)
(InCar TA_XE_y_eC_e_n_t_e_r)
(InCar TA_XF_a_c_u_l_t_yC_l_u_b)
(InCar TA_XF_a_c_u_l_t_yG_l_a_d_e)
(InCar TA_XF_o_u_n_d_e_r_sR_o_c_k)
(InCar TA_XF_o_xC_o_t_t_a_g_e)
(InCar TA_XF_r_a_n_kW_a_y)
(InCar TA_XG_a_y_l_e_yR_d)
(InCar TA_XG_e_n_e_t_i_c_sP_l_a_n_tB_l_d_g)
(InCar TA_XG_i_a_n_n_i_n_iH_a_l_l)
(InCar TA_XH_e_r_t_zH_a_l_l)
(InCar TA_XC_a_f_e3)
(InCar TA_X_u_n_i_t3)
(Path XG_r_e_e_n_h_o_u_s_e XH_i_l_g_a_r_dH_a_l_l )
(Path XH_i_l_g_a_r_dH_a_l_l XG_r_e_e_n_h_o_u_s_e )
(= (Distance XG_r_e_e_n_h_o_u_s_e XH_i_l_g_a_r_dH_a_l_l )1)
(= (Distance XH_i_l_g_a_r_dH_a_l_l XG_r_e_e_n_h_o_u_s_e )1)

(Path XG_r_e_e_n_h_o_u_s_e XI_n_s_e_c_t_a_r_y )
(Path XI_n_s_e_c_t_a_r_y XG_r_e_e_n_h_o_u_s_e )
(= (Distance XG_r_e_e_n_h_o_u_s_e XI_n_s_e_c_t_a_r_y )1)
(= (Distance XI_n_s_e_c_t_a_r_y XG_r_e_e_n_h_o_u_s_e )1)

(Path XG_r_e_e_n_h_o_u_s_e X_iH_o_u_s_e )
(Path X_iH_o_u_s_e XG_r_e_e_n_h_o_u_s_e )
(= (Distance XG_r_e_e_n_h_o_u_s_e X_iH_o_u_s_e )1)
(= (Distance X_iH_o_u_s_e XG_r_e_e_n_h_o_u_s_e )1)

(Path XG_r_e_e_n_h_o_u_s_e XI_s_h_iC_o_u_r_t )
(Path XI_s_h_iC_o_u_r_t XG_r_e_e_n_h_o_u_s_e )
(= (Distance XG_r_e_e_n_h_o_u_s_e XI_s_h_iC_o_u_r_t )1)
(= (Distance XI_s_h_iC_o_u_r_t XG_r_e_e_n_h_o_u_s_e )1)

(Path XG_r_e_e_n_h_o_u_s_e XJ_a_c_o_b_sH_a_l_l )
(Path XJ_a_c_o_b_sH_a_l_l XG_r_e_e_n_h_o_u_s_e )
(= (Distance XG_r_e_e_n_h_o_u_s_e XJ_a_c_o_b_sH_a_l_l )1)
(= (Distance XJ_a_c_o_b_sH_a_l_l XG_r_e_e_n_h_o_u_s_e )1)

(Path XG_r_e_e_n_h_o_u_s_e XJ_o_n_e_sS_t_u_d_yC_e_n_t )
(Path XJ_o_n_e_sS_t_u_d_yC_e_n_t XG_r_e_e_n_h_o_u_s_e )
(= (Distance XG_r_e_e_n_h_o_u_s_e XJ_o_n_e_sS_t_u_d_yC_e_n_t )1)
(= (Distance XJ_o_n_e_sS_t_u_d_yC_e_n_t XG_r_e_e_n_h_o_u_s_e )1)

(Path XG_r_e_e_n_h_o_u_s_e XK_l_e_bF_i_e_l_dH_o_u_s_e )
(Path XK_l_e_bF_i_e_l_dH_o_u_s_e XG_r_e_e_n_h_o_u_s_e )
(= (Distance XG_r_e_e_n_h_o_u_s_e XK_l_e_bF_i_e_l_dH_o_u_s_e )1)
(= (Distance XK_l_e_bF_i_e_l_dH_o_u_s_e XG_r_e_e_n_h_o_u_s_e )1)

(Path XG_r_e_e_n_h_o_u_s_e XK_o_s_h_l_a_n_dH_a_l_l )
(Path XK_o_s_h_l_a_n_dH_a_l_l XG_r_e_e_n_h_o_u_s_e )
(= (Distance XG_r_e_e_n_h_o_u_s_e XK_o_s_h_l_a_n_dH_a_l_l )1)
(= (Distance XK_o_s_h_l_a_n_dH_a_l_l XG_r_e_e_n_h_o_u_s_e )1)

(Path XG_r_e_e_n_h_o_u_s_e XK_r_o_e_b_e_rH_a_l_l )
(Path XK_r_o_e_b_e_rH_a_l_l XG_r_e_e_n_h_o_u_s_e )
(= (Distance XG_r_e_e_n_h_o_u_s_e XK_r_o_e_b_e_rH_a_l_l )1)
(= (Distance XK_r_o_e_b_e_rH_a_l_l XG_r_e_e_n_h_o_u_s_e )1)

(Path XG_r_e_e_n_h_o_u_s_e XK_r_u_t_c_hT_h_e_a_t_e_r )
(Path XK_r_u_t_c_hT_h_e_a_t_e_r XG_r_e_e_n_h_o_u_s_e )
(= (Distance XG_r_e_e_n_h_o_u_s_e XK_r_u_t_c_hT_h_e_a_t_e_r )1)
(= (Distance XK_r_u_t_c_hT_h_e_a_t_e_r XG_r_e_e_n_h_o_u_s_e )1)

(Path XG_r_e_e_n_h_o_u_s_e XL_a_t_i_m_e_rH_a_l_l )
(Path XL_a_t_i_m_e_rH_a_l_l XG_r_e_e_n_h_o_u_s_e )
(= (Distance XG_r_e_e_n_h_o_u_s_e XL_a_t_i_m_e_rH_a_l_l )1)
(= (Distance XL_a_t_i_m_e_rH_a_l_l XG_r_e_e_n_h_o_u_s_e )1)

(Path XG_r_e_e_n_h_o_u_s_e X_l_a_w_r_e_n_c_e )
(Path X_l_a_w_r_e_n_c_e XG_r_e_e_n_h_o_u_s_e )
(= (Distance XG_r_e_e_n_h_o_u_s_e X_l_a_w_r_e_n_c_e )1)
(= (Distance X_l_a_w_r_e_n_c_e XG_r_e_e_n_h_o_u_s_e )1)

(Path XG_r_e_e_n_h_o_u_s_e XL_a_w_r_e_n_c_eH_a_l_l )
(Path XL_a_w_r_e_n_c_eH_a_l_l XG_r_e_e_n_h_o_u_s_e )
(= (Distance XG_r_e_e_n_h_o_u_s_e XL_a_w_r_e_n_c_eH_a_l_l )1)
(= (Distance XL_a_w_r_e_n_c_eH_a_l_l XG_r_e_e_n_h_o_u_s_e )1)

(Path XG_r_e_e_n_h_o_u_s_e XL_eC_o_n_t_eH_a_l_l )
(Path XL_eC_o_n_t_eH_a_l_l XG_r_e_e_n_h_o_u_s_e )
(= (Distance XG_r_e_e_n_h_o_u_s_e XL_eC_o_n_t_eH_a_l_l )1)
(= (Distance XL_eC_o_n_t_eH_a_l_l XG_r_e_e_n_h_o_u_s_e )1)

(Path XG_r_e_e_n_h_o_u_s_e XA_q_u_a_t_i_cC_e_n_t_e_r )
(Path XA_q_u_a_t_i_cC_e_n_t_e_r XG_r_e_e_n_h_o_u_s_e )
(= (Distance XG_r_e_e_n_h_o_u_s_e XA_q_u_a_t_i_cC_e_n_t_e_r )1)
(= (Distance XA_q_u_a_t_i_cC_e_n_t_e_r XG_r_e_e_n_h_o_u_s_e )1)

(Path XG_r_e_e_n_h_o_u_s_e XL_e_vF_r_i_cF_i_e_l_d )
(Path XL_e_vF_r_i_cF_i_e_l_d XG_r_e_e_n_h_o_u_s_e )
(= (Distance XG_r_e_e_n_h_o_u_s_e XL_e_vF_r_i_cF_i_e_l_d )1)
(= (Distance XL_e_vF_r_i_cF_i_e_l_d XG_r_e_e_n_h_o_u_s_e )1)

(Path XG_r_e_e_n_h_o_u_s_e XL_e_w_i_sH_a_l_l )
(Path XL_e_w_i_sH_a_l_l XG_r_e_e_n_h_o_u_s_e )
(= (Distance XG_r_e_e_n_h_o_u_s_e XL_e_w_i_sH_a_l_l )1)
(= (Distance XL_e_w_i_sH_a_l_l XG_r_e_e_n_h_o_u_s_e )1)

(Path XG_r_e_e_n_h_o_u_s_e XS_c_i_e_n_c_e_sA_d_d_i_t_i_o_n )
(Path XS_c_i_e_n_c_e_sA_d_d_i_t_i_o_n XG_r_e_e_n_h_o_u_s_e )
(= (Distance XG_r_e_e_n_h_o_u_s_e XS_c_i_e_n_c_e_sA_d_d_i_t_i_o_n )1)
(= (Distance XS_c_i_e_n_c_e_sA_d_d_i_t_i_o_n XG_r_e_e_n_h_o_u_s_e )1)

(Path XG_r_e_e_n_h_o_u_s_e XL_s_p_r_o_u_l )
(Path XL_s_p_r_o_u_l XG_r_e_e_n_h_o_u_s_e )
(= (Distance XG_r_e_e_n_h_o_u_s_e XL_s_p_r_o_u_l )1)
(= (Distance XL_s_p_r_o_u_l XG_r_e_e_n_h_o_u_s_e )1)

(Path XG_r_e_e_n_h_o_u_s_e X_m_l_k )
(Path X_m_l_k XG_r_e_e_n_h_o_u_s_e )
(= (Distance XG_r_e_e_n_h_o_u_s_e X_m_l_k )1)
(= (Distance X_m_l_k XG_r_e_e_n_h_o_u_s_e )1)

(Path XG_r_e_e_n_h_o_u_s_e XM_a_t_hS_c_i_e_n_c_e_sR_e_s )
(Path XM_a_t_hS_c_i_e_n_c_e_sR_e_s XG_r_e_e_n_h_o_u_s_e )
(= (Distance XG_r_e_e_n_h_o_u_s_e XM_a_t_hS_c_i_e_n_c_e_sR_e_s )1)
(= (Distance XM_a_t_hS_c_i_e_n_c_e_sR_e_s XG_r_e_e_n_h_o_u_s_e )1)

(Path XG_r_e_e_n_h_o_u_s_e X_m_a_x_w_e_l_l )
(Path X_m_a_x_w_e_l_l XG_r_e_e_n_h_o_u_s_e )
(= (Distance XG_r_e_e_n_h_o_u_s_e X_m_a_x_w_e_l_l )1)
(= (Distance X_m_a_x_w_e_l_l XG_r_e_e_n_h_o_u_s_e )1)

(Path XG_r_e_e_n_h_o_u_s_e XM_cC_o_n_eH_a_l_l )
(Path XM_cC_o_n_eH_a_l_l XG_r_e_e_n_h_o_u_s_e )
(= (Distance XG_r_e_e_n_h_o_u_s_e XM_cC_o_n_eH_a_l_l )1)
(= (Distance XM_cC_o_n_eH_a_l_l XG_r_e_e_n_h_o_u_s_e )1)

(Path XG_r_e_e_n_h_o_u_s_e XM_cE_n_e_r_n_e_yH_a_l_l )
(Path XM_cE_n_e_r_n_e_yH_a_l_l XG_r_e_e_n_h_o_u_s_e )
(= (Distance XG_r_e_e_n_h_o_u_s_e XM_cE_n_e_r_n_e_yH_a_l_l )1)
(= (Distance XM_cE_n_e_r_n_e_yH_a_l_l XG_r_e_e_n_h_o_u_s_e )1)

(Path XG_r_e_e_n_h_o_u_s_e XM_cL_a_u_g_h_l_i_n )
(Path XM_cL_a_u_g_h_l_i_n XG_r_e_e_n_h_o_u_s_e )
(= (Distance XG_r_e_e_n_h_o_u_s_e XM_cL_a_u_g_h_l_i_n )1)
(= (Distance XM_cL_a_u_g_h_l_i_n XG_r_e_e_n_h_o_u_s_e )1)

(Path XG_r_e_e_n_h_o_u_s_e X_m_e_m_o_r_i_a_l_p_o_o_l )
(Path X_m_e_m_o_r_i_a_l_p_o_o_l XG_r_e_e_n_h_o_u_s_e )
(= (Distance XG_r_e_e_n_h_o_u_s_e X_m_e_m_o_r_i_a_l_p_o_o_l )1)
(= (Distance X_m_e_m_o_r_i_a_l_p_o_o_l XG_r_e_e_n_h_o_u_s_e )1)

(Path XG_r_e_e_n_h_o_u_s_e XM_i_n_o_rH_a_l_l )
(Path XM_i_n_o_rH_a_l_l XG_r_e_e_n_h_o_u_s_e )
(= (Distance XG_r_e_e_n_h_o_u_s_e XM_i_n_o_rH_a_l_l )1)
(= (Distance XM_i_n_o_rH_a_l_l XG_r_e_e_n_h_o_u_s_e )1)

(Path XG_r_e_e_n_h_o_u_s_e XM_i_n_o_rH_a_l_lA_d_d )
(Path XM_i_n_o_rH_a_l_lA_d_d XG_r_e_e_n_h_o_u_s_e )
(= (Distance XG_r_e_e_n_h_o_u_s_e XM_i_n_o_rH_a_l_lA_d_d )1)
(= (Distance XM_i_n_o_rH_a_l_lA_d_d XG_r_e_e_n_h_o_u_s_e )1)

(Path XG_r_e_e_n_h_o_u_s_e X_m_o_f_f_i_t )
(Path X_m_o_f_f_i_t XG_r_e_e_n_h_o_u_s_e )
(= (Distance XG_r_e_e_n_h_o_u_s_e X_m_o_f_f_i_t )1)
(= (Distance X_m_o_f_f_i_t XG_r_e_e_n_h_o_u_s_e )1)

(Path XG_r_e_e_n_h_o_u_s_e XM_o_r_g_a_nH_a_l_l )
(Path XM_o_r_g_a_nH_a_l_l XG_r_e_e_n_h_o_u_s_e )
(= (Distance XG_r_e_e_n_h_o_u_s_e XM_o_r_g_a_nH_a_l_l )1)
(= (Distance XM_o_r_g_a_nH_a_l_l XG_r_e_e_n_h_o_u_s_e )1)

(Path XG_r_e_e_n_h_o_u_s_e XM_o_r_r_i_s_o_nH_a_l_l )
(Path XM_o_r_r_i_s_o_nH_a_l_l XG_r_e_e_n_h_o_u_s_e )
(= (Distance XG_r_e_e_n_h_o_u_s_e XM_o_r_r_i_s_o_nH_a_l_l )1)
(= (Distance XM_o_r_r_i_s_o_nH_a_l_l XG_r_e_e_n_h_o_u_s_e )1)

(Path XG_r_e_e_n_h_o_u_s_e XM_o_s_e_sH_a_l_l )
(Path XM_o_s_e_sH_a_l_l XG_r_e_e_n_h_o_u_s_e )
(= (Distance XG_r_e_e_n_h_o_u_s_e XM_o_s_e_sH_a_l_l )1)
(= (Distance XM_o_s_e_sH_a_l_l XG_r_e_e_n_h_o_u_s_e )1)

(Path XG_r_e_e_n_h_o_u_s_e XM_u_l_f_o_r_dH_a_l_l )
(Path XM_u_l_f_o_r_dH_a_l_l XG_r_e_e_n_h_o_u_s_e )
(= (Distance XG_r_e_e_n_h_o_u_s_e XM_u_l_f_o_r_dH_a_l_l )1)
(= (Distance XM_u_l_f_o_r_dH_a_l_l XG_r_e_e_n_h_o_u_s_e )1)

(Path XG_r_e_e_n_h_o_u_s_e X_n_r_l )
(Path X_n_r_l XG_r_e_e_n_h_o_u_s_e )
(= (Distance XG_r_e_e_n_h_o_u_s_e X_n_r_l )1)
(= (Distance X_n_r_l XG_r_e_e_n_h_o_u_s_e )1)

(Path XG_r_e_e_n_h_o_u_s_e XN_o_r_t_hF_i_e_l_d )
(Path XN_o_r_t_hF_i_e_l_d XG_r_e_e_n_h_o_u_s_e )
(= (Distance XG_r_e_e_n_h_o_u_s_e XN_o_r_t_hF_i_e_l_d )1)
(= (Distance XN_o_r_t_hF_i_e_l_d XG_r_e_e_n_h_o_u_s_e )1)

(Path XG_r_e_e_n_h_o_u_s_e XN_o_r_t_hG_a_t_eH_a_l_l )
(Path XN_o_r_t_hG_a_t_eH_a_l_l XG_r_e_e_n_h_o_u_s_e )
(= (Distance XG_r_e_e_n_h_o_u_s_e XN_o_r_t_hG_a_t_eH_a_l_l )1)
(= (Distance XN_o_r_t_hG_a_t_eH_a_l_l XG_r_e_e_n_h_o_u_s_e )1)

(Path XG_r_e_e_n_h_o_u_s_e XNA_n_i_m_a_lF_a_c_i_l )
(Path XNA_n_i_m_a_lF_a_c_i_l XG_r_e_e_n_h_o_u_s_e )
(= (Distance XG_r_e_e_n_h_o_u_s_e XNA_n_i_m_a_lF_a_c_i_l )1)
(= (Distance XNA_n_i_m_a_lF_a_c_i_l XG_r_e_e_n_h_o_u_s_e )1)

(Path XG_r_e_e_n_h_o_u_s_e XOB_r_i_e_nH_a_l_l )
(Path XOB_r_i_e_nH_a_l_l XG_r_e_e_n_h_o_u_s_e )
(= (Distance XG_r_e_e_n_h_o_u_s_e XOB_r_i_e_nH_a_l_l )1)
(= (Distance XOB_r_i_e_nH_a_l_l XG_r_e_e_n_h_o_u_s_e )1)

(Path XG_r_e_e_n_h_o_u_s_e XO_b_s_e_r_vH_i_l_l )
(Path XO_b_s_e_r_vH_i_l_l XG_r_e_e_n_h_o_u_s_e )
(= (Distance XG_r_e_e_n_h_o_u_s_e XO_b_s_e_r_vH_i_l_l )1)
(= (Distance XO_b_s_e_r_vH_i_l_l XG_r_e_e_n_h_o_u_s_e )1)

(Path XG_r_e_e_n_h_o_u_s_e XA_l_u_m_n_iH_o_u_s_e )
(Path XA_l_u_m_n_iH_o_u_s_e XG_r_e_e_n_h_o_u_s_e )
(= (Distance XG_r_e_e_n_h_o_u_s_e XA_l_u_m_n_iH_o_u_s_e )1)
(= (Distance XA_l_u_m_n_iH_o_u_s_e XG_r_e_e_n_h_o_u_s_e )1)

(Path XG_r_e_e_n_h_o_u_s_e XA_n_d_e_r_s_e_nA_u_d )
(Path XA_n_d_e_r_s_e_nA_u_d XG_r_e_e_n_h_o_u_s_e )
(= (Distance XG_r_e_e_n_h_o_u_s_e XA_n_d_e_r_s_e_nA_u_d )1)
(= (Distance XA_n_d_e_r_s_e_nA_u_d XG_r_e_e_n_h_o_u_s_e )1)

(Path XG_r_e_e_n_h_o_u_s_e XA_n_t_h_o_n_yH_a_l_l )
(Path XA_n_t_h_o_n_yH_a_l_l XG_r_e_e_n_h_o_u_s_e )
(= (Distance XG_r_e_e_n_h_o_u_s_e XA_n_t_h_o_n_yH_a_l_l )1)
(= (Distance XA_n_t_h_o_n_yH_a_l_l XG_r_e_e_n_h_o_u_s_e )1)

(Path XG_r_e_e_n_h_o_u_s_e XA_r_c_h_sE_n_g_i_n_e_e_r_s )
(Path XA_r_c_h_sE_n_g_i_n_e_e_r_s XG_r_e_e_n_h_o_u_s_e )
(= (Distance XG_r_e_e_n_h_o_u_s_e XA_r_c_h_sE_n_g_i_n_e_e_r_s )1)
(= (Distance XA_r_c_h_sE_n_g_i_n_e_e_r_s XG_r_e_e_n_h_o_u_s_e )1)

(Path XG_r_e_e_n_h_o_u_s_e XB_a_n_c_r_o_f_tL_i_b_r_a_r_y )
(Path XB_a_n_c_r_o_f_tL_i_b_r_a_r_y XG_r_e_e_n_h_o_u_s_e )
(= (Distance XG_r_e_e_n_h_o_u_s_e XB_a_n_c_r_o_f_tL_i_b_r_a_r_y )1)
(= (Distance XB_a_n_c_r_o_f_tL_i_b_r_a_r_y XG_r_e_e_n_h_o_u_s_e )1)

(Path XG_r_e_e_n_h_o_u_s_e XB_a_n_w_a_yB_l_d_g )
(Path XB_a_n_w_a_yB_l_d_g XG_r_e_e_n_h_o_u_s_e )
(= (Distance XG_r_e_e_n_h_o_u_s_e XB_a_n_w_a_yB_l_d_g )1)
(= (Distance XB_a_n_w_a_yB_l_d_g XG_r_e_e_n_h_o_u_s_e )1)

(Path XG_r_e_e_n_h_o_u_s_e XB_a_r_k_e_rH_a_l_l )
(Path XB_a_r_k_e_rH_a_l_l XG_r_e_e_n_h_o_u_s_e )
(= (Distance XG_r_e_e_n_h_o_u_s_e XB_a_r_k_e_rH_a_l_l )1)
(= (Distance XB_a_r_k_e_rH_a_l_l XG_r_e_e_n_h_o_u_s_e )1)

(Path XG_r_e_e_n_h_o_u_s_e XB_a_r_r_o_wL_a_n_e )
(Path XB_a_r_r_o_wL_a_n_e XG_r_e_e_n_h_o_u_s_e )
(= (Distance XG_r_e_e_n_h_o_u_s_e XB_a_r_r_o_wL_a_n_e )1)
(= (Distance XB_a_r_r_o_wL_a_n_e XG_r_e_e_n_h_o_u_s_e )1)

(Path XG_r_e_e_n_h_o_u_s_e XB_a_r_r_o_w_sH_a_l_l )
(Path XB_a_r_r_o_w_sH_a_l_l XG_r_e_e_n_h_o_u_s_e )
(= (Distance XG_r_e_e_n_h_o_u_s_e XB_a_r_r_o_w_sH_a_l_l )1)
(= (Distance XB_a_r_r_o_w_sH_a_l_l XG_r_e_e_n_h_o_u_s_e )1)

(Path XG_r_e_e_n_h_o_u_s_e XBARTS_t_a_t_i_o_n )
(Path XBARTS_t_a_t_i_o_n XG_r_e_e_n_h_o_u_s_e )
(= (Distance XG_r_e_e_n_h_o_u_s_e XBARTS_t_a_t_i_o_n )1)
(= (Distance XBARTS_t_a_t_i_o_n XG_r_e_e_n_h_o_u_s_e )1)

(Path XG_r_e_e_n_h_o_u_s_e XB_e_c_h_t_e_lE_n_g_i_n_e_e_r_i_n_g )
(Path XB_e_c_h_t_e_lE_n_g_i_n_e_e_r_i_n_g XG_r_e_e_n_h_o_u_s_e )
(= (Distance XG_r_e_e_n_h_o_u_s_e XB_e_c_h_t_e_lE_n_g_i_n_e_e_r_i_n_g )1)
(= (Distance XB_e_c_h_t_e_lE_n_g_i_n_e_e_r_i_n_g XG_r_e_e_n_h_o_u_s_e )1)

(Path XG_r_e_e_n_h_o_u_s_e XB_e_r_k_e_l_e_yM_u_s_e_u_m )
(Path XB_e_r_k_e_l_e_yM_u_s_e_u_m XG_r_e_e_n_h_o_u_s_e )
(= (Distance XG_r_e_e_n_h_o_u_s_e XB_e_r_k_e_l_e_yM_u_s_e_u_m )1)
(= (Distance XB_e_r_k_e_l_e_yM_u_s_e_u_m XG_r_e_e_n_h_o_u_s_e )1)

(Path XG_r_e_e_n_h_o_u_s_e XB_e_r_k_e_l_e_yW_e_s_t )
(Path XB_e_r_k_e_l_e_yW_e_s_t XG_r_e_e_n_h_o_u_s_e )
(= (Distance XG_r_e_e_n_h_o_u_s_e XB_e_r_k_e_l_e_yW_e_s_t )1)
(= (Distance XB_e_r_k_e_l_e_yW_e_s_t XG_r_e_e_n_h_o_u_s_e )1)

(Path XG_r_e_e_n_h_o_u_s_e XB_i_r_g_eH_a_l_l )
(Path XB_i_r_g_eH_a_l_l XG_r_e_e_n_h_o_u_s_e )
(= (Distance XG_r_e_e_n_h_o_u_s_e XB_i_r_g_eH_a_l_l )1)
(= (Distance XB_i_r_g_eH_a_l_l XG_r_e_e_n_h_o_u_s_e )1)

(Path XG_r_e_e_n_h_o_u_s_e XB_l_a_c_k_w_e_l_lH_a_l_l )
(Path XB_l_a_c_k_w_e_l_lH_a_l_l XG_r_e_e_n_h_o_u_s_e )
(= (Distance XG_r_e_e_n_h_o_u_s_e XB_l_a_c_k_w_e_l_lH_a_l_l )1)
(= (Distance XB_l_a_c_k_w_e_l_lH_a_l_l XG_r_e_e_n_h_o_u_s_e )1)

(Path XG_r_e_e_n_h_o_u_s_e XB_l_u_mH_a_l_l )
(Path XB_l_u_mH_a_l_l XG_r_e_e_n_h_o_u_s_e )
(= (Distance XG_r_e_e_n_h_o_u_s_e XB_l_u_mH_a_l_l )1)
(= (Distance XB_l_u_mH_a_l_l XG_r_e_e_n_h_o_u_s_e )1)

(Path XG_r_e_e_n_h_o_u_s_e XB_o_a_l_tH_a_l_l )
(Path XB_o_a_l_tH_a_l_l XG_r_e_e_n_h_o_u_s_e )
(= (Distance XG_r_e_e_n_h_o_u_s_e XB_o_a_l_tH_a_l_l )1)
(= (Distance XB_o_a_l_tH_a_l_l XG_r_e_e_n_h_o_u_s_e )1)

(Path XG_r_e_e_n_h_o_u_s_e XB_o_t_a_nG_a_r_d_e_n )
(Path XB_o_t_a_nG_a_r_d_e_n XG_r_e_e_n_h_o_u_s_e )
(= (Distance XG_r_e_e_n_h_o_u_s_e XB_o_t_a_nG_a_r_d_e_n )1)
(= (Distance XB_o_t_a_nG_a_r_d_e_n XG_r_e_e_n_h_o_u_s_e )1)

(Path XG_r_e_e_n_h_o_u_s_e XI_m_a_g_i_n_gC_e_n_t_e_r )
(Path XI_m_a_g_i_n_gC_e_n_t_e_r XG_r_e_e_n_h_o_u_s_e )
(= (Distance XG_r_e_e_n_h_o_u_s_e XI_m_a_g_i_n_gC_e_n_t_e_r )1)
(= (Distance XI_m_a_g_i_n_gC_e_n_t_e_r XG_r_e_e_n_h_o_u_s_e )1)

(Path XG_r_e_e_n_h_o_u_s_e XS_t_a_r_rL_i_b_r_a_r_y )
(Path XS_t_a_r_rL_i_b_r_a_r_y XG_r_e_e_n_h_o_u_s_e )
(= (Distance XG_r_e_e_n_h_o_u_s_e XS_t_a_r_rL_i_b_r_a_r_y )1)
(= (Distance XS_t_a_r_rL_i_b_r_a_r_y XG_r_e_e_n_h_o_u_s_e )1)

(Path XG_r_e_e_n_h_o_u_s_e XC_a_l_i_f_o_r_n_i_aH_a_l_l )
(Path XC_a_l_i_f_o_r_n_i_aH_a_l_l XG_r_e_e_n_h_o_u_s_e )
(= (Distance XG_r_e_e_n_h_o_u_s_e XC_a_l_i_f_o_r_n_i_aH_a_l_l )1)
(= (Distance XC_a_l_i_f_o_r_n_i_aH_a_l_l XG_r_e_e_n_h_o_u_s_e )1)

(Path XG_r_e_e_n_h_o_u_s_e XC_a_l_i_f_o_r_n_i_aS_t_a_d_i_u_m )
(Path XC_a_l_i_f_o_r_n_i_aS_t_a_d_i_u_m XG_r_e_e_n_h_o_u_s_e )
(= (Distance XG_r_e_e_n_h_o_u_s_e XC_a_l_i_f_o_r_n_i_aS_t_a_d_i_u_m )1)
(= (Distance XC_a_l_i_f_o_r_n_i_aS_t_a_d_i_u_m XG_r_e_e_n_h_o_u_s_e )1)

(Path XG_r_e_e_n_h_o_u_s_e XC_a_l_v_i_nL_a_b_o_r_a_t_o_r_y )
(Path XC_a_l_v_i_nL_a_b_o_r_a_t_o_r_y XG_r_e_e_n_h_o_u_s_e )
(= (Distance XG_r_e_e_n_h_o_u_s_e XC_a_l_v_i_nL_a_b_o_r_a_t_o_r_y )1)
(= (Distance XC_a_l_v_i_nL_a_b_o_r_a_t_o_r_y XG_r_e_e_n_h_o_u_s_e )1)

(Path XG_r_e_e_n_h_o_u_s_e XC_a_m_p_b_e_l_lH_a_l_l )
(Path XC_a_m_p_b_e_l_lH_a_l_l XG_r_e_e_n_h_o_u_s_e )
(= (Distance XG_r_e_e_n_h_o_u_s_e XC_a_m_p_b_e_l_lH_a_l_l )1)
(= (Distance XC_a_m_p_b_e_l_lH_a_l_l XG_r_e_e_n_h_o_u_s_e )1)

(Path XG_r_e_e_n_h_o_u_s_e XC_a_r_e_e_rC_e_n_t_e_r )
(Path XC_a_r_e_e_rC_e_n_t_e_r XG_r_e_e_n_h_o_u_s_e )
(= (Distance XG_r_e_e_n_h_o_u_s_e XC_a_r_e_e_rC_e_n_t_e_r )1)
(= (Distance XC_a_r_e_e_rC_e_n_t_e_r XG_r_e_e_n_h_o_u_s_e )1)

(Path XG_r_e_e_n_h_o_u_s_e XC_h_a_nA_u_d_i_t_o_r_i_u_m )
(Path XC_h_a_nA_u_d_i_t_o_r_i_u_m XG_r_e_e_n_h_o_u_s_e )
(= (Distance XG_r_e_e_n_h_o_u_s_e XC_h_a_nA_u_d_i_t_o_r_i_u_m )1)
(= (Distance XC_h_a_nA_u_d_i_t_o_r_i_u_m XG_r_e_e_n_h_o_u_s_e )1)

(Path XG_r_e_e_n_h_o_u_s_e XC_h_a_v_e_zC_e_n_t_e_r )
(Path XC_h_a_v_e_zC_e_n_t_e_r XG_r_e_e_n_h_o_u_s_e )
(= (Distance XG_r_e_e_n_h_o_u_s_e XC_h_a_v_e_zC_e_n_t_e_r )1)
(= (Distance XC_h_a_v_e_zC_e_n_t_e_r XG_r_e_e_n_h_o_u_s_e )1)

(Path XG_r_e_e_n_h_o_u_s_e XC_h_e_i_tH_a_l_l )
(Path XC_h_e_i_tH_a_l_l XG_r_e_e_n_h_o_u_s_e )
(= (Distance XG_r_e_e_n_h_o_u_s_e XC_h_e_i_tH_a_l_l )1)
(= (Distance XC_h_e_i_tH_a_l_l XG_r_e_e_n_h_o_u_s_e )1)

(Path XG_r_e_e_n_h_o_u_s_e XC_h_o_uH_a_l_l )
(Path XC_h_o_uH_a_l_l XG_r_e_e_n_h_o_u_s_e )
(= (Distance XG_r_e_e_n_h_o_u_s_e XC_h_o_uH_a_l_l )1)
(= (Distance XC_h_o_uH_a_l_l XG_r_e_e_n_h_o_u_s_e )1)

(Path XG_r_e_e_n_h_o_u_s_e XC_l_a_r_kC_a_m_p_u_s )
(Path XC_l_a_r_kC_a_m_p_u_s XG_r_e_e_n_h_o_u_s_e )
(= (Distance XG_r_e_e_n_h_o_u_s_e XC_l_a_r_kC_a_m_p_u_s )1)
(= (Distance XC_l_a_r_kC_a_m_p_u_s XG_r_e_e_n_h_o_u_s_e )1)

(Path XG_r_e_e_n_h_o_u_s_e XC_l_a_s_sF_o_u_n_t_a_i_n )
(Path XC_l_a_s_sF_o_u_n_t_a_i_n XG_r_e_e_n_h_o_u_s_e )
(= (Distance XG_r_e_e_n_h_o_u_s_e XC_l_a_s_sF_o_u_n_t_a_i_n )1)
(= (Distance XC_l_a_s_sF_o_u_n_t_a_i_n XG_r_e_e_n_h_o_u_s_e )1)

(Path XG_r_e_e_n_h_o_u_s_e XC_l_a_s_sG_a_t_e )
(Path XC_l_a_s_sG_a_t_e XG_r_e_e_n_h_o_u_s_e )
(= (Distance XG_r_e_e_n_h_o_u_s_e XC_l_a_s_sG_a_t_e )1)
(= (Distance XC_l_a_s_sG_a_t_e XG_r_e_e_n_h_o_u_s_e )1)

(Path XG_r_e_e_n_h_o_u_s_e XCNMAT )
(Path XCNMAT XG_r_e_e_n_h_o_u_s_e )
(= (Distance XG_r_e_e_n_h_o_u_s_e XCNMAT )1)
(= (Distance XCNMAT XG_r_e_e_n_h_o_u_s_e )1)

(Path XG_r_e_e_n_h_o_u_s_e XC_o_r_yH_a_l_l )
(Path XC_o_r_yH_a_l_l XG_r_e_e_n_h_o_u_s_e )
(= (Distance XG_r_e_e_n_h_o_u_s_e XC_o_r_yH_a_l_l )1)
(= (Distance XC_o_r_yH_a_l_l XG_r_e_e_n_h_o_u_s_e )1)

(Path XG_r_e_e_n_h_o_u_s_e XC_y_c_l_o_t_r_o_nR_d )
(Path XC_y_c_l_o_t_r_o_nR_d XG_r_e_e_n_h_o_u_s_e )
(= (Distance XG_r_e_e_n_h_o_u_s_e XC_y_c_l_o_t_r_o_nR_d )1)
(= (Distance XC_y_c_l_o_t_r_o_nR_d XG_r_e_e_n_h_o_u_s_e )1)

(Path XG_r_e_e_n_h_o_u_s_e XD_a_v_i_sH_a_l_l )
(Path XD_a_v_i_sH_a_l_l XG_r_e_e_n_h_o_u_s_e )
(= (Distance XG_r_e_e_n_h_o_u_s_e XD_a_v_i_sH_a_l_l )1)
(= (Distance XD_a_v_i_sH_a_l_l XG_r_e_e_n_h_o_u_s_e )1)

(Path XG_r_e_e_n_h_o_u_s_e XD_o_eL_i_b_r_a_r_y )
(Path XD_o_eL_i_b_r_a_r_y XG_r_e_e_n_h_o_u_s_e )
(= (Distance XG_r_e_e_n_h_o_u_s_e XD_o_eL_i_b_r_a_r_y )1)
(= (Distance XD_o_eL_i_b_r_a_r_y XG_r_e_e_n_h_o_u_s_e )1)

(Path XG_r_e_e_n_h_o_u_s_e XD_o_n_n_e_rL_a_b )
(Path XD_o_n_n_e_rL_a_b XG_r_e_e_n_h_o_u_s_e )
(= (Distance XG_r_e_e_n_h_o_u_s_e XD_o_n_n_e_rL_a_b )1)
(= (Distance XD_o_n_n_e_rL_a_b XG_r_e_e_n_h_o_u_s_e )1)

(Path XG_r_e_e_n_h_o_u_s_e XD_u_r_a_n_tH_a_l_l )
(Path XD_u_r_a_n_tH_a_l_l XG_r_e_e_n_h_o_u_s_e )
(= (Distance XG_r_e_e_n_h_o_u_s_e XD_u_r_a_n_tH_a_l_l )1)
(= (Distance XD_u_r_a_n_tH_a_l_l XG_r_e_e_n_h_o_u_s_e )1)

(Path XG_r_e_e_n_h_o_u_s_e XD_u_r_h_a_mT_h_e_a_t_r_e )
(Path XD_u_r_h_a_mT_h_e_a_t_r_e XG_r_e_e_n_h_o_u_s_e )
(= (Distance XG_r_e_e_n_h_o_u_s_e XD_u_r_h_a_mT_h_e_a_t_r_e )1)
(= (Distance XD_u_r_h_a_mT_h_e_a_t_r_e XG_r_e_e_n_h_o_u_s_e )1)

(Path XG_r_e_e_n_h_o_u_s_e XD_w_i_n_e_l_l_eA_n_n_e_x )
(Path XD_w_i_n_e_l_l_eA_n_n_e_x XG_r_e_e_n_h_o_u_s_e )
(= (Distance XG_r_e_e_n_h_o_u_s_e XD_w_i_n_e_l_l_eA_n_n_e_x )1)
(= (Distance XD_w_i_n_e_l_l_eA_n_n_e_x XG_r_e_e_n_h_o_u_s_e )1)

(Path XG_r_e_e_n_h_o_u_s_e XD_w_i_n_e_l_l_eH_a_l_l )
(Path XD_w_i_n_e_l_l_eH_a_l_l XG_r_e_e_n_h_o_u_s_e )
(= (Distance XG_r_e_e_n_h_o_u_s_e XD_w_i_n_e_l_l_eH_a_l_l )1)
(= (Distance XD_w_i_n_e_l_l_eH_a_l_l XG_r_e_e_n_h_o_u_s_e )1)

(Path XG_r_e_e_n_h_o_u_s_e XE_a_s_tG_a_t_e )
(Path XE_a_s_tG_a_t_e XG_r_e_e_n_h_o_u_s_e )
(= (Distance XG_r_e_e_n_h_o_u_s_e XE_a_s_tG_a_t_e )1)
(= (Distance XE_a_s_tG_a_t_e XG_r_e_e_n_h_o_u_s_e )1)

(Path XG_r_e_e_n_h_o_u_s_e XE_d_w_a_r_d_sS_t_a_d_i_u_m )
(Path XE_d_w_a_r_d_sS_t_a_d_i_u_m XG_r_e_e_n_h_o_u_s_e )
(= (Distance XG_r_e_e_n_h_o_u_s_e XE_d_w_a_r_d_sS_t_a_d_i_u_m )1)
(= (Distance XE_d_w_a_r_d_sS_t_a_d_i_u_m XG_r_e_e_n_h_o_u_s_e )1)

(Path XG_r_e_e_n_h_o_u_s_e XE_n_e_r_g_yB_u_i_l_d_i_n_g )
(Path XE_n_e_r_g_yB_u_i_l_d_i_n_g XG_r_e_e_n_h_o_u_s_e )
(= (Distance XG_r_e_e_n_h_o_u_s_e XE_n_e_r_g_yB_u_i_l_d_i_n_g )1)
(= (Distance XE_n_e_r_g_yB_u_i_l_d_i_n_g XG_r_e_e_n_h_o_u_s_e )1)

(Path XG_r_e_e_n_h_o_u_s_e XE_s_h_l_e_m_a_nH_a_l_l )
(Path XE_s_h_l_e_m_a_nH_a_l_l XG_r_e_e_n_h_o_u_s_e )
(= (Distance XG_r_e_e_n_h_o_u_s_e XE_s_h_l_e_m_a_nH_a_l_l )1)
(= (Distance XE_s_h_l_e_m_a_nH_a_l_l XG_r_e_e_n_h_o_u_s_e )1)

(Path XG_r_e_e_n_h_o_u_s_e XE_t_c_h_e_v_e_r_r_yH_a_l_l )
(Path XE_t_c_h_e_v_e_r_r_yH_a_l_l XG_r_e_e_n_h_o_u_s_e )
(= (Distance XG_r_e_e_n_h_o_u_s_e XE_t_c_h_e_v_e_r_r_yH_a_l_l )1)
(= (Distance XE_t_c_h_e_v_e_r_r_yH_a_l_l XG_r_e_e_n_h_o_u_s_e )1)

(Path XG_r_e_e_n_h_o_u_s_e XE_v_a_n_sD_i_a_m_o_n_d )
(Path XE_v_a_n_sD_i_a_m_o_n_d XG_r_e_e_n_h_o_u_s_e )
(= (Distance XG_r_e_e_n_h_o_u_s_e XE_v_a_n_sD_i_a_m_o_n_d )1)
(= (Distance XE_v_a_n_sD_i_a_m_o_n_d XG_r_e_e_n_h_o_u_s_e )1)

(Path XG_r_e_e_n_h_o_u_s_e XE_v_a_n_sH_a_l_l )
(Path XE_v_a_n_sH_a_l_l XG_r_e_e_n_h_o_u_s_e )
(= (Distance XG_r_e_e_n_h_o_u_s_e XE_v_a_n_sH_a_l_l )1)
(= (Distance XE_v_a_n_sH_a_l_l XG_r_e_e_n_h_o_u_s_e )1)

(Path XG_r_e_e_n_h_o_u_s_e XE_y_eC_e_n_t_e_r )
(Path XE_y_eC_e_n_t_e_r XG_r_e_e_n_h_o_u_s_e )
(= (Distance XG_r_e_e_n_h_o_u_s_e XE_y_eC_e_n_t_e_r )1)
(= (Distance XE_y_eC_e_n_t_e_r XG_r_e_e_n_h_o_u_s_e )1)

(Path XG_r_e_e_n_h_o_u_s_e XF_a_c_u_l_t_yC_l_u_b )
(Path XF_a_c_u_l_t_yC_l_u_b XG_r_e_e_n_h_o_u_s_e )
(= (Distance XG_r_e_e_n_h_o_u_s_e XF_a_c_u_l_t_yC_l_u_b )1)
(= (Distance XF_a_c_u_l_t_yC_l_u_b XG_r_e_e_n_h_o_u_s_e )1)

(Path XG_r_e_e_n_h_o_u_s_e XF_a_c_u_l_t_yG_l_a_d_e )
(Path XF_a_c_u_l_t_yG_l_a_d_e XG_r_e_e_n_h_o_u_s_e )
(= (Distance XG_r_e_e_n_h_o_u_s_e XF_a_c_u_l_t_yG_l_a_d_e )1)
(= (Distance XF_a_c_u_l_t_yG_l_a_d_e XG_r_e_e_n_h_o_u_s_e )1)

(Path XG_r_e_e_n_h_o_u_s_e XF_o_u_n_d_e_r_sR_o_c_k )
(Path XF_o_u_n_d_e_r_sR_o_c_k XG_r_e_e_n_h_o_u_s_e )
(= (Distance XG_r_e_e_n_h_o_u_s_e XF_o_u_n_d_e_r_sR_o_c_k )1)
(= (Distance XF_o_u_n_d_e_r_sR_o_c_k XG_r_e_e_n_h_o_u_s_e )1)

(Path XG_r_e_e_n_h_o_u_s_e XF_o_xC_o_t_t_a_g_e )
(Path XF_o_xC_o_t_t_a_g_e XG_r_e_e_n_h_o_u_s_e )
(= (Distance XG_r_e_e_n_h_o_u_s_e XF_o_xC_o_t_t_a_g_e )1)
(= (Distance XF_o_xC_o_t_t_a_g_e XG_r_e_e_n_h_o_u_s_e )1)

(Path XG_r_e_e_n_h_o_u_s_e XF_r_a_n_kW_a_y )
(Path XF_r_a_n_kW_a_y XG_r_e_e_n_h_o_u_s_e )
(= (Distance XG_r_e_e_n_h_o_u_s_e XF_r_a_n_kW_a_y )1)
(= (Distance XF_r_a_n_kW_a_y XG_r_e_e_n_h_o_u_s_e )1)

(Path XG_r_e_e_n_h_o_u_s_e XG_a_y_l_e_yR_d )
(Path XG_a_y_l_e_yR_d XG_r_e_e_n_h_o_u_s_e )
(= (Distance XG_r_e_e_n_h_o_u_s_e XG_a_y_l_e_yR_d )1)
(= (Distance XG_a_y_l_e_yR_d XG_r_e_e_n_h_o_u_s_e )1)

(Path XG_r_e_e_n_h_o_u_s_e XG_e_n_e_t_i_c_sP_l_a_n_tB_l_d_g )
(Path XG_e_n_e_t_i_c_sP_l_a_n_tB_l_d_g XG_r_e_e_n_h_o_u_s_e )
(= (Distance XG_r_e_e_n_h_o_u_s_e XG_e_n_e_t_i_c_sP_l_a_n_tB_l_d_g )1)
(= (Distance XG_e_n_e_t_i_c_sP_l_a_n_tB_l_d_g XG_r_e_e_n_h_o_u_s_e )1)

(Path XG_r_e_e_n_h_o_u_s_e XG_i_a_n_n_i_n_iH_a_l_l )
(Path XG_i_a_n_n_i_n_iH_a_l_l XG_r_e_e_n_h_o_u_s_e )
(= (Distance XG_r_e_e_n_h_o_u_s_e XG_i_a_n_n_i_n_iH_a_l_l )1)
(= (Distance XG_i_a_n_n_i_n_iH_a_l_l XG_r_e_e_n_h_o_u_s_e )1)

(Path XG_r_e_e_n_h_o_u_s_e XH_e_r_t_zH_a_l_l )
(Path XH_e_r_t_zH_a_l_l XG_r_e_e_n_h_o_u_s_e )
(= (Distance XG_r_e_e_n_h_o_u_s_e XH_e_r_t_zH_a_l_l )1)
(= (Distance XH_e_r_t_zH_a_l_l XG_r_e_e_n_h_o_u_s_e )1)

(Path XG_r_e_e_n_h_o_u_s_e XC_a_f_e3 )
(Path XC_a_f_e3 XG_r_e_e_n_h_o_u_s_e )
(= (Distance XG_r_e_e_n_h_o_u_s_e XC_a_f_e3 )1)
(= (Distance XC_a_f_e3 XG_r_e_e_n_h_o_u_s_e )1)

(Path XG_r_e_e_n_h_o_u_s_e X_u_n_i_t3 )
(Path X_u_n_i_t3 XG_r_e_e_n_h_o_u_s_e )
(= (Distance XG_r_e_e_n_h_o_u_s_e X_u_n_i_t3 )1)
(= (Distance X_u_n_i_t3 XG_r_e_e_n_h_o_u_s_e )1)

(EmptyHome XB_e_r_k_e_l_e_yM_u_s_e_u_m)
(EmptyHome XB_e_r_k_e_l_e_yW_e_s_t)
(EmptyHome XB_i_r_g_eH_a_l_l)
(EmptyHome XB_l_a_c_k_w_e_l_lH_a_l_l)
(EmptyHome XB_l_u_mH_a_l_l)
(EmptyHome XB_o_a_l_tH_a_l_l)
(EmptyHome XB_o_t_a_nG_a_r_d_e_n)
(EmptyHome XI_m_a_g_i_n_gC_e_n_t_e_r)
(EmptyHome XS_t_a_r_rL_i_b_r_a_r_y)
(EmptyHome XC_a_l_i_f_o_r_n_i_aH_a_l_l)
(EmptyHome XC_a_l_i_f_o_r_n_i_aS_t_a_d_i_u_m)
(EmptyHome XC_a_l_v_i_nL_a_b_o_r_a_t_o_r_y)
(EmptyHome XC_a_m_p_b_e_l_lH_a_l_l)
(EmptyHome XC_a_r_e_e_rC_e_n_t_e_r)
(EmptyHome XC_h_a_nA_u_d_i_t_o_r_i_u_m)
(EmptyHome XC_h_a_v_e_zC_e_n_t_e_r)
(EmptyHome XC_h_e_i_tH_a_l_l)
(EmptyHome XC_h_o_uH_a_l_l)
(EmptyHome XC_l_a_r_kC_a_m_p_u_s)
(EmptyHome XC_l_a_s_sF_o_u_n_t_a_i_n)
(EmptyHome XC_l_a_s_sG_a_t_e)
(EmptyHome XCNMAT)
(EmptyHome XC_o_r_yH_a_l_l)
(EmptyHome XC_y_c_l_o_t_r_o_nR_d)
(EmptyHome XD_a_v_i_sH_a_l_l)
(EmptyHome XD_o_eL_i_b_r_a_r_y)
(EmptyHome XD_o_n_n_e_rL_a_b)
(EmptyHome XD_u_r_a_n_tH_a_l_l)
(EmptyHome XD_u_r_h_a_mT_h_e_a_t_r_e)
(EmptyHome XD_w_i_n_e_l_l_eA_n_n_e_x)
(EmptyHome XD_w_i_n_e_l_l_eH_a_l_l)
(EmptyHome XE_a_s_tG_a_t_e)
(EmptyHome XE_d_w_a_r_d_sS_t_a_d_i_u_m)
(EmptyHome XE_n_e_r_g_yB_u_i_l_d_i_n_g)
(EmptyHome XE_s_h_l_e_m_a_nH_a_l_l)
(EmptyHome XE_t_c_h_e_v_e_r_r_yH_a_l_l)
(EmptyHome XE_v_a_n_sD_i_a_m_o_n_d)
(EmptyHome XE_v_a_n_sH_a_l_l)
(EmptyHome XE_y_eC_e_n_t_e_r)
(EmptyHome XF_a_c_u_l_t_yC_l_u_b)
(EmptyHome XF_a_c_u_l_t_yG_l_a_d_e)
(EmptyHome XF_o_u_n_d_e_r_sR_o_c_k)
(EmptyHome XF_o_xC_o_t_t_a_g_e)
(EmptyHome XF_r_a_n_kW_a_y)
(EmptyHome XG_a_y_l_e_yR_d)
(EmptyHome XG_e_n_e_t_i_c_sP_l_a_n_tB_l_d_g)
(EmptyHome XG_i_a_n_n_i_n_iH_a_l_l)
(EmptyHome XH_e_r_t_zH_a_l_l)
(EmptyHome XC_a_f_e3)
(EmptyHome X_u_n_i_t3)
)

  ; The goal state describe what we desire to achieve
  (:goal (and
( Car_At XG_r_e_e_n_h_o_u_s_e )
(not (EmptyHome XB_e_r_k_e_l_e_yM_u_s_e_u_m))
(not (EmptyHome XB_e_r_k_e_l_e_yW_e_s_t))
(not (EmptyHome XB_i_r_g_eH_a_l_l))
(not (EmptyHome XB_l_a_c_k_w_e_l_lH_a_l_l))
(not (EmptyHome XB_l_u_mH_a_l_l))
(not (EmptyHome XB_o_a_l_tH_a_l_l))
(not (EmptyHome XB_o_t_a_nG_a_r_d_e_n))
(not (EmptyHome XI_m_a_g_i_n_gC_e_n_t_e_r))
(not (EmptyHome XS_t_a_r_rL_i_b_r_a_r_y))
(not (EmptyHome XC_a_l_i_f_o_r_n_i_aH_a_l_l))
(not (EmptyHome XC_a_l_i_f_o_r_n_i_aS_t_a_d_i_u_m))
(not (EmptyHome XC_a_l_v_i_nL_a_b_o_r_a_t_o_r_y))
(not (EmptyHome XC_a_m_p_b_e_l_lH_a_l_l))
(not (EmptyHome XC_a_r_e_e_rC_e_n_t_e_r))
(not (EmptyHome XC_h_a_nA_u_d_i_t_o_r_i_u_m))
(not (EmptyHome XC_h_a_v_e_zC_e_n_t_e_r))
(not (EmptyHome XC_h_e_i_tH_a_l_l))
(not (EmptyHome XC_h_o_uH_a_l_l))
(not (EmptyHome XC_l_a_r_kC_a_m_p_u_s))
(not (EmptyHome XC_l_a_s_sF_o_u_n_t_a_i_n))
(not (EmptyHome XC_l_a_s_sG_a_t_e))
(not (EmptyHome XCNMAT))
(not (EmptyHome XC_o_r_yH_a_l_l))
(not (EmptyHome XC_y_c_l_o_t_r_o_nR_d))
(not (EmptyHome XD_a_v_i_sH_a_l_l))
(not (EmptyHome XD_o_eL_i_b_r_a_r_y))
(not (EmptyHome XD_o_n_n_e_rL_a_b))
(not (EmptyHome XD_u_r_a_n_tH_a_l_l))
(not (EmptyHome XD_u_r_h_a_mT_h_e_a_t_r_e))
(not (EmptyHome XD_w_i_n_e_l_l_eA_n_n_e_x))
(not (EmptyHome XD_w_i_n_e_l_l_eH_a_l_l))
(not (EmptyHome XE_a_s_tG_a_t_e))
(not (EmptyHome XE_d_w_a_r_d_sS_t_a_d_i_u_m))
(not (EmptyHome XE_n_e_r_g_yB_u_i_l_d_i_n_g))
(not (EmptyHome XE_s_h_l_e_m_a_nH_a_l_l))
(not (EmptyHome XE_t_c_h_e_v_e_r_r_yH_a_l_l))
(not (EmptyHome XE_v_a_n_sD_i_a_m_o_n_d))
(not (EmptyHome XE_v_a_n_sH_a_l_l))
(not (EmptyHome XE_y_eC_e_n_t_e_r))
(not (EmptyHome XF_a_c_u_l_t_yC_l_u_b))
(not (EmptyHome XF_a_c_u_l_t_yG_l_a_d_e))
(not (EmptyHome XF_o_u_n_d_e_r_sR_o_c_k))
(not (EmptyHome XF_o_xC_o_t_t_a_g_e))
(not (EmptyHome XF_r_a_n_kW_a_y))
(not (EmptyHome XG_a_y_l_e_yR_d))
(not (EmptyHome XG_e_n_e_t_i_c_sP_l_a_n_tB_l_d_g))
(not (EmptyHome XG_i_a_n_n_i_n_iH_a_l_l))
(not (EmptyHome XH_e_r_t_zH_a_l_l))
(not (EmptyHome XC_a_f_e3))
(not (EmptyHome X_u_n_i_t3))
  ))
)