; Problem description
; This file describes the example input from the problem statement
(define (problem pb1)
  (:metric minimize (total-cost))
  (:domain CS170)
(:objects TA_X_b_u_i_l_d_i_n_g7 TA_X_b_u_i_l_d_i_n_g8 TA_X_b_u_i_l_d_i_n_g9 TA_X_b_u_i_l_d_i_n_g10 TA_X_b_u_i_l_d_i_n_g11 TA_X_b_u_i_l_d_i_n_g12 TA_X_b_u_i_l_d_i_n_g13 TA_X_b_u_i_l_d_i_n_g14 TA_X_b_u_i_l_d_i_n_g15 TA_X_b_u_i_l_d_i_n_g16 TA_X_b_u_i_l_d_i_n_g17 TA_X_b_u_i_l_d_i_n_g18 TA_X_b_u_i_l_d_i_n_g19 TA_X_b_u_i_l_d_i_n_g20 TA_X_b_u_i_l_d_i_n_g21 TA_X_b_u_i_l_d_i_n_g22 TA_X_b_u_i_l_d_i_n_g23 TA_X_b_u_i_l_d_i_n_g24 TA_X_b_u_i_l_d_i_n_g25 TA_X_b_u_i_l_d_i_n_g26 TA_X_b_u_i_l_d_i_n_g27 TA_X_b_u_i_l_d_i_n_g28 TA_X_b_u_i_l_d_i_n_g29 TA_X_b_u_i_l_d_i_n_g30 TA_X_b_u_i_l_d_i_n_g31 TA_X_b_u_i_l_d_i_n_g32 TA_X_b_u_i_l_d_i_n_g33 TA_X_b_u_i_l_d_i_n_g34 TA_X_b_u_i_l_d_i_n_g35 TA_X_b_u_i_l_d_i_n_g36 TA_X_b_u_i_l_d_i_n_g37 TA_X_b_u_i_l_d_i_n_g38 TA_X_b_u_i_l_d_i_n_g39 TA_X_b_u_i_l_d_i_n_g40 TA_X_b_u_i_l_d_i_n_g41 TA_X_b_u_i_l_d_i_n_g42 TA_X_b_u_i_l_d_i_n_g43 TA_X_b_u_i_l_d_i_n_g44 TA_X_b_u_i_l_d_i_n_g45 TA_X_b_u_i_l_d_i_n_g46 TA_X_b_u_i_l_d_i_n_g47 TA_X_b_u_i_l_d_i_n_g48 TA_X_b_u_i_l_d_i_n_g49 TA_X_b_u_i_l_d_i_n_g50 TA_X_b_u_i_l_d_i_n_g51 TA_X_b_u_i_l_d_i_n_g52 TA_X_b_u_i_l_d_i_n_g53 TA_X_b_u_i_l_d_i_n_g54 TA_X_b_u_i_l_d_i_n_g55 TA_X_b_u_i_l_d_i_n_g56 TA_X_b_u_i_l_d_i_n_g57 TA_X_b_u_i_l_d_i_n_g58 TA_X_b_u_i_l_d_i_n_g59 TA_X_b_u_i_l_d_i_n_g60 TA_X_b_u_i_l_d_i_n_g61 TA_X_b_u_i_l_d_i_n_g62 TA_X_b_u_i_l_d_i_n_g63 TA_X_b_u_i_l_d_i_n_g64 TA_X_b_u_i_l_d_i_n_g65 TA_X_b_u_i_l_d_i_n_g66 TA_X_b_u_i_l_d_i_n_g67 TA_X_b_u_i_l_d_i_n_g68 TA_X_b_u_i_l_d_i_n_g69 TA_X_b_u_i_l_d_i_n_g70 TA_X_b_u_i_l_d_i_n_g71 TA_X_b_u_i_l_d_i_n_g72 TA_X_b_u_i_l_d_i_n_g73 TA_X_b_u_i_l_d_i_n_g74 TA_X_b_u_i_l_d_i_n_g75 TA_X_b_u_i_l_d_i_n_g76 TA_X_b_u_i_l_d_i_n_g77 TA_X_b_u_i_l_d_i_n_g78 XS_o_d_a X_b_u_i_l_d_i_n_g1 X_b_u_i_l_d_i_n_g2 X_b_u_i_l_d_i_n_g3 X_b_u_i_l_d_i_n_g4 X_b_u_i_l_d_i_n_g5 X_b_u_i_l_d_i_n_g6 X_b_u_i_l_d_i_n_g7 X_b_u_i_l_d_i_n_g8 X_b_u_i_l_d_i_n_g9 X_b_u_i_l_d_i_n_g10 X_b_u_i_l_d_i_n_g11 X_b_u_i_l_d_i_n_g12 X_b_u_i_l_d_i_n_g13 X_b_u_i_l_d_i_n_g14 X_b_u_i_l_d_i_n_g15 X_b_u_i_l_d_i_n_g16 X_b_u_i_l_d_i_n_g17 X_b_u_i_l_d_i_n_g18 X_b_u_i_l_d_i_n_g19 X_b_u_i_l_d_i_n_g20 X_b_u_i_l_d_i_n_g21 X_b_u_i_l_d_i_n_g22 X_b_u_i_l_d_i_n_g23 X_b_u_i_l_d_i_n_g24 X_b_u_i_l_d_i_n_g25 X_b_u_i_l_d_i_n_g26 X_b_u_i_l_d_i_n_g27 X_b_u_i_l_d_i_n_g28 X_b_u_i_l_d_i_n_g29 X_b_u_i_l_d_i_n_g30 X_b_u_i_l_d_i_n_g31 X_b_u_i_l_d_i_n_g32 X_b_u_i_l_d_i_n_g33 X_b_u_i_l_d_i_n_g34 X_b_u_i_l_d_i_n_g35 X_b_u_i_l_d_i_n_g36 X_b_u_i_l_d_i_n_g37 X_b_u_i_l_d_i_n_g38 X_b_u_i_l_d_i_n_g39 X_b_u_i_l_d_i_n_g40 X_b_u_i_l_d_i_n_g41 X_b_u_i_l_d_i_n_g42 X_b_u_i_l_d_i_n_g43 X_b_u_i_l_d_i_n_g44 X_b_u_i_l_d_i_n_g45 X_b_u_i_l_d_i_n_g46 X_b_u_i_l_d_i_n_g47 X_b_u_i_l_d_i_n_g48 X_b_u_i_l_d_i_n_g49 X_b_u_i_l_d_i_n_g50 X_b_u_i_l_d_i_n_g51 X_b_u_i_l_d_i_n_g52 X_b_u_i_l_d_i_n_g53 X_b_u_i_l_d_i_n_g54 X_b_u_i_l_d_i_n_g55 X_b_u_i_l_d_i_n_g56 X_b_u_i_l_d_i_n_g57 X_b_u_i_l_d_i_n_g58 X_b_u_i_l_d_i_n_g59 X_b_u_i_l_d_i_n_g60 X_b_u_i_l_d_i_n_g61 X_b_u_i_l_d_i_n_g62 X_b_u_i_l_d_i_n_g63 X_b_u_i_l_d_i_n_g64 X_b_u_i_l_d_i_n_g65 X_b_u_i_l_d_i_n_g66 X_b_u_i_l_d_i_n_g67 X_b_u_i_l_d_i_n_g68 X_b_u_i_l_d_i_n_g69 X_b_u_i_l_d_i_n_g70 X_b_u_i_l_d_i_n_g71 X_b_u_i_l_d_i_n_g72 X_b_u_i_l_d_i_n_g73 X_b_u_i_l_d_i_n_g74 X_b_u_i_l_d_i_n_g75 X_b_u_i_l_d_i_n_g76 X_b_u_i_l_d_i_n_g77 X_b_u_i_l_d_i_n_g78 )
(:init(= (total-cost) 0)
( Car_At XS_o_d_a )
(InCar TA_X_b_u_i_l_d_i_n_g7)
(InCar TA_X_b_u_i_l_d_i_n_g8)
(InCar TA_X_b_u_i_l_d_i_n_g9)
(InCar TA_X_b_u_i_l_d_i_n_g10)
(InCar TA_X_b_u_i_l_d_i_n_g11)
(InCar TA_X_b_u_i_l_d_i_n_g12)
(InCar TA_X_b_u_i_l_d_i_n_g13)
(InCar TA_X_b_u_i_l_d_i_n_g14)
(InCar TA_X_b_u_i_l_d_i_n_g15)
(InCar TA_X_b_u_i_l_d_i_n_g16)
(InCar TA_X_b_u_i_l_d_i_n_g17)
(InCar TA_X_b_u_i_l_d_i_n_g18)
(InCar TA_X_b_u_i_l_d_i_n_g19)
(InCar TA_X_b_u_i_l_d_i_n_g20)
(InCar TA_X_b_u_i_l_d_i_n_g21)
(InCar TA_X_b_u_i_l_d_i_n_g22)
(InCar TA_X_b_u_i_l_d_i_n_g23)
(InCar TA_X_b_u_i_l_d_i_n_g24)
(InCar TA_X_b_u_i_l_d_i_n_g25)
(InCar TA_X_b_u_i_l_d_i_n_g26)
(InCar TA_X_b_u_i_l_d_i_n_g27)
(InCar TA_X_b_u_i_l_d_i_n_g28)
(InCar TA_X_b_u_i_l_d_i_n_g29)
(InCar TA_X_b_u_i_l_d_i_n_g30)
(InCar TA_X_b_u_i_l_d_i_n_g31)
(InCar TA_X_b_u_i_l_d_i_n_g32)
(InCar TA_X_b_u_i_l_d_i_n_g33)
(InCar TA_X_b_u_i_l_d_i_n_g34)
(InCar TA_X_b_u_i_l_d_i_n_g35)
(InCar TA_X_b_u_i_l_d_i_n_g36)
(InCar TA_X_b_u_i_l_d_i_n_g37)
(InCar TA_X_b_u_i_l_d_i_n_g38)
(InCar TA_X_b_u_i_l_d_i_n_g39)
(InCar TA_X_b_u_i_l_d_i_n_g40)
(InCar TA_X_b_u_i_l_d_i_n_g41)
(InCar TA_X_b_u_i_l_d_i_n_g42)
(InCar TA_X_b_u_i_l_d_i_n_g43)
(InCar TA_X_b_u_i_l_d_i_n_g44)
(InCar TA_X_b_u_i_l_d_i_n_g45)
(InCar TA_X_b_u_i_l_d_i_n_g46)
(InCar TA_X_b_u_i_l_d_i_n_g47)
(InCar TA_X_b_u_i_l_d_i_n_g48)
(InCar TA_X_b_u_i_l_d_i_n_g49)
(InCar TA_X_b_u_i_l_d_i_n_g50)
(InCar TA_X_b_u_i_l_d_i_n_g51)
(InCar TA_X_b_u_i_l_d_i_n_g52)
(InCar TA_X_b_u_i_l_d_i_n_g53)
(InCar TA_X_b_u_i_l_d_i_n_g54)
(InCar TA_X_b_u_i_l_d_i_n_g55)
(InCar TA_X_b_u_i_l_d_i_n_g56)
(InCar TA_X_b_u_i_l_d_i_n_g57)
(InCar TA_X_b_u_i_l_d_i_n_g58)
(InCar TA_X_b_u_i_l_d_i_n_g59)
(InCar TA_X_b_u_i_l_d_i_n_g60)
(InCar TA_X_b_u_i_l_d_i_n_g61)
(InCar TA_X_b_u_i_l_d_i_n_g62)
(InCar TA_X_b_u_i_l_d_i_n_g63)
(InCar TA_X_b_u_i_l_d_i_n_g64)
(InCar TA_X_b_u_i_l_d_i_n_g65)
(InCar TA_X_b_u_i_l_d_i_n_g66)
(InCar TA_X_b_u_i_l_d_i_n_g67)
(InCar TA_X_b_u_i_l_d_i_n_g68)
(InCar TA_X_b_u_i_l_d_i_n_g69)
(InCar TA_X_b_u_i_l_d_i_n_g70)
(InCar TA_X_b_u_i_l_d_i_n_g71)
(InCar TA_X_b_u_i_l_d_i_n_g72)
(InCar TA_X_b_u_i_l_d_i_n_g73)
(InCar TA_X_b_u_i_l_d_i_n_g74)
(InCar TA_X_b_u_i_l_d_i_n_g75)
(InCar TA_X_b_u_i_l_d_i_n_g76)
(InCar TA_X_b_u_i_l_d_i_n_g77)
(InCar TA_X_b_u_i_l_d_i_n_g78)
(Path XS_o_d_a X_b_u_i_l_d_i_n_g1 )
(Path X_b_u_i_l_d_i_n_g1 XS_o_d_a )
(= (Distance XS_o_d_a X_b_u_i_l_d_i_n_g1 )1.62297)
(= (Distance X_b_u_i_l_d_i_n_g1 XS_o_d_a )1.62297)

(Path XS_o_d_a X_b_u_i_l_d_i_n_g2 )
(Path X_b_u_i_l_d_i_n_g2 XS_o_d_a )
(= (Distance XS_o_d_a X_b_u_i_l_d_i_n_g2 )1.55806)
(= (Distance X_b_u_i_l_d_i_n_g2 XS_o_d_a )1.55806)

(Path XS_o_d_a X_b_u_i_l_d_i_n_g3 )
(Path X_b_u_i_l_d_i_n_g3 XS_o_d_a )
(= (Distance XS_o_d_a X_b_u_i_l_d_i_n_g3 )1.0934)
(= (Distance X_b_u_i_l_d_i_n_g3 XS_o_d_a )1.0934)

(Path XS_o_d_a X_b_u_i_l_d_i_n_g4 )
(Path X_b_u_i_l_d_i_n_g4 XS_o_d_a )
(= (Distance XS_o_d_a X_b_u_i_l_d_i_n_g4 )1.51709)
(= (Distance X_b_u_i_l_d_i_n_g4 XS_o_d_a )1.51709)

(Path XS_o_d_a X_b_u_i_l_d_i_n_g5 )
(Path X_b_u_i_l_d_i_n_g5 XS_o_d_a )
(= (Distance XS_o_d_a X_b_u_i_l_d_i_n_g5 )1.00679)
(= (Distance X_b_u_i_l_d_i_n_g5 XS_o_d_a )1.00679)

(Path XS_o_d_a X_b_u_i_l_d_i_n_g6 )
(Path X_b_u_i_l_d_i_n_g6 XS_o_d_a )
(= (Distance XS_o_d_a X_b_u_i_l_d_i_n_g6 )1.49796)
(= (Distance X_b_u_i_l_d_i_n_g6 XS_o_d_a )1.49796)

(Path X_b_u_i_l_d_i_n_g1 X_b_u_i_l_d_i_n_g7 )
(Path X_b_u_i_l_d_i_n_g7 X_b_u_i_l_d_i_n_g1 )
(= (Distance X_b_u_i_l_d_i_n_g1 X_b_u_i_l_d_i_n_g7 )1.79346)
(= (Distance X_b_u_i_l_d_i_n_g7 X_b_u_i_l_d_i_n_g1 )1.79346)

(Path X_b_u_i_l_d_i_n_g1 X_b_u_i_l_d_i_n_g8 )
(Path X_b_u_i_l_d_i_n_g8 X_b_u_i_l_d_i_n_g1 )
(= (Distance X_b_u_i_l_d_i_n_g1 X_b_u_i_l_d_i_n_g8 )1.62422)
(= (Distance X_b_u_i_l_d_i_n_g8 X_b_u_i_l_d_i_n_g1 )1.62422)

(Path X_b_u_i_l_d_i_n_g1 X_b_u_i_l_d_i_n_g9 )
(Path X_b_u_i_l_d_i_n_g9 X_b_u_i_l_d_i_n_g1 )
(= (Distance X_b_u_i_l_d_i_n_g1 X_b_u_i_l_d_i_n_g9 )1.14541)
(= (Distance X_b_u_i_l_d_i_n_g9 X_b_u_i_l_d_i_n_g1 )1.14541)

(Path X_b_u_i_l_d_i_n_g1 X_b_u_i_l_d_i_n_g10 )
(Path X_b_u_i_l_d_i_n_g10 X_b_u_i_l_d_i_n_g1 )
(= (Distance X_b_u_i_l_d_i_n_g1 X_b_u_i_l_d_i_n_g10 )1.89011)
(= (Distance X_b_u_i_l_d_i_n_g10 X_b_u_i_l_d_i_n_g1 )1.89011)

(Path X_b_u_i_l_d_i_n_g1 X_b_u_i_l_d_i_n_g11 )
(Path X_b_u_i_l_d_i_n_g11 X_b_u_i_l_d_i_n_g1 )
(= (Distance X_b_u_i_l_d_i_n_g1 X_b_u_i_l_d_i_n_g11 )1.41955)
(= (Distance X_b_u_i_l_d_i_n_g11 X_b_u_i_l_d_i_n_g1 )1.41955)

(Path X_b_u_i_l_d_i_n_g1 X_b_u_i_l_d_i_n_g12 )
(Path X_b_u_i_l_d_i_n_g12 X_b_u_i_l_d_i_n_g1 )
(= (Distance X_b_u_i_l_d_i_n_g1 X_b_u_i_l_d_i_n_g12 )1.49716)
(= (Distance X_b_u_i_l_d_i_n_g12 X_b_u_i_l_d_i_n_g1 )1.49716)

(Path X_b_u_i_l_d_i_n_g2 X_b_u_i_l_d_i_n_g13 )
(Path X_b_u_i_l_d_i_n_g13 X_b_u_i_l_d_i_n_g2 )
(= (Distance X_b_u_i_l_d_i_n_g2 X_b_u_i_l_d_i_n_g13 )1.62734)
(= (Distance X_b_u_i_l_d_i_n_g13 X_b_u_i_l_d_i_n_g2 )1.62734)

(Path X_b_u_i_l_d_i_n_g2 X_b_u_i_l_d_i_n_g14 )
(Path X_b_u_i_l_d_i_n_g14 X_b_u_i_l_d_i_n_g2 )
(= (Distance X_b_u_i_l_d_i_n_g2 X_b_u_i_l_d_i_n_g14 )1.86543)
(= (Distance X_b_u_i_l_d_i_n_g14 X_b_u_i_l_d_i_n_g2 )1.86543)

(Path X_b_u_i_l_d_i_n_g2 X_b_u_i_l_d_i_n_g15 )
(Path X_b_u_i_l_d_i_n_g15 X_b_u_i_l_d_i_n_g2 )
(= (Distance X_b_u_i_l_d_i_n_g2 X_b_u_i_l_d_i_n_g15 )1.68434)
(= (Distance X_b_u_i_l_d_i_n_g15 X_b_u_i_l_d_i_n_g2 )1.68434)

(Path X_b_u_i_l_d_i_n_g2 X_b_u_i_l_d_i_n_g16 )
(Path X_b_u_i_l_d_i_n_g16 X_b_u_i_l_d_i_n_g2 )
(= (Distance X_b_u_i_l_d_i_n_g2 X_b_u_i_l_d_i_n_g16 )1.35407)
(= (Distance X_b_u_i_l_d_i_n_g16 X_b_u_i_l_d_i_n_g2 )1.35407)

(Path X_b_u_i_l_d_i_n_g2 X_b_u_i_l_d_i_n_g17 )
(Path X_b_u_i_l_d_i_n_g17 X_b_u_i_l_d_i_n_g2 )
(= (Distance X_b_u_i_l_d_i_n_g2 X_b_u_i_l_d_i_n_g17 )1.32673)
(= (Distance X_b_u_i_l_d_i_n_g17 X_b_u_i_l_d_i_n_g2 )1.32673)

(Path X_b_u_i_l_d_i_n_g2 X_b_u_i_l_d_i_n_g18 )
(Path X_b_u_i_l_d_i_n_g18 X_b_u_i_l_d_i_n_g2 )
(= (Distance X_b_u_i_l_d_i_n_g2 X_b_u_i_l_d_i_n_g18 )1.4769)
(= (Distance X_b_u_i_l_d_i_n_g18 X_b_u_i_l_d_i_n_g2 )1.4769)

(Path X_b_u_i_l_d_i_n_g3 X_b_u_i_l_d_i_n_g19 )
(Path X_b_u_i_l_d_i_n_g19 X_b_u_i_l_d_i_n_g3 )
(= (Distance X_b_u_i_l_d_i_n_g3 X_b_u_i_l_d_i_n_g19 )1.39686)
(= (Distance X_b_u_i_l_d_i_n_g19 X_b_u_i_l_d_i_n_g3 )1.39686)

(Path X_b_u_i_l_d_i_n_g3 X_b_u_i_l_d_i_n_g20 )
(Path X_b_u_i_l_d_i_n_g20 X_b_u_i_l_d_i_n_g3 )
(= (Distance X_b_u_i_l_d_i_n_g3 X_b_u_i_l_d_i_n_g20 )1.19867)
(= (Distance X_b_u_i_l_d_i_n_g20 X_b_u_i_l_d_i_n_g3 )1.19867)

(Path X_b_u_i_l_d_i_n_g3 X_b_u_i_l_d_i_n_g21 )
(Path X_b_u_i_l_d_i_n_g21 X_b_u_i_l_d_i_n_g3 )
(= (Distance X_b_u_i_l_d_i_n_g3 X_b_u_i_l_d_i_n_g21 )1.33402)
(= (Distance X_b_u_i_l_d_i_n_g21 X_b_u_i_l_d_i_n_g3 )1.33402)

(Path X_b_u_i_l_d_i_n_g3 X_b_u_i_l_d_i_n_g22 )
(Path X_b_u_i_l_d_i_n_g22 X_b_u_i_l_d_i_n_g3 )
(= (Distance X_b_u_i_l_d_i_n_g3 X_b_u_i_l_d_i_n_g22 )1.01262)
(= (Distance X_b_u_i_l_d_i_n_g22 X_b_u_i_l_d_i_n_g3 )1.01262)

(Path X_b_u_i_l_d_i_n_g3 X_b_u_i_l_d_i_n_g23 )
(Path X_b_u_i_l_d_i_n_g23 X_b_u_i_l_d_i_n_g3 )
(= (Distance X_b_u_i_l_d_i_n_g3 X_b_u_i_l_d_i_n_g23 )1.68994)
(= (Distance X_b_u_i_l_d_i_n_g23 X_b_u_i_l_d_i_n_g3 )1.68994)

(Path X_b_u_i_l_d_i_n_g3 X_b_u_i_l_d_i_n_g24 )
(Path X_b_u_i_l_d_i_n_g24 X_b_u_i_l_d_i_n_g3 )
(= (Distance X_b_u_i_l_d_i_n_g3 X_b_u_i_l_d_i_n_g24 )1.32401)
(= (Distance X_b_u_i_l_d_i_n_g24 X_b_u_i_l_d_i_n_g3 )1.32401)

(Path X_b_u_i_l_d_i_n_g4 X_b_u_i_l_d_i_n_g25 )
(Path X_b_u_i_l_d_i_n_g25 X_b_u_i_l_d_i_n_g4 )
(= (Distance X_b_u_i_l_d_i_n_g4 X_b_u_i_l_d_i_n_g25 )1.34422)
(= (Distance X_b_u_i_l_d_i_n_g25 X_b_u_i_l_d_i_n_g4 )1.34422)

(Path X_b_u_i_l_d_i_n_g4 X_b_u_i_l_d_i_n_g26 )
(Path X_b_u_i_l_d_i_n_g26 X_b_u_i_l_d_i_n_g4 )
(= (Distance X_b_u_i_l_d_i_n_g4 X_b_u_i_l_d_i_n_g26 )1.37545)
(= (Distance X_b_u_i_l_d_i_n_g26 X_b_u_i_l_d_i_n_g4 )1.37545)

(Path X_b_u_i_l_d_i_n_g4 X_b_u_i_l_d_i_n_g27 )
(Path X_b_u_i_l_d_i_n_g27 X_b_u_i_l_d_i_n_g4 )
(= (Distance X_b_u_i_l_d_i_n_g4 X_b_u_i_l_d_i_n_g27 )1.48822)
(= (Distance X_b_u_i_l_d_i_n_g27 X_b_u_i_l_d_i_n_g4 )1.48822)

(Path X_b_u_i_l_d_i_n_g4 X_b_u_i_l_d_i_n_g28 )
(Path X_b_u_i_l_d_i_n_g28 X_b_u_i_l_d_i_n_g4 )
(= (Distance X_b_u_i_l_d_i_n_g4 X_b_u_i_l_d_i_n_g28 )1.99534)
(= (Distance X_b_u_i_l_d_i_n_g28 X_b_u_i_l_d_i_n_g4 )1.99534)

(Path X_b_u_i_l_d_i_n_g4 X_b_u_i_l_d_i_n_g29 )
(Path X_b_u_i_l_d_i_n_g29 X_b_u_i_l_d_i_n_g4 )
(= (Distance X_b_u_i_l_d_i_n_g4 X_b_u_i_l_d_i_n_g29 )1.76343)
(= (Distance X_b_u_i_l_d_i_n_g29 X_b_u_i_l_d_i_n_g4 )1.76343)

(Path X_b_u_i_l_d_i_n_g4 X_b_u_i_l_d_i_n_g30 )
(Path X_b_u_i_l_d_i_n_g30 X_b_u_i_l_d_i_n_g4 )
(= (Distance X_b_u_i_l_d_i_n_g4 X_b_u_i_l_d_i_n_g30 )1.1808)
(= (Distance X_b_u_i_l_d_i_n_g30 X_b_u_i_l_d_i_n_g4 )1.1808)

(Path X_b_u_i_l_d_i_n_g5 X_b_u_i_l_d_i_n_g31 )
(Path X_b_u_i_l_d_i_n_g31 X_b_u_i_l_d_i_n_g5 )
(= (Distance X_b_u_i_l_d_i_n_g5 X_b_u_i_l_d_i_n_g31 )1.19761)
(= (Distance X_b_u_i_l_d_i_n_g31 X_b_u_i_l_d_i_n_g5 )1.19761)

(Path X_b_u_i_l_d_i_n_g5 X_b_u_i_l_d_i_n_g32 )
(Path X_b_u_i_l_d_i_n_g32 X_b_u_i_l_d_i_n_g5 )
(= (Distance X_b_u_i_l_d_i_n_g5 X_b_u_i_l_d_i_n_g32 )1.07967)
(= (Distance X_b_u_i_l_d_i_n_g32 X_b_u_i_l_d_i_n_g5 )1.07967)

(Path X_b_u_i_l_d_i_n_g5 X_b_u_i_l_d_i_n_g33 )
(Path X_b_u_i_l_d_i_n_g33 X_b_u_i_l_d_i_n_g5 )
(= (Distance X_b_u_i_l_d_i_n_g5 X_b_u_i_l_d_i_n_g33 )1.14849)
(= (Distance X_b_u_i_l_d_i_n_g33 X_b_u_i_l_d_i_n_g5 )1.14849)

(Path X_b_u_i_l_d_i_n_g5 X_b_u_i_l_d_i_n_g34 )
(Path X_b_u_i_l_d_i_n_g34 X_b_u_i_l_d_i_n_g5 )
(= (Distance X_b_u_i_l_d_i_n_g5 X_b_u_i_l_d_i_n_g34 )1.17484)
(= (Distance X_b_u_i_l_d_i_n_g34 X_b_u_i_l_d_i_n_g5 )1.17484)

(Path X_b_u_i_l_d_i_n_g5 X_b_u_i_l_d_i_n_g35 )
(Path X_b_u_i_l_d_i_n_g35 X_b_u_i_l_d_i_n_g5 )
(= (Distance X_b_u_i_l_d_i_n_g5 X_b_u_i_l_d_i_n_g35 )1.40807)
(= (Distance X_b_u_i_l_d_i_n_g35 X_b_u_i_l_d_i_n_g5 )1.40807)

(Path X_b_u_i_l_d_i_n_g5 X_b_u_i_l_d_i_n_g36 )
(Path X_b_u_i_l_d_i_n_g36 X_b_u_i_l_d_i_n_g5 )
(= (Distance X_b_u_i_l_d_i_n_g5 X_b_u_i_l_d_i_n_g36 )1.28434)
(= (Distance X_b_u_i_l_d_i_n_g36 X_b_u_i_l_d_i_n_g5 )1.28434)

(Path X_b_u_i_l_d_i_n_g6 X_b_u_i_l_d_i_n_g37 )
(Path X_b_u_i_l_d_i_n_g37 X_b_u_i_l_d_i_n_g6 )
(= (Distance X_b_u_i_l_d_i_n_g6 X_b_u_i_l_d_i_n_g37 )1.15322)
(= (Distance X_b_u_i_l_d_i_n_g37 X_b_u_i_l_d_i_n_g6 )1.15322)

(Path X_b_u_i_l_d_i_n_g6 X_b_u_i_l_d_i_n_g38 )
(Path X_b_u_i_l_d_i_n_g38 X_b_u_i_l_d_i_n_g6 )
(= (Distance X_b_u_i_l_d_i_n_g6 X_b_u_i_l_d_i_n_g38 )1.67118)
(= (Distance X_b_u_i_l_d_i_n_g38 X_b_u_i_l_d_i_n_g6 )1.67118)

(Path X_b_u_i_l_d_i_n_g6 X_b_u_i_l_d_i_n_g39 )
(Path X_b_u_i_l_d_i_n_g39 X_b_u_i_l_d_i_n_g6 )
(= (Distance X_b_u_i_l_d_i_n_g6 X_b_u_i_l_d_i_n_g39 )1.92836)
(= (Distance X_b_u_i_l_d_i_n_g39 X_b_u_i_l_d_i_n_g6 )1.92836)

(Path X_b_u_i_l_d_i_n_g6 X_b_u_i_l_d_i_n_g40 )
(Path X_b_u_i_l_d_i_n_g40 X_b_u_i_l_d_i_n_g6 )
(= (Distance X_b_u_i_l_d_i_n_g6 X_b_u_i_l_d_i_n_g40 )1.0211)
(= (Distance X_b_u_i_l_d_i_n_g40 X_b_u_i_l_d_i_n_g6 )1.0211)

(Path X_b_u_i_l_d_i_n_g6 X_b_u_i_l_d_i_n_g41 )
(Path X_b_u_i_l_d_i_n_g41 X_b_u_i_l_d_i_n_g6 )
(= (Distance X_b_u_i_l_d_i_n_g6 X_b_u_i_l_d_i_n_g41 )1.26264)
(= (Distance X_b_u_i_l_d_i_n_g41 X_b_u_i_l_d_i_n_g6 )1.26264)

(Path X_b_u_i_l_d_i_n_g6 X_b_u_i_l_d_i_n_g42 )
(Path X_b_u_i_l_d_i_n_g42 X_b_u_i_l_d_i_n_g6 )
(= (Distance X_b_u_i_l_d_i_n_g6 X_b_u_i_l_d_i_n_g42 )1.99573)
(= (Distance X_b_u_i_l_d_i_n_g42 X_b_u_i_l_d_i_n_g6 )1.99573)

(Path X_b_u_i_l_d_i_n_g7 X_b_u_i_l_d_i_n_g43 )
(Path X_b_u_i_l_d_i_n_g43 X_b_u_i_l_d_i_n_g7 )
(= (Distance X_b_u_i_l_d_i_n_g7 X_b_u_i_l_d_i_n_g43 )0.0456)
(= (Distance X_b_u_i_l_d_i_n_g43 X_b_u_i_l_d_i_n_g7 )0.0456)

(Path X_b_u_i_l_d_i_n_g8 X_b_u_i_l_d_i_n_g44 )
(Path X_b_u_i_l_d_i_n_g44 X_b_u_i_l_d_i_n_g8 )
(= (Distance X_b_u_i_l_d_i_n_g8 X_b_u_i_l_d_i_n_g44 )0.01817)
(= (Distance X_b_u_i_l_d_i_n_g44 X_b_u_i_l_d_i_n_g8 )0.01817)

(Path X_b_u_i_l_d_i_n_g9 X_b_u_i_l_d_i_n_g45 )
(Path X_b_u_i_l_d_i_n_g45 X_b_u_i_l_d_i_n_g9 )
(= (Distance X_b_u_i_l_d_i_n_g9 X_b_u_i_l_d_i_n_g45 )0.07114)
(= (Distance X_b_u_i_l_d_i_n_g45 X_b_u_i_l_d_i_n_g9 )0.07114)

(Path X_b_u_i_l_d_i_n_g10 X_b_u_i_l_d_i_n_g46 )
(Path X_b_u_i_l_d_i_n_g46 X_b_u_i_l_d_i_n_g10 )
(= (Distance X_b_u_i_l_d_i_n_g10 X_b_u_i_l_d_i_n_g46 )0.01143)
(= (Distance X_b_u_i_l_d_i_n_g46 X_b_u_i_l_d_i_n_g10 )0.01143)

(Path X_b_u_i_l_d_i_n_g11 X_b_u_i_l_d_i_n_g47 )
(Path X_b_u_i_l_d_i_n_g47 X_b_u_i_l_d_i_n_g11 )
(= (Distance X_b_u_i_l_d_i_n_g11 X_b_u_i_l_d_i_n_g47 )0.03112)
(= (Distance X_b_u_i_l_d_i_n_g47 X_b_u_i_l_d_i_n_g11 )0.03112)

(Path X_b_u_i_l_d_i_n_g12 X_b_u_i_l_d_i_n_g48 )
(Path X_b_u_i_l_d_i_n_g48 X_b_u_i_l_d_i_n_g12 )
(= (Distance X_b_u_i_l_d_i_n_g12 X_b_u_i_l_d_i_n_g48 )0.05008)
(= (Distance X_b_u_i_l_d_i_n_g48 X_b_u_i_l_d_i_n_g12 )0.05008)

(Path X_b_u_i_l_d_i_n_g13 X_b_u_i_l_d_i_n_g49 )
(Path X_b_u_i_l_d_i_n_g49 X_b_u_i_l_d_i_n_g13 )
(= (Distance X_b_u_i_l_d_i_n_g13 X_b_u_i_l_d_i_n_g49 )0.07278)
(= (Distance X_b_u_i_l_d_i_n_g49 X_b_u_i_l_d_i_n_g13 )0.07278)

(Path X_b_u_i_l_d_i_n_g14 X_b_u_i_l_d_i_n_g50 )
(Path X_b_u_i_l_d_i_n_g50 X_b_u_i_l_d_i_n_g14 )
(= (Distance X_b_u_i_l_d_i_n_g14 X_b_u_i_l_d_i_n_g50 )0.07918)
(= (Distance X_b_u_i_l_d_i_n_g50 X_b_u_i_l_d_i_n_g14 )0.07918)

(Path X_b_u_i_l_d_i_n_g15 X_b_u_i_l_d_i_n_g51 )
(Path X_b_u_i_l_d_i_n_g51 X_b_u_i_l_d_i_n_g15 )
(= (Distance X_b_u_i_l_d_i_n_g15 X_b_u_i_l_d_i_n_g51 )0.09646)
(= (Distance X_b_u_i_l_d_i_n_g51 X_b_u_i_l_d_i_n_g15 )0.09646)

(Path X_b_u_i_l_d_i_n_g16 X_b_u_i_l_d_i_n_g52 )
(Path X_b_u_i_l_d_i_n_g52 X_b_u_i_l_d_i_n_g16 )
(= (Distance X_b_u_i_l_d_i_n_g16 X_b_u_i_l_d_i_n_g52 )0.01903)
(= (Distance X_b_u_i_l_d_i_n_g52 X_b_u_i_l_d_i_n_g16 )0.01903)

(Path X_b_u_i_l_d_i_n_g17 X_b_u_i_l_d_i_n_g53 )
(Path X_b_u_i_l_d_i_n_g53 X_b_u_i_l_d_i_n_g17 )
(= (Distance X_b_u_i_l_d_i_n_g17 X_b_u_i_l_d_i_n_g53 )0.09474)
(= (Distance X_b_u_i_l_d_i_n_g53 X_b_u_i_l_d_i_n_g17 )0.09474)

(Path X_b_u_i_l_d_i_n_g18 X_b_u_i_l_d_i_n_g54 )
(Path X_b_u_i_l_d_i_n_g54 X_b_u_i_l_d_i_n_g18 )
(= (Distance X_b_u_i_l_d_i_n_g18 X_b_u_i_l_d_i_n_g54 )0.08052)
(= (Distance X_b_u_i_l_d_i_n_g54 X_b_u_i_l_d_i_n_g18 )0.08052)

(Path X_b_u_i_l_d_i_n_g19 X_b_u_i_l_d_i_n_g55 )
(Path X_b_u_i_l_d_i_n_g55 X_b_u_i_l_d_i_n_g19 )
(= (Distance X_b_u_i_l_d_i_n_g19 X_b_u_i_l_d_i_n_g55 )0.03617)
(= (Distance X_b_u_i_l_d_i_n_g55 X_b_u_i_l_d_i_n_g19 )0.03617)

(Path X_b_u_i_l_d_i_n_g20 X_b_u_i_l_d_i_n_g56 )
(Path X_b_u_i_l_d_i_n_g56 X_b_u_i_l_d_i_n_g20 )
(= (Distance X_b_u_i_l_d_i_n_g20 X_b_u_i_l_d_i_n_g56 )0.0903)
(= (Distance X_b_u_i_l_d_i_n_g56 X_b_u_i_l_d_i_n_g20 )0.0903)

(Path X_b_u_i_l_d_i_n_g21 X_b_u_i_l_d_i_n_g57 )
(Path X_b_u_i_l_d_i_n_g57 X_b_u_i_l_d_i_n_g21 )
(= (Distance X_b_u_i_l_d_i_n_g21 X_b_u_i_l_d_i_n_g57 )0.02553)
(= (Distance X_b_u_i_l_d_i_n_g57 X_b_u_i_l_d_i_n_g21 )0.02553)

(Path X_b_u_i_l_d_i_n_g22 X_b_u_i_l_d_i_n_g58 )
(Path X_b_u_i_l_d_i_n_g58 X_b_u_i_l_d_i_n_g22 )
(= (Distance X_b_u_i_l_d_i_n_g22 X_b_u_i_l_d_i_n_g58 )0.04006)
(= (Distance X_b_u_i_l_d_i_n_g58 X_b_u_i_l_d_i_n_g22 )0.04006)

(Path X_b_u_i_l_d_i_n_g23 X_b_u_i_l_d_i_n_g59 )
(Path X_b_u_i_l_d_i_n_g59 X_b_u_i_l_d_i_n_g23 )
(= (Distance X_b_u_i_l_d_i_n_g23 X_b_u_i_l_d_i_n_g59 )0.00459)
(= (Distance X_b_u_i_l_d_i_n_g59 X_b_u_i_l_d_i_n_g23 )0.00459)

(Path X_b_u_i_l_d_i_n_g24 X_b_u_i_l_d_i_n_g60 )
(Path X_b_u_i_l_d_i_n_g60 X_b_u_i_l_d_i_n_g24 )
(= (Distance X_b_u_i_l_d_i_n_g24 X_b_u_i_l_d_i_n_g60 )0.0605)
(= (Distance X_b_u_i_l_d_i_n_g60 X_b_u_i_l_d_i_n_g24 )0.0605)

(Path X_b_u_i_l_d_i_n_g25 X_b_u_i_l_d_i_n_g61 )
(Path X_b_u_i_l_d_i_n_g61 X_b_u_i_l_d_i_n_g25 )
(= (Distance X_b_u_i_l_d_i_n_g25 X_b_u_i_l_d_i_n_g61 )0.06437)
(= (Distance X_b_u_i_l_d_i_n_g61 X_b_u_i_l_d_i_n_g25 )0.06437)

(Path X_b_u_i_l_d_i_n_g26 X_b_u_i_l_d_i_n_g62 )
(Path X_b_u_i_l_d_i_n_g62 X_b_u_i_l_d_i_n_g26 )
(= (Distance X_b_u_i_l_d_i_n_g26 X_b_u_i_l_d_i_n_g62 )0.0657)
(= (Distance X_b_u_i_l_d_i_n_g62 X_b_u_i_l_d_i_n_g26 )0.0657)

(Path X_b_u_i_l_d_i_n_g27 X_b_u_i_l_d_i_n_g63 )
(Path X_b_u_i_l_d_i_n_g63 X_b_u_i_l_d_i_n_g27 )
(= (Distance X_b_u_i_l_d_i_n_g27 X_b_u_i_l_d_i_n_g63 )0.07968)
(= (Distance X_b_u_i_l_d_i_n_g63 X_b_u_i_l_d_i_n_g27 )0.07968)

(Path X_b_u_i_l_d_i_n_g28 X_b_u_i_l_d_i_n_g64 )
(Path X_b_u_i_l_d_i_n_g64 X_b_u_i_l_d_i_n_g28 )
(= (Distance X_b_u_i_l_d_i_n_g28 X_b_u_i_l_d_i_n_g64 )0.05773)
(= (Distance X_b_u_i_l_d_i_n_g64 X_b_u_i_l_d_i_n_g28 )0.05773)

(Path X_b_u_i_l_d_i_n_g29 X_b_u_i_l_d_i_n_g65 )
(Path X_b_u_i_l_d_i_n_g65 X_b_u_i_l_d_i_n_g29 )
(= (Distance X_b_u_i_l_d_i_n_g29 X_b_u_i_l_d_i_n_g65 )0.09954)
(= (Distance X_b_u_i_l_d_i_n_g65 X_b_u_i_l_d_i_n_g29 )0.09954)

(Path X_b_u_i_l_d_i_n_g30 X_b_u_i_l_d_i_n_g66 )
(Path X_b_u_i_l_d_i_n_g66 X_b_u_i_l_d_i_n_g30 )
(= (Distance X_b_u_i_l_d_i_n_g30 X_b_u_i_l_d_i_n_g66 )0.07829)
(= (Distance X_b_u_i_l_d_i_n_g66 X_b_u_i_l_d_i_n_g30 )0.07829)

(Path X_b_u_i_l_d_i_n_g31 X_b_u_i_l_d_i_n_g67 )
(Path X_b_u_i_l_d_i_n_g67 X_b_u_i_l_d_i_n_g31 )
(= (Distance X_b_u_i_l_d_i_n_g31 X_b_u_i_l_d_i_n_g67 )0.04563)
(= (Distance X_b_u_i_l_d_i_n_g67 X_b_u_i_l_d_i_n_g31 )0.04563)

(Path X_b_u_i_l_d_i_n_g32 X_b_u_i_l_d_i_n_g68 )
(Path X_b_u_i_l_d_i_n_g68 X_b_u_i_l_d_i_n_g32 )
(= (Distance X_b_u_i_l_d_i_n_g32 X_b_u_i_l_d_i_n_g68 )0.05543)
(= (Distance X_b_u_i_l_d_i_n_g68 X_b_u_i_l_d_i_n_g32 )0.05543)

(Path X_b_u_i_l_d_i_n_g33 X_b_u_i_l_d_i_n_g69 )
(Path X_b_u_i_l_d_i_n_g69 X_b_u_i_l_d_i_n_g33 )
(= (Distance X_b_u_i_l_d_i_n_g33 X_b_u_i_l_d_i_n_g69 )0.0298)
(= (Distance X_b_u_i_l_d_i_n_g69 X_b_u_i_l_d_i_n_g33 )0.0298)

(Path X_b_u_i_l_d_i_n_g34 X_b_u_i_l_d_i_n_g70 )
(Path X_b_u_i_l_d_i_n_g70 X_b_u_i_l_d_i_n_g34 )
(= (Distance X_b_u_i_l_d_i_n_g34 X_b_u_i_l_d_i_n_g70 )0.0468)
(= (Distance X_b_u_i_l_d_i_n_g70 X_b_u_i_l_d_i_n_g34 )0.0468)

(Path X_b_u_i_l_d_i_n_g35 X_b_u_i_l_d_i_n_g71 )
(Path X_b_u_i_l_d_i_n_g71 X_b_u_i_l_d_i_n_g35 )
(= (Distance X_b_u_i_l_d_i_n_g35 X_b_u_i_l_d_i_n_g71 )0.04947)
(= (Distance X_b_u_i_l_d_i_n_g71 X_b_u_i_l_d_i_n_g35 )0.04947)

(Path X_b_u_i_l_d_i_n_g36 X_b_u_i_l_d_i_n_g72 )
(Path X_b_u_i_l_d_i_n_g72 X_b_u_i_l_d_i_n_g36 )
(= (Distance X_b_u_i_l_d_i_n_g36 X_b_u_i_l_d_i_n_g72 )0.02166)
(= (Distance X_b_u_i_l_d_i_n_g72 X_b_u_i_l_d_i_n_g36 )0.02166)

(Path X_b_u_i_l_d_i_n_g37 X_b_u_i_l_d_i_n_g73 )
(Path X_b_u_i_l_d_i_n_g73 X_b_u_i_l_d_i_n_g37 )
(= (Distance X_b_u_i_l_d_i_n_g37 X_b_u_i_l_d_i_n_g73 )0.04627)
(= (Distance X_b_u_i_l_d_i_n_g73 X_b_u_i_l_d_i_n_g37 )0.04627)

(Path X_b_u_i_l_d_i_n_g38 X_b_u_i_l_d_i_n_g74 )
(Path X_b_u_i_l_d_i_n_g74 X_b_u_i_l_d_i_n_g38 )
(= (Distance X_b_u_i_l_d_i_n_g38 X_b_u_i_l_d_i_n_g74 )0.05654)
(= (Distance X_b_u_i_l_d_i_n_g74 X_b_u_i_l_d_i_n_g38 )0.05654)

(Path X_b_u_i_l_d_i_n_g39 X_b_u_i_l_d_i_n_g75 )
(Path X_b_u_i_l_d_i_n_g75 X_b_u_i_l_d_i_n_g39 )
(= (Distance X_b_u_i_l_d_i_n_g39 X_b_u_i_l_d_i_n_g75 )0.06249)
(= (Distance X_b_u_i_l_d_i_n_g75 X_b_u_i_l_d_i_n_g39 )0.06249)

(Path X_b_u_i_l_d_i_n_g40 X_b_u_i_l_d_i_n_g76 )
(Path X_b_u_i_l_d_i_n_g76 X_b_u_i_l_d_i_n_g40 )
(= (Distance X_b_u_i_l_d_i_n_g40 X_b_u_i_l_d_i_n_g76 )0.02861)
(= (Distance X_b_u_i_l_d_i_n_g76 X_b_u_i_l_d_i_n_g40 )0.02861)

(Path X_b_u_i_l_d_i_n_g41 X_b_u_i_l_d_i_n_g77 )
(Path X_b_u_i_l_d_i_n_g77 X_b_u_i_l_d_i_n_g41 )
(= (Distance X_b_u_i_l_d_i_n_g41 X_b_u_i_l_d_i_n_g77 )0.07291)
(= (Distance X_b_u_i_l_d_i_n_g77 X_b_u_i_l_d_i_n_g41 )0.07291)

(Path X_b_u_i_l_d_i_n_g42 X_b_u_i_l_d_i_n_g78 )
(Path X_b_u_i_l_d_i_n_g78 X_b_u_i_l_d_i_n_g42 )
(= (Distance X_b_u_i_l_d_i_n_g42 X_b_u_i_l_d_i_n_g78 )0.00728)
(= (Distance X_b_u_i_l_d_i_n_g78 X_b_u_i_l_d_i_n_g42 )0.00728)

(EmptyHome X_b_u_i_l_d_i_n_g7)
(EmptyHome X_b_u_i_l_d_i_n_g8)
(EmptyHome X_b_u_i_l_d_i_n_g9)
(EmptyHome X_b_u_i_l_d_i_n_g10)
(EmptyHome X_b_u_i_l_d_i_n_g11)
(EmptyHome X_b_u_i_l_d_i_n_g12)
(EmptyHome X_b_u_i_l_d_i_n_g13)
(EmptyHome X_b_u_i_l_d_i_n_g14)
(EmptyHome X_b_u_i_l_d_i_n_g15)
(EmptyHome X_b_u_i_l_d_i_n_g16)
(EmptyHome X_b_u_i_l_d_i_n_g17)
(EmptyHome X_b_u_i_l_d_i_n_g18)
(EmptyHome X_b_u_i_l_d_i_n_g19)
(EmptyHome X_b_u_i_l_d_i_n_g20)
(EmptyHome X_b_u_i_l_d_i_n_g21)
(EmptyHome X_b_u_i_l_d_i_n_g22)
(EmptyHome X_b_u_i_l_d_i_n_g23)
(EmptyHome X_b_u_i_l_d_i_n_g24)
(EmptyHome X_b_u_i_l_d_i_n_g25)
(EmptyHome X_b_u_i_l_d_i_n_g26)
(EmptyHome X_b_u_i_l_d_i_n_g27)
(EmptyHome X_b_u_i_l_d_i_n_g28)
(EmptyHome X_b_u_i_l_d_i_n_g29)
(EmptyHome X_b_u_i_l_d_i_n_g30)
(EmptyHome X_b_u_i_l_d_i_n_g31)
(EmptyHome X_b_u_i_l_d_i_n_g32)
(EmptyHome X_b_u_i_l_d_i_n_g33)
(EmptyHome X_b_u_i_l_d_i_n_g34)
(EmptyHome X_b_u_i_l_d_i_n_g35)
(EmptyHome X_b_u_i_l_d_i_n_g36)
(EmptyHome X_b_u_i_l_d_i_n_g37)
(EmptyHome X_b_u_i_l_d_i_n_g38)
(EmptyHome X_b_u_i_l_d_i_n_g39)
(EmptyHome X_b_u_i_l_d_i_n_g40)
(EmptyHome X_b_u_i_l_d_i_n_g41)
(EmptyHome X_b_u_i_l_d_i_n_g42)
(EmptyHome X_b_u_i_l_d_i_n_g43)
(EmptyHome X_b_u_i_l_d_i_n_g44)
(EmptyHome X_b_u_i_l_d_i_n_g45)
(EmptyHome X_b_u_i_l_d_i_n_g46)
(EmptyHome X_b_u_i_l_d_i_n_g47)
(EmptyHome X_b_u_i_l_d_i_n_g48)
(EmptyHome X_b_u_i_l_d_i_n_g49)
(EmptyHome X_b_u_i_l_d_i_n_g50)
(EmptyHome X_b_u_i_l_d_i_n_g51)
(EmptyHome X_b_u_i_l_d_i_n_g52)
(EmptyHome X_b_u_i_l_d_i_n_g53)
(EmptyHome X_b_u_i_l_d_i_n_g54)
(EmptyHome X_b_u_i_l_d_i_n_g55)
(EmptyHome X_b_u_i_l_d_i_n_g56)
(EmptyHome X_b_u_i_l_d_i_n_g57)
(EmptyHome X_b_u_i_l_d_i_n_g58)
(EmptyHome X_b_u_i_l_d_i_n_g59)
(EmptyHome X_b_u_i_l_d_i_n_g60)
(EmptyHome X_b_u_i_l_d_i_n_g61)
(EmptyHome X_b_u_i_l_d_i_n_g62)
(EmptyHome X_b_u_i_l_d_i_n_g63)
(EmptyHome X_b_u_i_l_d_i_n_g64)
(EmptyHome X_b_u_i_l_d_i_n_g65)
(EmptyHome X_b_u_i_l_d_i_n_g66)
(EmptyHome X_b_u_i_l_d_i_n_g67)
(EmptyHome X_b_u_i_l_d_i_n_g68)
(EmptyHome X_b_u_i_l_d_i_n_g69)
(EmptyHome X_b_u_i_l_d_i_n_g70)
(EmptyHome X_b_u_i_l_d_i_n_g71)
(EmptyHome X_b_u_i_l_d_i_n_g72)
(EmptyHome X_b_u_i_l_d_i_n_g73)
(EmptyHome X_b_u_i_l_d_i_n_g74)
(EmptyHome X_b_u_i_l_d_i_n_g75)
(EmptyHome X_b_u_i_l_d_i_n_g76)
(EmptyHome X_b_u_i_l_d_i_n_g77)
(EmptyHome X_b_u_i_l_d_i_n_g78)
)

  ; The goal state describe what we desire to achieve
  (:goal (and
( Car_At XS_o_d_a )
(not (EmptyHome X_b_u_i_l_d_i_n_g7))
(not (EmptyHome X_b_u_i_l_d_i_n_g8))
(not (EmptyHome X_b_u_i_l_d_i_n_g9))
(not (EmptyHome X_b_u_i_l_d_i_n_g10))
(not (EmptyHome X_b_u_i_l_d_i_n_g11))
(not (EmptyHome X_b_u_i_l_d_i_n_g12))
(not (EmptyHome X_b_u_i_l_d_i_n_g13))
(not (EmptyHome X_b_u_i_l_d_i_n_g14))
(not (EmptyHome X_b_u_i_l_d_i_n_g15))
(not (EmptyHome X_b_u_i_l_d_i_n_g16))
(not (EmptyHome X_b_u_i_l_d_i_n_g17))
(not (EmptyHome X_b_u_i_l_d_i_n_g18))
(not (EmptyHome X_b_u_i_l_d_i_n_g19))
(not (EmptyHome X_b_u_i_l_d_i_n_g20))
(not (EmptyHome X_b_u_i_l_d_i_n_g21))
(not (EmptyHome X_b_u_i_l_d_i_n_g22))
(not (EmptyHome X_b_u_i_l_d_i_n_g23))
(not (EmptyHome X_b_u_i_l_d_i_n_g24))
(not (EmptyHome X_b_u_i_l_d_i_n_g25))
(not (EmptyHome X_b_u_i_l_d_i_n_g26))
(not (EmptyHome X_b_u_i_l_d_i_n_g27))
(not (EmptyHome X_b_u_i_l_d_i_n_g28))
(not (EmptyHome X_b_u_i_l_d_i_n_g29))
(not (EmptyHome X_b_u_i_l_d_i_n_g30))
(not (EmptyHome X_b_u_i_l_d_i_n_g31))
(not (EmptyHome X_b_u_i_l_d_i_n_g32))
(not (EmptyHome X_b_u_i_l_d_i_n_g33))
(not (EmptyHome X_b_u_i_l_d_i_n_g34))
(not (EmptyHome X_b_u_i_l_d_i_n_g35))
(not (EmptyHome X_b_u_i_l_d_i_n_g36))
(not (EmptyHome X_b_u_i_l_d_i_n_g37))
(not (EmptyHome X_b_u_i_l_d_i_n_g38))
(not (EmptyHome X_b_u_i_l_d_i_n_g39))
(not (EmptyHome X_b_u_i_l_d_i_n_g40))
(not (EmptyHome X_b_u_i_l_d_i_n_g41))
(not (EmptyHome X_b_u_i_l_d_i_n_g42))
(not (EmptyHome X_b_u_i_l_d_i_n_g43))
(not (EmptyHome X_b_u_i_l_d_i_n_g44))
(not (EmptyHome X_b_u_i_l_d_i_n_g45))
(not (EmptyHome X_b_u_i_l_d_i_n_g46))
(not (EmptyHome X_b_u_i_l_d_i_n_g47))
(not (EmptyHome X_b_u_i_l_d_i_n_g48))
(not (EmptyHome X_b_u_i_l_d_i_n_g49))
(not (EmptyHome X_b_u_i_l_d_i_n_g50))
(not (EmptyHome X_b_u_i_l_d_i_n_g51))
(not (EmptyHome X_b_u_i_l_d_i_n_g52))
(not (EmptyHome X_b_u_i_l_d_i_n_g53))
(not (EmptyHome X_b_u_i_l_d_i_n_g54))
(not (EmptyHome X_b_u_i_l_d_i_n_g55))
(not (EmptyHome X_b_u_i_l_d_i_n_g56))
(not (EmptyHome X_b_u_i_l_d_i_n_g57))
(not (EmptyHome X_b_u_i_l_d_i_n_g58))
(not (EmptyHome X_b_u_i_l_d_i_n_g59))
(not (EmptyHome X_b_u_i_l_d_i_n_g60))
(not (EmptyHome X_b_u_i_l_d_i_n_g61))
(not (EmptyHome X_b_u_i_l_d_i_n_g62))
(not (EmptyHome X_b_u_i_l_d_i_n_g63))
(not (EmptyHome X_b_u_i_l_d_i_n_g64))
(not (EmptyHome X_b_u_i_l_d_i_n_g65))
(not (EmptyHome X_b_u_i_l_d_i_n_g66))
(not (EmptyHome X_b_u_i_l_d_i_n_g67))
(not (EmptyHome X_b_u_i_l_d_i_n_g68))
(not (EmptyHome X_b_u_i_l_d_i_n_g69))
(not (EmptyHome X_b_u_i_l_d_i_n_g70))
(not (EmptyHome X_b_u_i_l_d_i_n_g71))
(not (EmptyHome X_b_u_i_l_d_i_n_g72))
(not (EmptyHome X_b_u_i_l_d_i_n_g73))
(not (EmptyHome X_b_u_i_l_d_i_n_g74))
(not (EmptyHome X_b_u_i_l_d_i_n_g75))
(not (EmptyHome X_b_u_i_l_d_i_n_g76))
(not (EmptyHome X_b_u_i_l_d_i_n_g77))
(not (EmptyHome X_b_u_i_l_d_i_n_g78))
  ))
)