; Problem description
; This file describes the example input from the problem statement
(define (problem pb1)
  (:metric minimize (total-cost))
  (:domain CS170)
(:objects TA_XJ_o_h_n_s_o_n_b_e_r_g TA_XA_d_a_m_v_i_e_w TA_XF_e_l_i_c_i_a_v_i_l_l_e TA_XB_u_c_k_l_e_y_s_i_d_e TA_XC_o_m_b_s_v_i_l_l_e TA_XT_h_o_m_p_s_o_n_s_h_i_r_e TA_XM_i_r_a_n_d_a_v_i_e_w TA_XD_e_r_e_k_v_i_l_l_e TA_XW_i_l_s_o_n_s_t_a_d TA_XS_u_s_a_n_f_o_r_t TA_XH_a_l_e_v_i_e_w TA_XH_a_l_l_s_t_a_d TA_XA_d_a_m_p_o_r_t TA_XD_a_n_n_y_s_i_d_e TA_XJ_e_r_m_a_i_n_e_t_o_n TA_XP_a_r_k_e_r_m_o_u_t_h TA_XJ_a_m_e_s_t_o_n TA_XH_a_n_s_o_n_b_u_r_y TA_XK_y_l_i_e_v_i_e_w TA_XB_r_e_n_d_a_v_i_e_w TA_XM_e_r_c_e_d_e_s_m_o_u_t_h TA_XK_i_m_b_e_r_l_y_b_u_r_g_h TA_XL_e_a_h_m_o_u_t_h TA_XC_a_n_d_i_c_e_l_a_n_d TA_XH_o_u_s_t_o_n_c_h_e_s_t_e_r TA_XM_i_c_h_a_e_l_v_i_e_w TA_XD_y_e_r_p_o_r_t TA_XT_r_o_y_f_o_r_t TA_XC_r_a_n_e_m_o_u_t_h TA_XA_u_d_r_e_y_f_o_r_t TA_XR_e_y_n_o_l_d_s_v_i_e_w TA_XE_l_l_i_s_s_t_a_d TA_XB_y_r_d_f_u_r_t TA_XA_n_d_r_e_w_s_c_h_e_s_t_e_r TA_XT_a_n_n_e_r_h_a_v_e_n TA_XC_h_r_i_s_t_y_l_a_n_d TA_XP_a_t_r_i_c_i_a_s_i_d_e TA_XG_a_r_c_i_a_m_o_u_t_h TA_XR_o_b_i_n_s_o_n_m_o_u_t_h TA_XA_d_a_m_s_i_d_e TA_XB_a_k_e_r_t_o_w_n TA_XW_i_l_l_i_a_m_l_a_n_d TA_XP_a_t_r_i_c_i_a_b_u_r_y TA_XH_o_r_n_e_s_i_d_e TA_XJ_a_c_k_s_o_n_l_a_n_d TA_XL_o_w_e_r_y_b_o_r_o_u_g_h TA_XB_r_a_d_b_e_r_g TA_XC_h_r_i_s_t_o_p_h_e_r_h_a_v_e_n TA_XH_a_r_r_i_s_p_o_r_t TA_XR_i_o_s_h_a_v_e_n TA_XJ_o_n_e_s_f_u_r_t TA_XT_a_y_l_o_r_t_o_n TA_XW_i_l_l_i_a_m_s_c_h_e_s_t_e_r TA_XC_a_n_d_a_c_e_b_o_r_o_u_g_h TA_XH_o_d_g_e_s_s_t_a_d TA_XG_a_b_r_i_e_l_b_u_r_g_h TA_XC_l_a_r_k_p_o_r_t TA_XB_o_n_d_m_o_u_t_h TA_XF_o_r_d_h_a_v_e_n TA_XC_l_a_r_k_b_o_r_o_u_g_h TA_XH_o_l_t_h_a_v_e_n TA_XO_s_b_o_r_n_e_m_o_u_t_h TA_XO_r_t_e_g_a_b_e_r_g TA_XD_a_n_i_e_l_v_i_l_l_e TA_XS_h_a_w_n_m_o_u_t_h TA_XR_y_a_n_s_i_d_e TA_XS_m_i_t_h_t_o_w_n TA_XJ_a_c_k_s_o_n_v_i_e_w TA_XR_a_m_o_s_b_o_r_o_u_g_h TA_XS_w_a_n_s_o_n_s_h_i_r_e TA_XT_h_o_m_a_s_m_o_u_t_h TA_XS_u_t_t_o_n_v_i_l_l_e TA_XA_n_n_b_e_r_g TA_XM_a_r_y_p_o_r_t TA_XO_r_t_i_z_b_e_r_g TA_XC_a_l_v_i_n_t_o_n TA_XW_i_l_l_i_a_m_s_h_i_r_e TA_XC_o_d_y_t_o_n TA_XV_i_c_k_i_v_i_l_l_e TA_XM_i_n_d_y_v_i_e_w TA_XA_b_i_g_a_i_l_v_i_l_l_e TA_XC_l_a_r_e_n_c_e_v_i_e_w TA_XM_a_s_s_e_y_s_i_d_e TA_XR_o_b_e_r_t_o_m_o_u_t_h TA_XM_i_c_h_a_e_l_v_i_l_l_e TA_XJ_e_n_n_i_f_e_r_t_o_w_n TA_XN_e_a_l_f_u_r_t TA_XH_a_r_r_i_s_b_o_r_o_u_g_h TA_XA_d_k_i_n_s_b_e_r_g TA_XM_i_l_l_e_r_b_o_r_o_u_g_h TA_XS_h_a_w_n_f_o_r_t TA_XW_a_t_s_o_n_v_i_l_l_e TA_XA_b_i_g_a_i_l_h_a_v_e_n TA_XS_m_i_t_h_f_o_r_t TA_XJ_o_s_e_p_h_s_t_a_d TA_XC_l_a_r_k_b_u_r_y TA_XP_r_i_c_e_v_i_l_l_e TA_XJ_o_n_e_s_c_h_e_s_t_e_r TA_XH_a_l_l_b_o_r_o_u_g_h TA_XT_h_o_m_a_s_b_o_r_o_u_g_h XL_o_p_e_z_b_o_r_o_u_g_h XL_o_p_e_z_b_u_r_g_h XL_a_u_r_e_n_b_u_r_y XR_o_b_e_r_t_s_s_t_a_d XW_e_b_b_v_i_e_w XA_b_i_g_a_i_l_h_a_v_e_n XW_i_l_l_i_a_m_s_h_i_r_e XB_u_r_t_o_n_v_i_e_w XD_e_r_e_k_m_o_u_t_h XO_s_b_o_r_n_e_m_o_u_t_h XB_u_r_g_e_s_s_v_i_e_w XB_o_n_d_m_o_u_t_h XT_y_l_e_r_b_u_r_y XS_w_a_n_s_o_n_s_h_i_r_e XS_m_i_t_h_f_o_r_t XK_i_m_b_e_r_l_y_b_u_r_g_h XT_h_o_m_p_s_o_n_s_h_i_r_e XA_d_a_m_p_o_r_t XJ_o_n_e_s_f_u_r_t XM_i_n_d_y_v_i_e_w XJ_o_s_e_p_o_r_t XM_o_o_d_y_b_u_r_g_h XN_e_w_m_a_n_b_u_r_g_h XB_i_l_l_t_o_n XL_o_w_e_r_y_b_o_r_o_u_g_h XS_t_u_a_r_t_s_h_i_r_e XM_i_c_h_a_e_l_v_i_e_w XR_e_e_v_e_s_t_o_w_n XD_a_n_i_e_l_l_e_p_o_r_t XR_a_m_o_s_b_o_r_o_u_g_h XS_h_a_w_n_m_o_u_t_h XA_u_d_r_e_y_f_o_r_t XC_a_l_v_i_n_t_o_n XC_o_o_p_e_r_t_o_n XK_i_m_b_e_r_l_y_m_o_u_t_h XO_s_b_o_r_n_e_v_i_l_l_e XP_a_r_k_e_r_m_o_u_t_h XG_a_b_r_i_e_l_b_u_r_g_h XS_m_i_t_h_t_o_w_n XM_i_c_h_a_e_l_v_i_l_l_e XK_e_v_i_n_b_e_r_g XT_a_n_n_e_r_h_a_v_e_n XH_a_r_r_i_s_b_o_r_o_u_g_h XC_h_a_r_l_e_s_b_e_r_g XV_i_c_k_i_v_i_l_l_e XC_l_a_r_k_p_o_r_t XB_a_n_k_s_b_u_r_g_h XB_e_c_k_e_r_t_o_n XJ_e_r_m_a_i_n_e_t_o_n XC_o_d_y_t_o_n XD_i_a_n_a_s_h_i_r_e XB_o_n_d_f_o_r_t XF_l_e_t_c_h_e_r_l_a_n_d XP_a_y_n_e_v_i_e_w XS_e_t_h_l_a_n_d XR_o_b_i_n_s_o_n_m_o_u_t_h XA_b_i_g_a_i_l_v_i_l_l_e XW_i_l_s_o_n_s_t_a_d XW_i_l_l_i_a_m_s_c_h_e_s_t_e_r XA_n_n_b_e_r_g XJ_o_s_e_p_h_s_t_a_d XJ_a_c_k_s_o_n_v_i_e_w XO_r_t_i_z_b_e_r_g XK_y_l_i_e_v_i_e_w XA_d_a_m_v_i_e_w XA_s_h_l_e_y_b_o_r_o_u_g_h XB_a_i_l_e_y_f_o_r_t XO_r_t_e_g_a_h_a_v_e_n XN_e_a_l_f_u_r_t XP_e_t_t_y_t_o_n XJ_a_c_k_s_o_n_v_i_l_l_e XT_o_d_d_t_o_w_n XC_a_n_d_a_c_e_b_o_r_o_u_g_h XC_l_a_r_k_b_e_r_g XG_a_r_c_i_a_m_o_u_t_h XT_h_o_m_a_s_v_i_l_l_e XF_o_r_d_h_a_v_e_n XS_a_m_a_n_t_h_a_s_h_i_r_e XA_s_h_l_e_y_s_t_a_d XF_e_l_i_c_i_a_v_i_l_l_e XH_a_l_l_b_o_r_o_u_g_h XH_o_r_n_e_s_i_d_e XJ_e_s_s_i_c_a_t_o_n XG_r_e_g_o_r_y_b_e_r_g XD_a_n_n_y_s_i_d_e XD_e_r_e_k_v_i_l_l_e XC_h_r_i_s_t_y_l_a_n_d XJ_u_d_i_t_h_v_i_e_w XP_a_u_l_t_o_w_n XS_u_s_a_n_f_o_r_t XL_e_a_h_m_o_u_t_h XB_r_e_n_d_a_v_i_e_w XD_y_e_r_p_o_r_t XM_i_c_h_e_l_l_e_h_a_v_e_n XW_a_t_s_o_n_v_i_l_l_e XB_y_r_d_f_u_r_t XH_a_r_r_i_s_p_o_r_t XC_l_a_r_k_b_u_r_y XH_a_n_s_o_n_b_u_r_y XS_h_a_w_n_h_a_v_e_n XJ_o_h_n_s_i_d_e XJ_e_n_n_i_f_e_r_t_o_w_n XP_r_i_c_e_v_i_l_l_e XC_a_s_t_a_n_e_d_a_c_h_e_s_t_e_r XH_a_l_l_s_t_a_d XD_a_n_i_e_l_v_i_l_l_e XM_e_l_i_s_s_a_v_i_e_w XH_e_a_t_h_e_r_b_e_r_g XM_a_s_s_e_y_s_i_d_e XA_n_d_r_e_w_s_c_h_e_s_t_e_r XJ_a_m_e_s_t_o_n XC_h_e_y_e_n_n_e_f_u_r_t XM_a_r_t_i_n_c_h_e_s_t_e_r XC_o_m_b_s_v_i_l_l_e XB_u_c_k_l_e_y_s_i_d_e XC_h_r_i_s_t_o_p_h_e_r_m_o_u_t_h XR_e_y_n_o_l_d_s_v_i_e_w XB_a_k_e_r_t_o_w_n XJ_e_f_f_r_e_y_f_o_r_t XR_i_c_h_t_o_w_n XD_a_v_i_d_t_o_w_n XA_d_k_i_n_s_b_e_r_g XE_m_i_l_y_v_i_e_w XJ_o_h_n_s_o_n_b_e_r_g XC_l_a_r_e_n_c_e_v_i_e_w XW_a_l_l_t_o_n XG_e_r_a_l_d_s_i_d_e XP_h_a_m_h_a_v_e_n XW_a_l_t_e_r_s_m_o_u_t_h XS_i_n_g_l_e_t_o_n_t_o_n XB_r_a_d_b_e_r_g XM_a_r_y_p_o_r_t XM_e_r_c_e_d_e_s_m_o_u_t_h XT_h_o_m_a_s_b_o_r_o_u_g_h XM_i_l_l_e_r_b_o_r_o_u_g_h XY_v_o_n_n_e_b_o_r_o_u_g_h XG_o_n_z_a_l_e_s_f_u_r_t XE_l_l_i_s_s_t_a_d XS_c_o_t_t_t_o_w_n XR_y_a_n_s_i_d_e XJ_a_c_k_s_o_n_t_o_n XL_e_e_c_h_e_s_t_e_r XH_o_d_g_e_s_s_t_a_d XC_a_n_d_i_c_e_l_a_n_d XB_a_r_n_e_s_m_o_u_t_h XJ_a_m_e_s_s_h_i_r_e XS_c_o_t_t_b_u_r_g_h XV_i_r_g_i_n_i_a_s_t_a_d XW_i_l_l_i_s_f_u_r_t XW_a_l_l_t_o_w_n XK_r_i_s_t_i_e_t_o_w_n XJ_o_e_b_u_r_y XT_a_y_l_o_r_t_o_n XW_i_l_l_i_a_m_p_o_r_t XD_a_v_i_s_s_t_a_d XC_a_m_p_b_e_l_l_h_a_v_e_n XS_i_m_m_o_n_s_b_u_r_g_h XP_a_t_r_i_c_i_a_b_u_r_y XO_r_t_e_g_a_b_e_r_g XC_h_r_i_s_t_o_p_h_e_r_h_a_v_e_n XH_o_u_s_t_o_n_c_h_e_s_t_e_r XC_l_a_r_k_b_o_r_o_u_g_h XG_a_b_r_i_e_l_f_o_r_t XS_u_t_t_o_n_v_i_l_l_e XT_e_r_e_s_a_f_o_r_t XP_a_t_r_i_c_i_a_s_i_d_e XD_e_n_i_s_e_c_h_e_s_t_e_r XW_i_l_l_i_a_m_l_a_n_d XC_a_l_l_a_h_a_n_t_o_w_n XP_a_u_l_b_u_r_g_h XP_a_t_t_e_r_s_o_n_b_e_r_g XH_o_l_t_h_a_v_e_n XB_r_o_o_k_e_m_o_u_t_h XT_r_o_y_f_o_r_t XM_u_r_p_h_y_s_i_d_e XJ_o_n_e_s_c_h_e_s_t_e_r XJ_a_m_i_e_s_i_d_e XM_a_t_t_h_e_w_b_u_r_g_h XD_a_v_i_d_s_o_n_v_i_e_w XS_h_a_w_n_f_o_r_t XJ_o_h_n_b_e_r_g XT_h_o_m_a_s_m_o_u_t_h XC_h_a_n_g_b_u_r_y XT_h_o_m_a_s_s_i_d_e XA_d_a_m_s_i_d_e XJ_o_h_n_s_o_n_c_h_e_s_t_e_r XG_a_r_y_t_o_w_n XM_i_r_a_n_d_a_v_i_e_w XW_e_b_e_r_b_u_r_y XG_a_l_l_o_w_a_y_m_o_u_t_h XR_i_o_s_h_a_v_e_n XK_i_n_g_v_i_e_w XR_o_b_e_r_t_o_m_o_u_t_h XH_a_l_e_v_i_e_w XM_a_r_c_u_s_b_u_r_g_h XJ_a_m_e_s_t_o_w_n XJ_a_c_k_s_o_n_l_a_n_d XP_o_r_t_e_r_t_o_n XC_r_a_n_e_m_o_u_t_h XW_i_l_l_i_a_m_f_o_r_t )
(:init(= (total-cost) 0)
( Car_At XP_o_r_t_e_r_t_o_n )
(InCar TA_XJ_o_h_n_s_o_n_b_e_r_g)
(InCar TA_XA_d_a_m_v_i_e_w)
(InCar TA_XF_e_l_i_c_i_a_v_i_l_l_e)
(InCar TA_XB_u_c_k_l_e_y_s_i_d_e)
(InCar TA_XC_o_m_b_s_v_i_l_l_e)
(InCar TA_XT_h_o_m_p_s_o_n_s_h_i_r_e)
(InCar TA_XM_i_r_a_n_d_a_v_i_e_w)
(InCar TA_XD_e_r_e_k_v_i_l_l_e)
(InCar TA_XW_i_l_s_o_n_s_t_a_d)
(InCar TA_XS_u_s_a_n_f_o_r_t)
(InCar TA_XH_a_l_e_v_i_e_w)
(InCar TA_XH_a_l_l_s_t_a_d)
(InCar TA_XA_d_a_m_p_o_r_t)
(InCar TA_XD_a_n_n_y_s_i_d_e)
(InCar TA_XJ_e_r_m_a_i_n_e_t_o_n)
(InCar TA_XP_a_r_k_e_r_m_o_u_t_h)
(InCar TA_XJ_a_m_e_s_t_o_n)
(InCar TA_XH_a_n_s_o_n_b_u_r_y)
(InCar TA_XK_y_l_i_e_v_i_e_w)
(InCar TA_XB_r_e_n_d_a_v_i_e_w)
(InCar TA_XM_e_r_c_e_d_e_s_m_o_u_t_h)
(InCar TA_XK_i_m_b_e_r_l_y_b_u_r_g_h)
(InCar TA_XL_e_a_h_m_o_u_t_h)
(InCar TA_XC_a_n_d_i_c_e_l_a_n_d)
(InCar TA_XH_o_u_s_t_o_n_c_h_e_s_t_e_r)
(InCar TA_XM_i_c_h_a_e_l_v_i_e_w)
(InCar TA_XD_y_e_r_p_o_r_t)
(InCar TA_XT_r_o_y_f_o_r_t)
(InCar TA_XC_r_a_n_e_m_o_u_t_h)
(InCar TA_XA_u_d_r_e_y_f_o_r_t)
(InCar TA_XR_e_y_n_o_l_d_s_v_i_e_w)
(InCar TA_XE_l_l_i_s_s_t_a_d)
(InCar TA_XB_y_r_d_f_u_r_t)
(InCar TA_XA_n_d_r_e_w_s_c_h_e_s_t_e_r)
(InCar TA_XT_a_n_n_e_r_h_a_v_e_n)
(InCar TA_XC_h_r_i_s_t_y_l_a_n_d)
(InCar TA_XP_a_t_r_i_c_i_a_s_i_d_e)
(InCar TA_XG_a_r_c_i_a_m_o_u_t_h)
(InCar TA_XR_o_b_i_n_s_o_n_m_o_u_t_h)
(InCar TA_XA_d_a_m_s_i_d_e)
(InCar TA_XB_a_k_e_r_t_o_w_n)
(InCar TA_XW_i_l_l_i_a_m_l_a_n_d)
(InCar TA_XP_a_t_r_i_c_i_a_b_u_r_y)
(InCar TA_XH_o_r_n_e_s_i_d_e)
(InCar TA_XJ_a_c_k_s_o_n_l_a_n_d)
(InCar TA_XL_o_w_e_r_y_b_o_r_o_u_g_h)
(InCar TA_XB_r_a_d_b_e_r_g)
(InCar TA_XC_h_r_i_s_t_o_p_h_e_r_h_a_v_e_n)
(InCar TA_XH_a_r_r_i_s_p_o_r_t)
(InCar TA_XR_i_o_s_h_a_v_e_n)
(InCar TA_XJ_o_n_e_s_f_u_r_t)
(InCar TA_XT_a_y_l_o_r_t_o_n)
(InCar TA_XW_i_l_l_i_a_m_s_c_h_e_s_t_e_r)
(InCar TA_XC_a_n_d_a_c_e_b_o_r_o_u_g_h)
(InCar TA_XH_o_d_g_e_s_s_t_a_d)
(InCar TA_XG_a_b_r_i_e_l_b_u_r_g_h)
(InCar TA_XC_l_a_r_k_p_o_r_t)
(InCar TA_XB_o_n_d_m_o_u_t_h)
(InCar TA_XF_o_r_d_h_a_v_e_n)
(InCar TA_XC_l_a_r_k_b_o_r_o_u_g_h)
(InCar TA_XH_o_l_t_h_a_v_e_n)
(InCar TA_XO_s_b_o_r_n_e_m_o_u_t_h)
(InCar TA_XO_r_t_e_g_a_b_e_r_g)
(InCar TA_XD_a_n_i_e_l_v_i_l_l_e)
(InCar TA_XS_h_a_w_n_m_o_u_t_h)
(InCar TA_XR_y_a_n_s_i_d_e)
(InCar TA_XS_m_i_t_h_t_o_w_n)
(InCar TA_XJ_a_c_k_s_o_n_v_i_e_w)
(InCar TA_XR_a_m_o_s_b_o_r_o_u_g_h)
(InCar TA_XS_w_a_n_s_o_n_s_h_i_r_e)
(InCar TA_XT_h_o_m_a_s_m_o_u_t_h)
(InCar TA_XS_u_t_t_o_n_v_i_l_l_e)
(InCar TA_XA_n_n_b_e_r_g)
(InCar TA_XM_a_r_y_p_o_r_t)
(InCar TA_XO_r_t_i_z_b_e_r_g)
(InCar TA_XC_a_l_v_i_n_t_o_n)
(InCar TA_XW_i_l_l_i_a_m_s_h_i_r_e)
(InCar TA_XC_o_d_y_t_o_n)
(InCar TA_XV_i_c_k_i_v_i_l_l_e)
(InCar TA_XM_i_n_d_y_v_i_e_w)
(InCar TA_XA_b_i_g_a_i_l_v_i_l_l_e)
(InCar TA_XC_l_a_r_e_n_c_e_v_i_e_w)
(InCar TA_XM_a_s_s_e_y_s_i_d_e)
(InCar TA_XR_o_b_e_r_t_o_m_o_u_t_h)
(InCar TA_XM_i_c_h_a_e_l_v_i_l_l_e)
(InCar TA_XJ_e_n_n_i_f_e_r_t_o_w_n)
(InCar TA_XN_e_a_l_f_u_r_t)
(InCar TA_XH_a_r_r_i_s_b_o_r_o_u_g_h)
(InCar TA_XA_d_k_i_n_s_b_e_r_g)
(InCar TA_XM_i_l_l_e_r_b_o_r_o_u_g_h)
(InCar TA_XS_h_a_w_n_f_o_r_t)
(InCar TA_XW_a_t_s_o_n_v_i_l_l_e)
(InCar TA_XA_b_i_g_a_i_l_h_a_v_e_n)
(InCar TA_XS_m_i_t_h_f_o_r_t)
(InCar TA_XJ_o_s_e_p_h_s_t_a_d)
(InCar TA_XC_l_a_r_k_b_u_r_y)
(InCar TA_XP_r_i_c_e_v_i_l_l_e)
(InCar TA_XJ_o_n_e_s_c_h_e_s_t_e_r)
(InCar TA_XH_a_l_l_b_o_r_o_u_g_h)
(InCar TA_XT_h_o_m_a_s_b_o_r_o_u_g_h)
(Path XL_o_p_e_z_b_o_r_o_u_g_h XC_o_o_p_e_r_t_o_n )
(Path XC_o_o_p_e_r_t_o_n XL_o_p_e_z_b_o_r_o_u_g_h )
(= (Distance XL_o_p_e_z_b_o_r_o_u_g_h XC_o_o_p_e_r_t_o_n )1849284224.14885)
(= (Distance XC_o_o_p_e_r_t_o_n XL_o_p_e_z_b_o_r_o_u_g_h )1849284224.14885)

(Path XL_o_p_e_z_b_o_r_o_u_g_h XW_a_l_t_e_r_s_m_o_u_t_h )
(Path XW_a_l_t_e_r_s_m_o_u_t_h XL_o_p_e_z_b_o_r_o_u_g_h )
(= (Distance XL_o_p_e_z_b_o_r_o_u_g_h XW_a_l_t_e_r_s_m_o_u_t_h )1109256933.73799)
(= (Distance XW_a_l_t_e_r_s_m_o_u_t_h XL_o_p_e_z_b_o_r_o_u_g_h )1109256933.73799)

(Path XL_o_p_e_z_b_u_r_g_h XT_h_o_m_a_s_v_i_l_l_e )
(Path XT_h_o_m_a_s_v_i_l_l_e XL_o_p_e_z_b_u_r_g_h )
(= (Distance XL_o_p_e_z_b_u_r_g_h XT_h_o_m_a_s_v_i_l_l_e )1946614122.47359)
(= (Distance XT_h_o_m_a_s_v_i_l_l_e XL_o_p_e_z_b_u_r_g_h )1946614122.47359)

(Path XL_o_p_e_z_b_u_r_g_h XL_e_a_h_m_o_u_t_h )
(Path XL_e_a_h_m_o_u_t_h XL_o_p_e_z_b_u_r_g_h )
(= (Distance XL_o_p_e_z_b_u_r_g_h XL_e_a_h_m_o_u_t_h )1757386104.13745)
(= (Distance XL_e_a_h_m_o_u_t_h XL_o_p_e_z_b_u_r_g_h )1757386104.13745)

(Path XL_o_p_e_z_b_u_r_g_h XB_y_r_d_f_u_r_t )
(Path XB_y_r_d_f_u_r_t XL_o_p_e_z_b_u_r_g_h )
(= (Distance XL_o_p_e_z_b_u_r_g_h XB_y_r_d_f_u_r_t )1907127397.27079)
(= (Distance XB_y_r_d_f_u_r_t XL_o_p_e_z_b_u_r_g_h )1907127397.27079)

(Path XL_a_u_r_e_n_b_u_r_y XS_c_o_t_t_b_u_r_g_h )
(Path XS_c_o_t_t_b_u_r_g_h XL_a_u_r_e_n_b_u_r_y )
(= (Distance XL_a_u_r_e_n_b_u_r_y XS_c_o_t_t_b_u_r_g_h )1242356098.43514)
(= (Distance XS_c_o_t_t_b_u_r_g_h XL_a_u_r_e_n_b_u_r_y )1242356098.43514)

(Path XL_a_u_r_e_n_b_u_r_y XH_a_l_e_v_i_e_w )
(Path XH_a_l_e_v_i_e_w XL_a_u_r_e_n_b_u_r_y )
(= (Distance XL_a_u_r_e_n_b_u_r_y XH_a_l_e_v_i_e_w )1196237367.08968)
(= (Distance XH_a_l_e_v_i_e_w XL_a_u_r_e_n_b_u_r_y )1196237367.08968)

(Path XR_o_b_e_r_t_s_s_t_a_d XT_o_d_d_t_o_w_n )
(Path XT_o_d_d_t_o_w_n XR_o_b_e_r_t_s_s_t_a_d )
(= (Distance XR_o_b_e_r_t_s_s_t_a_d XT_o_d_d_t_o_w_n )1076029105.51243)
(= (Distance XT_o_d_d_t_o_w_n XR_o_b_e_r_t_s_s_t_a_d )1076029105.51243)

(Path XR_o_b_e_r_t_s_s_t_a_d XJ_e_s_s_i_c_a_t_o_n )
(Path XJ_e_s_s_i_c_a_t_o_n XR_o_b_e_r_t_s_s_t_a_d )
(= (Distance XR_o_b_e_r_t_s_s_t_a_d XJ_e_s_s_i_c_a_t_o_n )1335778891.37652)
(= (Distance XJ_e_s_s_i_c_a_t_o_n XR_o_b_e_r_t_s_s_t_a_d )1335778891.37652)

(Path XR_o_b_e_r_t_s_s_t_a_d XP_a_u_l_b_u_r_g_h )
(Path XP_a_u_l_b_u_r_g_h XR_o_b_e_r_t_s_s_t_a_d )
(= (Distance XR_o_b_e_r_t_s_s_t_a_d XP_a_u_l_b_u_r_g_h )1638717391.25475)
(= (Distance XP_a_u_l_b_u_r_g_h XR_o_b_e_r_t_s_s_t_a_d )1638717391.25475)

(Path XW_e_b_b_v_i_e_w XT_h_o_m_a_s_v_i_l_l_e )
(Path XT_h_o_m_a_s_v_i_l_l_e XW_e_b_b_v_i_e_w )
(= (Distance XW_e_b_b_v_i_e_w XT_h_o_m_a_s_v_i_l_l_e )1335750902.94171)
(= (Distance XT_h_o_m_a_s_v_i_l_l_e XW_e_b_b_v_i_e_w )1335750902.94171)

(Path XA_b_i_g_a_i_l_h_a_v_e_n XS_w_a_n_s_o_n_s_h_i_r_e )
(Path XS_w_a_n_s_o_n_s_h_i_r_e XA_b_i_g_a_i_l_h_a_v_e_n )
(= (Distance XA_b_i_g_a_i_l_h_a_v_e_n XS_w_a_n_s_o_n_s_h_i_r_e )1531241383.17032)
(= (Distance XS_w_a_n_s_o_n_s_h_i_r_e XA_b_i_g_a_i_l_h_a_v_e_n )1531241383.17032)

(Path XW_i_l_l_i_a_m_s_h_i_r_e XJ_o_h_n_b_e_r_g )
(Path XJ_o_h_n_b_e_r_g XW_i_l_l_i_a_m_s_h_i_r_e )
(= (Distance XW_i_l_l_i_a_m_s_h_i_r_e XJ_o_h_n_b_e_r_g )1756611699.68669)
(= (Distance XJ_o_h_n_b_e_r_g XW_i_l_l_i_a_m_s_h_i_r_e )1756611699.68669)

(Path XB_u_r_t_o_n_v_i_e_w XC_l_a_r_k_b_e_r_g )
(Path XC_l_a_r_k_b_e_r_g XB_u_r_t_o_n_v_i_e_w )
(= (Distance XB_u_r_t_o_n_v_i_e_w XC_l_a_r_k_b_e_r_g )1208617386.45279)
(= (Distance XC_l_a_r_k_b_e_r_g XB_u_r_t_o_n_v_i_e_w )1208617386.45279)

(Path XB_u_r_t_o_n_v_i_e_w XP_h_a_m_h_a_v_e_n )
(Path XP_h_a_m_h_a_v_e_n XB_u_r_t_o_n_v_i_e_w )
(= (Distance XB_u_r_t_o_n_v_i_e_w XP_h_a_m_h_a_v_e_n )1315119378.518)
(= (Distance XP_h_a_m_h_a_v_e_n XB_u_r_t_o_n_v_i_e_w )1315119378.518)

(Path XB_u_r_t_o_n_v_i_e_w XG_o_n_z_a_l_e_s_f_u_r_t )
(Path XG_o_n_z_a_l_e_s_f_u_r_t XB_u_r_t_o_n_v_i_e_w )
(= (Distance XB_u_r_t_o_n_v_i_e_w XG_o_n_z_a_l_e_s_f_u_r_t )1780674192.55617)
(= (Distance XG_o_n_z_a_l_e_s_f_u_r_t XB_u_r_t_o_n_v_i_e_w )1780674192.55617)

(Path XB_u_r_t_o_n_v_i_e_w XM_u_r_p_h_y_s_i_d_e )
(Path XM_u_r_p_h_y_s_i_d_e XB_u_r_t_o_n_v_i_e_w )
(= (Distance XB_u_r_t_o_n_v_i_e_w XM_u_r_p_h_y_s_i_d_e )1387781911.10955)
(= (Distance XM_u_r_p_h_y_s_i_d_e XB_u_r_t_o_n_v_i_e_w )1387781911.10955)

(Path XD_e_r_e_k_m_o_u_t_h XC_h_a_r_l_e_s_b_e_r_g )
(Path XC_h_a_r_l_e_s_b_e_r_g XD_e_r_e_k_m_o_u_t_h )
(= (Distance XD_e_r_e_k_m_o_u_t_h XC_h_a_r_l_e_s_b_e_r_g )1380502320.56875)
(= (Distance XC_h_a_r_l_e_s_b_e_r_g XD_e_r_e_k_m_o_u_t_h )1380502320.56875)

(Path XD_e_r_e_k_m_o_u_t_h XJ_e_f_f_r_e_y_f_o_r_t )
(Path XJ_e_f_f_r_e_y_f_o_r_t XD_e_r_e_k_m_o_u_t_h )
(= (Distance XD_e_r_e_k_m_o_u_t_h XJ_e_f_f_r_e_y_f_o_r_t )1454748473.57731)
(= (Distance XJ_e_f_f_r_e_y_f_o_r_t XD_e_r_e_k_m_o_u_t_h )1454748473.57731)

(Path XD_e_r_e_k_m_o_u_t_h XW_a_l_l_t_o_n )
(Path XW_a_l_l_t_o_n XD_e_r_e_k_m_o_u_t_h )
(= (Distance XD_e_r_e_k_m_o_u_t_h XW_a_l_l_t_o_n )1964786263.83538)
(= (Distance XW_a_l_l_t_o_n XD_e_r_e_k_m_o_u_t_h )1964786263.83538)

(Path XD_e_r_e_k_m_o_u_t_h XG_e_r_a_l_d_s_i_d_e )
(Path XG_e_r_a_l_d_s_i_d_e XD_e_r_e_k_m_o_u_t_h )
(= (Distance XD_e_r_e_k_m_o_u_t_h XG_e_r_a_l_d_s_i_d_e )1153390706.61454)
(= (Distance XG_e_r_a_l_d_s_i_d_e XD_e_r_e_k_m_o_u_t_h )1153390706.61454)

(Path XO_s_b_o_r_n_e_m_o_u_t_h XE_l_l_i_s_s_t_a_d )
(Path XE_l_l_i_s_s_t_a_d XO_s_b_o_r_n_e_m_o_u_t_h )
(= (Distance XO_s_b_o_r_n_e_m_o_u_t_h XE_l_l_i_s_s_t_a_d )1574668500.56513)
(= (Distance XE_l_l_i_s_s_t_a_d XO_s_b_o_r_n_e_m_o_u_t_h )1574668500.56513)

(Path XB_u_r_g_e_s_s_v_i_e_w XB_i_l_l_t_o_n )
(Path XB_i_l_l_t_o_n XB_u_r_g_e_s_s_v_i_e_w )
(= (Distance XB_u_r_g_e_s_s_v_i_e_w XB_i_l_l_t_o_n )1977544469.97479)
(= (Distance XB_i_l_l_t_o_n XB_u_r_g_e_s_s_v_i_e_w )1977544469.97479)

(Path XB_u_r_g_e_s_s_v_i_e_w XD_i_a_n_a_s_h_i_r_e )
(Path XD_i_a_n_a_s_h_i_r_e XB_u_r_g_e_s_s_v_i_e_w )
(= (Distance XB_u_r_g_e_s_s_v_i_e_w XD_i_a_n_a_s_h_i_r_e )1594341238.15548)
(= (Distance XD_i_a_n_a_s_h_i_r_e XB_u_r_g_e_s_s_v_i_e_w )1594341238.15548)

(Path XB_u_r_g_e_s_s_v_i_e_w XM_a_r_c_u_s_b_u_r_g_h )
(Path XM_a_r_c_u_s_b_u_r_g_h XB_u_r_g_e_s_s_v_i_e_w )
(= (Distance XB_u_r_g_e_s_s_v_i_e_w XM_a_r_c_u_s_b_u_r_g_h )1711705693.68034)
(= (Distance XM_a_r_c_u_s_b_u_r_g_h XB_u_r_g_e_s_s_v_i_e_w )1711705693.68034)

(Path XB_u_r_g_e_s_s_v_i_e_w XW_i_l_l_i_a_m_f_o_r_t )
(Path XW_i_l_l_i_a_m_f_o_r_t XB_u_r_g_e_s_s_v_i_e_w )
(= (Distance XB_u_r_g_e_s_s_v_i_e_w XW_i_l_l_i_a_m_f_o_r_t )1059126320.90949)
(= (Distance XW_i_l_l_i_a_m_f_o_r_t XB_u_r_g_e_s_s_v_i_e_w )1059126320.90949)

(Path XB_o_n_d_m_o_u_t_h XP_e_t_t_y_t_o_n )
(Path XP_e_t_t_y_t_o_n XB_o_n_d_m_o_u_t_h )
(= (Distance XB_o_n_d_m_o_u_t_h XP_e_t_t_y_t_o_n )1331746918.57294)
(= (Distance XP_e_t_t_y_t_o_n XB_o_n_d_m_o_u_t_h )1331746918.57294)

(Path XB_o_n_d_m_o_u_t_h XM_e_r_c_e_d_e_s_m_o_u_t_h )
(Path XM_e_r_c_e_d_e_s_m_o_u_t_h XB_o_n_d_m_o_u_t_h )
(= (Distance XB_o_n_d_m_o_u_t_h XM_e_r_c_e_d_e_s_m_o_u_t_h )1719633674.41694)
(= (Distance XM_e_r_c_e_d_e_s_m_o_u_t_h XB_o_n_d_m_o_u_t_h )1719633674.41694)

(Path XB_o_n_d_m_o_u_t_h XT_a_y_l_o_r_t_o_n )
(Path XT_a_y_l_o_r_t_o_n XB_o_n_d_m_o_u_t_h )
(= (Distance XB_o_n_d_m_o_u_t_h XT_a_y_l_o_r_t_o_n )1766350761.46567)
(= (Distance XT_a_y_l_o_r_t_o_n XB_o_n_d_m_o_u_t_h )1766350761.46567)

(Path XT_y_l_e_r_b_u_r_y XP_a_u_l_t_o_w_n )
(Path XP_a_u_l_t_o_w_n XT_y_l_e_r_b_u_r_y )
(= (Distance XT_y_l_e_r_b_u_r_y XP_a_u_l_t_o_w_n )1093731038.15622)
(= (Distance XP_a_u_l_t_o_w_n XT_y_l_e_r_b_u_r_y )1093731038.15622)

(Path XT_y_l_e_r_b_u_r_y XP_a_t_t_e_r_s_o_n_b_e_r_g )
(Path XP_a_t_t_e_r_s_o_n_b_e_r_g XT_y_l_e_r_b_u_r_y )
(= (Distance XT_y_l_e_r_b_u_r_y XP_a_t_t_e_r_s_o_n_b_e_r_g )1053257789.59698)
(= (Distance XP_a_t_t_e_r_s_o_n_b_e_r_g XT_y_l_e_r_b_u_r_y )1053257789.59698)

(Path XT_y_l_e_r_b_u_r_y XM_a_r_c_u_s_b_u_r_g_h )
(Path XM_a_r_c_u_s_b_u_r_g_h XT_y_l_e_r_b_u_r_y )
(= (Distance XT_y_l_e_r_b_u_r_y XM_a_r_c_u_s_b_u_r_g_h )1728504537.28051)
(= (Distance XM_a_r_c_u_s_b_u_r_g_h XT_y_l_e_r_b_u_r_y )1728504537.28051)

(Path XT_y_l_e_r_b_u_r_y XJ_a_m_e_s_t_o_w_n )
(Path XJ_a_m_e_s_t_o_w_n XT_y_l_e_r_b_u_r_y )
(= (Distance XT_y_l_e_r_b_u_r_y XJ_a_m_e_s_t_o_w_n )1947059134.75841)
(= (Distance XJ_a_m_e_s_t_o_w_n XT_y_l_e_r_b_u_r_y )1947059134.75841)

(Path XS_w_a_n_s_o_n_s_h_i_r_e XT_o_d_d_t_o_w_n )
(Path XT_o_d_d_t_o_w_n XS_w_a_n_s_o_n_s_h_i_r_e )
(= (Distance XS_w_a_n_s_o_n_s_h_i_r_e XT_o_d_d_t_o_w_n )1154158187.70556)
(= (Distance XT_o_d_d_t_o_w_n XS_w_a_n_s_o_n_s_h_i_r_e )1154158187.70556)

(Path XS_m_i_t_h_f_o_r_t XG_r_e_g_o_r_y_b_e_r_g )
(Path XG_r_e_g_o_r_y_b_e_r_g XS_m_i_t_h_f_o_r_t )
(= (Distance XS_m_i_t_h_f_o_r_t XG_r_e_g_o_r_y_b_e_r_g )1125781756.24294)
(= (Distance XG_r_e_g_o_r_y_b_e_r_g XS_m_i_t_h_f_o_r_t )1125781756.24294)

(Path XS_m_i_t_h_f_o_r_t XM_i_l_l_e_r_b_o_r_o_u_g_h )
(Path XM_i_l_l_e_r_b_o_r_o_u_g_h XS_m_i_t_h_f_o_r_t )
(= (Distance XS_m_i_t_h_f_o_r_t XM_i_l_l_e_r_b_o_r_o_u_g_h )1813257196.81901)
(= (Distance XM_i_l_l_e_r_b_o_r_o_u_g_h XS_m_i_t_h_f_o_r_t )1813257196.81901)

(Path XK_i_m_b_e_r_l_y_b_u_r_g_h XC_a_n_d_i_c_e_l_a_n_d )
(Path XC_a_n_d_i_c_e_l_a_n_d XK_i_m_b_e_r_l_y_b_u_r_g_h )
(= (Distance XK_i_m_b_e_r_l_y_b_u_r_g_h XC_a_n_d_i_c_e_l_a_n_d )1115967676.69145)
(= (Distance XC_a_n_d_i_c_e_l_a_n_d XK_i_m_b_e_r_l_y_b_u_r_g_h )1115967676.69145)

(Path XK_i_m_b_e_r_l_y_b_u_r_g_h XW_e_b_e_r_b_u_r_y )
(Path XW_e_b_e_r_b_u_r_y XK_i_m_b_e_r_l_y_b_u_r_g_h )
(= (Distance XK_i_m_b_e_r_l_y_b_u_r_g_h XW_e_b_e_r_b_u_r_y )1620985681.193)
(= (Distance XW_e_b_e_r_b_u_r_y XK_i_m_b_e_r_l_y_b_u_r_g_h )1620985681.193)

(Path XT_h_o_m_p_s_o_n_s_h_i_r_e XC_h_e_y_e_n_n_e_f_u_r_t )
(Path XC_h_e_y_e_n_n_e_f_u_r_t XT_h_o_m_p_s_o_n_s_h_i_r_e )
(= (Distance XT_h_o_m_p_s_o_n_s_h_i_r_e XC_h_e_y_e_n_n_e_f_u_r_t )1226756882.66498)
(= (Distance XC_h_e_y_e_n_n_e_f_u_r_t XT_h_o_m_p_s_o_n_s_h_i_r_e )1226756882.66498)

(Path XA_d_a_m_p_o_r_t XW_a_l_t_e_r_s_m_o_u_t_h )
(Path XW_a_l_t_e_r_s_m_o_u_t_h XA_d_a_m_p_o_r_t )
(= (Distance XA_d_a_m_p_o_r_t XW_a_l_t_e_r_s_m_o_u_t_h )1394125189.23024)
(= (Distance XW_a_l_t_e_r_s_m_o_u_t_h XA_d_a_m_p_o_r_t )1394125189.23024)

(Path XJ_o_n_e_s_f_u_r_t XP_e_t_t_y_t_o_n )
(Path XP_e_t_t_y_t_o_n XJ_o_n_e_s_f_u_r_t )
(= (Distance XJ_o_n_e_s_f_u_r_t XP_e_t_t_y_t_o_n )1359592290.35735)
(= (Distance XP_e_t_t_y_t_o_n XJ_o_n_e_s_f_u_r_t )1359592290.35735)

(Path XM_i_n_d_y_v_i_e_w XC_o_d_y_t_o_n )
(Path XC_o_d_y_t_o_n XM_i_n_d_y_v_i_e_w )
(= (Distance XM_i_n_d_y_v_i_e_w XC_o_d_y_t_o_n )1699148729.19663)
(= (Distance XC_o_d_y_t_o_n XM_i_n_d_y_v_i_e_w )1699148729.19663)

(Path XJ_o_s_e_p_o_r_t XG_a_b_r_i_e_l_b_u_r_g_h )
(Path XG_a_b_r_i_e_l_b_u_r_g_h XJ_o_s_e_p_o_r_t )
(= (Distance XJ_o_s_e_p_o_r_t XG_a_b_r_i_e_l_b_u_r_g_h )1630343166.02311)
(= (Distance XG_a_b_r_i_e_l_b_u_r_g_h XJ_o_s_e_p_o_r_t )1630343166.02311)

(Path XJ_o_s_e_p_o_r_t XH_a_l_l_b_o_r_o_u_g_h )
(Path XH_a_l_l_b_o_r_o_u_g_h XJ_o_s_e_p_o_r_t )
(= (Distance XJ_o_s_e_p_o_r_t XH_a_l_l_b_o_r_o_u_g_h )1267894729.09368)
(= (Distance XH_a_l_l_b_o_r_o_u_g_h XJ_o_s_e_p_o_r_t )1267894729.09368)

(Path XJ_o_s_e_p_o_r_t XG_e_r_a_l_d_s_i_d_e )
(Path XG_e_r_a_l_d_s_i_d_e XJ_o_s_e_p_o_r_t )
(= (Distance XJ_o_s_e_p_o_r_t XG_e_r_a_l_d_s_i_d_e )1281767569.04917)
(= (Distance XG_e_r_a_l_d_s_i_d_e XJ_o_s_e_p_o_r_t )1281767569.04917)

(Path XM_o_o_d_y_b_u_r_g_h XG_r_e_g_o_r_y_b_e_r_g )
(Path XG_r_e_g_o_r_y_b_e_r_g XM_o_o_d_y_b_u_r_g_h )
(= (Distance XM_o_o_d_y_b_u_r_g_h XG_r_e_g_o_r_y_b_e_r_g )1093403875.41747)
(= (Distance XG_r_e_g_o_r_y_b_e_r_g XM_o_o_d_y_b_u_r_g_h )1093403875.41747)

(Path XM_o_o_d_y_b_u_r_g_h XH_e_a_t_h_e_r_b_e_r_g )
(Path XH_e_a_t_h_e_r_b_e_r_g XM_o_o_d_y_b_u_r_g_h )
(= (Distance XM_o_o_d_y_b_u_r_g_h XH_e_a_t_h_e_r_b_e_r_g )1475637787.72918)
(= (Distance XH_e_a_t_h_e_r_b_e_r_g XM_o_o_d_y_b_u_r_g_h )1475637787.72918)

(Path XM_o_o_d_y_b_u_r_g_h XW_i_l_l_i_a_m_f_o_r_t )
(Path XW_i_l_l_i_a_m_f_o_r_t XM_o_o_d_y_b_u_r_g_h )
(= (Distance XM_o_o_d_y_b_u_r_g_h XW_i_l_l_i_a_m_f_o_r_t )1034428441.29708)
(= (Distance XW_i_l_l_i_a_m_f_o_r_t XM_o_o_d_y_b_u_r_g_h )1034428441.29708)

(Path XN_e_w_m_a_n_b_u_r_g_h XS_a_m_a_n_t_h_a_s_h_i_r_e )
(Path XS_a_m_a_n_t_h_a_s_h_i_r_e XN_e_w_m_a_n_b_u_r_g_h )
(= (Distance XN_e_w_m_a_n_b_u_r_g_h XS_a_m_a_n_t_h_a_s_h_i_r_e )1918133023.64487)
(= (Distance XS_a_m_a_n_t_h_a_s_h_i_r_e XN_e_w_m_a_n_b_u_r_g_h )1918133023.64487)

(Path XN_e_w_m_a_n_b_u_r_g_h XD_a_v_i_s_s_t_a_d )
(Path XD_a_v_i_s_s_t_a_d XN_e_w_m_a_n_b_u_r_g_h )
(= (Distance XN_e_w_m_a_n_b_u_r_g_h XD_a_v_i_s_s_t_a_d )1246228393.68277)
(= (Distance XD_a_v_i_s_s_t_a_d XN_e_w_m_a_n_b_u_r_g_h )1246228393.68277)

(Path XN_e_w_m_a_n_b_u_r_g_h XG_a_l_l_o_w_a_y_m_o_u_t_h )
(Path XG_a_l_l_o_w_a_y_m_o_u_t_h XN_e_w_m_a_n_b_u_r_g_h )
(= (Distance XN_e_w_m_a_n_b_u_r_g_h XG_a_l_l_o_w_a_y_m_o_u_t_h )1272708253.1419)
(= (Distance XG_a_l_l_o_w_a_y_m_o_u_t_h XN_e_w_m_a_n_b_u_r_g_h )1272708253.1419)

(Path XB_i_l_l_t_o_n XB_a_n_k_s_b_u_r_g_h )
(Path XB_a_n_k_s_b_u_r_g_h XB_i_l_l_t_o_n )
(= (Distance XB_i_l_l_t_o_n XB_a_n_k_s_b_u_r_g_h )1159608861.78773)
(= (Distance XB_a_n_k_s_b_u_r_g_h XB_i_l_l_t_o_n )1159608861.78773)

(Path XB_i_l_l_t_o_n XG_a_b_r_i_e_l_f_o_r_t )
(Path XG_a_b_r_i_e_l_f_o_r_t XB_i_l_l_t_o_n )
(= (Distance XB_i_l_l_t_o_n XG_a_b_r_i_e_l_f_o_r_t )1242311928.03323)
(= (Distance XG_a_b_r_i_e_l_f_o_r_t XB_i_l_l_t_o_n )1242311928.03323)

(Path XB_i_l_l_t_o_n XB_r_o_o_k_e_m_o_u_t_h )
(Path XB_r_o_o_k_e_m_o_u_t_h XB_i_l_l_t_o_n )
(= (Distance XB_i_l_l_t_o_n XB_r_o_o_k_e_m_o_u_t_h )1527518677.81059)
(= (Distance XB_r_o_o_k_e_m_o_u_t_h XB_i_l_l_t_o_n )1527518677.81059)

(Path XL_o_w_e_r_y_b_o_r_o_u_g_h XB_y_r_d_f_u_r_t )
(Path XB_y_r_d_f_u_r_t XL_o_w_e_r_y_b_o_r_o_u_g_h )
(= (Distance XL_o_w_e_r_y_b_o_r_o_u_g_h XB_y_r_d_f_u_r_t )1054311562.2046)
(= (Distance XB_y_r_d_f_u_r_t XL_o_w_e_r_y_b_o_r_o_u_g_h )1054311562.2046)

(Path XS_t_u_a_r_t_s_h_i_r_e XG_a_b_r_i_e_l_f_o_r_t )
(Path XG_a_b_r_i_e_l_f_o_r_t XS_t_u_a_r_t_s_h_i_r_e )
(= (Distance XS_t_u_a_r_t_s_h_i_r_e XG_a_b_r_i_e_l_f_o_r_t )1568205658.10699)
(= (Distance XG_a_b_r_i_e_l_f_o_r_t XS_t_u_a_r_t_s_h_i_r_e )1568205658.10699)

(Path XM_i_c_h_a_e_l_v_i_e_w XJ_u_d_i_t_h_v_i_e_w )
(Path XJ_u_d_i_t_h_v_i_e_w XM_i_c_h_a_e_l_v_i_e_w )
(= (Distance XM_i_c_h_a_e_l_v_i_e_w XJ_u_d_i_t_h_v_i_e_w )1085647958.56213)
(= (Distance XJ_u_d_i_t_h_v_i_e_w XM_i_c_h_a_e_l_v_i_e_w )1085647958.56213)

(Path XM_i_c_h_a_e_l_v_i_e_w XC_l_a_r_e_n_c_e_v_i_e_w )
(Path XC_l_a_r_e_n_c_e_v_i_e_w XM_i_c_h_a_e_l_v_i_e_w )
(= (Distance XM_i_c_h_a_e_l_v_i_e_w XC_l_a_r_e_n_c_e_v_i_e_w )1114740440.18907)
(= (Distance XC_l_a_r_e_n_c_e_v_i_e_w XM_i_c_h_a_e_l_v_i_e_w )1114740440.18907)

(Path XR_e_e_v_e_s_t_o_w_n XC_l_a_r_k_b_e_r_g )
(Path XC_l_a_r_k_b_e_r_g XR_e_e_v_e_s_t_o_w_n )
(= (Distance XR_e_e_v_e_s_t_o_w_n XC_l_a_r_k_b_e_r_g )1177229089.82352)
(= (Distance XC_l_a_r_k_b_e_r_g XR_e_e_v_e_s_t_o_w_n )1177229089.82352)

(Path XR_e_e_v_e_s_t_o_w_n XJ_u_d_i_t_h_v_i_e_w )
(Path XJ_u_d_i_t_h_v_i_e_w XR_e_e_v_e_s_t_o_w_n )
(= (Distance XR_e_e_v_e_s_t_o_w_n XJ_u_d_i_t_h_v_i_e_w )1124587947.49146)
(= (Distance XJ_u_d_i_t_h_v_i_e_w XR_e_e_v_e_s_t_o_w_n )1124587947.49146)

(Path XR_e_e_v_e_s_t_o_w_n XD_a_v_i_d_s_o_n_v_i_e_w )
(Path XD_a_v_i_d_s_o_n_v_i_e_w XR_e_e_v_e_s_t_o_w_n )
(= (Distance XR_e_e_v_e_s_t_o_w_n XD_a_v_i_d_s_o_n_v_i_e_w )1466544547.8795)
(= (Distance XD_a_v_i_d_s_o_n_v_i_e_w XR_e_e_v_e_s_t_o_w_n )1466544547.8795)

(Path XR_e_e_v_e_s_t_o_w_n XC_h_a_n_g_b_u_r_y )
(Path XC_h_a_n_g_b_u_r_y XR_e_e_v_e_s_t_o_w_n )
(= (Distance XR_e_e_v_e_s_t_o_w_n XC_h_a_n_g_b_u_r_y )1841072003.14569)
(= (Distance XC_h_a_n_g_b_u_r_y XR_e_e_v_e_s_t_o_w_n )1841072003.14569)

(Path XD_a_n_i_e_l_l_e_p_o_r_t XC_o_o_p_e_r_t_o_n )
(Path XC_o_o_p_e_r_t_o_n XD_a_n_i_e_l_l_e_p_o_r_t )
(= (Distance XD_a_n_i_e_l_l_e_p_o_r_t XC_o_o_p_e_r_t_o_n )1489616069.22174)
(= (Distance XC_o_o_p_e_r_t_o_n XD_a_n_i_e_l_l_e_p_o_r_t )1489616069.22174)

(Path XD_a_n_i_e_l_l_e_p_o_r_t XM_e_l_i_s_s_a_v_i_e_w )
(Path XM_e_l_i_s_s_a_v_i_e_w XD_a_n_i_e_l_l_e_p_o_r_t )
(= (Distance XD_a_n_i_e_l_l_e_p_o_r_t XM_e_l_i_s_s_a_v_i_e_w )1405894788.34148)
(= (Distance XM_e_l_i_s_s_a_v_i_e_w XD_a_n_i_e_l_l_e_p_o_r_t )1405894788.34148)

(Path XD_a_n_i_e_l_l_e_p_o_r_t XW_a_l_l_t_o_n )
(Path XW_a_l_l_t_o_n XD_a_n_i_e_l_l_e_p_o_r_t )
(= (Distance XD_a_n_i_e_l_l_e_p_o_r_t XW_a_l_l_t_o_n )1649499838.36053)
(= (Distance XW_a_l_l_t_o_n XD_a_n_i_e_l_l_e_p_o_r_t )1649499838.36053)

(Path XD_a_n_i_e_l_l_e_p_o_r_t XS_c_o_t_t_b_u_r_g_h )
(Path XS_c_o_t_t_b_u_r_g_h XD_a_n_i_e_l_l_e_p_o_r_t )
(= (Distance XD_a_n_i_e_l_l_e_p_o_r_t XS_c_o_t_t_b_u_r_g_h )1827191928.96923)
(= (Distance XS_c_o_t_t_b_u_r_g_h XD_a_n_i_e_l_l_e_p_o_r_t )1827191928.96923)

(Path XR_a_m_o_s_b_o_r_o_u_g_h XF_o_r_d_h_a_v_e_n )
(Path XF_o_r_d_h_a_v_e_n XR_a_m_o_s_b_o_r_o_u_g_h )
(= (Distance XR_a_m_o_s_b_o_r_o_u_g_h XF_o_r_d_h_a_v_e_n )1906003891.61588)
(= (Distance XF_o_r_d_h_a_v_e_n XR_a_m_o_s_b_o_r_o_u_g_h )1906003891.61588)

(Path XR_a_m_o_s_b_o_r_o_u_g_h XM_i_c_h_e_l_l_e_h_a_v_e_n )
(Path XM_i_c_h_e_l_l_e_h_a_v_e_n XR_a_m_o_s_b_o_r_o_u_g_h )
(= (Distance XR_a_m_o_s_b_o_r_o_u_g_h XM_i_c_h_e_l_l_e_h_a_v_e_n )1107585072.25418)
(= (Distance XM_i_c_h_e_l_l_e_h_a_v_e_n XR_a_m_o_s_b_o_r_o_u_g_h )1107585072.25418)

(Path XS_h_a_w_n_m_o_u_t_h XB_o_n_d_f_o_r_t )
(Path XB_o_n_d_f_o_r_t XS_h_a_w_n_m_o_u_t_h )
(= (Distance XS_h_a_w_n_m_o_u_t_h XB_o_n_d_f_o_r_t )1106067708.48477)
(= (Distance XB_o_n_d_f_o_r_t XS_h_a_w_n_m_o_u_t_h )1106067708.48477)

(Path XS_h_a_w_n_m_o_u_t_h XP_r_i_c_e_v_i_l_l_e )
(Path XP_r_i_c_e_v_i_l_l_e XS_h_a_w_n_m_o_u_t_h )
(= (Distance XS_h_a_w_n_m_o_u_t_h XP_r_i_c_e_v_i_l_l_e )1991251575.41686)
(= (Distance XP_r_i_c_e_v_i_l_l_e XS_h_a_w_n_m_o_u_t_h )1991251575.41686)

(Path XS_h_a_w_n_m_o_u_t_h XB_u_c_k_l_e_y_s_i_d_e )
(Path XB_u_c_k_l_e_y_s_i_d_e XS_h_a_w_n_m_o_u_t_h )
(= (Distance XS_h_a_w_n_m_o_u_t_h XB_u_c_k_l_e_y_s_i_d_e )1501419432.47244)
(= (Distance XB_u_c_k_l_e_y_s_i_d_e XS_h_a_w_n_m_o_u_t_h )1501419432.47244)

(Path XA_u_d_r_e_y_f_o_r_t XP_a_t_r_i_c_i_a_s_i_d_e )
(Path XP_a_t_r_i_c_i_a_s_i_d_e XA_u_d_r_e_y_f_o_r_t )
(= (Distance XA_u_d_r_e_y_f_o_r_t XP_a_t_r_i_c_i_a_s_i_d_e )1417046767.16759)
(= (Distance XP_a_t_r_i_c_i_a_s_i_d_e XA_u_d_r_e_y_f_o_r_t )1417046767.16759)

(Path XA_u_d_r_e_y_f_o_r_t XG_a_r_y_t_o_w_n )
(Path XG_a_r_y_t_o_w_n XA_u_d_r_e_y_f_o_r_t )
(= (Distance XA_u_d_r_e_y_f_o_r_t XG_a_r_y_t_o_w_n )1883139473.33836)
(= (Distance XG_a_r_y_t_o_w_n XA_u_d_r_e_y_f_o_r_t )1883139473.33836)

(Path XC_a_l_v_i_n_t_o_n XT_e_r_e_s_a_f_o_r_t )
(Path XT_e_r_e_s_a_f_o_r_t XC_a_l_v_i_n_t_o_n )
(= (Distance XC_a_l_v_i_n_t_o_n XT_e_r_e_s_a_f_o_r_t )1666199493.79358)
(= (Distance XT_e_r_e_s_a_f_o_r_t XC_a_l_v_i_n_t_o_n )1666199493.79358)

(Path XC_o_o_p_e_r_t_o_n XK_r_i_s_t_i_e_t_o_w_n )
(Path XK_r_i_s_t_i_e_t_o_w_n XC_o_o_p_e_r_t_o_n )
(= (Distance XC_o_o_p_e_r_t_o_n XK_r_i_s_t_i_e_t_o_w_n )1481431453.61667)
(= (Distance XK_r_i_s_t_i_e_t_o_w_n XC_o_o_p_e_r_t_o_n )1481431453.61667)

(Path XC_o_o_p_e_r_t_o_n XT_h_o_m_a_s_s_i_d_e )
(Path XT_h_o_m_a_s_s_i_d_e XC_o_o_p_e_r_t_o_n )
(= (Distance XC_o_o_p_e_r_t_o_n XT_h_o_m_a_s_s_i_d_e )1349562751.14673)
(= (Distance XT_h_o_m_a_s_s_i_d_e XC_o_o_p_e_r_t_o_n )1349562751.14673)

(Path XK_i_m_b_e_r_l_y_m_o_u_t_h XB_r_o_o_k_e_m_o_u_t_h )
(Path XB_r_o_o_k_e_m_o_u_t_h XK_i_m_b_e_r_l_y_m_o_u_t_h )
(= (Distance XK_i_m_b_e_r_l_y_m_o_u_t_h XB_r_o_o_k_e_m_o_u_t_h )1547229906.14242)
(= (Distance XB_r_o_o_k_e_m_o_u_t_h XK_i_m_b_e_r_l_y_m_o_u_t_h )1547229906.14242)

(Path XO_s_b_o_r_n_e_v_i_l_l_e XP_a_y_n_e_v_i_e_w )
(Path XP_a_y_n_e_v_i_e_w XO_s_b_o_r_n_e_v_i_l_l_e )
(= (Distance XO_s_b_o_r_n_e_v_i_l_l_e XP_a_y_n_e_v_i_e_w )1310771889.39918)
(= (Distance XP_a_y_n_e_v_i_e_w XO_s_b_o_r_n_e_v_i_l_l_e )1310771889.39918)

(Path XO_s_b_o_r_n_e_v_i_l_l_e XA_s_h_l_e_y_b_o_r_o_u_g_h )
(Path XA_s_h_l_e_y_b_o_r_o_u_g_h XO_s_b_o_r_n_e_v_i_l_l_e )
(= (Distance XO_s_b_o_r_n_e_v_i_l_l_e XA_s_h_l_e_y_b_o_r_o_u_g_h )1917734705.12839)
(= (Distance XA_s_h_l_e_y_b_o_r_o_u_g_h XO_s_b_o_r_n_e_v_i_l_l_e )1917734705.12839)

(Path XO_s_b_o_r_n_e_v_i_l_l_e XC_h_r_i_s_t_o_p_h_e_r_m_o_u_t_h )
(Path XC_h_r_i_s_t_o_p_h_e_r_m_o_u_t_h XO_s_b_o_r_n_e_v_i_l_l_e )
(= (Distance XO_s_b_o_r_n_e_v_i_l_l_e XC_h_r_i_s_t_o_p_h_e_r_m_o_u_t_h )1372817571.45124)
(= (Distance XC_h_r_i_s_t_o_p_h_e_r_m_o_u_t_h XO_s_b_o_r_n_e_v_i_l_l_e )1372817571.45124)

(Path XP_a_r_k_e_r_m_o_u_t_h XY_v_o_n_n_e_b_o_r_o_u_g_h )
(Path XY_v_o_n_n_e_b_o_r_o_u_g_h XP_a_r_k_e_r_m_o_u_t_h )
(= (Distance XP_a_r_k_e_r_m_o_u_t_h XY_v_o_n_n_e_b_o_r_o_u_g_h )1024796150.57399)
(= (Distance XY_v_o_n_n_e_b_o_r_o_u_g_h XP_a_r_k_e_r_m_o_u_t_h )1024796150.57399)

(Path XP_a_r_k_e_r_m_o_u_t_h XS_h_a_w_n_f_o_r_t )
(Path XS_h_a_w_n_f_o_r_t XP_a_r_k_e_r_m_o_u_t_h )
(= (Distance XP_a_r_k_e_r_m_o_u_t_h XS_h_a_w_n_f_o_r_t )1288676993.02396)
(= (Distance XS_h_a_w_n_f_o_r_t XP_a_r_k_e_r_m_o_u_t_h )1288676993.02396)

(Path XG_a_b_r_i_e_l_b_u_r_g_h XH_o_d_g_e_s_s_t_a_d )
(Path XH_o_d_g_e_s_s_t_a_d XG_a_b_r_i_e_l_b_u_r_g_h )
(= (Distance XG_a_b_r_i_e_l_b_u_r_g_h XH_o_d_g_e_s_s_t_a_d )1074356034.33033)
(= (Distance XH_o_d_g_e_s_s_t_a_d XG_a_b_r_i_e_l_b_u_r_g_h )1074356034.33033)

(Path XS_m_i_t_h_t_o_w_n XA_b_i_g_a_i_l_v_i_l_l_e )
(Path XA_b_i_g_a_i_l_v_i_l_l_e XS_m_i_t_h_t_o_w_n )
(= (Distance XS_m_i_t_h_t_o_w_n XA_b_i_g_a_i_l_v_i_l_l_e )1150172509.51052)
(= (Distance XA_b_i_g_a_i_l_v_i_l_l_e XS_m_i_t_h_t_o_w_n )1150172509.51052)

(Path XS_m_i_t_h_t_o_w_n XT_e_r_e_s_a_f_o_r_t )
(Path XT_e_r_e_s_a_f_o_r_t XS_m_i_t_h_t_o_w_n )
(= (Distance XS_m_i_t_h_t_o_w_n XT_e_r_e_s_a_f_o_r_t )1267214848.81016)
(= (Distance XT_e_r_e_s_a_f_o_r_t XS_m_i_t_h_t_o_w_n )1267214848.81016)

(Path XS_m_i_t_h_t_o_w_n XJ_a_c_k_s_o_n_l_a_n_d )
(Path XJ_a_c_k_s_o_n_l_a_n_d XS_m_i_t_h_t_o_w_n )
(= (Distance XS_m_i_t_h_t_o_w_n XJ_a_c_k_s_o_n_l_a_n_d )1177923753.48026)
(= (Distance XJ_a_c_k_s_o_n_l_a_n_d XS_m_i_t_h_t_o_w_n )1177923753.48026)

(Path XM_i_c_h_a_e_l_v_i_l_l_e XS_i_m_m_o_n_s_b_u_r_g_h )
(Path XS_i_m_m_o_n_s_b_u_r_g_h XM_i_c_h_a_e_l_v_i_l_l_e )
(= (Distance XM_i_c_h_a_e_l_v_i_l_l_e XS_i_m_m_o_n_s_b_u_r_g_h )1181490963.90389)
(= (Distance XS_i_m_m_o_n_s_b_u_r_g_h XM_i_c_h_a_e_l_v_i_l_l_e )1181490963.90389)

(Path XM_i_c_h_a_e_l_v_i_l_l_e XW_i_l_l_i_a_m_l_a_n_d )
(Path XW_i_l_l_i_a_m_l_a_n_d XM_i_c_h_a_e_l_v_i_l_l_e )
(= (Distance XM_i_c_h_a_e_l_v_i_l_l_e XW_i_l_l_i_a_m_l_a_n_d )1722503793.75646)
(= (Distance XW_i_l_l_i_a_m_l_a_n_d XM_i_c_h_a_e_l_v_i_l_l_e )1722503793.75646)

(Path XK_e_v_i_n_b_e_r_g XC_h_a_r_l_e_s_b_e_r_g )
(Path XC_h_a_r_l_e_s_b_e_r_g XK_e_v_i_n_b_e_r_g )
(= (Distance XK_e_v_i_n_b_e_r_g XC_h_a_r_l_e_s_b_e_r_g )1825519241.75538)
(= (Distance XC_h_a_r_l_e_s_b_e_r_g XK_e_v_i_n_b_e_r_g )1825519241.75538)

(Path XK_e_v_i_n_b_e_r_g XP_a_t_r_i_c_i_a_b_u_r_y )
(Path XP_a_t_r_i_c_i_a_b_u_r_y XK_e_v_i_n_b_e_r_g )
(= (Distance XK_e_v_i_n_b_e_r_g XP_a_t_r_i_c_i_a_b_u_r_y )1519564762.18098)
(= (Distance XP_a_t_r_i_c_i_a_b_u_r_y XK_e_v_i_n_b_e_r_g )1519564762.18098)

(Path XK_e_v_i_n_b_e_r_g XA_d_a_m_s_i_d_e )
(Path XA_d_a_m_s_i_d_e XK_e_v_i_n_b_e_r_g )
(= (Distance XK_e_v_i_n_b_e_r_g XA_d_a_m_s_i_d_e )1907914182.5711)
(= (Distance XA_d_a_m_s_i_d_e XK_e_v_i_n_b_e_r_g )1907914182.5711)

(Path XT_a_n_n_e_r_h_a_v_e_n XS_e_t_h_l_a_n_d )
(Path XS_e_t_h_l_a_n_d XT_a_n_n_e_r_h_a_v_e_n )
(= (Distance XT_a_n_n_e_r_h_a_v_e_n XS_e_t_h_l_a_n_d )1511725768.65451)
(= (Distance XS_e_t_h_l_a_n_d XT_a_n_n_e_r_h_a_v_e_n )1511725768.65451)

(Path XH_a_r_r_i_s_b_o_r_o_u_g_h XA_d_a_m_v_i_e_w )
(Path XA_d_a_m_v_i_e_w XH_a_r_r_i_s_b_o_r_o_u_g_h )
(= (Distance XH_a_r_r_i_s_b_o_r_o_u_g_h XA_d_a_m_v_i_e_w )1405617012.59886)
(= (Distance XA_d_a_m_v_i_e_w XH_a_r_r_i_s_b_o_r_o_u_g_h )1405617012.59886)

(Path XC_h_a_r_l_e_s_b_e_r_g XS_e_t_h_l_a_n_d )
(Path XS_e_t_h_l_a_n_d XC_h_a_r_l_e_s_b_e_r_g )
(= (Distance XC_h_a_r_l_e_s_b_e_r_g XS_e_t_h_l_a_n_d )1320173585.90266)
(= (Distance XS_e_t_h_l_a_n_d XC_h_a_r_l_e_s_b_e_r_g )1320173585.90266)

(Path XC_h_a_r_l_e_s_b_e_r_g XW_e_b_e_r_b_u_r_y )
(Path XW_e_b_e_r_b_u_r_y XC_h_a_r_l_e_s_b_e_r_g )
(= (Distance XC_h_a_r_l_e_s_b_e_r_g XW_e_b_e_r_b_u_r_y )1110385641.68135)
(= (Distance XW_e_b_e_r_b_u_r_y XC_h_a_r_l_e_s_b_e_r_g )1110385641.68135)

(Path XV_i_c_k_i_v_i_l_l_e XH_o_l_t_h_a_v_e_n )
(Path XH_o_l_t_h_a_v_e_n XV_i_c_k_i_v_i_l_l_e )
(= (Distance XV_i_c_k_i_v_i_l_l_e XH_o_l_t_h_a_v_e_n )1100385811.59249)
(= (Distance XH_o_l_t_h_a_v_e_n XV_i_c_k_i_v_i_l_l_e )1100385811.59249)

(Path XC_l_a_r_k_p_o_r_t XW_e_b_e_r_b_u_r_y )
(Path XW_e_b_e_r_b_u_r_y XC_l_a_r_k_p_o_r_t )
(= (Distance XC_l_a_r_k_p_o_r_t XW_e_b_e_r_b_u_r_y )1590273874.03023)
(= (Distance XW_e_b_e_r_b_u_r_y XC_l_a_r_k_p_o_r_t )1590273874.03023)

(Path XB_a_n_k_s_b_u_r_g_h XY_v_o_n_n_e_b_o_r_o_u_g_h )
(Path XY_v_o_n_n_e_b_o_r_o_u_g_h XB_a_n_k_s_b_u_r_g_h )
(= (Distance XB_a_n_k_s_b_u_r_g_h XY_v_o_n_n_e_b_o_r_o_u_g_h )1736090881.44411)
(= (Distance XY_v_o_n_n_e_b_o_r_o_u_g_h XB_a_n_k_s_b_u_r_g_h )1736090881.44411)

(Path XB_a_n_k_s_b_u_r_g_h XS_i_m_m_o_n_s_b_u_r_g_h )
(Path XS_i_m_m_o_n_s_b_u_r_g_h XB_a_n_k_s_b_u_r_g_h )
(= (Distance XB_a_n_k_s_b_u_r_g_h XS_i_m_m_o_n_s_b_u_r_g_h )1417709973.43526)
(= (Distance XS_i_m_m_o_n_s_b_u_r_g_h XB_a_n_k_s_b_u_r_g_h )1417709973.43526)

(Path XB_e_c_k_e_r_t_o_n XC_h_r_i_s_t_o_p_h_e_r_m_o_u_t_h )
(Path XC_h_r_i_s_t_o_p_h_e_r_m_o_u_t_h XB_e_c_k_e_r_t_o_n )
(= (Distance XB_e_c_k_e_r_t_o_n XC_h_r_i_s_t_o_p_h_e_r_m_o_u_t_h )1326336389.62139)
(= (Distance XC_h_r_i_s_t_o_p_h_e_r_m_o_u_t_h XB_e_c_k_e_r_t_o_n )1326336389.62139)

(Path XJ_e_r_m_a_i_n_e_t_o_n XC_l_a_r_k_b_u_r_y )
(Path XC_l_a_r_k_b_u_r_y XJ_e_r_m_a_i_n_e_t_o_n )
(= (Distance XJ_e_r_m_a_i_n_e_t_o_n XC_l_a_r_k_b_u_r_y )1597677219.21471)
(= (Distance XC_l_a_r_k_b_u_r_y XJ_e_r_m_a_i_n_e_t_o_n )1597677219.21471)

(Path XC_o_d_y_t_o_n XA_s_h_l_e_y_s_t_a_d )
(Path XA_s_h_l_e_y_s_t_a_d XC_o_d_y_t_o_n )
(= (Distance XC_o_d_y_t_o_n XA_s_h_l_e_y_s_t_a_d )1801867269.90233)
(= (Distance XA_s_h_l_e_y_s_t_a_d XC_o_d_y_t_o_n )1801867269.90233)

(Path XC_o_d_y_t_o_n XR_y_a_n_s_i_d_e )
(Path XR_y_a_n_s_i_d_e XC_o_d_y_t_o_n )
(= (Distance XC_o_d_y_t_o_n XR_y_a_n_s_i_d_e )1033123135.22217)
(= (Distance XR_y_a_n_s_i_d_e XC_o_d_y_t_o_n )1033123135.22217)

(Path XD_i_a_n_a_s_h_i_r_e XA_s_h_l_e_y_b_o_r_o_u_g_h )
(Path XA_s_h_l_e_y_b_o_r_o_u_g_h XD_i_a_n_a_s_h_i_r_e )
(= (Distance XD_i_a_n_a_s_h_i_r_e XA_s_h_l_e_y_b_o_r_o_u_g_h )1752192642.33098)
(= (Distance XA_s_h_l_e_y_b_o_r_o_u_g_h XD_i_a_n_a_s_h_i_r_e )1752192642.33098)

(Path XD_i_a_n_a_s_h_i_r_e XP_o_r_t_e_r_t_o_n )
(Path XP_o_r_t_e_r_t_o_n XD_i_a_n_a_s_h_i_r_e )
(= (Distance XD_i_a_n_a_s_h_i_r_e XP_o_r_t_e_r_t_o_n )1075649625.66904)
(= (Distance XP_o_r_t_e_r_t_o_n XD_i_a_n_a_s_h_i_r_e )1075649625.66904)

(Path XB_o_n_d_f_o_r_t XA_d_a_m_v_i_e_w )
(Path XA_d_a_m_v_i_e_w XB_o_n_d_f_o_r_t )
(= (Distance XB_o_n_d_f_o_r_t XA_d_a_m_v_i_e_w )1664999073.34082)
(= (Distance XA_d_a_m_v_i_e_w XB_o_n_d_f_o_r_t )1664999073.34082)

(Path XB_o_n_d_f_o_r_t XM_a_t_t_h_e_w_b_u_r_g_h )
(Path XM_a_t_t_h_e_w_b_u_r_g_h XB_o_n_d_f_o_r_t )
(= (Distance XB_o_n_d_f_o_r_t XM_a_t_t_h_e_w_b_u_r_g_h )1314916111.32941)
(= (Distance XM_a_t_t_h_e_w_b_u_r_g_h XB_o_n_d_f_o_r_t )1314916111.32941)

(Path XF_l_e_t_c_h_e_r_l_a_n_d XJ_o_h_n_s_i_d_e )
(Path XJ_o_h_n_s_i_d_e XF_l_e_t_c_h_e_r_l_a_n_d )
(= (Distance XF_l_e_t_c_h_e_r_l_a_n_d XJ_o_h_n_s_i_d_e )1713531827.84804)
(= (Distance XJ_o_h_n_s_i_d_e XF_l_e_t_c_h_e_r_l_a_n_d )1713531827.84804)

(Path XF_l_e_t_c_h_e_r_l_a_n_d XW_i_l_l_i_s_f_u_r_t )
(Path XW_i_l_l_i_s_f_u_r_t XF_l_e_t_c_h_e_r_l_a_n_d )
(= (Distance XF_l_e_t_c_h_e_r_l_a_n_d XW_i_l_l_i_s_f_u_r_t )1177431602.74078)
(= (Distance XW_i_l_l_i_s_f_u_r_t XF_l_e_t_c_h_e_r_l_a_n_d )1177431602.74078)

(Path XF_l_e_t_c_h_e_r_l_a_n_d XK_i_n_g_v_i_e_w )
(Path XK_i_n_g_v_i_e_w XF_l_e_t_c_h_e_r_l_a_n_d )
(= (Distance XF_l_e_t_c_h_e_r_l_a_n_d XK_i_n_g_v_i_e_w )1554815448.73332)
(= (Distance XK_i_n_g_v_i_e_w XF_l_e_t_c_h_e_r_l_a_n_d )1554815448.73332)

(Path XF_l_e_t_c_h_e_r_l_a_n_d XM_a_r_c_u_s_b_u_r_g_h )
(Path XM_a_r_c_u_s_b_u_r_g_h XF_l_e_t_c_h_e_r_l_a_n_d )
(= (Distance XF_l_e_t_c_h_e_r_l_a_n_d XM_a_r_c_u_s_b_u_r_g_h )1808293703.29653)
(= (Distance XM_a_r_c_u_s_b_u_r_g_h XF_l_e_t_c_h_e_r_l_a_n_d )1808293703.29653)

(Path XP_a_y_n_e_v_i_e_w XJ_a_c_k_s_o_n_v_i_l_l_e )
(Path XJ_a_c_k_s_o_n_v_i_l_l_e XP_a_y_n_e_v_i_e_w )
(= (Distance XP_a_y_n_e_v_i_e_w XJ_a_c_k_s_o_n_v_i_l_l_e )1612336072.47455)
(= (Distance XJ_a_c_k_s_o_n_v_i_l_l_e XP_a_y_n_e_v_i_e_w )1612336072.47455)

(Path XP_a_y_n_e_v_i_e_w XB_a_r_n_e_s_m_o_u_t_h )
(Path XB_a_r_n_e_s_m_o_u_t_h XP_a_y_n_e_v_i_e_w )
(= (Distance XP_a_y_n_e_v_i_e_w XB_a_r_n_e_s_m_o_u_t_h )1218356182.30652)
(= (Distance XB_a_r_n_e_s_m_o_u_t_h XP_a_y_n_e_v_i_e_w )1218356182.30652)

(Path XP_a_y_n_e_v_i_e_w XT_e_r_e_s_a_f_o_r_t )
(Path XT_e_r_e_s_a_f_o_r_t XP_a_y_n_e_v_i_e_w )
(= (Distance XP_a_y_n_e_v_i_e_w XT_e_r_e_s_a_f_o_r_t )1722309187.07539)
(= (Distance XT_e_r_e_s_a_f_o_r_t XP_a_y_n_e_v_i_e_w )1722309187.07539)

(Path XS_e_t_h_l_a_n_d XE_l_l_i_s_s_t_a_d )
(Path XE_l_l_i_s_s_t_a_d XS_e_t_h_l_a_n_d )
(= (Distance XS_e_t_h_l_a_n_d XE_l_l_i_s_s_t_a_d )1581362527.90174)
(= (Distance XE_l_l_i_s_s_t_a_d XS_e_t_h_l_a_n_d )1581362527.90174)

(Path XR_o_b_i_n_s_o_n_m_o_u_t_h XH_o_r_n_e_s_i_d_e )
(Path XH_o_r_n_e_s_i_d_e XR_o_b_i_n_s_o_n_m_o_u_t_h )
(= (Distance XR_o_b_i_n_s_o_n_m_o_u_t_h XH_o_r_n_e_s_i_d_e )1965043360.56177)
(= (Distance XH_o_r_n_e_s_i_d_e XR_o_b_i_n_s_o_n_m_o_u_t_h )1965043360.56177)

(Path XR_o_b_i_n_s_o_n_m_o_u_t_h XV_i_r_g_i_n_i_a_s_t_a_d )
(Path XV_i_r_g_i_n_i_a_s_t_a_d XR_o_b_i_n_s_o_n_m_o_u_t_h )
(= (Distance XR_o_b_i_n_s_o_n_m_o_u_t_h XV_i_r_g_i_n_i_a_s_t_a_d )1137370471.05861)
(= (Distance XV_i_r_g_i_n_i_a_s_t_a_d XR_o_b_i_n_s_o_n_m_o_u_t_h )1137370471.05861)

(Path XW_i_l_s_o_n_s_t_a_d XJ_a_m_e_s_t_o_w_n )
(Path XJ_a_m_e_s_t_o_w_n XW_i_l_s_o_n_s_t_a_d )
(= (Distance XW_i_l_s_o_n_s_t_a_d XJ_a_m_e_s_t_o_w_n )1126060761.3299)
(= (Distance XJ_a_m_e_s_t_o_w_n XW_i_l_s_o_n_s_t_a_d )1126060761.3299)

(Path XW_i_l_l_i_a_m_s_c_h_e_s_t_e_r XM_i_r_a_n_d_a_v_i_e_w )
(Path XM_i_r_a_n_d_a_v_i_e_w XW_i_l_l_i_a_m_s_c_h_e_s_t_e_r )
(= (Distance XW_i_l_l_i_a_m_s_c_h_e_s_t_e_r XM_i_r_a_n_d_a_v_i_e_w )1073497302.51971)
(= (Distance XM_i_r_a_n_d_a_v_i_e_w XW_i_l_l_i_a_m_s_c_h_e_s_t_e_r )1073497302.51971)

(Path XW_i_l_l_i_a_m_s_c_h_e_s_t_e_r XK_i_n_g_v_i_e_w )
(Path XK_i_n_g_v_i_e_w XW_i_l_l_i_a_m_s_c_h_e_s_t_e_r )
(= (Distance XW_i_l_l_i_a_m_s_c_h_e_s_t_e_r XK_i_n_g_v_i_e_w )1212018982.76983)
(= (Distance XK_i_n_g_v_i_e_w XW_i_l_l_i_a_m_s_c_h_e_s_t_e_r )1212018982.76983)

(Path XA_n_n_b_e_r_g XD_y_e_r_p_o_r_t )
(Path XD_y_e_r_p_o_r_t XA_n_n_b_e_r_g )
(= (Distance XA_n_n_b_e_r_g XD_y_e_r_p_o_r_t )1620619085.8892)
(= (Distance XD_y_e_r_p_o_r_t XA_n_n_b_e_r_g )1620619085.8892)

(Path XA_n_n_b_e_r_g XC_a_m_p_b_e_l_l_h_a_v_e_n )
(Path XC_a_m_p_b_e_l_l_h_a_v_e_n XA_n_n_b_e_r_g )
(= (Distance XA_n_n_b_e_r_g XC_a_m_p_b_e_l_l_h_a_v_e_n )1743962379.35893)
(= (Distance XC_a_m_p_b_e_l_l_h_a_v_e_n XA_n_n_b_e_r_g )1743962379.35893)

(Path XA_n_n_b_e_r_g XH_o_u_s_t_o_n_c_h_e_s_t_e_r )
(Path XH_o_u_s_t_o_n_c_h_e_s_t_e_r XA_n_n_b_e_r_g )
(= (Distance XA_n_n_b_e_r_g XH_o_u_s_t_o_n_c_h_e_s_t_e_r )1342150532.57883)
(= (Distance XH_o_u_s_t_o_n_c_h_e_s_t_e_r XA_n_n_b_e_r_g )1342150532.57883)

(Path XJ_o_s_e_p_h_s_t_a_d XR_i_o_s_h_a_v_e_n )
(Path XR_i_o_s_h_a_v_e_n XJ_o_s_e_p_h_s_t_a_d )
(= (Distance XJ_o_s_e_p_h_s_t_a_d XR_i_o_s_h_a_v_e_n )1772168928.08152)
(= (Distance XR_i_o_s_h_a_v_e_n XJ_o_s_e_p_h_s_t_a_d )1772168928.08152)

(Path XJ_a_c_k_s_o_n_v_i_e_w XD_a_n_i_e_l_v_i_l_l_e )
(Path XD_a_n_i_e_l_v_i_l_l_e XJ_a_c_k_s_o_n_v_i_e_w )
(= (Distance XJ_a_c_k_s_o_n_v_i_e_w XD_a_n_i_e_l_v_i_l_l_e )1566233135.43327)
(= (Distance XD_a_n_i_e_l_v_i_l_l_e XJ_a_c_k_s_o_n_v_i_e_w )1566233135.43327)

(Path XJ_a_c_k_s_o_n_v_i_e_w XS_c_o_t_t_t_o_w_n )
(Path XS_c_o_t_t_t_o_w_n XJ_a_c_k_s_o_n_v_i_e_w )
(= (Distance XJ_a_c_k_s_o_n_v_i_e_w XS_c_o_t_t_t_o_w_n )1838892120.65705)
(= (Distance XS_c_o_t_t_t_o_w_n XJ_a_c_k_s_o_n_v_i_e_w )1838892120.65705)

(Path XO_r_t_i_z_b_e_r_g XW_i_l_l_i_s_f_u_r_t )
(Path XW_i_l_l_i_s_f_u_r_t XO_r_t_i_z_b_e_r_g )
(= (Distance XO_r_t_i_z_b_e_r_g XW_i_l_l_i_s_f_u_r_t )1354555937.66209)
(= (Distance XW_i_l_l_i_s_f_u_r_t XO_r_t_i_z_b_e_r_g )1354555937.66209)

(Path XK_y_l_i_e_v_i_e_w XH_a_l_l_b_o_r_o_u_g_h )
(Path XH_a_l_l_b_o_r_o_u_g_h XK_y_l_i_e_v_i_e_w )
(= (Distance XK_y_l_i_e_v_i_e_w XH_a_l_l_b_o_r_o_u_g_h )1733774323.09648)
(= (Distance XH_a_l_l_b_o_r_o_u_g_h XK_y_l_i_e_v_i_e_w )1733774323.09648)

(Path XA_s_h_l_e_y_b_o_r_o_u_g_h XC_l_a_r_k_b_e_r_g )
(Path XC_l_a_r_k_b_e_r_g XA_s_h_l_e_y_b_o_r_o_u_g_h )
(= (Distance XA_s_h_l_e_y_b_o_r_o_u_g_h XC_l_a_r_k_b_e_r_g )1557524038.31655)
(= (Distance XC_l_a_r_k_b_e_r_g XA_s_h_l_e_y_b_o_r_o_u_g_h )1557524038.31655)

(Path XA_s_h_l_e_y_b_o_r_o_u_g_h XP_a_u_l_b_u_r_g_h )
(Path XP_a_u_l_b_u_r_g_h XA_s_h_l_e_y_b_o_r_o_u_g_h )
(= (Distance XA_s_h_l_e_y_b_o_r_o_u_g_h XP_a_u_l_b_u_r_g_h )1334634242.88216)
(= (Distance XP_a_u_l_b_u_r_g_h XA_s_h_l_e_y_b_o_r_o_u_g_h )1334634242.88216)

(Path XB_a_i_l_e_y_f_o_r_t XB_r_o_o_k_e_m_o_u_t_h )
(Path XB_r_o_o_k_e_m_o_u_t_h XB_a_i_l_e_y_f_o_r_t )
(= (Distance XB_a_i_l_e_y_f_o_r_t XB_r_o_o_k_e_m_o_u_t_h )1722074346.98398)
(= (Distance XB_r_o_o_k_e_m_o_u_t_h XB_a_i_l_e_y_f_o_r_t )1722074346.98398)

(Path XO_r_t_e_g_a_h_a_v_e_n XS_c_o_t_t_b_u_r_g_h )
(Path XS_c_o_t_t_b_u_r_g_h XO_r_t_e_g_a_h_a_v_e_n )
(= (Distance XO_r_t_e_g_a_h_a_v_e_n XS_c_o_t_t_b_u_r_g_h )1503567443.1982)
(= (Distance XS_c_o_t_t_b_u_r_g_h XO_r_t_e_g_a_h_a_v_e_n )1503567443.1982)

(Path XN_e_a_l_f_u_r_t XJ_o_h_n_s_o_n_c_h_e_s_t_e_r )
(Path XJ_o_h_n_s_o_n_c_h_e_s_t_e_r XN_e_a_l_f_u_r_t )
(= (Distance XN_e_a_l_f_u_r_t XJ_o_h_n_s_o_n_c_h_e_s_t_e_r )1270350086.01883)
(= (Distance XJ_o_h_n_s_o_n_c_h_e_s_t_e_r XN_e_a_l_f_u_r_t )1270350086.01883)

(Path XP_e_t_t_y_t_o_n XL_e_e_c_h_e_s_t_e_r )
(Path XL_e_e_c_h_e_s_t_e_r XP_e_t_t_y_t_o_n )
(= (Distance XP_e_t_t_y_t_o_n XL_e_e_c_h_e_s_t_e_r )1454968764.11953)
(= (Distance XL_e_e_c_h_e_s_t_e_r XP_e_t_t_y_t_o_n )1454968764.11953)

(Path XJ_a_c_k_s_o_n_v_i_l_l_e XJ_e_n_n_i_f_e_r_t_o_w_n )
(Path XJ_e_n_n_i_f_e_r_t_o_w_n XJ_a_c_k_s_o_n_v_i_l_l_e )
(= (Distance XJ_a_c_k_s_o_n_v_i_l_l_e XJ_e_n_n_i_f_e_r_t_o_w_n )1798792378.10838)
(= (Distance XJ_e_n_n_i_f_e_r_t_o_w_n XJ_a_c_k_s_o_n_v_i_l_l_e )1798792378.10838)

(Path XJ_a_c_k_s_o_n_v_i_l_l_e XC_h_r_i_s_t_o_p_h_e_r_h_a_v_e_n )
(Path XC_h_r_i_s_t_o_p_h_e_r_h_a_v_e_n XJ_a_c_k_s_o_n_v_i_l_l_e )
(= (Distance XJ_a_c_k_s_o_n_v_i_l_l_e XC_h_r_i_s_t_o_p_h_e_r_h_a_v_e_n )1576370886.87033)
(= (Distance XC_h_r_i_s_t_o_p_h_e_r_h_a_v_e_n XJ_a_c_k_s_o_n_v_i_l_l_e )1576370886.87033)

(Path XC_a_n_d_a_c_e_b_o_r_o_u_g_h XS_h_a_w_n_h_a_v_e_n )
(Path XS_h_a_w_n_h_a_v_e_n XC_a_n_d_a_c_e_b_o_r_o_u_g_h )
(= (Distance XC_a_n_d_a_c_e_b_o_r_o_u_g_h XS_h_a_w_n_h_a_v_e_n )1617512047.27368)
(= (Distance XS_h_a_w_n_h_a_v_e_n XC_a_n_d_a_c_e_b_o_r_o_u_g_h )1617512047.27368)

(Path XG_a_r_c_i_a_m_o_u_t_h XB_y_r_d_f_u_r_t )
(Path XB_y_r_d_f_u_r_t XG_a_r_c_i_a_m_o_u_t_h )
(= (Distance XG_a_r_c_i_a_m_o_u_t_h XB_y_r_d_f_u_r_t )1001926638.07709)
(= (Distance XB_y_r_d_f_u_r_t XG_a_r_c_i_a_m_o_u_t_h )1001926638.07709)

(Path XT_h_o_m_a_s_v_i_l_l_e XM_a_r_t_i_n_c_h_e_s_t_e_r )
(Path XM_a_r_t_i_n_c_h_e_s_t_e_r XT_h_o_m_a_s_v_i_l_l_e )
(= (Distance XT_h_o_m_a_s_v_i_l_l_e XM_a_r_t_i_n_c_h_e_s_t_e_r )1158306009.02647)
(= (Distance XM_a_r_t_i_n_c_h_e_s_t_e_r XT_h_o_m_a_s_v_i_l_l_e )1158306009.02647)

(Path XT_h_o_m_a_s_v_i_l_l_e XW_i_l_l_i_a_m_f_o_r_t )
(Path XW_i_l_l_i_a_m_f_o_r_t XT_h_o_m_a_s_v_i_l_l_e )
(= (Distance XT_h_o_m_a_s_v_i_l_l_e XW_i_l_l_i_a_m_f_o_r_t )1719868754.16693)
(= (Distance XW_i_l_l_i_a_m_f_o_r_t XT_h_o_m_a_s_v_i_l_l_e )1719868754.16693)

(Path XA_s_h_l_e_y_s_t_a_d XW_i_l_l_i_a_m_p_o_r_t )
(Path XW_i_l_l_i_a_m_p_o_r_t XA_s_h_l_e_y_s_t_a_d )
(= (Distance XA_s_h_l_e_y_s_t_a_d XW_i_l_l_i_a_m_p_o_r_t )1217767625.22225)
(= (Distance XW_i_l_l_i_a_m_p_o_r_t XA_s_h_l_e_y_s_t_a_d )1217767625.22225)

(Path XA_s_h_l_e_y_s_t_a_d XH_o_l_t_h_a_v_e_n )
(Path XH_o_l_t_h_a_v_e_n XA_s_h_l_e_y_s_t_a_d )
(= (Distance XA_s_h_l_e_y_s_t_a_d XH_o_l_t_h_a_v_e_n )1583544582.82388)
(= (Distance XH_o_l_t_h_a_v_e_n XA_s_h_l_e_y_s_t_a_d )1583544582.82388)

(Path XF_e_l_i_c_i_a_v_i_l_l_e XJ_e_n_n_i_f_e_r_t_o_w_n )
(Path XJ_e_n_n_i_f_e_r_t_o_w_n XF_e_l_i_c_i_a_v_i_l_l_e )
(= (Distance XF_e_l_i_c_i_a_v_i_l_l_e XJ_e_n_n_i_f_e_r_t_o_w_n )1101481923.99061)
(= (Distance XJ_e_n_n_i_f_e_r_t_o_w_n XF_e_l_i_c_i_a_v_i_l_l_e )1101481923.99061)

(Path XD_a_n_n_y_s_i_d_e XS_h_a_w_n_h_a_v_e_n )
(Path XS_h_a_w_n_h_a_v_e_n XD_a_n_n_y_s_i_d_e )
(= (Distance XD_a_n_n_y_s_i_d_e XS_h_a_w_n_h_a_v_e_n )1111106547.59533)
(= (Distance XS_h_a_w_n_h_a_v_e_n XD_a_n_n_y_s_i_d_e )1111106547.59533)

(Path XD_e_r_e_k_v_i_l_l_e XB_a_k_e_r_t_o_w_n )
(Path XB_a_k_e_r_t_o_w_n XD_e_r_e_k_v_i_l_l_e )
(= (Distance XD_e_r_e_k_v_i_l_l_e XB_a_k_e_r_t_o_w_n )1725054136.03936)
(= (Distance XB_a_k_e_r_t_o_w_n XD_e_r_e_k_v_i_l_l_e )1725054136.03936)

(Path XC_h_r_i_s_t_y_l_a_n_d XW_a_t_s_o_n_v_i_l_l_e )
(Path XW_a_t_s_o_n_v_i_l_l_e XC_h_r_i_s_t_y_l_a_n_d )
(= (Distance XC_h_r_i_s_t_y_l_a_n_d XW_a_t_s_o_n_v_i_l_l_e )1243188257.37033)
(= (Distance XW_a_t_s_o_n_v_i_l_l_e XC_h_r_i_s_t_y_l_a_n_d )1243188257.37033)

(Path XP_a_u_l_t_o_w_n XH_a_n_s_o_n_b_u_r_y )
(Path XH_a_n_s_o_n_b_u_r_y XP_a_u_l_t_o_w_n )
(= (Distance XP_a_u_l_t_o_w_n XH_a_n_s_o_n_b_u_r_y )1530716765.92693)
(= (Distance XH_a_n_s_o_n_b_u_r_y XP_a_u_l_t_o_w_n )1530716765.92693)

(Path XS_u_s_a_n_f_o_r_t XJ_o_h_n_s_o_n_c_h_e_s_t_e_r )
(Path XJ_o_h_n_s_o_n_c_h_e_s_t_e_r XS_u_s_a_n_f_o_r_t )
(= (Distance XS_u_s_a_n_f_o_r_t XJ_o_h_n_s_o_n_c_h_e_s_t_e_r )1210175851.88282)
(= (Distance XJ_o_h_n_s_o_n_c_h_e_s_t_e_r XS_u_s_a_n_f_o_r_t )1210175851.88282)

(Path XB_r_e_n_d_a_v_i_e_w XH_a_r_r_i_s_p_o_r_t )
(Path XH_a_r_r_i_s_p_o_r_t XB_r_e_n_d_a_v_i_e_w )
(= (Distance XB_r_e_n_d_a_v_i_e_w XH_a_r_r_i_s_p_o_r_t )1353959419.06429)
(= (Distance XH_a_r_r_i_s_p_o_r_t XB_r_e_n_d_a_v_i_e_w )1353959419.06429)

(Path XM_i_c_h_e_l_l_e_h_a_v_e_n XG_e_r_a_l_d_s_i_d_e )
(Path XG_e_r_a_l_d_s_i_d_e XM_i_c_h_e_l_l_e_h_a_v_e_n )
(= (Distance XM_i_c_h_e_l_l_e_h_a_v_e_n XG_e_r_a_l_d_s_i_d_e )1100744295.46319)
(= (Distance XG_e_r_a_l_d_s_i_d_e XM_i_c_h_e_l_l_e_h_a_v_e_n )1100744295.46319)

(Path XM_i_c_h_e_l_l_e_h_a_v_e_n XC_r_a_n_e_m_o_u_t_h )
(Path XC_r_a_n_e_m_o_u_t_h XM_i_c_h_e_l_l_e_h_a_v_e_n )
(= (Distance XM_i_c_h_e_l_l_e_h_a_v_e_n XC_r_a_n_e_m_o_u_t_h )1191259464.90717)
(= (Distance XC_r_a_n_e_m_o_u_t_h XM_i_c_h_e_l_l_e_h_a_v_e_n )1191259464.90717)

(Path XW_a_t_s_o_n_v_i_l_l_e XC_h_e_y_e_n_n_e_f_u_r_t )
(Path XC_h_e_y_e_n_n_e_f_u_r_t XW_a_t_s_o_n_v_i_l_l_e )
(= (Distance XW_a_t_s_o_n_v_i_l_l_e XC_h_e_y_e_n_n_e_f_u_r_t )1640035359.90487)
(= (Distance XC_h_e_y_e_n_n_e_f_u_r_t XW_a_t_s_o_n_v_i_l_l_e )1640035359.90487)

(Path XW_a_t_s_o_n_v_i_l_l_e XR_o_b_e_r_t_o_m_o_u_t_h )
(Path XR_o_b_e_r_t_o_m_o_u_t_h XW_a_t_s_o_n_v_i_l_l_e )
(= (Distance XW_a_t_s_o_n_v_i_l_l_e XR_o_b_e_r_t_o_m_o_u_t_h )1879616191.00436)
(= (Distance XR_o_b_e_r_t_o_m_o_u_t_h XW_a_t_s_o_n_v_i_l_l_e )1879616191.00436)

(Path XH_a_r_r_i_s_p_o_r_t XB_a_r_n_e_s_m_o_u_t_h )
(Path XB_a_r_n_e_s_m_o_u_t_h XH_a_r_r_i_s_p_o_r_t )
(= (Distance XH_a_r_r_i_s_p_o_r_t XB_a_r_n_e_s_m_o_u_t_h )1788041660.92834)
(= (Distance XB_a_r_n_e_s_m_o_u_t_h XH_a_r_r_i_s_p_o_r_t )1788041660.92834)

(Path XC_l_a_r_k_b_u_r_y XS_i_n_g_l_e_t_o_n_t_o_n )
(Path XS_i_n_g_l_e_t_o_n_t_o_n XC_l_a_r_k_b_u_r_y )
(= (Distance XC_l_a_r_k_b_u_r_y XS_i_n_g_l_e_t_o_n_t_o_n )1898432691.16071)
(= (Distance XS_i_n_g_l_e_t_o_n_t_o_n XC_l_a_r_k_b_u_r_y )1898432691.16071)

(Path XS_h_a_w_n_h_a_v_e_n XC_h_r_i_s_t_o_p_h_e_r_m_o_u_t_h )
(Path XC_h_r_i_s_t_o_p_h_e_r_m_o_u_t_h XS_h_a_w_n_h_a_v_e_n )
(= (Distance XS_h_a_w_n_h_a_v_e_n XC_h_r_i_s_t_o_p_h_e_r_m_o_u_t_h )1070072345.95677)
(= (Distance XC_h_r_i_s_t_o_p_h_e_r_m_o_u_t_h XS_h_a_w_n_h_a_v_e_n )1070072345.95677)

(Path XC_a_s_t_a_n_e_d_a_c_h_e_s_t_e_r XL_e_e_c_h_e_s_t_e_r )
(Path XL_e_e_c_h_e_s_t_e_r XC_a_s_t_a_n_e_d_a_c_h_e_s_t_e_r )
(= (Distance XC_a_s_t_a_n_e_d_a_c_h_e_s_t_e_r XL_e_e_c_h_e_s_t_e_r )1075354244.67583)
(= (Distance XL_e_e_c_h_e_s_t_e_r XC_a_s_t_a_n_e_d_a_c_h_e_s_t_e_r )1075354244.67583)

(Path XC_a_s_t_a_n_e_d_a_c_h_e_s_t_e_r XS_u_t_t_o_n_v_i_l_l_e )
(Path XS_u_t_t_o_n_v_i_l_l_e XC_a_s_t_a_n_e_d_a_c_h_e_s_t_e_r )
(= (Distance XC_a_s_t_a_n_e_d_a_c_h_e_s_t_e_r XS_u_t_t_o_n_v_i_l_l_e )1992494819.50166)
(= (Distance XS_u_t_t_o_n_v_i_l_l_e XC_a_s_t_a_n_e_d_a_c_h_e_s_t_e_r )1992494819.50166)

(Path XH_a_l_l_s_t_a_d XH_a_l_e_v_i_e_w )
(Path XH_a_l_e_v_i_e_w XH_a_l_l_s_t_a_d )
(= (Distance XH_a_l_l_s_t_a_d XH_a_l_e_v_i_e_w )1859660401.60797)
(= (Distance XH_a_l_e_v_i_e_w XH_a_l_l_s_t_a_d )1859660401.60797)

(Path XM_e_l_i_s_s_a_v_i_e_w XC_h_e_y_e_n_n_e_f_u_r_t )
(Path XC_h_e_y_e_n_n_e_f_u_r_t XM_e_l_i_s_s_a_v_i_e_w )
(= (Distance XM_e_l_i_s_s_a_v_i_e_w XC_h_e_y_e_n_n_e_f_u_r_t )1765652838.67769)
(= (Distance XC_h_e_y_e_n_n_e_f_u_r_t XM_e_l_i_s_s_a_v_i_e_w )1765652838.67769)

(Path XM_e_l_i_s_s_a_v_i_e_w XC_a_m_p_b_e_l_l_h_a_v_e_n )
(Path XC_a_m_p_b_e_l_l_h_a_v_e_n XM_e_l_i_s_s_a_v_i_e_w )
(= (Distance XM_e_l_i_s_s_a_v_i_e_w XC_a_m_p_b_e_l_l_h_a_v_e_n )1903590179.54614)
(= (Distance XC_a_m_p_b_e_l_l_h_a_v_e_n XM_e_l_i_s_s_a_v_i_e_w )1903590179.54614)

(Path XH_e_a_t_h_e_r_b_e_r_g XT_h_o_m_a_s_b_o_r_o_u_g_h )
(Path XT_h_o_m_a_s_b_o_r_o_u_g_h XH_e_a_t_h_e_r_b_e_r_g )
(= (Distance XH_e_a_t_h_e_r_b_e_r_g XT_h_o_m_a_s_b_o_r_o_u_g_h )1067389445.13406)
(= (Distance XT_h_o_m_a_s_b_o_r_o_u_g_h XH_e_a_t_h_e_r_b_e_r_g )1067389445.13406)

(Path XM_a_s_s_e_y_s_i_d_e XT_h_o_m_a_s_b_o_r_o_u_g_h )
(Path XT_h_o_m_a_s_b_o_r_o_u_g_h XM_a_s_s_e_y_s_i_d_e )
(= (Distance XM_a_s_s_e_y_s_i_d_e XT_h_o_m_a_s_b_o_r_o_u_g_h )1464454995.35818)
(= (Distance XT_h_o_m_a_s_b_o_r_o_u_g_h XM_a_s_s_e_y_s_i_d_e )1464454995.35818)

(Path XA_n_d_r_e_w_s_c_h_e_s_t_e_r XA_d_a_m_s_i_d_e )
(Path XA_d_a_m_s_i_d_e XA_n_d_r_e_w_s_c_h_e_s_t_e_r )
(= (Distance XA_n_d_r_e_w_s_c_h_e_s_t_e_r XA_d_a_m_s_i_d_e )1114962685.59415)
(= (Distance XA_d_a_m_s_i_d_e XA_n_d_r_e_w_s_c_h_e_s_t_e_r )1114962685.59415)

(Path XJ_a_m_e_s_t_o_n XB_a_k_e_r_t_o_w_n )
(Path XB_a_k_e_r_t_o_w_n XJ_a_m_e_s_t_o_n )
(= (Distance XJ_a_m_e_s_t_o_n XB_a_k_e_r_t_o_w_n )1767556993.19226)
(= (Distance XB_a_k_e_r_t_o_w_n XJ_a_m_e_s_t_o_n )1767556993.19226)

(Path XC_o_m_b_s_v_i_l_l_e XM_a_r_y_p_o_r_t )
(Path XM_a_r_y_p_o_r_t XC_o_m_b_s_v_i_l_l_e )
(= (Distance XC_o_m_b_s_v_i_l_l_e XM_a_r_y_p_o_r_t )1029294949.67283)
(= (Distance XM_a_r_y_p_o_r_t XC_o_m_b_s_v_i_l_l_e )1029294949.67283)

(Path XC_h_r_i_s_t_o_p_h_e_r_m_o_u_t_h XD_a_v_i_d_t_o_w_n )
(Path XD_a_v_i_d_t_o_w_n XC_h_r_i_s_t_o_p_h_e_r_m_o_u_t_h )
(= (Distance XC_h_r_i_s_t_o_p_h_e_r_m_o_u_t_h XD_a_v_i_d_t_o_w_n )1714768807.86423)
(= (Distance XD_a_v_i_d_t_o_w_n XC_h_r_i_s_t_o_p_h_e_r_m_o_u_t_h )1714768807.86423)

(Path XR_e_y_n_o_l_d_s_v_i_e_w XM_a_r_y_p_o_r_t )
(Path XM_a_r_y_p_o_r_t XR_e_y_n_o_l_d_s_v_i_e_w )
(= (Distance XR_e_y_n_o_l_d_s_v_i_e_w XM_a_r_y_p_o_r_t )1422490553.20288)
(= (Distance XM_a_r_y_p_o_r_t XR_e_y_n_o_l_d_s_v_i_e_w )1422490553.20288)

(Path XB_a_k_e_r_t_o_w_n XM_u_r_p_h_y_s_i_d_e )
(Path XM_u_r_p_h_y_s_i_d_e XB_a_k_e_r_t_o_w_n )
(= (Distance XB_a_k_e_r_t_o_w_n XM_u_r_p_h_y_s_i_d_e )1461877936.02206)
(= (Distance XM_u_r_p_h_y_s_i_d_e XB_a_k_e_r_t_o_w_n )1461877936.02206)

(Path XJ_e_f_f_r_e_y_f_o_r_t XJ_o_h_n_s_o_n_c_h_e_s_t_e_r )
(Path XJ_o_h_n_s_o_n_c_h_e_s_t_e_r XJ_e_f_f_r_e_y_f_o_r_t )
(= (Distance XJ_e_f_f_r_e_y_f_o_r_t XJ_o_h_n_s_o_n_c_h_e_s_t_e_r )1647171516.17359)
(= (Distance XJ_o_h_n_s_o_n_c_h_e_s_t_e_r XJ_e_f_f_r_e_y_f_o_r_t )1647171516.17359)

(Path XJ_e_f_f_r_e_y_f_o_r_t XG_a_r_y_t_o_w_n )
(Path XG_a_r_y_t_o_w_n XJ_e_f_f_r_e_y_f_o_r_t )
(= (Distance XJ_e_f_f_r_e_y_f_o_r_t XG_a_r_y_t_o_w_n )1182235032.70792)
(= (Distance XG_a_r_y_t_o_w_n XJ_e_f_f_r_e_y_f_o_r_t )1182235032.70792)

(Path XR_i_c_h_t_o_w_n XG_e_r_a_l_d_s_i_d_e )
(Path XG_e_r_a_l_d_s_i_d_e XR_i_c_h_t_o_w_n )
(= (Distance XR_i_c_h_t_o_w_n XG_e_r_a_l_d_s_i_d_e )1064906925.33539)
(= (Distance XG_e_r_a_l_d_s_i_d_e XR_i_c_h_t_o_w_n )1064906925.33539)

(Path XA_d_k_i_n_s_b_e_r_g XW_a_l_t_e_r_s_m_o_u_t_h )
(Path XW_a_l_t_e_r_s_m_o_u_t_h XA_d_k_i_n_s_b_e_r_g )
(= (Distance XA_d_k_i_n_s_b_e_r_g XW_a_l_t_e_r_s_m_o_u_t_h )1932061678.16605)
(= (Distance XW_a_l_t_e_r_s_m_o_u_t_h XA_d_k_i_n_s_b_e_r_g )1932061678.16605)

(Path XE_m_i_l_y_v_i_e_w XJ_a_c_k_s_o_n_t_o_n )
(Path XJ_a_c_k_s_o_n_t_o_n XE_m_i_l_y_v_i_e_w )
(= (Distance XE_m_i_l_y_v_i_e_w XJ_a_c_k_s_o_n_t_o_n )1283211694.13681)
(= (Distance XJ_a_c_k_s_o_n_t_o_n XE_m_i_l_y_v_i_e_w )1283211694.13681)

(Path XJ_o_h_n_s_o_n_b_e_r_g XV_i_r_g_i_n_i_a_s_t_a_d )
(Path XV_i_r_g_i_n_i_a_s_t_a_d XJ_o_h_n_s_o_n_b_e_r_g )
(= (Distance XJ_o_h_n_s_o_n_b_e_r_g XV_i_r_g_i_n_i_a_s_t_a_d )1552201285.05737)
(= (Distance XV_i_r_g_i_n_i_a_s_t_a_d XJ_o_h_n_s_o_n_b_e_r_g )1552201285.05737)

(Path XW_a_l_l_t_o_n XD_a_v_i_s_s_t_a_d )
(Path XD_a_v_i_s_s_t_a_d XW_a_l_l_t_o_n )
(= (Distance XW_a_l_l_t_o_n XD_a_v_i_s_s_t_a_d )1144315154.85996)
(= (Distance XD_a_v_i_s_s_t_a_d XW_a_l_l_t_o_n )1144315154.85996)

(Path XW_a_l_l_t_o_n XP_o_r_t_e_r_t_o_n )
(Path XP_o_r_t_e_r_t_o_n XW_a_l_l_t_o_n )
(= (Distance XW_a_l_l_t_o_n XP_o_r_t_e_r_t_o_n )1743867233.73033)
(= (Distance XP_o_r_t_e_r_t_o_n XW_a_l_l_t_o_n )1743867233.73033)

(Path XS_i_n_g_l_e_t_o_n_t_o_n XJ_a_c_k_s_o_n_t_o_n )
(Path XJ_a_c_k_s_o_n_t_o_n XS_i_n_g_l_e_t_o_n_t_o_n )
(= (Distance XS_i_n_g_l_e_t_o_n_t_o_n XJ_a_c_k_s_o_n_t_o_n )1790989743.41984)
(= (Distance XJ_a_c_k_s_o_n_t_o_n XS_i_n_g_l_e_t_o_n_t_o_n )1790989743.41984)

(Path XB_r_a_d_b_e_r_g XA_d_a_m_s_i_d_e )
(Path XA_d_a_m_s_i_d_e XB_r_a_d_b_e_r_g )
(= (Distance XB_r_a_d_b_e_r_g XA_d_a_m_s_i_d_e )1974964726.55267)
(= (Distance XA_d_a_m_s_i_d_e XB_r_a_d_b_e_r_g )1974964726.55267)

(Path XM_a_r_y_p_o_r_t XC_a_l_l_a_h_a_n_t_o_w_n )
(Path XC_a_l_l_a_h_a_n_t_o_w_n XM_a_r_y_p_o_r_t )
(= (Distance XM_a_r_y_p_o_r_t XC_a_l_l_a_h_a_n_t_o_w_n )1566859926.83022)
(= (Distance XC_a_l_l_a_h_a_n_t_o_w_n XM_a_r_y_p_o_r_t )1566859926.83022)

(Path XT_h_o_m_a_s_b_o_r_o_u_g_h XO_r_t_e_g_a_b_e_r_g )
(Path XO_r_t_e_g_a_b_e_r_g XT_h_o_m_a_s_b_o_r_o_u_g_h )
(= (Distance XT_h_o_m_a_s_b_o_r_o_u_g_h XO_r_t_e_g_a_b_e_r_g )1903570699.77294)
(= (Distance XO_r_t_e_g_a_b_e_r_g XT_h_o_m_a_s_b_o_r_o_u_g_h )1903570699.77294)

(Path XS_c_o_t_t_t_o_w_n XW_a_l_l_t_o_w_n )
(Path XW_a_l_l_t_o_w_n XS_c_o_t_t_t_o_w_n )
(= (Distance XS_c_o_t_t_t_o_w_n XW_a_l_l_t_o_w_n )1923749452.38929)
(= (Distance XW_a_l_l_t_o_w_n XS_c_o_t_t_t_o_w_n )1923749452.38929)

(Path XJ_a_c_k_s_o_n_t_o_n XD_a_v_i_s_s_t_a_d )
(Path XD_a_v_i_s_s_t_a_d XJ_a_c_k_s_o_n_t_o_n )
(= (Distance XJ_a_c_k_s_o_n_t_o_n XD_a_v_i_s_s_t_a_d )1982577127.29183)
(= (Distance XD_a_v_i_s_s_t_a_d XJ_a_c_k_s_o_n_t_o_n )1982577127.29183)

(Path XL_e_e_c_h_e_s_t_e_r XD_a_v_i_s_s_t_a_d )
(Path XD_a_v_i_s_s_t_a_d XL_e_e_c_h_e_s_t_e_r )
(= (Distance XL_e_e_c_h_e_s_t_e_r XD_a_v_i_s_s_t_a_d )1739809316.60044)
(= (Distance XD_a_v_i_s_s_t_a_d XL_e_e_c_h_e_s_t_e_r )1739809316.60044)

(Path XB_a_r_n_e_s_m_o_u_t_h XC_l_a_r_k_b_o_r_o_u_g_h )
(Path XC_l_a_r_k_b_o_r_o_u_g_h XB_a_r_n_e_s_m_o_u_t_h )
(= (Distance XB_a_r_n_e_s_m_o_u_t_h XC_l_a_r_k_b_o_r_o_u_g_h )1360357946.59045)
(= (Distance XC_l_a_r_k_b_o_r_o_u_g_h XB_a_r_n_e_s_m_o_u_t_h )1360357946.59045)

(Path XJ_a_m_e_s_s_h_i_r_e XG_a_b_r_i_e_l_f_o_r_t )
(Path XG_a_b_r_i_e_l_f_o_r_t XJ_a_m_e_s_s_h_i_r_e )
(= (Distance XJ_a_m_e_s_s_h_i_r_e XG_a_b_r_i_e_l_f_o_r_t )1491775273.56136)
(= (Distance XG_a_b_r_i_e_l_f_o_r_t XJ_a_m_e_s_s_h_i_r_e )1491775273.56136)

(Path XV_i_r_g_i_n_i_a_s_t_a_d XM_a_t_t_h_e_w_b_u_r_g_h )
(Path XM_a_t_t_h_e_w_b_u_r_g_h XV_i_r_g_i_n_i_a_s_t_a_d )
(= (Distance XV_i_r_g_i_n_i_a_s_t_a_d XM_a_t_t_h_e_w_b_u_r_g_h )1766096518.0673)
(= (Distance XM_a_t_t_h_e_w_b_u_r_g_h XV_i_r_g_i_n_i_a_s_t_a_d )1766096518.0673)

(Path XW_a_l_l_t_o_w_n XC_a_l_l_a_h_a_n_t_o_w_n )
(Path XC_a_l_l_a_h_a_n_t_o_w_n XW_a_l_l_t_o_w_n )
(= (Distance XW_a_l_l_t_o_w_n XC_a_l_l_a_h_a_n_t_o_w_n )1384315710.20405)
(= (Distance XC_a_l_l_a_h_a_n_t_o_w_n XW_a_l_l_t_o_w_n )1384315710.20405)

(Path XW_a_l_l_t_o_w_n XP_a_u_l_b_u_r_g_h )
(Path XP_a_u_l_b_u_r_g_h XW_a_l_l_t_o_w_n )
(= (Distance XW_a_l_l_t_o_w_n XP_a_u_l_b_u_r_g_h )1394886657.73967)
(= (Distance XP_a_u_l_b_u_r_g_h XW_a_l_l_t_o_w_n )1394886657.73967)

(Path XW_a_l_l_t_o_w_n XJ_o_h_n_b_e_r_g )
(Path XJ_o_h_n_b_e_r_g XW_a_l_l_t_o_w_n )
(= (Distance XW_a_l_l_t_o_w_n XJ_o_h_n_b_e_r_g )1521655998.1305)
(= (Distance XJ_o_h_n_b_e_r_g XW_a_l_l_t_o_w_n )1521655998.1305)

(Path XJ_o_e_b_u_r_y XB_r_o_o_k_e_m_o_u_t_h )
(Path XB_r_o_o_k_e_m_o_u_t_h XJ_o_e_b_u_r_y )
(= (Distance XJ_o_e_b_u_r_y XB_r_o_o_k_e_m_o_u_t_h )1017544518.06462)
(= (Distance XB_r_o_o_k_e_m_o_u_t_h XJ_o_e_b_u_r_y )1017544518.06462)

(Path XW_i_l_l_i_a_m_p_o_r_t XD_e_n_i_s_e_c_h_e_s_t_e_r )
(Path XD_e_n_i_s_e_c_h_e_s_t_e_r XW_i_l_l_i_a_m_p_o_r_t )
(= (Distance XW_i_l_l_i_a_m_p_o_r_t XD_e_n_i_s_e_c_h_e_s_t_e_r )1329916917.23679)
(= (Distance XD_e_n_i_s_e_c_h_e_s_t_e_r XW_i_l_l_i_a_m_p_o_r_t )1329916917.23679)

(Path XW_i_l_l_i_a_m_p_o_r_t XW_i_l_l_i_a_m_f_o_r_t )
(Path XW_i_l_l_i_a_m_f_o_r_t XW_i_l_l_i_a_m_p_o_r_t )
(= (Distance XW_i_l_l_i_a_m_p_o_r_t XW_i_l_l_i_a_m_f_o_r_t )1890914912.78617)
(= (Distance XW_i_l_l_i_a_m_f_o_r_t XW_i_l_l_i_a_m_p_o_r_t )1890914912.78617)

(Path XP_a_t_r_i_c_i_a_b_u_r_y XT_r_o_y_f_o_r_t )
(Path XT_r_o_y_f_o_r_t XP_a_t_r_i_c_i_a_b_u_r_y )
(= (Distance XP_a_t_r_i_c_i_a_b_u_r_y XT_r_o_y_f_o_r_t )1026669641.52038)
(= (Distance XT_r_o_y_f_o_r_t XP_a_t_r_i_c_i_a_b_u_r_y )1026669641.52038)

(Path XP_a_t_r_i_c_i_a_b_u_r_y XT_h_o_m_a_s_m_o_u_t_h )
(Path XT_h_o_m_a_s_m_o_u_t_h XP_a_t_r_i_c_i_a_b_u_r_y )
(= (Distance XP_a_t_r_i_c_i_a_b_u_r_y XT_h_o_m_a_s_m_o_u_t_h )1116748692.33658)
(= (Distance XT_h_o_m_a_s_m_o_u_t_h XP_a_t_r_i_c_i_a_b_u_r_y )1116748692.33658)

(Path XG_a_b_r_i_e_l_f_o_r_t XJ_a_m_i_e_s_i_d_e )
(Path XJ_a_m_i_e_s_i_d_e XG_a_b_r_i_e_l_f_o_r_t )
(= (Distance XG_a_b_r_i_e_l_f_o_r_t XJ_a_m_i_e_s_i_d_e )1617694475.10351)
(= (Distance XJ_a_m_i_e_s_i_d_e XG_a_b_r_i_e_l_f_o_r_t )1617694475.10351)

(Path XJ_o_n_e_s_c_h_e_s_t_e_r XC_r_a_n_e_m_o_u_t_h )
(Path XC_r_a_n_e_m_o_u_t_h XJ_o_n_e_s_c_h_e_s_t_e_r )
(= (Distance XJ_o_n_e_s_c_h_e_s_t_e_r XC_r_a_n_e_m_o_u_t_h )1540800905.83245)
(= (Distance XC_r_a_n_e_m_o_u_t_h XJ_o_n_e_s_c_h_e_s_t_e_r )1540800905.83245)

(Path XM_a_t_t_h_e_w_b_u_r_g_h XM_a_r_c_u_s_b_u_r_g_h )
(Path XM_a_r_c_u_s_b_u_r_g_h XM_a_t_t_h_e_w_b_u_r_g_h )
(= (Distance XM_a_t_t_h_e_w_b_u_r_g_h XM_a_r_c_u_s_b_u_r_g_h )1202371937.44458)
(= (Distance XM_a_r_c_u_s_b_u_r_g_h XM_a_t_t_h_e_w_b_u_r_g_h )1202371937.44458)

(Path XG_a_l_l_o_w_a_y_m_o_u_t_h XR_i_o_s_h_a_v_e_n )
(Path XR_i_o_s_h_a_v_e_n XG_a_l_l_o_w_a_y_m_o_u_t_h )
(= (Distance XG_a_l_l_o_w_a_y_m_o_u_t_h XR_i_o_s_h_a_v_e_n )1034840442.56946)
(= (Distance XR_i_o_s_h_a_v_e_n XG_a_l_l_o_w_a_y_m_o_u_t_h )1034840442.56946)

(EmptyHome XJ_o_h_n_s_o_n_b_e_r_g)
(EmptyHome XA_d_a_m_v_i_e_w)
(EmptyHome XF_e_l_i_c_i_a_v_i_l_l_e)
(EmptyHome XB_u_c_k_l_e_y_s_i_d_e)
(EmptyHome XC_o_m_b_s_v_i_l_l_e)
(EmptyHome XT_h_o_m_p_s_o_n_s_h_i_r_e)
(EmptyHome XM_i_r_a_n_d_a_v_i_e_w)
(EmptyHome XD_e_r_e_k_v_i_l_l_e)
(EmptyHome XW_i_l_s_o_n_s_t_a_d)
(EmptyHome XS_u_s_a_n_f_o_r_t)
(EmptyHome XH_a_l_e_v_i_e_w)
(EmptyHome XH_a_l_l_s_t_a_d)
(EmptyHome XA_d_a_m_p_o_r_t)
(EmptyHome XD_a_n_n_y_s_i_d_e)
(EmptyHome XJ_e_r_m_a_i_n_e_t_o_n)
(EmptyHome XP_a_r_k_e_r_m_o_u_t_h)
(EmptyHome XJ_a_m_e_s_t_o_n)
(EmptyHome XH_a_n_s_o_n_b_u_r_y)
(EmptyHome XK_y_l_i_e_v_i_e_w)
(EmptyHome XB_r_e_n_d_a_v_i_e_w)
(EmptyHome XM_e_r_c_e_d_e_s_m_o_u_t_h)
(EmptyHome XK_i_m_b_e_r_l_y_b_u_r_g_h)
(EmptyHome XL_e_a_h_m_o_u_t_h)
(EmptyHome XC_a_n_d_i_c_e_l_a_n_d)
(EmptyHome XH_o_u_s_t_o_n_c_h_e_s_t_e_r)
(EmptyHome XM_i_c_h_a_e_l_v_i_e_w)
(EmptyHome XD_y_e_r_p_o_r_t)
(EmptyHome XT_r_o_y_f_o_r_t)
(EmptyHome XC_r_a_n_e_m_o_u_t_h)
(EmptyHome XA_u_d_r_e_y_f_o_r_t)
(EmptyHome XR_e_y_n_o_l_d_s_v_i_e_w)
(EmptyHome XE_l_l_i_s_s_t_a_d)
(EmptyHome XB_y_r_d_f_u_r_t)
(EmptyHome XA_n_d_r_e_w_s_c_h_e_s_t_e_r)
(EmptyHome XT_a_n_n_e_r_h_a_v_e_n)
(EmptyHome XC_h_r_i_s_t_y_l_a_n_d)
(EmptyHome XP_a_t_r_i_c_i_a_s_i_d_e)
(EmptyHome XG_a_r_c_i_a_m_o_u_t_h)
(EmptyHome XR_o_b_i_n_s_o_n_m_o_u_t_h)
(EmptyHome XA_d_a_m_s_i_d_e)
(EmptyHome XB_a_k_e_r_t_o_w_n)
(EmptyHome XW_i_l_l_i_a_m_l_a_n_d)
(EmptyHome XP_a_t_r_i_c_i_a_b_u_r_y)
(EmptyHome XH_o_r_n_e_s_i_d_e)
(EmptyHome XJ_a_c_k_s_o_n_l_a_n_d)
(EmptyHome XL_o_w_e_r_y_b_o_r_o_u_g_h)
(EmptyHome XB_r_a_d_b_e_r_g)
(EmptyHome XC_h_r_i_s_t_o_p_h_e_r_h_a_v_e_n)
(EmptyHome XH_a_r_r_i_s_p_o_r_t)
(EmptyHome XR_i_o_s_h_a_v_e_n)
(EmptyHome XJ_o_n_e_s_f_u_r_t)
(EmptyHome XT_a_y_l_o_r_t_o_n)
(EmptyHome XW_i_l_l_i_a_m_s_c_h_e_s_t_e_r)
(EmptyHome XC_a_n_d_a_c_e_b_o_r_o_u_g_h)
(EmptyHome XH_o_d_g_e_s_s_t_a_d)
(EmptyHome XG_a_b_r_i_e_l_b_u_r_g_h)
(EmptyHome XC_l_a_r_k_p_o_r_t)
(EmptyHome XB_o_n_d_m_o_u_t_h)
(EmptyHome XF_o_r_d_h_a_v_e_n)
(EmptyHome XC_l_a_r_k_b_o_r_o_u_g_h)
(EmptyHome XH_o_l_t_h_a_v_e_n)
(EmptyHome XO_s_b_o_r_n_e_m_o_u_t_h)
(EmptyHome XO_r_t_e_g_a_b_e_r_g)
(EmptyHome XD_a_n_i_e_l_v_i_l_l_e)
(EmptyHome XS_h_a_w_n_m_o_u_t_h)
(EmptyHome XR_y_a_n_s_i_d_e)
(EmptyHome XS_m_i_t_h_t_o_w_n)
(EmptyHome XJ_a_c_k_s_o_n_v_i_e_w)
(EmptyHome XR_a_m_o_s_b_o_r_o_u_g_h)
(EmptyHome XS_w_a_n_s_o_n_s_h_i_r_e)
(EmptyHome XT_h_o_m_a_s_m_o_u_t_h)
(EmptyHome XS_u_t_t_o_n_v_i_l_l_e)
(EmptyHome XA_n_n_b_e_r_g)
(EmptyHome XM_a_r_y_p_o_r_t)
(EmptyHome XO_r_t_i_z_b_e_r_g)
(EmptyHome XC_a_l_v_i_n_t_o_n)
(EmptyHome XW_i_l_l_i_a_m_s_h_i_r_e)
(EmptyHome XC_o_d_y_t_o_n)
(EmptyHome XV_i_c_k_i_v_i_l_l_e)
(EmptyHome XM_i_n_d_y_v_i_e_w)
(EmptyHome XA_b_i_g_a_i_l_v_i_l_l_e)
(EmptyHome XC_l_a_r_e_n_c_e_v_i_e_w)
(EmptyHome XM_a_s_s_e_y_s_i_d_e)
(EmptyHome XR_o_b_e_r_t_o_m_o_u_t_h)
(EmptyHome XM_i_c_h_a_e_l_v_i_l_l_e)
(EmptyHome XJ_e_n_n_i_f_e_r_t_o_w_n)
(EmptyHome XN_e_a_l_f_u_r_t)
(EmptyHome XH_a_r_r_i_s_b_o_r_o_u_g_h)
(EmptyHome XA_d_k_i_n_s_b_e_r_g)
(EmptyHome XM_i_l_l_e_r_b_o_r_o_u_g_h)
(EmptyHome XS_h_a_w_n_f_o_r_t)
(EmptyHome XW_a_t_s_o_n_v_i_l_l_e)
(EmptyHome XA_b_i_g_a_i_l_h_a_v_e_n)
(EmptyHome XS_m_i_t_h_f_o_r_t)
(EmptyHome XJ_o_s_e_p_h_s_t_a_d)
(EmptyHome XC_l_a_r_k_b_u_r_y)
(EmptyHome XP_r_i_c_e_v_i_l_l_e)
(EmptyHome XJ_o_n_e_s_c_h_e_s_t_e_r)
(EmptyHome XH_a_l_l_b_o_r_o_u_g_h)
(EmptyHome XT_h_o_m_a_s_b_o_r_o_u_g_h)
)

  ; The goal state describe what we desire to achieve
  (:goal (and
( Car_At XP_o_r_t_e_r_t_o_n )
(not (EmptyHome XJ_o_h_n_s_o_n_b_e_r_g))
(not (EmptyHome XA_d_a_m_v_i_e_w))
(not (EmptyHome XF_e_l_i_c_i_a_v_i_l_l_e))
(not (EmptyHome XB_u_c_k_l_e_y_s_i_d_e))
(not (EmptyHome XC_o_m_b_s_v_i_l_l_e))
(not (EmptyHome XT_h_o_m_p_s_o_n_s_h_i_r_e))
(not (EmptyHome XM_i_r_a_n_d_a_v_i_e_w))
(not (EmptyHome XD_e_r_e_k_v_i_l_l_e))
(not (EmptyHome XW_i_l_s_o_n_s_t_a_d))
(not (EmptyHome XS_u_s_a_n_f_o_r_t))
(not (EmptyHome XH_a_l_e_v_i_e_w))
(not (EmptyHome XH_a_l_l_s_t_a_d))
(not (EmptyHome XA_d_a_m_p_o_r_t))
(not (EmptyHome XD_a_n_n_y_s_i_d_e))
(not (EmptyHome XJ_e_r_m_a_i_n_e_t_o_n))
(not (EmptyHome XP_a_r_k_e_r_m_o_u_t_h))
(not (EmptyHome XJ_a_m_e_s_t_o_n))
(not (EmptyHome XH_a_n_s_o_n_b_u_r_y))
(not (EmptyHome XK_y_l_i_e_v_i_e_w))
(not (EmptyHome XB_r_e_n_d_a_v_i_e_w))
(not (EmptyHome XM_e_r_c_e_d_e_s_m_o_u_t_h))
(not (EmptyHome XK_i_m_b_e_r_l_y_b_u_r_g_h))
(not (EmptyHome XL_e_a_h_m_o_u_t_h))
(not (EmptyHome XC_a_n_d_i_c_e_l_a_n_d))
(not (EmptyHome XH_o_u_s_t_o_n_c_h_e_s_t_e_r))
(not (EmptyHome XM_i_c_h_a_e_l_v_i_e_w))
(not (EmptyHome XD_y_e_r_p_o_r_t))
(not (EmptyHome XT_r_o_y_f_o_r_t))
(not (EmptyHome XC_r_a_n_e_m_o_u_t_h))
(not (EmptyHome XA_u_d_r_e_y_f_o_r_t))
(not (EmptyHome XR_e_y_n_o_l_d_s_v_i_e_w))
(not (EmptyHome XE_l_l_i_s_s_t_a_d))
(not (EmptyHome XB_y_r_d_f_u_r_t))
(not (EmptyHome XA_n_d_r_e_w_s_c_h_e_s_t_e_r))
(not (EmptyHome XT_a_n_n_e_r_h_a_v_e_n))
(not (EmptyHome XC_h_r_i_s_t_y_l_a_n_d))
(not (EmptyHome XP_a_t_r_i_c_i_a_s_i_d_e))
(not (EmptyHome XG_a_r_c_i_a_m_o_u_t_h))
(not (EmptyHome XR_o_b_i_n_s_o_n_m_o_u_t_h))
(not (EmptyHome XA_d_a_m_s_i_d_e))
(not (EmptyHome XB_a_k_e_r_t_o_w_n))
(not (EmptyHome XW_i_l_l_i_a_m_l_a_n_d))
(not (EmptyHome XP_a_t_r_i_c_i_a_b_u_r_y))
(not (EmptyHome XH_o_r_n_e_s_i_d_e))
(not (EmptyHome XJ_a_c_k_s_o_n_l_a_n_d))
(not (EmptyHome XL_o_w_e_r_y_b_o_r_o_u_g_h))
(not (EmptyHome XB_r_a_d_b_e_r_g))
(not (EmptyHome XC_h_r_i_s_t_o_p_h_e_r_h_a_v_e_n))
(not (EmptyHome XH_a_r_r_i_s_p_o_r_t))
(not (EmptyHome XR_i_o_s_h_a_v_e_n))
(not (EmptyHome XJ_o_n_e_s_f_u_r_t))
(not (EmptyHome XT_a_y_l_o_r_t_o_n))
(not (EmptyHome XW_i_l_l_i_a_m_s_c_h_e_s_t_e_r))
(not (EmptyHome XC_a_n_d_a_c_e_b_o_r_o_u_g_h))
(not (EmptyHome XH_o_d_g_e_s_s_t_a_d))
(not (EmptyHome XG_a_b_r_i_e_l_b_u_r_g_h))
(not (EmptyHome XC_l_a_r_k_p_o_r_t))
(not (EmptyHome XB_o_n_d_m_o_u_t_h))
(not (EmptyHome XF_o_r_d_h_a_v_e_n))
(not (EmptyHome XC_l_a_r_k_b_o_r_o_u_g_h))
(not (EmptyHome XH_o_l_t_h_a_v_e_n))
(not (EmptyHome XO_s_b_o_r_n_e_m_o_u_t_h))
(not (EmptyHome XO_r_t_e_g_a_b_e_r_g))
(not (EmptyHome XD_a_n_i_e_l_v_i_l_l_e))
(not (EmptyHome XS_h_a_w_n_m_o_u_t_h))
(not (EmptyHome XR_y_a_n_s_i_d_e))
(not (EmptyHome XS_m_i_t_h_t_o_w_n))
(not (EmptyHome XJ_a_c_k_s_o_n_v_i_e_w))
(not (EmptyHome XR_a_m_o_s_b_o_r_o_u_g_h))
(not (EmptyHome XS_w_a_n_s_o_n_s_h_i_r_e))
(not (EmptyHome XT_h_o_m_a_s_m_o_u_t_h))
(not (EmptyHome XS_u_t_t_o_n_v_i_l_l_e))
(not (EmptyHome XA_n_n_b_e_r_g))
(not (EmptyHome XM_a_r_y_p_o_r_t))
(not (EmptyHome XO_r_t_i_z_b_e_r_g))
(not (EmptyHome XC_a_l_v_i_n_t_o_n))
(not (EmptyHome XW_i_l_l_i_a_m_s_h_i_r_e))
(not (EmptyHome XC_o_d_y_t_o_n))
(not (EmptyHome XV_i_c_k_i_v_i_l_l_e))
(not (EmptyHome XM_i_n_d_y_v_i_e_w))
(not (EmptyHome XA_b_i_g_a_i_l_v_i_l_l_e))
(not (EmptyHome XC_l_a_r_e_n_c_e_v_i_e_w))
(not (EmptyHome XM_a_s_s_e_y_s_i_d_e))
(not (EmptyHome XR_o_b_e_r_t_o_m_o_u_t_h))
(not (EmptyHome XM_i_c_h_a_e_l_v_i_l_l_e))
(not (EmptyHome XJ_e_n_n_i_f_e_r_t_o_w_n))
(not (EmptyHome XN_e_a_l_f_u_r_t))
(not (EmptyHome XH_a_r_r_i_s_b_o_r_o_u_g_h))
(not (EmptyHome XA_d_k_i_n_s_b_e_r_g))
(not (EmptyHome XM_i_l_l_e_r_b_o_r_o_u_g_h))
(not (EmptyHome XS_h_a_w_n_f_o_r_t))
(not (EmptyHome XW_a_t_s_o_n_v_i_l_l_e))
(not (EmptyHome XA_b_i_g_a_i_l_h_a_v_e_n))
(not (EmptyHome XS_m_i_t_h_f_o_r_t))
(not (EmptyHome XJ_o_s_e_p_h_s_t_a_d))
(not (EmptyHome XC_l_a_r_k_b_u_r_y))
(not (EmptyHome XP_r_i_c_e_v_i_l_l_e))
(not (EmptyHome XJ_o_n_e_s_c_h_e_s_t_e_r))
(not (EmptyHome XH_a_l_l_b_o_r_o_u_g_h))
(not (EmptyHome XT_h_o_m_a_s_b_o_r_o_u_g_h))
  ))
)