; Problem description
; This file describes the example input from the problem statement
(define (problem pb1)
  (:metric minimize (total-cost))
  (:domain CS170)
(:objects TA_XA TA_XB TA_XD TA_XF TA_XG TA_XH TA_XI TA_XK TA_XM TA_XO TA_XP TA_XS TA_XT TA_XV TA_XX TA_XY TA_XAD TA_XAG TA_XAJ TA_XAM TA_XAO TA_XAQ TA_XAS TA_XAV TA_XAX TA_XBA TA_XBF TA_XBG TA_XBI TA_XBJ TA_XBN TA_XCA TA_XCB TA_XCC TA_XCK TA_XCN TA_XCO TA_XCP TA_XCS TA_XCT XA XB XC XD XE XF XG XH XI XJ XK XL XM XN XO XP XQ XR XS XT XU XV XW XX XY XZ XAA XAB XAC XAD XAE XAF XAG XAH XAI XAJ XAK XAL XAM XAN XAO XAP XAQ XAR XAS XAT XAU XAV XAW XAX XAY XAZ XBA XBB XBC XBD XBE XBF XBG XBH XBI XBJ XBK XBL XBM XBN XBO XBP XBQ XBR XBS XBT XBU XBV XBW XBX XBY XBZ XCA XCB XCC XCD XCE XCF XCG XCH XCI XCJ XCK XCL XCM XCN XCO XCP XCQ XCR XCS XCT XCU XCV )
(:init(= (total-cost) 0)
( Car_At XAY )
(InCar TA_XA)
(InCar TA_XB)
(InCar TA_XD)
(InCar TA_XF)
(InCar TA_XG)
(InCar TA_XH)
(InCar TA_XI)
(InCar TA_XK)
(InCar TA_XM)
(InCar TA_XO)
(InCar TA_XP)
(InCar TA_XS)
(InCar TA_XT)
(InCar TA_XV)
(InCar TA_XX)
(InCar TA_XY)
(InCar TA_XAD)
(InCar TA_XAG)
(InCar TA_XAJ)
(InCar TA_XAM)
(InCar TA_XAO)
(InCar TA_XAQ)
(InCar TA_XAS)
(InCar TA_XAV)
(InCar TA_XAX)
(InCar TA_XBA)
(InCar TA_XBF)
(InCar TA_XBG)
(InCar TA_XBI)
(InCar TA_XBJ)
(InCar TA_XBN)
(InCar TA_XCA)
(InCar TA_XCB)
(InCar TA_XCC)
(InCar TA_XCK)
(InCar TA_XCN)
(InCar TA_XCO)
(InCar TA_XCP)
(InCar TA_XCS)
(InCar TA_XCT)
(Path XA XB )
(Path XB XA )
(= (Distance XA XB )5)
(= (Distance XB XA )5)

(Path XB XE )
(Path XE XB )
(= (Distance XB XE )1)
(= (Distance XE XB )1)

(Path XB XX )
(Path XX XB )
(= (Distance XB XX )6)
(= (Distance XX XB )6)

(Path XC XE )
(Path XE XC )
(= (Distance XC XE )7)
(= (Distance XE XC )7)

(Path XD XE )
(Path XE XD )
(= (Distance XD XE )6)
(= (Distance XE XD )6)

(Path XD XF )
(Path XF XD )
(= (Distance XD XF )3)
(= (Distance XF XD )3)

(Path XD XX )
(Path XX XD )
(= (Distance XD XX )5)
(= (Distance XX XD )5)

(Path XD XAC )
(Path XAC XD )
(= (Distance XD XAC )4)
(= (Distance XAC XD )4)

(Path XF XG )
(Path XG XF )
(= (Distance XF XG )1)
(= (Distance XG XF )1)

(Path XF XI )
(Path XI XF )
(= (Distance XF XI )3)
(= (Distance XI XF )3)

(Path XF XN )
(Path XN XF )
(= (Distance XF XN )1)
(= (Distance XN XF )1)

(Path XH XJ )
(Path XJ XH )
(= (Distance XH XJ )11)
(= (Distance XJ XH )11)

(Path XH XN )
(Path XN XH )
(= (Distance XH XN )2)
(= (Distance XN XH )2)

(Path XH XAE )
(Path XAE XH )
(= (Distance XH XAE )7)
(= (Distance XAE XH )7)

(Path XJ XL )
(Path XL XJ )
(= (Distance XJ XL )1)
(= (Distance XL XJ )1)

(Path XJ XO )
(Path XO XJ )
(= (Distance XJ XO )8)
(= (Distance XO XJ )8)

(Path XK XN )
(Path XN XK )
(= (Distance XK XN )7)
(= (Distance XN XK )7)

(Path XL XAH )
(Path XAH XL )
(= (Distance XL XAH )5)
(= (Distance XAH XL )5)

(Path XM XN )
(Path XN XM )
(= (Distance XM XN )5)
(= (Distance XN XM )5)

(Path XO XP )
(Path XP XO )
(= (Distance XO XP )4)
(= (Distance XP XO )4)

(Path XP XR )
(Path XR XP )
(= (Distance XP XR )1)
(= (Distance XR XP )1)

(Path XQ XR )
(Path XR XQ )
(= (Distance XQ XR )9)
(= (Distance XR XQ )9)

(Path XQ XAJ )
(Path XAJ XQ )
(= (Distance XQ XAJ )2)
(= (Distance XAJ XQ )2)

(Path XR XT )
(Path XT XR )
(= (Distance XR XT )5)
(= (Distance XT XR )5)

(Path XS XAI )
(Path XAI XS )
(= (Distance XS XAI )1)
(= (Distance XAI XS )1)

(Path XS XAL )
(Path XAL XS )
(= (Distance XS XAL )5)
(= (Distance XAL XS )5)

(Path XT XAN )
(Path XAN XT )
(= (Distance XT XAN )6)
(= (Distance XAN XT )6)

(Path XT XBH )
(Path XBH XT )
(= (Distance XT XBH )7)
(= (Distance XBH XT )7)

(Path XU XV )
(Path XV XU )
(= (Distance XU XV )7)
(= (Distance XV XU )7)

(Path XV XAP )
(Path XAP XV )
(= (Distance XV XAP )11)
(= (Distance XAP XV )11)

(Path XW XX )
(Path XX XW )
(= (Distance XW XX )9)
(= (Distance XX XW )9)

(Path XW XAP )
(Path XAP XW )
(= (Distance XW XAP )6)
(= (Distance XAP XW )6)

(Path XY XAC )
(Path XAC XY )
(= (Distance XY XAC )3)
(= (Distance XAC XY )3)

(Path XY XAE )
(Path XAE XY )
(= (Distance XY XAE )3)
(= (Distance XAE XY )3)

(Path XZ XAA )
(Path XAA XZ )
(= (Distance XZ XAA )3)
(= (Distance XAA XZ )3)

(Path XZ XAS )
(Path XAS XZ )
(= (Distance XZ XAS )5)
(= (Distance XAS XZ )5)

(Path XAB XAD )
(Path XAD XAB )
(= (Distance XAB XAD )5)
(= (Distance XAD XAB )5)

(Path XAB XAU )
(Path XAU XAB )
(= (Distance XAB XAU )6)
(= (Distance XAU XAB )6)

(Path XAD XAE )
(Path XAE XAD )
(= (Distance XAD XAE )7)
(= (Distance XAE XAD )7)

(Path XAD XAX )
(Path XAX XAD )
(= (Distance XAD XAX )5)
(= (Distance XAX XAD )5)

(Path XAF XAH )
(Path XAH XAF )
(= (Distance XAF XAH )3)
(= (Distance XAH XAF )3)

(Path XAF XAZ )
(Path XAZ XAF )
(= (Distance XAF XAZ )8)
(= (Distance XAZ XAF )8)

(Path XAG XAK )
(Path XAK XAG )
(= (Distance XAG XAK )2)
(= (Distance XAK XAG )2)

(Path XAG XAZ )
(Path XAZ XAG )
(= (Distance XAG XAZ )3)
(= (Distance XAZ XAG )3)

(Path XAG XBC )
(Path XBC XAG )
(= (Distance XAG XBC )4)
(= (Distance XBC XAG )4)

(Path XAH XAJ )
(Path XAJ XAH )
(= (Distance XAH XAJ )1)
(= (Distance XAJ XAH )1)

(Path XAI XBD )
(Path XBD XAI )
(= (Distance XAI XBD )7)
(= (Distance XBD XAI )7)

(Path XAI XBF )
(Path XBF XAI )
(= (Distance XAI XBF )7)
(= (Distance XBF XAI )7)

(Path XAI XBY )
(Path XBY XAI )
(= (Distance XAI XBY )6)
(= (Distance XBY XAI )6)

(Path XAJ XAK )
(Path XAK XAJ )
(= (Distance XAJ XAK )1)
(= (Distance XAK XAJ )1)

(Path XAL XAN )
(Path XAN XAL )
(= (Distance XAL XAN )7)
(= (Distance XAN XAL )7)

(Path XAM XBE )
(Path XBE XAM )
(= (Distance XAM XBE )3)
(= (Distance XBE XAM )3)

(Path XAM XBF )
(Path XBF XAM )
(= (Distance XAM XBF )7)
(= (Distance XBF XAM )7)

(Path XAN XBY )
(Path XBY XAN )
(= (Distance XAN XBY )1)
(= (Distance XBY XAN )1)

(Path XAO XAQ )
(Path XAQ XAO )
(= (Distance XAO XAQ )6)
(= (Distance XAQ XAO )6)

(Path XAP XAQ )
(Path XAQ XAP )
(= (Distance XAP XAQ )2)
(= (Distance XAQ XAP )2)

(Path XAP XAS )
(Path XAS XAP )
(= (Distance XAP XAS )3)
(= (Distance XAS XAP )3)

(Path XAQ XBL )
(Path XBL XAQ )
(= (Distance XAQ XBL )4)
(= (Distance XBL XAQ )4)

(Path XAR XAU )
(Path XAU XAR )
(= (Distance XAR XAU )8)
(= (Distance XAU XAR )8)

(Path XAR XBL )
(Path XBL XAR )
(= (Distance XAR XBL )7)
(= (Distance XBL XAR )7)

(Path XAS XAU )
(Path XAU XAS )
(= (Distance XAS XAU )5)
(= (Distance XAU XAS )5)

(Path XAT XBM )
(Path XBM XAT )
(= (Distance XAT XBM )3)
(= (Distance XBM XAT )3)

(Path XAU XAW )
(Path XAW XAU )
(= (Distance XAU XAW )1)
(= (Distance XAW XAU )1)

(Path XAV XAW )
(Path XAW XAV )
(= (Distance XAV XAW )1)
(= (Distance XAW XAV )1)

(Path XAV XBM )
(Path XBM XAV )
(= (Distance XAV XBM )1)
(= (Distance XBM XAV )1)

(Path XAW XAY )
(Path XAY XAW )
(= (Distance XAW XAY )5)
(= (Distance XAY XAW )5)

(Path XAX XAY )
(Path XAY XAX )
(= (Distance XAX XAY )6)
(= (Distance XAY XAX )6)

(Path XAY XAZ )
(Path XAZ XAY )
(= (Distance XAY XAZ )1)
(= (Distance XAZ XAY )1)

(Path XBA XBD )
(Path XBD XBA )
(= (Distance XBA XBD )1)
(= (Distance XBD XBA )1)

(Path XBA XBT )
(Path XBT XBA )
(= (Distance XBA XBT )6)
(= (Distance XBT XBA )6)

(Path XBB XBC )
(Path XBC XBB )
(= (Distance XBB XBC )3)
(= (Distance XBC XBB )3)

(Path XBC XBD )
(Path XBD XBC )
(= (Distance XBC XBD )7)
(= (Distance XBD XBC )7)

(Path XBD XBW )
(Path XBW XBD )
(= (Distance XBD XBW )7)
(= (Distance XBW XBD )7)

(Path XBE XBX )
(Path XBX XBE )
(= (Distance XBE XBX )1)
(= (Distance XBX XBE )1)

(Path XBE XBZ )
(Path XBZ XBE )
(= (Distance XBE XBZ )9)
(= (Distance XBZ XBE )9)

(Path XBE XCT )
(Path XCT XBE )
(= (Distance XBE XCT )3)
(= (Distance XCT XBE )3)

(Path XBF XBG )
(Path XBG XBF )
(= (Distance XBF XBG )1)
(= (Distance XBG XBF )1)

(Path XBG XBY )
(Path XBY XBG )
(= (Distance XBG XBY )3)
(= (Distance XBY XBG )3)

(Path XBG XCA )
(Path XCA XBG )
(= (Distance XBG XCA )1)
(= (Distance XCA XBG )1)

(Path XBG XCB )
(Path XCB XBG )
(= (Distance XBG XCB )7)
(= (Distance XCB XBG )7)

(Path XBG XCU )
(Path XCU XBG )
(= (Distance XBG XCU )6)
(= (Distance XCU XBG )6)

(Path XBH XBY )
(Path XBY XBH )
(= (Distance XBH XBY )3)
(= (Distance XBY XBH )3)

(Path XBI XBJ )
(Path XBJ XBI )
(= (Distance XBI XBJ )1)
(= (Distance XBJ XBI )1)

(Path XBI XCC )
(Path XCC XBI )
(= (Distance XBI XCC )5)
(= (Distance XCC XBI )5)

(Path XBJ XBK )
(Path XBK XBJ )
(= (Distance XBJ XBK )1)
(= (Distance XBK XBJ )1)

(Path XBJ XCD )
(Path XCD XBJ )
(= (Distance XBJ XCD )3)
(= (Distance XCD XBJ )3)

(Path XBK XBL )
(Path XBL XBK )
(= (Distance XBK XBL )1)
(= (Distance XBL XBK )1)

(Path XBK XBN )
(Path XBN XBK )
(= (Distance XBK XBN )3)
(= (Distance XBN XBK )3)

(Path XBK XCE )
(Path XCE XBK )
(= (Distance XBK XCE )7)
(= (Distance XCE XBK )7)

(Path XBM XBS )
(Path XBS XBM )
(= (Distance XBM XBS )8)
(= (Distance XBS XBM )8)

(Path XBN XBO )
(Path XBO XBN )
(= (Distance XBN XBO )8)
(= (Distance XBO XBN )8)

(Path XBO XBP )
(Path XBP XBO )
(= (Distance XBO XBP )1)
(= (Distance XBP XBO )1)

(Path XBP XCI )
(Path XCI XBP )
(= (Distance XBP XCI )7)
(= (Distance XCI XBP )7)

(Path XBQ XBS )
(Path XBS XBQ )
(= (Distance XBQ XBS )1)
(= (Distance XBS XBQ )1)

(Path XBQ XCK )
(Path XCK XBQ )
(= (Distance XBQ XCK )8)
(= (Distance XCK XBQ )8)

(Path XBR XBT )
(Path XBT XBR )
(= (Distance XBR XBT )6)
(= (Distance XBT XBR )6)

(Path XBS XBV )
(Path XBV XBS )
(= (Distance XBS XBV )3)
(= (Distance XBV XBS )3)

(Path XBS XCL )
(Path XCL XBS )
(= (Distance XBS XCL )3)
(= (Distance XCL XBS )3)

(Path XBU XBV )
(Path XBV XBU )
(= (Distance XBU XBV )7)
(= (Distance XBV XBU )7)

(Path XBU XCL )
(Path XCL XBU )
(= (Distance XBU XCL )1)
(= (Distance XCL XBU )1)

(Path XBW XBX )
(Path XBX XBW )
(= (Distance XBW XBX )3)
(= (Distance XBX XBW )3)

(Path XBZ XCS )
(Path XCS XBZ )
(= (Distance XBZ XCS )3)
(= (Distance XCS XBZ )3)

(Path XBZ XCV )
(Path XCV XBZ )
(= (Distance XBZ XCV )6)
(= (Distance XCV XBZ )6)

(Path XCC XCD )
(Path XCD XCC )
(= (Distance XCC XCD )1)
(= (Distance XCD XCC )1)

(Path XCD XCF )
(Path XCF XCD )
(= (Distance XCD XCF )1)
(= (Distance XCF XCD )1)

(Path XCE XCG )
(Path XCG XCE )
(= (Distance XCE XCG )5)
(= (Distance XCG XCE )5)

(Path XCF XCG )
(Path XCG XCF )
(= (Distance XCF XCG )5)
(= (Distance XCG XCF )5)

(Path XCH XCJ )
(Path XCJ XCH )
(= (Distance XCH XCJ )5)
(= (Distance XCJ XCH )5)

(Path XCI XCK )
(Path XCK XCI )
(= (Distance XCI XCK )6)
(= (Distance XCK XCI )6)

(Path XCJ XCK )
(Path XCK XCJ )
(= (Distance XCJ XCK )1)
(= (Distance XCK XCJ )1)

(Path XCJ XCN )
(Path XCN XCJ )
(= (Distance XCJ XCN )3)
(= (Distance XCN XCJ )3)

(Path XCL XCN )
(Path XCN XCL )
(= (Distance XCL XCN )2)
(= (Distance XCN XCL )2)

(Path XCM XCN )
(Path XCN XCM )
(= (Distance XCM XCN )6)
(= (Distance XCN XCM )6)

(Path XCM XCO )
(Path XCO XCM )
(= (Distance XCM XCO )7)
(= (Distance XCO XCM )7)

(Path XCN XCQ )
(Path XCQ XCN )
(= (Distance XCN XCQ )7)
(= (Distance XCQ XCN )7)

(Path XCP XCQ )
(Path XCQ XCP )
(= (Distance XCP XCQ )2)
(= (Distance XCQ XCP )2)

(Path XCP XCS )
(Path XCS XCP )
(= (Distance XCP XCS )1)
(= (Distance XCS XCP )1)

(Path XCQ XCS )
(Path XCS XCQ )
(= (Distance XCQ XCS )3)
(= (Distance XCS XCQ )3)

(Path XCR XCS )
(Path XCS XCR )
(= (Distance XCR XCS )4)
(= (Distance XCS XCR )4)

(Path XCT XCV )
(Path XCV XCT )
(= (Distance XCT XCV )9)
(= (Distance XCV XCT )9)

(EmptyHome XA)
(EmptyHome XB)
(EmptyHome XD)
(EmptyHome XF)
(EmptyHome XG)
(EmptyHome XH)
(EmptyHome XI)
(EmptyHome XK)
(EmptyHome XM)
(EmptyHome XO)
(EmptyHome XP)
(EmptyHome XS)
(EmptyHome XT)
(EmptyHome XV)
(EmptyHome XX)
(EmptyHome XY)
(EmptyHome XAD)
(EmptyHome XAG)
(EmptyHome XAJ)
(EmptyHome XAM)
(EmptyHome XAO)
(EmptyHome XAQ)
(EmptyHome XAS)
(EmptyHome XAV)
(EmptyHome XAX)
(EmptyHome XBA)
(EmptyHome XBF)
(EmptyHome XBG)
(EmptyHome XBI)
(EmptyHome XBJ)
(EmptyHome XBN)
(EmptyHome XCA)
(EmptyHome XCB)
(EmptyHome XCC)
(EmptyHome XCK)
(EmptyHome XCN)
(EmptyHome XCO)
(EmptyHome XCP)
(EmptyHome XCS)
(EmptyHome XCT)
)

  ; The goal state describe what we desire to achieve
  (:goal (and
( Car_At XAY )
(not (EmptyHome XA))
(not (EmptyHome XB))
(not (EmptyHome XD))
(not (EmptyHome XF))
(not (EmptyHome XG))
(not (EmptyHome XH))
(not (EmptyHome XI))
(not (EmptyHome XK))
(not (EmptyHome XM))
(not (EmptyHome XO))
(not (EmptyHome XP))
(not (EmptyHome XS))
(not (EmptyHome XT))
(not (EmptyHome XV))
(not (EmptyHome XX))
(not (EmptyHome XY))
(not (EmptyHome XAD))
(not (EmptyHome XAG))
(not (EmptyHome XAJ))
(not (EmptyHome XAM))
(not (EmptyHome XAO))
(not (EmptyHome XAQ))
(not (EmptyHome XAS))
(not (EmptyHome XAV))
(not (EmptyHome XAX))
(not (EmptyHome XBA))
(not (EmptyHome XBF))
(not (EmptyHome XBG))
(not (EmptyHome XBI))
(not (EmptyHome XBJ))
(not (EmptyHome XBN))
(not (EmptyHome XCA))
(not (EmptyHome XCB))
(not (EmptyHome XCC))
(not (EmptyHome XCK))
(not (EmptyHome XCN))
(not (EmptyHome XCO))
(not (EmptyHome XCP))
(not (EmptyHome XCS))
(not (EmptyHome XCT))
  ))
)