; Problem description
; This file describes the example input from the problem statement
(define (problem pb1)
  (:metric minimize (total-cost))
  (:domain CS170)
(:objects TA_X_s_t_o_p3 TA_X_s_t_o_p10 TA_X_s_t_o_p4 TA_X_s_t_o_p6 TA_X_s_t_o_p0 TA_X_s_t_o_p1 TA_X_s_t_o_p5 X_s_t_o_p0 X_s_t_o_p1 X_s_t_o_p2 X_s_t_o_p3 X_s_t_o_p4 X_s_t_o_p10 X_s_t_o_p6 X_s_t_o_p5 X_l_o_c_a_t_i_o_n0 X_l_o_c_a_t_i_o_n1 X_l_o_c_a_t_i_o_n2 X_l_o_c_a_t_i_o_n3 )
(:init(= (total-cost) 0)
( Car_At X_s_t_o_p0 )
(InCar TA_X_s_t_o_p3)
(InCar TA_X_s_t_o_p10)
(InCar TA_X_s_t_o_p4)
(InCar TA_X_s_t_o_p6)
(InCar TA_X_s_t_o_p0)
(InCar TA_X_s_t_o_p1)
(InCar TA_X_s_t_o_p5)
(Path X_s_t_o_p0 X_s_t_o_p1 )
(Path X_s_t_o_p1 X_s_t_o_p0 )
(= (Distance X_s_t_o_p0 X_s_t_o_p1 )1)
(= (Distance X_s_t_o_p1 X_s_t_o_p0 )1)

(Path X_s_t_o_p0 X_s_t_o_p2 )
(Path X_s_t_o_p2 X_s_t_o_p0 )
(= (Distance X_s_t_o_p0 X_s_t_o_p2 )1)
(= (Distance X_s_t_o_p2 X_s_t_o_p0 )1)

(Path X_s_t_o_p0 X_s_t_o_p3 )
(Path X_s_t_o_p3 X_s_t_o_p0 )
(= (Distance X_s_t_o_p0 X_s_t_o_p3 )1)
(= (Distance X_s_t_o_p3 X_s_t_o_p0 )1)

(Path X_s_t_o_p0 X_s_t_o_p4 )
(Path X_s_t_o_p4 X_s_t_o_p0 )
(= (Distance X_s_t_o_p0 X_s_t_o_p4 )1)
(= (Distance X_s_t_o_p4 X_s_t_o_p0 )1)

(Path X_s_t_o_p0 X_s_t_o_p6 )
(Path X_s_t_o_p6 X_s_t_o_p0 )
(= (Distance X_s_t_o_p0 X_s_t_o_p6 )1)
(= (Distance X_s_t_o_p6 X_s_t_o_p0 )1)

(Path X_s_t_o_p0 X_s_t_o_p5 )
(Path X_s_t_o_p5 X_s_t_o_p0 )
(= (Distance X_s_t_o_p0 X_s_t_o_p5 )1)
(= (Distance X_s_t_o_p5 X_s_t_o_p0 )1)

(Path X_s_t_o_p0 X_l_o_c_a_t_i_o_n1 )
(Path X_l_o_c_a_t_i_o_n1 X_s_t_o_p0 )
(= (Distance X_s_t_o_p0 X_l_o_c_a_t_i_o_n1 )1)
(= (Distance X_l_o_c_a_t_i_o_n1 X_s_t_o_p0 )1)

(Path X_s_t_o_p0 X_l_o_c_a_t_i_o_n2 )
(Path X_l_o_c_a_t_i_o_n2 X_s_t_o_p0 )
(= (Distance X_s_t_o_p0 X_l_o_c_a_t_i_o_n2 )1)
(= (Distance X_l_o_c_a_t_i_o_n2 X_s_t_o_p0 )1)

(Path X_s_t_o_p1 X_s_t_o_p2 )
(Path X_s_t_o_p2 X_s_t_o_p1 )
(= (Distance X_s_t_o_p1 X_s_t_o_p2 )1)
(= (Distance X_s_t_o_p2 X_s_t_o_p1 )1)

(Path X_s_t_o_p1 X_s_t_o_p10 )
(Path X_s_t_o_p10 X_s_t_o_p1 )
(= (Distance X_s_t_o_p1 X_s_t_o_p10 )1)
(= (Distance X_s_t_o_p10 X_s_t_o_p1 )1)

(Path X_s_t_o_p1 X_s_t_o_p6 )
(Path X_s_t_o_p6 X_s_t_o_p1 )
(= (Distance X_s_t_o_p1 X_s_t_o_p6 )1)
(= (Distance X_s_t_o_p6 X_s_t_o_p1 )1)

(Path X_s_t_o_p1 X_s_t_o_p5 )
(Path X_s_t_o_p5 X_s_t_o_p1 )
(= (Distance X_s_t_o_p1 X_s_t_o_p5 )1)
(= (Distance X_s_t_o_p5 X_s_t_o_p1 )1)

(Path X_s_t_o_p1 X_l_o_c_a_t_i_o_n2 )
(Path X_l_o_c_a_t_i_o_n2 X_s_t_o_p1 )
(= (Distance X_s_t_o_p1 X_l_o_c_a_t_i_o_n2 )1)
(= (Distance X_l_o_c_a_t_i_o_n2 X_s_t_o_p1 )1)

(Path X_s_t_o_p2 X_s_t_o_p3 )
(Path X_s_t_o_p3 X_s_t_o_p2 )
(= (Distance X_s_t_o_p2 X_s_t_o_p3 )1)
(= (Distance X_s_t_o_p3 X_s_t_o_p2 )1)

(Path X_s_t_o_p3 X_s_t_o_p4 )
(Path X_s_t_o_p4 X_s_t_o_p3 )
(= (Distance X_s_t_o_p3 X_s_t_o_p4 )1)
(= (Distance X_s_t_o_p4 X_s_t_o_p3 )1)

(Path X_s_t_o_p3 X_s_t_o_p10 )
(Path X_s_t_o_p10 X_s_t_o_p3 )
(= (Distance X_s_t_o_p3 X_s_t_o_p10 )1)
(= (Distance X_s_t_o_p10 X_s_t_o_p3 )1)

(Path X_s_t_o_p3 X_l_o_c_a_t_i_o_n0 )
(Path X_l_o_c_a_t_i_o_n0 X_s_t_o_p3 )
(= (Distance X_s_t_o_p3 X_l_o_c_a_t_i_o_n0 )1)
(= (Distance X_l_o_c_a_t_i_o_n0 X_s_t_o_p3 )1)

(Path X_s_t_o_p3 X_l_o_c_a_t_i_o_n1 )
(Path X_l_o_c_a_t_i_o_n1 X_s_t_o_p3 )
(= (Distance X_s_t_o_p3 X_l_o_c_a_t_i_o_n1 )1)
(= (Distance X_l_o_c_a_t_i_o_n1 X_s_t_o_p3 )1)

(Path X_s_t_o_p3 X_l_o_c_a_t_i_o_n3 )
(Path X_l_o_c_a_t_i_o_n3 X_s_t_o_p3 )
(= (Distance X_s_t_o_p3 X_l_o_c_a_t_i_o_n3 )1)
(= (Distance X_l_o_c_a_t_i_o_n3 X_s_t_o_p3 )1)

(Path X_s_t_o_p4 X_s_t_o_p10 )
(Path X_s_t_o_p10 X_s_t_o_p4 )
(= (Distance X_s_t_o_p4 X_s_t_o_p10 )1)
(= (Distance X_s_t_o_p10 X_s_t_o_p4 )1)

(Path X_s_t_o_p4 X_s_t_o_p6 )
(Path X_s_t_o_p6 X_s_t_o_p4 )
(= (Distance X_s_t_o_p4 X_s_t_o_p6 )1)
(= (Distance X_s_t_o_p6 X_s_t_o_p4 )1)

(Path X_s_t_o_p4 X_s_t_o_p5 )
(Path X_s_t_o_p5 X_s_t_o_p4 )
(= (Distance X_s_t_o_p4 X_s_t_o_p5 )1)
(= (Distance X_s_t_o_p5 X_s_t_o_p4 )1)

(Path X_s_t_o_p4 X_l_o_c_a_t_i_o_n1 )
(Path X_l_o_c_a_t_i_o_n1 X_s_t_o_p4 )
(= (Distance X_s_t_o_p4 X_l_o_c_a_t_i_o_n1 )1)
(= (Distance X_l_o_c_a_t_i_o_n1 X_s_t_o_p4 )1)

(Path X_s_t_o_p4 X_l_o_c_a_t_i_o_n2 )
(Path X_l_o_c_a_t_i_o_n2 X_s_t_o_p4 )
(= (Distance X_s_t_o_p4 X_l_o_c_a_t_i_o_n2 )1)
(= (Distance X_l_o_c_a_t_i_o_n2 X_s_t_o_p4 )1)

(Path X_s_t_o_p10 X_s_t_o_p6 )
(Path X_s_t_o_p6 X_s_t_o_p10 )
(= (Distance X_s_t_o_p10 X_s_t_o_p6 )1)
(= (Distance X_s_t_o_p6 X_s_t_o_p10 )1)

(Path X_s_t_o_p10 X_s_t_o_p5 )
(Path X_s_t_o_p5 X_s_t_o_p10 )
(= (Distance X_s_t_o_p10 X_s_t_o_p5 )1)
(= (Distance X_s_t_o_p5 X_s_t_o_p10 )1)

(Path X_s_t_o_p10 X_l_o_c_a_t_i_o_n0 )
(Path X_l_o_c_a_t_i_o_n0 X_s_t_o_p10 )
(= (Distance X_s_t_o_p10 X_l_o_c_a_t_i_o_n0 )1)
(= (Distance X_l_o_c_a_t_i_o_n0 X_s_t_o_p10 )1)

(Path X_s_t_o_p10 X_l_o_c_a_t_i_o_n3 )
(Path X_l_o_c_a_t_i_o_n3 X_s_t_o_p10 )
(= (Distance X_s_t_o_p10 X_l_o_c_a_t_i_o_n3 )1)
(= (Distance X_l_o_c_a_t_i_o_n3 X_s_t_o_p10 )1)

(Path X_s_t_o_p5 X_l_o_c_a_t_i_o_n0 )
(Path X_l_o_c_a_t_i_o_n0 X_s_t_o_p5 )
(= (Distance X_s_t_o_p5 X_l_o_c_a_t_i_o_n0 )1)
(= (Distance X_l_o_c_a_t_i_o_n0 X_s_t_o_p5 )1)

(Path X_s_t_o_p5 X_l_o_c_a_t_i_o_n2 )
(Path X_l_o_c_a_t_i_o_n2 X_s_t_o_p5 )
(= (Distance X_s_t_o_p5 X_l_o_c_a_t_i_o_n2 )1)
(= (Distance X_l_o_c_a_t_i_o_n2 X_s_t_o_p5 )1)

(Path X_l_o_c_a_t_i_o_n0 X_l_o_c_a_t_i_o_n1 )
(Path X_l_o_c_a_t_i_o_n1 X_l_o_c_a_t_i_o_n0 )
(= (Distance X_l_o_c_a_t_i_o_n0 X_l_o_c_a_t_i_o_n1 )1)
(= (Distance X_l_o_c_a_t_i_o_n1 X_l_o_c_a_t_i_o_n0 )1)

(Path X_l_o_c_a_t_i_o_n1 X_l_o_c_a_t_i_o_n3 )
(Path X_l_o_c_a_t_i_o_n3 X_l_o_c_a_t_i_o_n1 )
(= (Distance X_l_o_c_a_t_i_o_n1 X_l_o_c_a_t_i_o_n3 )1)
(= (Distance X_l_o_c_a_t_i_o_n3 X_l_o_c_a_t_i_o_n1 )1)

(EmptyHome X_s_t_o_p3)
(EmptyHome X_s_t_o_p10)
(EmptyHome X_s_t_o_p4)
(EmptyHome X_s_t_o_p6)
(EmptyHome X_s_t_o_p0)
(EmptyHome X_s_t_o_p1)
(EmptyHome X_s_t_o_p5)
)

  ; The goal state describe what we desire to achieve
  (:goal (and
( Car_At X_s_t_o_p0 )
(not (EmptyHome X_s_t_o_p3))
(not (EmptyHome X_s_t_o_p10))
(not (EmptyHome X_s_t_o_p4))
(not (EmptyHome X_s_t_o_p6))
(not (EmptyHome X_s_t_o_p0))
(not (EmptyHome X_s_t_o_p1))
(not (EmptyHome X_s_t_o_p5))
  ))
)