; Problem description
; This file describes the example input from the problem statement
(define (problem pb1)
  (:metric minimize (total-cost))
  (:domain CS170)
(:objects TA_X_s_h_y TA_X_s_w_e_a_r TA_X_d_o_u_g_h TA_X_p_a_i_n TA_X_b_u_f_f_e_t TA_X_l_i_n_g_e_r TA_X_c_i_r_c_u_l_a_t_i_o_n TA_X_c_l_a_s_s TA_X_n_a_t_i_o_n_a_l_i_s_t TA_X_t_o_o_l TA_X_h_o_n_o_r TA_X_p_r_i_s_o_n TA_X_i_m_p_o_s_t_e_r TA_X_g_u_a_r_a_n_t_e_e TA_X_e_x_c_l_u_s_i_v_e TA_X_o_t_h_e_r TA_X_r_o_b TA_X_s_u_n_r_i_s_e TA_X_v_o_i_c_e TA_X_w_i_n_n_e_r TA_X_v_e_g_e_t_a_r_i_a_n TA_X_t_o_l_e_r_a_t_e TA_X_l_a_k_e TA_X_h_e_a_d_l_i_n_e TA_X_t_h_r_o_n_e TA_X_s_e_i_z_e TA_X_g_l_a_s_s_e_s TA_X_p_a_p_e_r TA_X_t_a_b_l_e_t TA_X_l_e_g_i_s_l_a_t_i_o_n TA_X_e_n_t_e_r TA_X_e_n_h_a_n_c_e TA_X_q_u_a_l_i_t_y TA_X_i_n_j_u_r_y TA_X_b_i_t_t_e_r TA_X_d_i_p TA_X_p_a_g_e TA_X_m_y_s_t_e_r_y TA_X_f_i_g_u_r_e TA_X_a_u_t_o_n_o_m_y TA_X_l_i_k_e_l_y TA_X_d_e_m_a_n_d TA_X_o_u_t_p_u_t TA_X_t_h_u_m_b TA_X_c_i_g_a_r_e_t_t_e TA_X_b_r_a_k_e TA_X_f_i_n_a_n_c_i_a_l TA_X_t_i_t_l_e TA_X_k_i_n_g TA_X_s_i_g_n X_p_a_c_e X_l_i_k_e_l_y X_d_i_s_c_l_o_s_e X_e_x_c_u_s_e X_p_r_i_s_o_n X_f_e_a_t_u_r_e X_t_i_t_l_e X_m_i_s_e_r_a_b_l_e X_s_k_e_l_e_t_o_n X_k_i_n_g X_e_n_v_i_r_o_n_m_e_n_t X_m_i_x_t_u_r_e X_q_u_a_l_i_t_y X_i_n_j_u_r_y X_p_a_p_e_r X_o_u_t_p_u_t X_c_i_r_c_u_l_a_t_i_o_n X_d_u_e X_p_a_g_e X_w_r_i_t_e X_v_i_e_w X_a_u_d_i_e_n_c_e X_v_o_i_c_e X_d_e_p_o_s_i_t X_p_r_o_f_o_u_n_d X_h_o_n_o_r X_e_n_t_e_r X_t_h_r_o_n_e X_u_n_d_e_r_s_t_a_n_d X_g_u_a_r_a_n_t_e_e X_p_h_y_s_i_c_s X_g_a_t_e X_e_x_e_m_p_t X_t_a_b_l_e_t X_i_n_j_e_c_t_i_o_n X_m_a_r_k_e_t X_f_o_r_g_e X_t_h_u_m_b X_o_p_p_o_s_e_d X_h_e_a_d_l_i_n_e X_d_o_u_g_h X_c_e_r_t_a_i_n X_e_x_c_l_u_s_i_v_e X_o_t_h_e_r X_a_s_s_i_g_n_m_e_n_t X_p_i_e_r X_b_r_a_k_e X_n_a_t_i_o_n_a_l_i_s_t X_a_p_p_r_o_v_a_l X_w_i_n_n_e_r X_t_h_i_r_s_t_y X_c_i_g_a_r_e_t_t_e X_b_u_f_f_e_t X_a_s_s_u_m_e X_m_y_s_t_e_r_y X_a_u_t_o_n_o_m_y X_j_u_d_i_c_i_a_l X_i_r_o_n X_r_e_s_p_e_c_t X_r_o_m_a_n_t_i_c X_t_o_l_e_r_a_t_e X_s_i_g_n X_p_i_g X_f_i_n_a_n_c_i_a_l X_i_n_t_e_r_a_c_t_i_v_e X_l_e_g_i_s_l_a_t_i_o_n X_c_l_a_s_s X_g_l_a_s_s_e_s X_t_o_o_l X_s_o_l_v_e X_l_a_k_e X_f_o_r_t_u_n_e X_d_i_a_l_o_g_u_e X_s_u_n_r_i_s_e X_l_i_n_g_e_r X_r_o_b X_g_a_l_l_o_n X_b_i_t_t_e_r X_s_e_i_z_e X_f_i_g_u_r_e X_s_t_r_o_k_e X_s_h_y X_b_a_n_a_n_a X_d_i_p X_i_m_p_o_s_t_e_r X_d_e_m_a_n_d X_e_n_h_a_n_c_e X_s_w_e_a_r X_v_e_g_e_t_a_r_i_a_n X_j_o_i_n_t X_s_h_i_v_e_r X_w_a_r_d X_p_a_i_n X_d_i_s_c_r_i_m_i_n_a_t_e X_c_o_a_s_t X_s_t_r_e_s_s X_m_a_t_u_r_e X_c_h_a_i_r X_r_e_n_t X_s_t_r_a_i_g_h_t_e_n )
(:init(= (total-cost) 0)
( Car_At X_p_a_c_e )
(InCar TA_X_s_h_y)
(InCar TA_X_s_w_e_a_r)
(InCar TA_X_d_o_u_g_h)
(InCar TA_X_p_a_i_n)
(InCar TA_X_b_u_f_f_e_t)
(InCar TA_X_l_i_n_g_e_r)
(InCar TA_X_c_i_r_c_u_l_a_t_i_o_n)
(InCar TA_X_c_l_a_s_s)
(InCar TA_X_n_a_t_i_o_n_a_l_i_s_t)
(InCar TA_X_t_o_o_l)
(InCar TA_X_h_o_n_o_r)
(InCar TA_X_p_r_i_s_o_n)
(InCar TA_X_i_m_p_o_s_t_e_r)
(InCar TA_X_g_u_a_r_a_n_t_e_e)
(InCar TA_X_e_x_c_l_u_s_i_v_e)
(InCar TA_X_o_t_h_e_r)
(InCar TA_X_r_o_b)
(InCar TA_X_s_u_n_r_i_s_e)
(InCar TA_X_v_o_i_c_e)
(InCar TA_X_w_i_n_n_e_r)
(InCar TA_X_v_e_g_e_t_a_r_i_a_n)
(InCar TA_X_t_o_l_e_r_a_t_e)
(InCar TA_X_l_a_k_e)
(InCar TA_X_h_e_a_d_l_i_n_e)
(InCar TA_X_t_h_r_o_n_e)
(InCar TA_X_s_e_i_z_e)
(InCar TA_X_g_l_a_s_s_e_s)
(InCar TA_X_p_a_p_e_r)
(InCar TA_X_t_a_b_l_e_t)
(InCar TA_X_l_e_g_i_s_l_a_t_i_o_n)
(InCar TA_X_e_n_t_e_r)
(InCar TA_X_e_n_h_a_n_c_e)
(InCar TA_X_q_u_a_l_i_t_y)
(InCar TA_X_i_n_j_u_r_y)
(InCar TA_X_b_i_t_t_e_r)
(InCar TA_X_d_i_p)
(InCar TA_X_p_a_g_e)
(InCar TA_X_m_y_s_t_e_r_y)
(InCar TA_X_f_i_g_u_r_e)
(InCar TA_X_a_u_t_o_n_o_m_y)
(InCar TA_X_l_i_k_e_l_y)
(InCar TA_X_d_e_m_a_n_d)
(InCar TA_X_o_u_t_p_u_t)
(InCar TA_X_t_h_u_m_b)
(InCar TA_X_c_i_g_a_r_e_t_t_e)
(InCar TA_X_b_r_a_k_e)
(InCar TA_X_f_i_n_a_n_c_i_a_l)
(InCar TA_X_t_i_t_l_e)
(InCar TA_X_k_i_n_g)
(InCar TA_X_s_i_g_n)
(Path X_p_a_c_e X_k_i_n_g )
(Path X_k_i_n_g X_p_a_c_e )
(= (Distance X_p_a_c_e X_k_i_n_g )19.07554)
(= (Distance X_k_i_n_g X_p_a_c_e )19.07554)

(Path X_p_a_c_e X_v_o_i_c_e )
(Path X_v_o_i_c_e X_p_a_c_e )
(= (Distance X_p_a_c_e X_v_o_i_c_e )13.56677)
(= (Distance X_v_o_i_c_e X_p_a_c_e )13.56677)

(Path X_p_a_c_e X_h_o_n_o_r )
(Path X_h_o_n_o_r X_p_a_c_e )
(= (Distance X_p_a_c_e X_h_o_n_o_r )28.03504)
(= (Distance X_h_o_n_o_r X_p_a_c_e )28.03504)

(Path X_p_a_c_e X_p_h_y_s_i_c_s )
(Path X_p_h_y_s_i_c_s X_p_a_c_e )
(= (Distance X_p_a_c_e X_p_h_y_s_i_c_s )16.86037)
(= (Distance X_p_h_y_s_i_c_s X_p_a_c_e )16.86037)

(Path X_p_a_c_e X_i_n_t_e_r_a_c_t_i_v_e )
(Path X_i_n_t_e_r_a_c_t_i_v_e X_p_a_c_e )
(= (Distance X_p_a_c_e X_i_n_t_e_r_a_c_t_i_v_e )24.46444)
(= (Distance X_i_n_t_e_r_a_c_t_i_v_e X_p_a_c_e )24.46444)

(Path X_p_a_c_e X_s_h_i_v_e_r )
(Path X_s_h_i_v_e_r X_p_a_c_e )
(= (Distance X_p_a_c_e X_s_h_i_v_e_r )16.05675)
(= (Distance X_s_h_i_v_e_r X_p_a_c_e )16.05675)

(Path X_l_i_k_e_l_y X_s_k_e_l_e_t_o_n )
(Path X_s_k_e_l_e_t_o_n X_l_i_k_e_l_y )
(= (Distance X_l_i_k_e_l_y X_s_k_e_l_e_t_o_n )24.8681)
(= (Distance X_s_k_e_l_e_t_o_n X_l_i_k_e_l_y )24.8681)

(Path X_l_i_k_e_l_y X_d_i_a_l_o_g_u_e )
(Path X_d_i_a_l_o_g_u_e X_l_i_k_e_l_y )
(= (Distance X_l_i_k_e_l_y X_d_i_a_l_o_g_u_e )11.59847)
(= (Distance X_d_i_a_l_o_g_u_e X_l_i_k_e_l_y )11.59847)

(Path X_l_i_k_e_l_y X_e_n_h_a_n_c_e )
(Path X_e_n_h_a_n_c_e X_l_i_k_e_l_y )
(= (Distance X_l_i_k_e_l_y X_e_n_h_a_n_c_e )22.40038)
(= (Distance X_e_n_h_a_n_c_e X_l_i_k_e_l_y )22.40038)

(Path X_l_i_k_e_l_y X_s_h_i_v_e_r )
(Path X_s_h_i_v_e_r X_l_i_k_e_l_y )
(= (Distance X_l_i_k_e_l_y X_s_h_i_v_e_r )25.27574)
(= (Distance X_s_h_i_v_e_r X_l_i_k_e_l_y )25.27574)

(Path X_d_i_s_c_l_o_s_e X_s_k_e_l_e_t_o_n )
(Path X_s_k_e_l_e_t_o_n X_d_i_s_c_l_o_s_e )
(= (Distance X_d_i_s_c_l_o_s_e X_s_k_e_l_e_t_o_n )2.89935)
(= (Distance X_s_k_e_l_e_t_o_n X_d_i_s_c_l_o_s_e )2.89935)

(Path X_d_i_s_c_l_o_s_e X_i_n_j_u_r_y )
(Path X_i_n_j_u_r_y X_d_i_s_c_l_o_s_e )
(= (Distance X_d_i_s_c_l_o_s_e X_i_n_j_u_r_y )8.40798)
(= (Distance X_i_n_j_u_r_y X_d_i_s_c_l_o_s_e )8.40798)

(Path X_d_i_s_c_l_o_s_e X_o_u_t_p_u_t )
(Path X_o_u_t_p_u_t X_d_i_s_c_l_o_s_e )
(= (Distance X_d_i_s_c_l_o_s_e X_o_u_t_p_u_t )47.52413)
(= (Distance X_o_u_t_p_u_t X_d_i_s_c_l_o_s_e )47.52413)

(Path X_d_i_s_c_l_o_s_e X_g_a_t_e )
(Path X_g_a_t_e X_d_i_s_c_l_o_s_e )
(= (Distance X_d_i_s_c_l_o_s_e X_g_a_t_e )30.79678)
(= (Distance X_g_a_t_e X_d_i_s_c_l_o_s_e )30.79678)

(Path X_d_i_s_c_l_o_s_e X_c_e_r_t_a_i_n )
(Path X_c_e_r_t_a_i_n X_d_i_s_c_l_o_s_e )
(= (Distance X_d_i_s_c_l_o_s_e X_c_e_r_t_a_i_n )46.42584)
(= (Distance X_c_e_r_t_a_i_n X_d_i_s_c_l_o_s_e )46.42584)

(Path X_d_i_s_c_l_o_s_e X_c_l_a_s_s )
(Path X_c_l_a_s_s X_d_i_s_c_l_o_s_e )
(= (Distance X_d_i_s_c_l_o_s_e X_c_l_a_s_s )9.76797)
(= (Distance X_c_l_a_s_s X_d_i_s_c_l_o_s_e )9.76797)

(Path X_e_x_c_u_s_e X_t_h_u_m_b )
(Path X_t_h_u_m_b X_e_x_c_u_s_e )
(= (Distance X_e_x_c_u_s_e X_t_h_u_m_b )11.71858)
(= (Distance X_t_h_u_m_b X_e_x_c_u_s_e )11.71858)

(Path X_e_x_c_u_s_e X_o_t_h_e_r )
(Path X_o_t_h_e_r X_e_x_c_u_s_e )
(= (Distance X_e_x_c_u_s_e X_o_t_h_e_r )25.98894)
(= (Distance X_o_t_h_e_r X_e_x_c_u_s_e )25.98894)

(Path X_e_x_c_u_s_e X_b_u_f_f_e_t )
(Path X_b_u_f_f_e_t X_e_x_c_u_s_e )
(= (Distance X_e_x_c_u_s_e X_b_u_f_f_e_t )30.95553)
(= (Distance X_b_u_f_f_e_t X_e_x_c_u_s_e )30.95553)

(Path X_e_x_c_u_s_e X_l_e_g_i_s_l_a_t_i_o_n )
(Path X_l_e_g_i_s_l_a_t_i_o_n X_e_x_c_u_s_e )
(= (Distance X_e_x_c_u_s_e X_l_e_g_i_s_l_a_t_i_o_n )22.89897)
(= (Distance X_l_e_g_i_s_l_a_t_i_o_n X_e_x_c_u_s_e )22.89897)

(Path X_e_x_c_u_s_e X_s_t_r_o_k_e )
(Path X_s_t_r_o_k_e X_e_x_c_u_s_e )
(= (Distance X_e_x_c_u_s_e X_s_t_r_o_k_e )20.66151)
(= (Distance X_s_t_r_o_k_e X_e_x_c_u_s_e )20.66151)

(Path X_p_r_i_s_o_n X_t_i_t_l_e )
(Path X_t_i_t_l_e X_p_r_i_s_o_n )
(= (Distance X_p_r_i_s_o_n X_t_i_t_l_e )40.35491)
(= (Distance X_t_i_t_l_e X_p_r_i_s_o_n )40.35491)

(Path X_p_r_i_s_o_n X_i_n_j_u_r_y )
(Path X_i_n_j_u_r_y X_p_r_i_s_o_n )
(= (Distance X_p_r_i_s_o_n X_i_n_j_u_r_y )24.4008)
(= (Distance X_i_n_j_u_r_y X_p_r_i_s_o_n )24.4008)

(Path X_p_r_i_s_o_n X_t_h_u_m_b )
(Path X_t_h_u_m_b X_p_r_i_s_o_n )
(= (Distance X_p_r_i_s_o_n X_t_h_u_m_b )50.71325)
(= (Distance X_t_h_u_m_b X_p_r_i_s_o_n )50.71325)

(Path X_p_r_i_s_o_n X_p_i_e_r )
(Path X_p_i_e_r X_p_r_i_s_o_n )
(= (Distance X_p_r_i_s_o_n X_p_i_e_r )47.10368)
(= (Distance X_p_i_e_r X_p_r_i_s_o_n )47.10368)

(Path X_p_r_i_s_o_n X_t_h_i_r_s_t_y )
(Path X_t_h_i_r_s_t_y X_p_r_i_s_o_n )
(= (Distance X_p_r_i_s_o_n X_t_h_i_r_s_t_y )43.86188)
(= (Distance X_t_h_i_r_s_t_y X_p_r_i_s_o_n )43.86188)

(Path X_p_r_i_s_o_n X_c_i_g_a_r_e_t_t_e )
(Path X_c_i_g_a_r_e_t_t_e X_p_r_i_s_o_n )
(= (Distance X_p_r_i_s_o_n X_c_i_g_a_r_e_t_t_e )46.18394)
(= (Distance X_c_i_g_a_r_e_t_t_e X_p_r_i_s_o_n )46.18394)

(Path X_p_r_i_s_o_n X_i_n_t_e_r_a_c_t_i_v_e )
(Path X_i_n_t_e_r_a_c_t_i_v_e X_p_r_i_s_o_n )
(= (Distance X_p_r_i_s_o_n X_i_n_t_e_r_a_c_t_i_v_e )52.38064)
(= (Distance X_i_n_t_e_r_a_c_t_i_v_e X_p_r_i_s_o_n )52.38064)

(Path X_p_r_i_s_o_n X_s_o_l_v_e )
(Path X_s_o_l_v_e X_p_r_i_s_o_n )
(= (Distance X_p_r_i_s_o_n X_s_o_l_v_e )13.01734)
(= (Distance X_s_o_l_v_e X_p_r_i_s_o_n )13.01734)

(Path X_p_r_i_s_o_n X_d_i_a_l_o_g_u_e )
(Path X_d_i_a_l_o_g_u_e X_p_r_i_s_o_n )
(= (Distance X_p_r_i_s_o_n X_d_i_a_l_o_g_u_e )9.39668)
(= (Distance X_d_i_a_l_o_g_u_e X_p_r_i_s_o_n )9.39668)

(Path X_p_r_i_s_o_n X_s_t_r_e_s_s )
(Path X_s_t_r_e_s_s X_p_r_i_s_o_n )
(= (Distance X_p_r_i_s_o_n X_s_t_r_e_s_s )26.65443)
(= (Distance X_s_t_r_e_s_s X_p_r_i_s_o_n )26.65443)

(Path X_f_e_a_t_u_r_e X_h_o_n_o_r )
(Path X_h_o_n_o_r X_f_e_a_t_u_r_e )
(= (Distance X_f_e_a_t_u_r_e X_h_o_n_o_r )15.48618)
(= (Distance X_h_o_n_o_r X_f_e_a_t_u_r_e )15.48618)

(Path X_f_e_a_t_u_r_e X_i_n_t_e_r_a_c_t_i_v_e )
(Path X_i_n_t_e_r_a_c_t_i_v_e X_f_e_a_t_u_r_e )
(= (Distance X_f_e_a_t_u_r_e X_i_n_t_e_r_a_c_t_i_v_e )6.34441)
(= (Distance X_i_n_t_e_r_a_c_t_i_v_e X_f_e_a_t_u_r_e )6.34441)

(Path X_f_e_a_t_u_r_e X_l_e_g_i_s_l_a_t_i_o_n )
(Path X_l_e_g_i_s_l_a_t_i_o_n X_f_e_a_t_u_r_e )
(= (Distance X_f_e_a_t_u_r_e X_l_e_g_i_s_l_a_t_i_o_n )38.83733)
(= (Distance X_l_e_g_i_s_l_a_t_i_o_n X_f_e_a_t_u_r_e )38.83733)

(Path X_f_e_a_t_u_r_e X_g_l_a_s_s_e_s )
(Path X_g_l_a_s_s_e_s X_f_e_a_t_u_r_e )
(= (Distance X_f_e_a_t_u_r_e X_g_l_a_s_s_e_s )49.1111)
(= (Distance X_g_l_a_s_s_e_s X_f_e_a_t_u_r_e )49.1111)

(Path X_f_e_a_t_u_r_e X_s_h_y )
(Path X_s_h_y X_f_e_a_t_u_r_e )
(= (Distance X_f_e_a_t_u_r_e X_s_h_y )34.4373)
(= (Distance X_s_h_y X_f_e_a_t_u_r_e )34.4373)

(Path X_f_e_a_t_u_r_e X_c_h_a_i_r )
(Path X_c_h_a_i_r X_f_e_a_t_u_r_e )
(= (Distance X_f_e_a_t_u_r_e X_c_h_a_i_r )37.29656)
(= (Distance X_c_h_a_i_r X_f_e_a_t_u_r_e )37.29656)

(Path X_t_i_t_l_e X_w_r_i_t_e )
(Path X_w_r_i_t_e X_t_i_t_l_e )
(= (Distance X_t_i_t_l_e X_w_r_i_t_e )25.24967)
(= (Distance X_w_r_i_t_e X_t_i_t_l_e )25.24967)

(Path X_t_i_t_l_e X_d_e_p_o_s_i_t )
(Path X_d_e_p_o_s_i_t X_t_i_t_l_e )
(= (Distance X_t_i_t_l_e X_d_e_p_o_s_i_t )27.92471)
(= (Distance X_d_e_p_o_s_i_t X_t_i_t_l_e )27.92471)

(Path X_t_i_t_l_e X_t_a_b_l_e_t )
(Path X_t_a_b_l_e_t X_t_i_t_l_e )
(= (Distance X_t_i_t_l_e X_t_a_b_l_e_t )30.24719)
(= (Distance X_t_a_b_l_e_t X_t_i_t_l_e )30.24719)

(Path X_t_i_t_l_e X_o_p_p_o_s_e_d )
(Path X_o_p_p_o_s_e_d X_t_i_t_l_e )
(= (Distance X_t_i_t_l_e X_o_p_p_o_s_e_d )58.53255)
(= (Distance X_o_p_p_o_s_e_d X_t_i_t_l_e )58.53255)

(Path X_t_i_t_l_e X_r_e_s_p_e_c_t )
(Path X_r_e_s_p_e_c_t X_t_i_t_l_e )
(= (Distance X_t_i_t_l_e X_r_e_s_p_e_c_t )41.19915)
(= (Distance X_r_e_s_p_e_c_t X_t_i_t_l_e )41.19915)

(Path X_t_i_t_l_e X_i_n_t_e_r_a_c_t_i_v_e )
(Path X_i_n_t_e_r_a_c_t_i_v_e X_t_i_t_l_e )
(= (Distance X_t_i_t_l_e X_i_n_t_e_r_a_c_t_i_v_e )44.4446)
(= (Distance X_i_n_t_e_r_a_c_t_i_v_e X_t_i_t_l_e )44.4446)

(Path X_t_i_t_l_e X_l_a_k_e )
(Path X_l_a_k_e X_t_i_t_l_e )
(= (Distance X_t_i_t_l_e X_l_a_k_e )33.19027)
(= (Distance X_l_a_k_e X_t_i_t_l_e )33.19027)

(Path X_t_i_t_l_e X_s_u_n_r_i_s_e )
(Path X_s_u_n_r_i_s_e X_t_i_t_l_e )
(= (Distance X_t_i_t_l_e X_s_u_n_r_i_s_e )6.67867)
(= (Distance X_s_u_n_r_i_s_e X_t_i_t_l_e )6.67867)

(Path X_t_i_t_l_e X_s_h_y )
(Path X_s_h_y X_t_i_t_l_e )
(= (Distance X_t_i_t_l_e X_s_h_y )13.93233)
(= (Distance X_s_h_y X_t_i_t_l_e )13.93233)

(Path X_t_i_t_l_e X_d_e_m_a_n_d )
(Path X_d_e_m_a_n_d X_t_i_t_l_e )
(= (Distance X_t_i_t_l_e X_d_e_m_a_n_d )42.63318)
(= (Distance X_d_e_m_a_n_d X_t_i_t_l_e )42.63318)

(Path X_t_i_t_l_e X_c_o_a_s_t )
(Path X_c_o_a_s_t X_t_i_t_l_e )
(= (Distance X_t_i_t_l_e X_c_o_a_s_t )28.62567)
(= (Distance X_c_o_a_s_t X_t_i_t_l_e )28.62567)

(Path X_m_i_s_e_r_a_b_l_e X_s_k_e_l_e_t_o_n )
(Path X_s_k_e_l_e_t_o_n X_m_i_s_e_r_a_b_l_e )
(= (Distance X_m_i_s_e_r_a_b_l_e X_s_k_e_l_e_t_o_n )46.17604)
(= (Distance X_s_k_e_l_e_t_o_n X_m_i_s_e_r_a_b_l_e )46.17604)

(Path X_m_i_s_e_r_a_b_l_e X_e_n_v_i_r_o_n_m_e_n_t )
(Path X_e_n_v_i_r_o_n_m_e_n_t X_m_i_s_e_r_a_b_l_e )
(= (Distance X_m_i_s_e_r_a_b_l_e X_e_n_v_i_r_o_n_m_e_n_t )8.84032)
(= (Distance X_e_n_v_i_r_o_n_m_e_n_t X_m_i_s_e_r_a_b_l_e )8.84032)

(Path X_m_i_s_e_r_a_b_l_e X_a_u_d_i_e_n_c_e )
(Path X_a_u_d_i_e_n_c_e X_m_i_s_e_r_a_b_l_e )
(= (Distance X_m_i_s_e_r_a_b_l_e X_a_u_d_i_e_n_c_e )47.48383)
(= (Distance X_a_u_d_i_e_n_c_e X_m_i_s_e_r_a_b_l_e )47.48383)

(Path X_m_i_s_e_r_a_b_l_e X_p_r_o_f_o_u_n_d )
(Path X_p_r_o_f_o_u_n_d X_m_i_s_e_r_a_b_l_e )
(= (Distance X_m_i_s_e_r_a_b_l_e X_p_r_o_f_o_u_n_d )23.23461)
(= (Distance X_p_r_o_f_o_u_n_d X_m_i_s_e_r_a_b_l_e )23.23461)

(Path X_m_i_s_e_r_a_b_l_e X_m_a_r_k_e_t )
(Path X_m_a_r_k_e_t X_m_i_s_e_r_a_b_l_e )
(= (Distance X_m_i_s_e_r_a_b_l_e X_m_a_r_k_e_t )2.77856)
(= (Distance X_m_a_r_k_e_t X_m_i_s_e_r_a_b_l_e )2.77856)

(Path X_m_i_s_e_r_a_b_l_e X_a_s_s_u_m_e )
(Path X_a_s_s_u_m_e X_m_i_s_e_r_a_b_l_e )
(= (Distance X_m_i_s_e_r_a_b_l_e X_a_s_s_u_m_e )41.34319)
(= (Distance X_a_s_s_u_m_e X_m_i_s_e_r_a_b_l_e )41.34319)

(Path X_m_i_s_e_r_a_b_l_e X_a_u_t_o_n_o_m_y )
(Path X_a_u_t_o_n_o_m_y X_m_i_s_e_r_a_b_l_e )
(= (Distance X_m_i_s_e_r_a_b_l_e X_a_u_t_o_n_o_m_y )30.33588)
(= (Distance X_a_u_t_o_n_o_m_y X_m_i_s_e_r_a_b_l_e )30.33588)

(Path X_m_i_s_e_r_a_b_l_e X_g_l_a_s_s_e_s )
(Path X_g_l_a_s_s_e_s X_m_i_s_e_r_a_b_l_e )
(= (Distance X_m_i_s_e_r_a_b_l_e X_g_l_a_s_s_e_s )37.15964)
(= (Distance X_g_l_a_s_s_e_s X_m_i_s_e_r_a_b_l_e )37.15964)

(Path X_s_k_e_l_e_t_o_n X_u_n_d_e_r_s_t_a_n_d )
(Path X_u_n_d_e_r_s_t_a_n_d X_s_k_e_l_e_t_o_n )
(= (Distance X_s_k_e_l_e_t_o_n X_u_n_d_e_r_s_t_a_n_d )6.70312)
(= (Distance X_u_n_d_e_r_s_t_a_n_d X_s_k_e_l_e_t_o_n )6.70312)

(Path X_s_k_e_l_e_t_o_n X_h_e_a_d_l_i_n_e )
(Path X_h_e_a_d_l_i_n_e X_s_k_e_l_e_t_o_n )
(= (Distance X_s_k_e_l_e_t_o_n X_h_e_a_d_l_i_n_e )43.65031)
(= (Distance X_h_e_a_d_l_i_n_e X_s_k_e_l_e_t_o_n )43.65031)

(Path X_s_k_e_l_e_t_o_n X_b_a_n_a_n_a )
(Path X_b_a_n_a_n_a X_s_k_e_l_e_t_o_n )
(= (Distance X_s_k_e_l_e_t_o_n X_b_a_n_a_n_a )16.43916)
(= (Distance X_b_a_n_a_n_a X_s_k_e_l_e_t_o_n )16.43916)

(Path X_s_k_e_l_e_t_o_n X_m_a_t_u_r_e )
(Path X_m_a_t_u_r_e X_s_k_e_l_e_t_o_n )
(= (Distance X_s_k_e_l_e_t_o_n X_m_a_t_u_r_e )22.23784)
(= (Distance X_m_a_t_u_r_e X_s_k_e_l_e_t_o_n )22.23784)

(Path X_k_i_n_g X_v_i_e_w )
(Path X_v_i_e_w X_k_i_n_g )
(= (Distance X_k_i_n_g X_v_i_e_w )41.29372)
(= (Distance X_v_i_e_w X_k_i_n_g )41.29372)

(Path X_k_i_n_g X_g_u_a_r_a_n_t_e_e )
(Path X_g_u_a_r_a_n_t_e_e X_k_i_n_g )
(= (Distance X_k_i_n_g X_g_u_a_r_a_n_t_e_e )3.98881)
(= (Distance X_g_u_a_r_a_n_t_e_e X_k_i_n_g )3.98881)

(Path X_k_i_n_g X_p_h_y_s_i_c_s )
(Path X_p_h_y_s_i_c_s X_k_i_n_g )
(= (Distance X_k_i_n_g X_p_h_y_s_i_c_s )33.04332)
(= (Distance X_p_h_y_s_i_c_s X_k_i_n_g )33.04332)

(Path X_k_i_n_g X_b_a_n_a_n_a )
(Path X_b_a_n_a_n_a X_k_i_n_g )
(= (Distance X_k_i_n_g X_b_a_n_a_n_a )6.81863)
(= (Distance X_b_a_n_a_n_a X_k_i_n_g )6.81863)

(Path X_k_i_n_g X_r_e_n_t )
(Path X_r_e_n_t X_k_i_n_g )
(= (Distance X_k_i_n_g X_r_e_n_t )31.80423)
(= (Distance X_r_e_n_t X_k_i_n_g )31.80423)

(Path X_e_n_v_i_r_o_n_m_e_n_t X_i_n_j_u_r_y )
(Path X_i_n_j_u_r_y X_e_n_v_i_r_o_n_m_e_n_t )
(= (Distance X_e_n_v_i_r_o_n_m_e_n_t X_i_n_j_u_r_y )43.0965)
(= (Distance X_i_n_j_u_r_y X_e_n_v_i_r_o_n_m_e_n_t )43.0965)

(Path X_e_n_v_i_r_o_n_m_e_n_t X_e_x_e_m_p_t )
(Path X_e_x_e_m_p_t X_e_n_v_i_r_o_n_m_e_n_t )
(= (Distance X_e_n_v_i_r_o_n_m_e_n_t X_e_x_e_m_p_t )23.33166)
(= (Distance X_e_x_e_m_p_t X_e_n_v_i_r_o_n_m_e_n_t )23.33166)

(Path X_e_n_v_i_r_o_n_m_e_n_t X_a_p_p_r_o_v_a_l )
(Path X_a_p_p_r_o_v_a_l X_e_n_v_i_r_o_n_m_e_n_t )
(= (Distance X_e_n_v_i_r_o_n_m_e_n_t X_a_p_p_r_o_v_a_l )8.50811)
(= (Distance X_a_p_p_r_o_v_a_l X_e_n_v_i_r_o_n_m_e_n_t )8.50811)

(Path X_e_n_v_i_r_o_n_m_e_n_t X_s_h_i_v_e_r )
(Path X_s_h_i_v_e_r X_e_n_v_i_r_o_n_m_e_n_t )
(= (Distance X_e_n_v_i_r_o_n_m_e_n_t X_s_h_i_v_e_r )43.44607)
(= (Distance X_s_h_i_v_e_r X_e_n_v_i_r_o_n_m_e_n_t )43.44607)

(Path X_m_i_x_t_u_r_e X_p_a_p_e_r )
(Path X_p_a_p_e_r X_m_i_x_t_u_r_e )
(= (Distance X_m_i_x_t_u_r_e X_p_a_p_e_r )33.49339)
(= (Distance X_p_a_p_e_r X_m_i_x_t_u_r_e )33.49339)

(Path X_m_i_x_t_u_r_e X_u_n_d_e_r_s_t_a_n_d )
(Path X_u_n_d_e_r_s_t_a_n_d X_m_i_x_t_u_r_e )
(= (Distance X_m_i_x_t_u_r_e X_u_n_d_e_r_s_t_a_n_d )39.52366)
(= (Distance X_u_n_d_e_r_s_t_a_n_d X_m_i_x_t_u_r_e )39.52366)

(Path X_m_i_x_t_u_r_e X_j_u_d_i_c_i_a_l )
(Path X_j_u_d_i_c_i_a_l X_m_i_x_t_u_r_e )
(= (Distance X_m_i_x_t_u_r_e X_j_u_d_i_c_i_a_l )32.62585)
(= (Distance X_j_u_d_i_c_i_a_l X_m_i_x_t_u_r_e )32.62585)

(Path X_m_i_x_t_u_r_e X_s_o_l_v_e )
(Path X_s_o_l_v_e X_m_i_x_t_u_r_e )
(= (Distance X_m_i_x_t_u_r_e X_s_o_l_v_e )22.49247)
(= (Distance X_s_o_l_v_e X_m_i_x_t_u_r_e )22.49247)

(Path X_m_i_x_t_u_r_e X_r_e_n_t )
(Path X_r_e_n_t X_m_i_x_t_u_r_e )
(= (Distance X_m_i_x_t_u_r_e X_r_e_n_t )7.83575)
(= (Distance X_r_e_n_t X_m_i_x_t_u_r_e )7.83575)

(Path X_q_u_a_l_i_t_y X_t_h_r_o_n_e )
(Path X_t_h_r_o_n_e X_q_u_a_l_i_t_y )
(= (Distance X_q_u_a_l_i_t_y X_t_h_r_o_n_e )33.30691)
(= (Distance X_t_h_r_o_n_e X_q_u_a_l_i_t_y )33.30691)

(Path X_q_u_a_l_i_t_y X_h_e_a_d_l_i_n_e )
(Path X_h_e_a_d_l_i_n_e X_q_u_a_l_i_t_y )
(= (Distance X_q_u_a_l_i_t_y X_h_e_a_d_l_i_n_e )20.39633)
(= (Distance X_h_e_a_d_l_i_n_e X_q_u_a_l_i_t_y )20.39633)

(Path X_q_u_a_l_i_t_y X_c_e_r_t_a_i_n )
(Path X_c_e_r_t_a_i_n X_q_u_a_l_i_t_y )
(= (Distance X_q_u_a_l_i_t_y X_c_e_r_t_a_i_n )28.46896)
(= (Distance X_c_e_r_t_a_i_n X_q_u_a_l_i_t_y )28.46896)

(Path X_q_u_a_l_i_t_y X_d_i_s_c_r_i_m_i_n_a_t_e )
(Path X_d_i_s_c_r_i_m_i_n_a_t_e X_q_u_a_l_i_t_y )
(= (Distance X_q_u_a_l_i_t_y X_d_i_s_c_r_i_m_i_n_a_t_e )26.67966)
(= (Distance X_d_i_s_c_r_i_m_i_n_a_t_e X_q_u_a_l_i_t_y )26.67966)

(Path X_q_u_a_l_i_t_y X_s_t_r_a_i_g_h_t_e_n )
(Path X_s_t_r_a_i_g_h_t_e_n X_q_u_a_l_i_t_y )
(= (Distance X_q_u_a_l_i_t_y X_s_t_r_a_i_g_h_t_e_n )8.77523)
(= (Distance X_s_t_r_a_i_g_h_t_e_n X_q_u_a_l_i_t_y )8.77523)

(Path X_i_n_j_u_r_y X_a_u_d_i_e_n_c_e )
(Path X_a_u_d_i_e_n_c_e X_i_n_j_u_r_y )
(= (Distance X_i_n_j_u_r_y X_a_u_d_i_e_n_c_e )18.42432)
(= (Distance X_a_u_d_i_e_n_c_e X_i_n_j_u_r_y )18.42432)

(Path X_i_n_j_u_r_y X_h_o_n_o_r )
(Path X_h_o_n_o_r X_i_n_j_u_r_y )
(= (Distance X_i_n_j_u_r_y X_h_o_n_o_r )43.46176)
(= (Distance X_h_o_n_o_r X_i_n_j_u_r_y )43.46176)

(Path X_i_n_j_u_r_y X_e_x_e_m_p_t )
(Path X_e_x_e_m_p_t X_i_n_j_u_r_y )
(= (Distance X_i_n_j_u_r_y X_e_x_e_m_p_t )46.57348)
(= (Distance X_e_x_e_m_p_t X_i_n_j_u_r_y )46.57348)

(Path X_i_n_j_u_r_y X_p_i_e_r )
(Path X_p_i_e_r X_i_n_j_u_r_y )
(= (Distance X_i_n_j_u_r_y X_p_i_e_r )40.03992)
(= (Distance X_p_i_e_r X_i_n_j_u_r_y )40.03992)

(Path X_i_n_j_u_r_y X_s_i_g_n )
(Path X_s_i_g_n X_i_n_j_u_r_y )
(= (Distance X_i_n_j_u_r_y X_s_i_g_n )35.11796)
(= (Distance X_s_i_g_n X_i_n_j_u_r_y )35.11796)

(Path X_i_n_j_u_r_y X_s_h_y )
(Path X_s_h_y X_i_n_j_u_r_y )
(= (Distance X_i_n_j_u_r_y X_s_h_y )31.65859)
(= (Distance X_s_h_y X_i_n_j_u_r_y )31.65859)

(Path X_i_n_j_u_r_y X_w_a_r_d )
(Path X_w_a_r_d X_i_n_j_u_r_y )
(= (Distance X_i_n_j_u_r_y X_w_a_r_d )43.02896)
(= (Distance X_w_a_r_d X_i_n_j_u_r_y )43.02896)

(Path X_i_n_j_u_r_y X_p_a_i_n )
(Path X_p_a_i_n X_i_n_j_u_r_y )
(= (Distance X_i_n_j_u_r_y X_p_a_i_n )27.57632)
(= (Distance X_p_a_i_n X_i_n_j_u_r_y )27.57632)

(Path X_p_a_p_e_r X_d_e_p_o_s_i_t )
(Path X_d_e_p_o_s_i_t X_p_a_p_e_r )
(= (Distance X_p_a_p_e_r X_d_e_p_o_s_i_t )8.10987)
(= (Distance X_d_e_p_o_s_i_t X_p_a_p_e_r )8.10987)

(Path X_p_a_p_e_r X_u_n_d_e_r_s_t_a_n_d )
(Path X_u_n_d_e_r_s_t_a_n_d X_p_a_p_e_r )
(= (Distance X_p_a_p_e_r X_u_n_d_e_r_s_t_a_n_d )12.62389)
(= (Distance X_u_n_d_e_r_s_t_a_n_d X_p_a_p_e_r )12.62389)

(Path X_p_a_p_e_r X_g_a_t_e )
(Path X_g_a_t_e X_p_a_p_e_r )
(= (Distance X_p_a_p_e_r X_g_a_t_e )22.29198)
(= (Distance X_g_a_t_e X_p_a_p_e_r )22.29198)

(Path X_p_a_p_e_r X_m_y_s_t_e_r_y )
(Path X_m_y_s_t_e_r_y X_p_a_p_e_r )
(= (Distance X_p_a_p_e_r X_m_y_s_t_e_r_y )21.24268)
(= (Distance X_m_y_s_t_e_r_y X_p_a_p_e_r )21.24268)

(Path X_p_a_p_e_r X_j_u_d_i_c_i_a_l )
(Path X_j_u_d_i_c_i_a_l X_p_a_p_e_r )
(= (Distance X_p_a_p_e_r X_j_u_d_i_c_i_a_l )32.07548)
(= (Distance X_j_u_d_i_c_i_a_l X_p_a_p_e_r )32.07548)

(Path X_p_a_p_e_r X_i_m_p_o_s_t_e_r )
(Path X_i_m_p_o_s_t_e_r X_p_a_p_e_r )
(= (Distance X_p_a_p_e_r X_i_m_p_o_s_t_e_r )26.87506)
(= (Distance X_i_m_p_o_s_t_e_r X_p_a_p_e_r )26.87506)

(Path X_p_a_p_e_r X_s_t_r_e_s_s )
(Path X_s_t_r_e_s_s X_p_a_p_e_r )
(= (Distance X_p_a_p_e_r X_s_t_r_e_s_s )16.09173)
(= (Distance X_s_t_r_e_s_s X_p_a_p_e_r )16.09173)

(Path X_o_u_t_p_u_t X_c_i_r_c_u_l_a_t_i_o_n )
(Path X_c_i_r_c_u_l_a_t_i_o_n X_o_u_t_p_u_t )
(= (Distance X_o_u_t_p_u_t X_c_i_r_c_u_l_a_t_i_o_n )10.04968)
(= (Distance X_c_i_r_c_u_l_a_t_i_o_n X_o_u_t_p_u_t )10.04968)

(Path X_o_u_t_p_u_t X_a_u_d_i_e_n_c_e )
(Path X_a_u_d_i_e_n_c_e X_o_u_t_p_u_t )
(= (Distance X_o_u_t_p_u_t X_a_u_d_i_e_n_c_e )43.92688)
(= (Distance X_a_u_d_i_e_n_c_e X_o_u_t_p_u_t )43.92688)

(Path X_o_u_t_p_u_t X_t_h_u_m_b )
(Path X_t_h_u_m_b X_o_u_t_p_u_t )
(= (Distance X_o_u_t_p_u_t X_t_h_u_m_b )35.52763)
(= (Distance X_t_h_u_m_b X_o_u_t_p_u_t )35.52763)

(Path X_o_u_t_p_u_t X_a_u_t_o_n_o_m_y )
(Path X_a_u_t_o_n_o_m_y X_o_u_t_p_u_t )
(= (Distance X_o_u_t_p_u_t X_a_u_t_o_n_o_m_y )28.53501)
(= (Distance X_a_u_t_o_n_o_m_y X_o_u_t_p_u_t )28.53501)

(Path X_o_u_t_p_u_t X_j_u_d_i_c_i_a_l )
(Path X_j_u_d_i_c_i_a_l X_o_u_t_p_u_t )
(= (Distance X_o_u_t_p_u_t X_j_u_d_i_c_i_a_l )34.14912)
(= (Distance X_j_u_d_i_c_i_a_l X_o_u_t_p_u_t )34.14912)

(Path X_o_u_t_p_u_t X_g_l_a_s_s_e_s )
(Path X_g_l_a_s_s_e_s X_o_u_t_p_u_t )
(= (Distance X_o_u_t_p_u_t X_g_l_a_s_s_e_s )40.66373)
(= (Distance X_g_l_a_s_s_e_s X_o_u_t_p_u_t )40.66373)

(Path X_o_u_t_p_u_t X_d_i_s_c_r_i_m_i_n_a_t_e )
(Path X_d_i_s_c_r_i_m_i_n_a_t_e X_o_u_t_p_u_t )
(= (Distance X_o_u_t_p_u_t X_d_i_s_c_r_i_m_i_n_a_t_e )33.22674)
(= (Distance X_d_i_s_c_r_i_m_i_n_a_t_e X_o_u_t_p_u_t )33.22674)

(Path X_c_i_r_c_u_l_a_t_i_o_n X_d_e_p_o_s_i_t )
(Path X_d_e_p_o_s_i_t X_c_i_r_c_u_l_a_t_i_o_n )
(= (Distance X_c_i_r_c_u_l_a_t_i_o_n X_d_e_p_o_s_i_t )21.45523)
(= (Distance X_d_e_p_o_s_i_t X_c_i_r_c_u_l_a_t_i_o_n )21.45523)

(Path X_c_i_r_c_u_l_a_t_i_o_n X_g_a_t_e )
(Path X_g_a_t_e X_c_i_r_c_u_l_a_t_i_o_n )
(= (Distance X_c_i_r_c_u_l_a_t_i_o_n X_g_a_t_e )17.78184)
(= (Distance X_g_a_t_e X_c_i_r_c_u_l_a_t_i_o_n )17.78184)

(Path X_c_i_r_c_u_l_a_t_i_o_n X_j_u_d_i_c_i_a_l )
(Path X_j_u_d_i_c_i_a_l X_c_i_r_c_u_l_a_t_i_o_n )
(= (Distance X_c_i_r_c_u_l_a_t_i_o_n X_j_u_d_i_c_i_a_l )37.26588)
(= (Distance X_j_u_d_i_c_i_a_l X_c_i_r_c_u_l_a_t_i_o_n )37.26588)

(Path X_c_i_r_c_u_l_a_t_i_o_n X_i_n_t_e_r_a_c_t_i_v_e )
(Path X_i_n_t_e_r_a_c_t_i_v_e X_c_i_r_c_u_l_a_t_i_o_n )
(= (Distance X_c_i_r_c_u_l_a_t_i_o_n X_i_n_t_e_r_a_c_t_i_v_e )37.91557)
(= (Distance X_i_n_t_e_r_a_c_t_i_v_e X_c_i_r_c_u_l_a_t_i_o_n )37.91557)

(Path X_c_i_r_c_u_l_a_t_i_o_n X_t_o_o_l )
(Path X_t_o_o_l X_c_i_r_c_u_l_a_t_i_o_n )
(= (Distance X_c_i_r_c_u_l_a_t_i_o_n X_t_o_o_l )38.94311)
(= (Distance X_t_o_o_l X_c_i_r_c_u_l_a_t_i_o_n )38.94311)

(Path X_c_i_r_c_u_l_a_t_i_o_n X_r_o_b )
(Path X_r_o_b X_c_i_r_c_u_l_a_t_i_o_n )
(= (Distance X_c_i_r_c_u_l_a_t_i_o_n X_r_o_b )40.1949)
(= (Distance X_r_o_b X_c_i_r_c_u_l_a_t_i_o_n )40.1949)

(Path X_c_i_r_c_u_l_a_t_i_o_n X_p_a_i_n )
(Path X_p_a_i_n X_c_i_r_c_u_l_a_t_i_o_n )
(= (Distance X_c_i_r_c_u_l_a_t_i_o_n X_p_a_i_n )40.18407)
(= (Distance X_p_a_i_n X_c_i_r_c_u_l_a_t_i_o_n )40.18407)

(Path X_d_u_e X_w_r_i_t_e )
(Path X_w_r_i_t_e X_d_u_e )
(= (Distance X_d_u_e X_w_r_i_t_e )49.42908)
(= (Distance X_w_r_i_t_e X_d_u_e )49.42908)

(Path X_d_u_e X_g_u_a_r_a_n_t_e_e )
(Path X_g_u_a_r_a_n_t_e_e X_d_u_e )
(= (Distance X_d_u_e X_g_u_a_r_a_n_t_e_e )2.42394)
(= (Distance X_g_u_a_r_a_n_t_e_e X_d_u_e )2.42394)

(Path X_d_u_e X_o_t_h_e_r )
(Path X_o_t_h_e_r X_d_u_e )
(= (Distance X_d_u_e X_o_t_h_e_r )45.00373)
(= (Distance X_o_t_h_e_r X_d_u_e )45.00373)

(Path X_d_u_e X_s_e_i_z_e )
(Path X_s_e_i_z_e X_d_u_e )
(= (Distance X_d_u_e X_s_e_i_z_e )18.83029)
(= (Distance X_s_e_i_z_e X_d_u_e )18.83029)

(Path X_d_u_e X_j_o_i_n_t )
(Path X_j_o_i_n_t X_d_u_e )
(= (Distance X_d_u_e X_j_o_i_n_t )22.3675)
(= (Distance X_j_o_i_n_t X_d_u_e )22.3675)

(Path X_p_a_g_e X_c_e_r_t_a_i_n )
(Path X_c_e_r_t_a_i_n X_p_a_g_e )
(= (Distance X_p_a_g_e X_c_e_r_t_a_i_n )7.60192)
(= (Distance X_c_e_r_t_a_i_n X_p_a_g_e )7.60192)

(Path X_p_a_g_e X_a_p_p_r_o_v_a_l )
(Path X_a_p_p_r_o_v_a_l X_p_a_g_e )
(= (Distance X_p_a_g_e X_a_p_p_r_o_v_a_l )32.89962)
(= (Distance X_a_p_p_r_o_v_a_l X_p_a_g_e )32.89962)

(Path X_p_a_g_e X_l_a_k_e )
(Path X_l_a_k_e X_p_a_g_e )
(= (Distance X_p_a_g_e X_l_a_k_e )16.86364)
(= (Distance X_l_a_k_e X_p_a_g_e )16.86364)

(Path X_p_a_g_e X_f_o_r_t_u_n_e )
(Path X_f_o_r_t_u_n_e X_p_a_g_e )
(= (Distance X_p_a_g_e X_f_o_r_t_u_n_e )5.70412)
(= (Distance X_f_o_r_t_u_n_e X_p_a_g_e )5.70412)

(Path X_p_a_g_e X_d_e_m_a_n_d )
(Path X_d_e_m_a_n_d X_p_a_g_e )
(= (Distance X_p_a_g_e X_d_e_m_a_n_d )20.30089)
(= (Distance X_d_e_m_a_n_d X_p_a_g_e )20.30089)

(Path X_p_a_g_e X_s_h_i_v_e_r )
(Path X_s_h_i_v_e_r X_p_a_g_e )
(= (Distance X_p_a_g_e X_s_h_i_v_e_r )28.73698)
(= (Distance X_s_h_i_v_e_r X_p_a_g_e )28.73698)

(Path X_p_a_g_e X_s_t_r_a_i_g_h_t_e_n )
(Path X_s_t_r_a_i_g_h_t_e_n X_p_a_g_e )
(= (Distance X_p_a_g_e X_s_t_r_a_i_g_h_t_e_n )36.19207)
(= (Distance X_s_t_r_a_i_g_h_t_e_n X_p_a_g_e )36.19207)

(Path X_w_r_i_t_e X_t_h_r_o_n_e )
(Path X_t_h_r_o_n_e X_w_r_i_t_e )
(= (Distance X_w_r_i_t_e X_t_h_r_o_n_e )23.98183)
(= (Distance X_t_h_r_o_n_e X_w_r_i_t_e )23.98183)

(Path X_w_r_i_t_e X_g_a_t_e )
(Path X_g_a_t_e X_w_r_i_t_e )
(= (Distance X_w_r_i_t_e X_g_a_t_e )33.13337)
(= (Distance X_g_a_t_e X_w_r_i_t_e )33.13337)

(Path X_w_r_i_t_e X_e_x_e_m_p_t )
(Path X_e_x_e_m_p_t X_w_r_i_t_e )
(= (Distance X_w_r_i_t_e X_e_x_e_m_p_t )7.20385)
(= (Distance X_e_x_e_m_p_t X_w_r_i_t_e )7.20385)

(Path X_w_r_i_t_e X_b_r_a_k_e )
(Path X_b_r_a_k_e X_w_r_i_t_e )
(= (Distance X_w_r_i_t_e X_b_r_a_k_e )41.77994)
(= (Distance X_b_r_a_k_e X_w_r_i_t_e )41.77994)

(Path X_w_r_i_t_e X_t_o_o_l )
(Path X_t_o_o_l X_w_r_i_t_e )
(= (Distance X_w_r_i_t_e X_t_o_o_l )48.56249)
(= (Distance X_t_o_o_l X_w_r_i_t_e )48.56249)

(Path X_w_r_i_t_e X_d_i_p )
(Path X_d_i_p X_w_r_i_t_e )
(= (Distance X_w_r_i_t_e X_d_i_p )35.8036)
(= (Distance X_d_i_p X_w_r_i_t_e )35.8036)

(Path X_w_r_i_t_e X_r_e_n_t )
(Path X_r_e_n_t X_w_r_i_t_e )
(= (Distance X_w_r_i_t_e X_r_e_n_t )38.22179)
(= (Distance X_r_e_n_t X_w_r_i_t_e )38.22179)

(Path X_v_i_e_w X_f_o_r_g_e )
(Path X_f_o_r_g_e X_v_i_e_w )
(= (Distance X_v_i_e_w X_f_o_r_g_e )43.83219)
(= (Distance X_f_o_r_g_e X_v_i_e_w )43.83219)

(Path X_v_i_e_w X_d_i_a_l_o_g_u_e )
(Path X_d_i_a_l_o_g_u_e X_v_i_e_w )
(= (Distance X_v_i_e_w X_d_i_a_l_o_g_u_e )36.0206)
(= (Distance X_d_i_a_l_o_g_u_e X_v_i_e_w )36.0206)

(Path X_v_i_e_w X_i_m_p_o_s_t_e_r )
(Path X_i_m_p_o_s_t_e_r X_v_i_e_w )
(= (Distance X_v_i_e_w X_i_m_p_o_s_t_e_r )33.43374)
(= (Distance X_i_m_p_o_s_t_e_r X_v_i_e_w )33.43374)

(Path X_a_u_d_i_e_n_c_e X_a_s_s_u_m_e )
(Path X_a_s_s_u_m_e X_a_u_d_i_e_n_c_e )
(= (Distance X_a_u_d_i_e_n_c_e X_a_s_s_u_m_e )19.65265)
(= (Distance X_a_s_s_u_m_e X_a_u_d_i_e_n_c_e )19.65265)

(Path X_a_u_d_i_e_n_c_e X_r_e_s_p_e_c_t )
(Path X_r_e_s_p_e_c_t X_a_u_d_i_e_n_c_e )
(= (Distance X_a_u_d_i_e_n_c_e X_r_e_s_p_e_c_t )4.67262)
(= (Distance X_r_e_s_p_e_c_t X_a_u_d_i_e_n_c_e )4.67262)

(Path X_a_u_d_i_e_n_c_e X_c_l_a_s_s )
(Path X_c_l_a_s_s X_a_u_d_i_e_n_c_e )
(= (Distance X_a_u_d_i_e_n_c_e X_c_l_a_s_s )14.50464)
(= (Distance X_c_l_a_s_s X_a_u_d_i_e_n_c_e )14.50464)

(Path X_v_o_i_c_e X_f_i_n_a_n_c_i_a_l )
(Path X_f_i_n_a_n_c_i_a_l X_v_o_i_c_e )
(= (Distance X_v_o_i_c_e X_f_i_n_a_n_c_i_a_l )13.32913)
(= (Distance X_f_i_n_a_n_c_i_a_l X_v_o_i_c_e )13.32913)

(Path X_d_e_p_o_s_i_t X_h_o_n_o_r )
(Path X_h_o_n_o_r X_d_e_p_o_s_i_t )
(= (Distance X_d_e_p_o_s_i_t X_h_o_n_o_r )18.67052)
(= (Distance X_h_o_n_o_r X_d_e_p_o_s_i_t )18.67052)

(Path X_d_e_p_o_s_i_t X_s_i_g_n )
(Path X_s_i_g_n X_d_e_p_o_s_i_t )
(= (Distance X_d_e_p_o_s_i_t X_s_i_g_n )29.78419)
(= (Distance X_s_i_g_n X_d_e_p_o_s_i_t )29.78419)

(Path X_d_e_p_o_s_i_t X_s_u_n_r_i_s_e )
(Path X_s_u_n_r_i_s_e X_d_e_p_o_s_i_t )
(= (Distance X_d_e_p_o_s_i_t X_s_u_n_r_i_s_e )25.70004)
(= (Distance X_s_u_n_r_i_s_e X_d_e_p_o_s_i_t )25.70004)

(Path X_d_e_p_o_s_i_t X_i_m_p_o_s_t_e_r )
(Path X_i_m_p_o_s_t_e_r X_d_e_p_o_s_i_t )
(= (Distance X_d_e_p_o_s_i_t X_i_m_p_o_s_t_e_r )20.29062)
(= (Distance X_i_m_p_o_s_t_e_r X_d_e_p_o_s_i_t )20.29062)

(Path X_d_e_p_o_s_i_t X_s_w_e_a_r )
(Path X_s_w_e_a_r X_d_e_p_o_s_i_t )
(= (Distance X_d_e_p_o_s_i_t X_s_w_e_a_r )15.68439)
(= (Distance X_s_w_e_a_r X_d_e_p_o_s_i_t )15.68439)

(Path X_p_r_o_f_o_u_n_d X_f_i_n_a_n_c_i_a_l )
(Path X_f_i_n_a_n_c_i_a_l X_p_r_o_f_o_u_n_d )
(= (Distance X_p_r_o_f_o_u_n_d X_f_i_n_a_n_c_i_a_l )27.29882)
(= (Distance X_f_i_n_a_n_c_i_a_l X_p_r_o_f_o_u_n_d )27.29882)

(Path X_p_r_o_f_o_u_n_d X_f_o_r_t_u_n_e )
(Path X_f_o_r_t_u_n_e X_p_r_o_f_o_u_n_d )
(= (Distance X_p_r_o_f_o_u_n_d X_f_o_r_t_u_n_e )30.56509)
(= (Distance X_f_o_r_t_u_n_e X_p_r_o_f_o_u_n_d )30.56509)

(Path X_h_o_n_o_r X_e_x_c_l_u_s_i_v_e )
(Path X_e_x_c_l_u_s_i_v_e X_h_o_n_o_r )
(= (Distance X_h_o_n_o_r X_e_x_c_l_u_s_i_v_e )43.19992)
(= (Distance X_e_x_c_l_u_s_i_v_e X_h_o_n_o_r )43.19992)

(Path X_h_o_n_o_r X_n_a_t_i_o_n_a_l_i_s_t )
(Path X_n_a_t_i_o_n_a_l_i_s_t X_h_o_n_o_r )
(= (Distance X_h_o_n_o_r X_n_a_t_i_o_n_a_l_i_s_t )36.31441)
(= (Distance X_n_a_t_i_o_n_a_l_i_s_t X_h_o_n_o_r )36.31441)

(Path X_h_o_n_o_r X_r_o_b )
(Path X_r_o_b X_h_o_n_o_r )
(= (Distance X_h_o_n_o_r X_r_o_b )43.48569)
(= (Distance X_r_o_b X_h_o_n_o_r )43.48569)

(Path X_e_n_t_e_r X_m_y_s_t_e_r_y )
(Path X_m_y_s_t_e_r_y X_e_n_t_e_r )
(= (Distance X_e_n_t_e_r X_m_y_s_t_e_r_y )23.10318)
(= (Distance X_m_y_s_t_e_r_y X_e_n_t_e_r )23.10318)

(Path X_e_n_t_e_r X_a_u_t_o_n_o_m_y )
(Path X_a_u_t_o_n_o_m_y X_e_n_t_e_r )
(= (Distance X_e_n_t_e_r X_a_u_t_o_n_o_m_y )28.60341)
(= (Distance X_a_u_t_o_n_o_m_y X_e_n_t_e_r )28.60341)

(Path X_e_n_t_e_r X_c_o_a_s_t )
(Path X_c_o_a_s_t X_e_n_t_e_r )
(= (Distance X_e_n_t_e_r X_c_o_a_s_t )27.41495)
(= (Distance X_c_o_a_s_t X_e_n_t_e_r )27.41495)

(Path X_t_h_r_o_n_e X_a_p_p_r_o_v_a_l )
(Path X_a_p_p_r_o_v_a_l X_t_h_r_o_n_e )
(= (Distance X_t_h_r_o_n_e X_a_p_p_r_o_v_a_l )39.00512)
(= (Distance X_a_p_p_r_o_v_a_l X_t_h_r_o_n_e )39.00512)

(Path X_t_h_r_o_n_e X_m_y_s_t_e_r_y )
(Path X_m_y_s_t_e_r_y X_t_h_r_o_n_e )
(= (Distance X_t_h_r_o_n_e X_m_y_s_t_e_r_y )32.09385)
(= (Distance X_m_y_s_t_e_r_y X_t_h_r_o_n_e )32.09385)

(Path X_t_h_r_o_n_e X_i_n_t_e_r_a_c_t_i_v_e )
(Path X_i_n_t_e_r_a_c_t_i_v_e X_t_h_r_o_n_e )
(= (Distance X_t_h_r_o_n_e X_i_n_t_e_r_a_c_t_i_v_e )5.01841)
(= (Distance X_i_n_t_e_r_a_c_t_i_v_e X_t_h_r_o_n_e )5.01841)

(Path X_t_h_r_o_n_e X_s_t_r_o_k_e )
(Path X_s_t_r_o_k_e X_t_h_r_o_n_e )
(= (Distance X_t_h_r_o_n_e X_s_t_r_o_k_e )8.97419)
(= (Distance X_s_t_r_o_k_e X_t_h_r_o_n_e )8.97419)

(Path X_t_h_r_o_n_e X_s_h_y )
(Path X_s_h_y X_t_h_r_o_n_e )
(= (Distance X_t_h_r_o_n_e X_s_h_y )36.22675)
(= (Distance X_s_h_y X_t_h_r_o_n_e )36.22675)

(Path X_t_h_r_o_n_e X_i_m_p_o_s_t_e_r )
(Path X_i_m_p_o_s_t_e_r X_t_h_r_o_n_e )
(= (Distance X_t_h_r_o_n_e X_i_m_p_o_s_t_e_r )20.12817)
(= (Distance X_i_m_p_o_s_t_e_r X_t_h_r_o_n_e )20.12817)

(Path X_t_h_r_o_n_e X_v_e_g_e_t_a_r_i_a_n )
(Path X_v_e_g_e_t_a_r_i_a_n X_t_h_r_o_n_e )
(= (Distance X_t_h_r_o_n_e X_v_e_g_e_t_a_r_i_a_n )40.79112)
(= (Distance X_v_e_g_e_t_a_r_i_a_n X_t_h_r_o_n_e )40.79112)

(Path X_t_h_r_o_n_e X_s_t_r_e_s_s )
(Path X_s_t_r_e_s_s X_t_h_r_o_n_e )
(= (Distance X_t_h_r_o_n_e X_s_t_r_e_s_s )27.63794)
(= (Distance X_s_t_r_e_s_s X_t_h_r_o_n_e )27.63794)

(Path X_t_h_r_o_n_e X_r_e_n_t )
(Path X_r_e_n_t X_t_h_r_o_n_e )
(= (Distance X_t_h_r_o_n_e X_r_e_n_t )46.49633)
(= (Distance X_r_e_n_t X_t_h_r_o_n_e )46.49633)

(Path X_u_n_d_e_r_s_t_a_n_d X_s_e_i_z_e )
(Path X_s_e_i_z_e X_u_n_d_e_r_s_t_a_n_d )
(= (Distance X_u_n_d_e_r_s_t_a_n_d X_s_e_i_z_e )29.06677)
(= (Distance X_s_e_i_z_e X_u_n_d_e_r_s_t_a_n_d )29.06677)

(Path X_u_n_d_e_r_s_t_a_n_d X_f_i_g_u_r_e )
(Path X_f_i_g_u_r_e X_u_n_d_e_r_s_t_a_n_d )
(= (Distance X_u_n_d_e_r_s_t_a_n_d X_f_i_g_u_r_e )6.43129)
(= (Distance X_f_i_g_u_r_e X_u_n_d_e_r_s_t_a_n_d )6.43129)

(Path X_u_n_d_e_r_s_t_a_n_d X_p_a_i_n )
(Path X_p_a_i_n X_u_n_d_e_r_s_t_a_n_d )
(= (Distance X_u_n_d_e_r_s_t_a_n_d X_p_a_i_n )18.73991)
(= (Distance X_p_a_i_n X_u_n_d_e_r_s_t_a_n_d )18.73991)

(Path X_g_u_a_r_a_n_t_e_e X_c_e_r_t_a_i_n )
(Path X_c_e_r_t_a_i_n X_g_u_a_r_a_n_t_e_e )
(= (Distance X_g_u_a_r_a_n_t_e_e X_c_e_r_t_a_i_n )47.98661)
(= (Distance X_c_e_r_t_a_i_n X_g_u_a_r_a_n_t_e_e )47.98661)

(Path X_g_u_a_r_a_n_t_e_e X_b_u_f_f_e_t )
(Path X_b_u_f_f_e_t X_g_u_a_r_a_n_t_e_e )
(= (Distance X_g_u_a_r_a_n_t_e_e X_b_u_f_f_e_t )16.6186)
(= (Distance X_b_u_f_f_e_t X_g_u_a_r_a_n_t_e_e )16.6186)

(Path X_g_u_a_r_a_n_t_e_e X_f_o_r_t_u_n_e )
(Path X_f_o_r_t_u_n_e X_g_u_a_r_a_n_t_e_e )
(= (Distance X_g_u_a_r_a_n_t_e_e X_f_o_r_t_u_n_e )42.79064)
(= (Distance X_f_o_r_t_u_n_e X_g_u_a_r_a_n_t_e_e )42.79064)

(Path X_g_u_a_r_a_n_t_e_e X_d_i_a_l_o_g_u_e )
(Path X_d_i_a_l_o_g_u_e X_g_u_a_r_a_n_t_e_e )
(= (Distance X_g_u_a_r_a_n_t_e_e X_d_i_a_l_o_g_u_e )10.62576)
(= (Distance X_d_i_a_l_o_g_u_e X_g_u_a_r_a_n_t_e_e )10.62576)

(Path X_g_u_a_r_a_n_t_e_e X_g_a_l_l_o_n )
(Path X_g_a_l_l_o_n X_g_u_a_r_a_n_t_e_e )
(= (Distance X_g_u_a_r_a_n_t_e_e X_g_a_l_l_o_n )16.81861)
(= (Distance X_g_a_l_l_o_n X_g_u_a_r_a_n_t_e_e )16.81861)

(Path X_g_u_a_r_a_n_t_e_e X_b_i_t_t_e_r )
(Path X_b_i_t_t_e_r X_g_u_a_r_a_n_t_e_e )
(= (Distance X_g_u_a_r_a_n_t_e_e X_b_i_t_t_e_r )27.82699)
(= (Distance X_b_i_t_t_e_r X_g_u_a_r_a_n_t_e_e )27.82699)

(Path X_p_h_y_s_i_c_s X_a_s_s_i_g_n_m_e_n_t )
(Path X_a_s_s_i_g_n_m_e_n_t X_p_h_y_s_i_c_s )
(= (Distance X_p_h_y_s_i_c_s X_a_s_s_i_g_n_m_e_n_t )39.79372)
(= (Distance X_a_s_s_i_g_n_m_e_n_t X_p_h_y_s_i_c_s )39.79372)

(Path X_p_h_y_s_i_c_s X_b_i_t_t_e_r )
(Path X_b_i_t_t_e_r X_p_h_y_s_i_c_s )
(= (Distance X_p_h_y_s_i_c_s X_b_i_t_t_e_r )7.56397)
(= (Distance X_b_i_t_t_e_r X_p_h_y_s_i_c_s )7.56397)

(Path X_p_h_y_s_i_c_s X_s_t_r_e_s_s )
(Path X_s_t_r_e_s_s X_p_h_y_s_i_c_s )
(= (Distance X_p_h_y_s_i_c_s X_s_t_r_e_s_s )23.53033)
(= (Distance X_s_t_r_e_s_s X_p_h_y_s_i_c_s )23.53033)

(Path X_g_a_t_e X_a_p_p_r_o_v_a_l )
(Path X_a_p_p_r_o_v_a_l X_g_a_t_e )
(= (Distance X_g_a_t_e X_a_p_p_r_o_v_a_l )11.32391)
(= (Distance X_a_p_p_r_o_v_a_l X_g_a_t_e )11.32391)

(Path X_g_a_t_e X_m_y_s_t_e_r_y )
(Path X_m_y_s_t_e_r_y X_g_a_t_e )
(= (Distance X_g_a_t_e X_m_y_s_t_e_r_y )2.641)
(= (Distance X_m_y_s_t_e_r_y X_g_a_t_e )2.641)

(Path X_e_x_e_m_p_t X_i_n_j_e_c_t_i_o_n )
(Path X_i_n_j_e_c_t_i_o_n X_e_x_e_m_p_t )
(= (Distance X_e_x_e_m_p_t X_i_n_j_e_c_t_i_o_n )20.01798)
(= (Distance X_i_n_j_e_c_t_i_o_n X_e_x_e_m_p_t )20.01798)

(Path X_e_x_e_m_p_t X_a_s_s_u_m_e )
(Path X_a_s_s_u_m_e X_e_x_e_m_p_t )
(= (Distance X_e_x_e_m_p_t X_a_s_s_u_m_e )21.47677)
(= (Distance X_a_s_s_u_m_e X_e_x_e_m_p_t )21.47677)

(Path X_e_x_e_m_p_t X_r_e_s_p_e_c_t )
(Path X_r_e_s_p_e_c_t X_e_x_e_m_p_t )
(= (Distance X_e_x_e_m_p_t X_r_e_s_p_e_c_t )34.86224)
(= (Distance X_r_e_s_p_e_c_t X_e_x_e_m_p_t )34.86224)

(Path X_e_x_e_m_p_t X_s_h_y )
(Path X_s_h_y X_e_x_e_m_p_t )
(= (Distance X_e_x_e_m_p_t X_s_h_y )26.45128)
(= (Distance X_s_h_y X_e_x_e_m_p_t )26.45128)

(Path X_t_a_b_l_e_t X_c_i_g_a_r_e_t_t_e )
(Path X_c_i_g_a_r_e_t_t_e X_t_a_b_l_e_t )
(= (Distance X_t_a_b_l_e_t X_c_i_g_a_r_e_t_t_e )11.5679)
(= (Distance X_c_i_g_a_r_e_t_t_e X_t_a_b_l_e_t )11.5679)

(Path X_t_a_b_l_e_t X_i_r_o_n )
(Path X_i_r_o_n X_t_a_b_l_e_t )
(= (Distance X_t_a_b_l_e_t X_i_r_o_n )26.34121)
(= (Distance X_i_r_o_n X_t_a_b_l_e_t )26.34121)

(Path X_t_a_b_l_e_t X_r_o_b )
(Path X_r_o_b X_t_a_b_l_e_t )
(= (Distance X_t_a_b_l_e_t X_r_o_b )23.81701)
(= (Distance X_r_o_b X_t_a_b_l_e_t )23.81701)

(Path X_t_a_b_l_e_t X_g_a_l_l_o_n )
(Path X_g_a_l_l_o_n X_t_a_b_l_e_t )
(= (Distance X_t_a_b_l_e_t X_g_a_l_l_o_n )18.51271)
(= (Distance X_g_a_l_l_o_n X_t_a_b_l_e_t )18.51271)

(Path X_t_a_b_l_e_t X_s_h_y )
(Path X_s_h_y X_t_a_b_l_e_t )
(= (Distance X_t_a_b_l_e_t X_s_h_y )24.53525)
(= (Distance X_s_h_y X_t_a_b_l_e_t )24.53525)

(Path X_t_a_b_l_e_t X_s_w_e_a_r )
(Path X_s_w_e_a_r X_t_a_b_l_e_t )
(= (Distance X_t_a_b_l_e_t X_s_w_e_a_r )18.52515)
(= (Distance X_s_w_e_a_r X_t_a_b_l_e_t )18.52515)

(Path X_t_a_b_l_e_t X_s_t_r_e_s_s )
(Path X_s_t_r_e_s_s X_t_a_b_l_e_t )
(= (Distance X_t_a_b_l_e_t X_s_t_r_e_s_s )19.98177)
(= (Distance X_s_t_r_e_s_s X_t_a_b_l_e_t )19.98177)

(Path X_i_n_j_e_c_t_i_o_n X_e_x_c_l_u_s_i_v_e )
(Path X_e_x_c_l_u_s_i_v_e X_i_n_j_e_c_t_i_o_n )
(= (Distance X_i_n_j_e_c_t_i_o_n X_e_x_c_l_u_s_i_v_e )34.0278)
(= (Distance X_e_x_c_l_u_s_i_v_e X_i_n_j_e_c_t_i_o_n )34.0278)

(Path X_i_n_j_e_c_t_i_o_n X_a_s_s_u_m_e )
(Path X_a_s_s_u_m_e X_i_n_j_e_c_t_i_o_n )
(= (Distance X_i_n_j_e_c_t_i_o_n X_a_s_s_u_m_e )1.50117)
(= (Distance X_a_s_s_u_m_e X_i_n_j_e_c_t_i_o_n )1.50117)

(Path X_i_n_j_e_c_t_i_o_n X_r_e_s_p_e_c_t )
(Path X_r_e_s_p_e_c_t X_i_n_j_e_c_t_i_o_n )
(= (Distance X_i_n_j_e_c_t_i_o_n X_r_e_s_p_e_c_t )16.39243)
(= (Distance X_r_e_s_p_e_c_t X_i_n_j_e_c_t_i_o_n )16.39243)

(Path X_i_n_j_e_c_t_i_o_n X_i_n_t_e_r_a_c_t_i_v_e )
(Path X_i_n_t_e_r_a_c_t_i_v_e X_i_n_j_e_c_t_i_o_n )
(= (Distance X_i_n_j_e_c_t_i_o_n X_i_n_t_e_r_a_c_t_i_v_e )13.48994)
(= (Distance X_i_n_t_e_r_a_c_t_i_v_e X_i_n_j_e_c_t_i_o_n )13.48994)

(Path X_i_n_j_e_c_t_i_o_n X_f_i_g_u_r_e )
(Path X_f_i_g_u_r_e X_i_n_j_e_c_t_i_o_n )
(= (Distance X_i_n_j_e_c_t_i_o_n X_f_i_g_u_r_e )21.94159)
(= (Distance X_f_i_g_u_r_e X_i_n_j_e_c_t_i_o_n )21.94159)

(Path X_m_a_r_k_e_t X_m_y_s_t_e_r_y )
(Path X_m_y_s_t_e_r_y X_m_a_r_k_e_t )
(= (Distance X_m_a_r_k_e_t X_m_y_s_t_e_r_y )20.44576)
(= (Distance X_m_y_s_t_e_r_y X_m_a_r_k_e_t )20.44576)

(Path X_m_a_r_k_e_t X_f_i_g_u_r_e )
(Path X_f_i_g_u_r_e X_m_a_r_k_e_t )
(= (Distance X_m_a_r_k_e_t X_f_i_g_u_r_e )37.16794)
(= (Distance X_f_i_g_u_r_e X_m_a_r_k_e_t )37.16794)

(Path X_m_a_r_k_e_t X_s_h_y )
(Path X_s_h_y X_m_a_r_k_e_t )
(= (Distance X_m_a_r_k_e_t X_s_h_y )10.47225)
(= (Distance X_s_h_y X_m_a_r_k_e_t )10.47225)

(Path X_m_a_r_k_e_t X_p_a_i_n )
(Path X_p_a_i_n X_m_a_r_k_e_t )
(= (Distance X_m_a_r_k_e_t X_p_a_i_n )50.81029)
(= (Distance X_p_a_i_n X_m_a_r_k_e_t )50.81029)

(Path X_m_a_r_k_e_t X_s_t_r_e_s_s )
(Path X_s_t_r_e_s_s X_m_a_r_k_e_t )
(= (Distance X_m_a_r_k_e_t X_s_t_r_e_s_s )40.65652)
(= (Distance X_s_t_r_e_s_s X_m_a_r_k_e_t )40.65652)

(Path X_m_a_r_k_e_t X_c_h_a_i_r )
(Path X_c_h_a_i_r X_m_a_r_k_e_t )
(= (Distance X_m_a_r_k_e_t X_c_h_a_i_r )27.25708)
(= (Distance X_c_h_a_i_r X_m_a_r_k_e_t )27.25708)

(Path X_f_o_r_g_e X_w_i_n_n_e_r )
(Path X_w_i_n_n_e_r X_f_o_r_g_e )
(= (Distance X_f_o_r_g_e X_w_i_n_n_e_r )15.05164)
(= (Distance X_w_i_n_n_e_r X_f_o_r_g_e )15.05164)

(Path X_f_o_r_g_e X_t_o_l_e_r_a_t_e )
(Path X_t_o_l_e_r_a_t_e X_f_o_r_g_e )
(= (Distance X_f_o_r_g_e X_t_o_l_e_r_a_t_e )11.59334)
(= (Distance X_t_o_l_e_r_a_t_e X_f_o_r_g_e )11.59334)

(Path X_f_o_r_g_e X_v_e_g_e_t_a_r_i_a_n )
(Path X_v_e_g_e_t_a_r_i_a_n X_f_o_r_g_e )
(= (Distance X_f_o_r_g_e X_v_e_g_e_t_a_r_i_a_n )3.90391)
(= (Distance X_v_e_g_e_t_a_r_i_a_n X_f_o_r_g_e )3.90391)

(Path X_t_h_u_m_b X_n_a_t_i_o_n_a_l_i_s_t )
(Path X_n_a_t_i_o_n_a_l_i_s_t X_t_h_u_m_b )
(= (Distance X_t_h_u_m_b X_n_a_t_i_o_n_a_l_i_s_t )31.07775)
(= (Distance X_n_a_t_i_o_n_a_l_i_s_t X_t_h_u_m_b )31.07775)

(Path X_t_h_u_m_b X_g_a_l_l_o_n )
(Path X_g_a_l_l_o_n X_t_h_u_m_b )
(= (Distance X_t_h_u_m_b X_g_a_l_l_o_n )30.7533)
(= (Distance X_g_a_l_l_o_n X_t_h_u_m_b )30.7533)

(Path X_t_h_u_m_b X_b_a_n_a_n_a )
(Path X_b_a_n_a_n_a X_t_h_u_m_b )
(= (Distance X_t_h_u_m_b X_b_a_n_a_n_a )33.2609)
(= (Distance X_b_a_n_a_n_a X_t_h_u_m_b )33.2609)

(Path X_t_h_u_m_b X_e_n_h_a_n_c_e )
(Path X_e_n_h_a_n_c_e X_t_h_u_m_b )
(= (Distance X_t_h_u_m_b X_e_n_h_a_n_c_e )14.97085)
(= (Distance X_e_n_h_a_n_c_e X_t_h_u_m_b )14.97085)

(Path X_o_p_p_o_s_e_d X_c_e_r_t_a_i_n )
(Path X_c_e_r_t_a_i_n X_o_p_p_o_s_e_d )
(= (Distance X_o_p_p_o_s_e_d X_c_e_r_t_a_i_n )47.62294)
(= (Distance X_c_e_r_t_a_i_n X_o_p_p_o_s_e_d )47.62294)

(Path X_o_p_p_o_s_e_d X_a_p_p_r_o_v_a_l )
(Path X_a_p_p_r_o_v_a_l X_o_p_p_o_s_e_d )
(= (Distance X_o_p_p_o_s_e_d X_a_p_p_r_o_v_a_l )53.57931)
(= (Distance X_a_p_p_r_o_v_a_l X_o_p_p_o_s_e_d )53.57931)

(Path X_o_p_p_o_s_e_d X_b_u_f_f_e_t )
(Path X_b_u_f_f_e_t X_o_p_p_o_s_e_d )
(= (Distance X_o_p_p_o_s_e_d X_b_u_f_f_e_t )24.1255)
(= (Distance X_b_u_f_f_e_t X_o_p_p_o_s_e_d )24.1255)

(Path X_h_e_a_d_l_i_n_e X_r_o_b )
(Path X_r_o_b X_h_e_a_d_l_i_n_e )
(= (Distance X_h_e_a_d_l_i_n_e X_r_o_b )42.14399)
(= (Distance X_r_o_b X_h_e_a_d_l_i_n_e )42.14399)

(Path X_h_e_a_d_l_i_n_e X_s_h_i_v_e_r )
(Path X_s_h_i_v_e_r X_h_e_a_d_l_i_n_e )
(= (Distance X_h_e_a_d_l_i_n_e X_s_h_i_v_e_r )35.21393)
(= (Distance X_s_h_i_v_e_r X_h_e_a_d_l_i_n_e )35.21393)

(Path X_h_e_a_d_l_i_n_e X_m_a_t_u_r_e )
(Path X_m_a_t_u_r_e X_h_e_a_d_l_i_n_e )
(= (Distance X_h_e_a_d_l_i_n_e X_m_a_t_u_r_e )34.82624)
(= (Distance X_m_a_t_u_r_e X_h_e_a_d_l_i_n_e )34.82624)

(Path X_d_o_u_g_h X_f_i_n_a_n_c_i_a_l )
(Path X_f_i_n_a_n_c_i_a_l X_d_o_u_g_h )
(= (Distance X_d_o_u_g_h X_f_i_n_a_n_c_i_a_l )41.50778)
(= (Distance X_f_i_n_a_n_c_i_a_l X_d_o_u_g_h )41.50778)

(Path X_d_o_u_g_h X_t_o_o_l )
(Path X_t_o_o_l X_d_o_u_g_h )
(= (Distance X_d_o_u_g_h X_t_o_o_l )46.41429)
(= (Distance X_t_o_o_l X_d_o_u_g_h )46.41429)

(Path X_d_o_u_g_h X_l_i_n_g_e_r )
(Path X_l_i_n_g_e_r X_d_o_u_g_h )
(= (Distance X_d_o_u_g_h X_l_i_n_g_e_r )18.75041)
(= (Distance X_l_i_n_g_e_r X_d_o_u_g_h )18.75041)

(Path X_d_o_u_g_h X_e_n_h_a_n_c_e )
(Path X_e_n_h_a_n_c_e X_d_o_u_g_h )
(= (Distance X_d_o_u_g_h X_e_n_h_a_n_c_e )11.85113)
(= (Distance X_e_n_h_a_n_c_e X_d_o_u_g_h )11.85113)

(Path X_d_o_u_g_h X_c_o_a_s_t )
(Path X_c_o_a_s_t X_d_o_u_g_h )
(= (Distance X_d_o_u_g_h X_c_o_a_s_t )32.44939)
(= (Distance X_c_o_a_s_t X_d_o_u_g_h )32.44939)

(Path X_c_e_r_t_a_i_n X_t_h_i_r_s_t_y )
(Path X_t_h_i_r_s_t_y X_c_e_r_t_a_i_n )
(= (Distance X_c_e_r_t_a_i_n X_t_h_i_r_s_t_y )11.2971)
(= (Distance X_t_h_i_r_s_t_y X_c_e_r_t_a_i_n )11.2971)

(Path X_c_e_r_t_a_i_n X_r_o_m_a_n_t_i_c )
(Path X_r_o_m_a_n_t_i_c X_c_e_r_t_a_i_n )
(= (Distance X_c_e_r_t_a_i_n X_r_o_m_a_n_t_i_c )27.97869)
(= (Distance X_r_o_m_a_n_t_i_c X_c_e_r_t_a_i_n )27.97869)

(Path X_c_e_r_t_a_i_n X_s_u_n_r_i_s_e )
(Path X_s_u_n_r_i_s_e X_c_e_r_t_a_i_n )
(= (Distance X_c_e_r_t_a_i_n X_s_u_n_r_i_s_e )16.81421)
(= (Distance X_s_u_n_r_i_s_e X_c_e_r_t_a_i_n )16.81421)

(Path X_e_x_c_l_u_s_i_v_e X_b_u_f_f_e_t )
(Path X_b_u_f_f_e_t X_e_x_c_l_u_s_i_v_e )
(= (Distance X_e_x_c_l_u_s_i_v_e X_b_u_f_f_e_t )10.61936)
(= (Distance X_b_u_f_f_e_t X_e_x_c_l_u_s_i_v_e )10.61936)

(Path X_e_x_c_l_u_s_i_v_e X_s_i_g_n )
(Path X_s_i_g_n X_e_x_c_l_u_s_i_v_e )
(= (Distance X_e_x_c_l_u_s_i_v_e X_s_i_g_n )40.35574)
(= (Distance X_s_i_g_n X_e_x_c_l_u_s_i_v_e )40.35574)

(Path X_e_x_c_l_u_s_i_v_e X_i_n_t_e_r_a_c_t_i_v_e )
(Path X_i_n_t_e_r_a_c_t_i_v_e X_e_x_c_l_u_s_i_v_e )
(= (Distance X_e_x_c_l_u_s_i_v_e X_i_n_t_e_r_a_c_t_i_v_e )30.05579)
(= (Distance X_i_n_t_e_r_a_c_t_i_v_e X_e_x_c_l_u_s_i_v_e )30.05579)

(Path X_e_x_c_l_u_s_i_v_e X_c_l_a_s_s )
(Path X_c_l_a_s_s X_e_x_c_l_u_s_i_v_e )
(= (Distance X_e_x_c_l_u_s_i_v_e X_c_l_a_s_s )7.85818)
(= (Distance X_c_l_a_s_s X_e_x_c_l_u_s_i_v_e )7.85818)

(Path X_e_x_c_l_u_s_i_v_e X_d_i_p )
(Path X_d_i_p X_e_x_c_l_u_s_i_v_e )
(= (Distance X_e_x_c_l_u_s_i_v_e X_d_i_p )12.10973)
(= (Distance X_d_i_p X_e_x_c_l_u_s_i_v_e )12.10973)

(Path X_e_x_c_l_u_s_i_v_e X_s_w_e_a_r )
(Path X_s_w_e_a_r X_e_x_c_l_u_s_i_v_e )
(= (Distance X_e_x_c_l_u_s_i_v_e X_s_w_e_a_r )42.23838)
(= (Distance X_s_w_e_a_r X_e_x_c_l_u_s_i_v_e )42.23838)

(Path X_o_t_h_e_r X_a_p_p_r_o_v_a_l )
(Path X_a_p_p_r_o_v_a_l X_o_t_h_e_r )
(= (Distance X_o_t_h_e_r X_a_p_p_r_o_v_a_l )13.03754)
(= (Distance X_a_p_p_r_o_v_a_l X_o_t_h_e_r )13.03754)

(Path X_o_t_h_e_r X_p_i_g )
(Path X_p_i_g X_o_t_h_e_r )
(= (Distance X_o_t_h_e_r X_p_i_g )38.09427)
(= (Distance X_p_i_g X_o_t_h_e_r )38.09427)

(Path X_o_t_h_e_r X_s_w_e_a_r )
(Path X_s_w_e_a_r X_o_t_h_e_r )
(= (Distance X_o_t_h_e_r X_s_w_e_a_r )23.124)
(= (Distance X_s_w_e_a_r X_o_t_h_e_r )23.124)

(Path X_a_s_s_i_g_n_m_e_n_t X_w_i_n_n_e_r )
(Path X_w_i_n_n_e_r X_a_s_s_i_g_n_m_e_n_t )
(= (Distance X_a_s_s_i_g_n_m_e_n_t X_w_i_n_n_e_r )41.44121)
(= (Distance X_w_i_n_n_e_r X_a_s_s_i_g_n_m_e_n_t )41.44121)

(Path X_a_s_s_i_g_n_m_e_n_t X_t_o_o_l )
(Path X_t_o_o_l X_a_s_s_i_g_n_m_e_n_t )
(= (Distance X_a_s_s_i_g_n_m_e_n_t X_t_o_o_l )40.27218)
(= (Distance X_t_o_o_l X_a_s_s_i_g_n_m_e_n_t )40.27218)

(Path X_a_s_s_i_g_n_m_e_n_t X_b_a_n_a_n_a )
(Path X_b_a_n_a_n_a X_a_s_s_i_g_n_m_e_n_t )
(= (Distance X_a_s_s_i_g_n_m_e_n_t X_b_a_n_a_n_a )30.74052)
(= (Distance X_b_a_n_a_n_a X_a_s_s_i_g_n_m_e_n_t )30.74052)

(Path X_p_i_e_r X_l_a_k_e )
(Path X_l_a_k_e X_p_i_e_r )
(= (Distance X_p_i_e_r X_l_a_k_e )19.53346)
(= (Distance X_l_a_k_e X_p_i_e_r )19.53346)

(Path X_p_i_e_r X_i_m_p_o_s_t_e_r )
(Path X_i_m_p_o_s_t_e_r X_p_i_e_r )
(= (Distance X_p_i_e_r X_i_m_p_o_s_t_e_r )12.07909)
(= (Distance X_i_m_p_o_s_t_e_r X_p_i_e_r )12.07909)

(Path X_p_i_e_r X_s_h_i_v_e_r )
(Path X_s_h_i_v_e_r X_p_i_e_r )
(= (Distance X_p_i_e_r X_s_h_i_v_e_r )31.31679)
(= (Distance X_s_h_i_v_e_r X_p_i_e_r )31.31679)

(Path X_p_i_e_r X_c_o_a_s_t )
(Path X_c_o_a_s_t X_p_i_e_r )
(= (Distance X_p_i_e_r X_c_o_a_s_t )29.01435)
(= (Distance X_c_o_a_s_t X_p_i_e_r )29.01435)

(Path X_b_r_a_k_e X_m_a_t_u_r_e )
(Path X_m_a_t_u_r_e X_b_r_a_k_e )
(= (Distance X_b_r_a_k_e X_m_a_t_u_r_e )18.57655)
(= (Distance X_m_a_t_u_r_e X_b_r_a_k_e )18.57655)

(Path X_b_r_a_k_e X_c_h_a_i_r )
(Path X_c_h_a_i_r X_b_r_a_k_e )
(= (Distance X_b_r_a_k_e X_c_h_a_i_r )21.37647)
(= (Distance X_c_h_a_i_r X_b_r_a_k_e )21.37647)

(Path X_n_a_t_i_o_n_a_l_i_s_t X_s_h_y )
(Path X_s_h_y X_n_a_t_i_o_n_a_l_i_s_t )
(= (Distance X_n_a_t_i_o_n_a_l_i_s_t X_s_h_y )1.20853)
(= (Distance X_s_h_y X_n_a_t_i_o_n_a_l_i_s_t )1.20853)

(Path X_n_a_t_i_o_n_a_l_i_s_t X_d_i_p )
(Path X_d_i_p X_n_a_t_i_o_n_a_l_i_s_t )
(= (Distance X_n_a_t_i_o_n_a_l_i_s_t X_d_i_p )27.07932)
(= (Distance X_d_i_p X_n_a_t_i_o_n_a_l_i_s_t )27.07932)

(Path X_a_p_p_r_o_v_a_l X_m_y_s_t_e_r_y )
(Path X_m_y_s_t_e_r_y X_a_p_p_r_o_v_a_l )
(= (Distance X_a_p_p_r_o_v_a_l X_m_y_s_t_e_r_y )13.88824)
(= (Distance X_m_y_s_t_e_r_y X_a_p_p_r_o_v_a_l )13.88824)

(Path X_w_i_n_n_e_r X_s_o_l_v_e )
(Path X_s_o_l_v_e X_w_i_n_n_e_r )
(= (Distance X_w_i_n_n_e_r X_s_o_l_v_e )20.99054)
(= (Distance X_s_o_l_v_e X_w_i_n_n_e_r )20.99054)

(Path X_t_h_i_r_s_t_y X_t_o_l_e_r_a_t_e )
(Path X_t_o_l_e_r_a_t_e X_t_h_i_r_s_t_y )
(= (Distance X_t_h_i_r_s_t_y X_t_o_l_e_r_a_t_e )47.62088)
(= (Distance X_t_o_l_e_r_a_t_e X_t_h_i_r_s_t_y )47.62088)

(Path X_t_h_i_r_s_t_y X_s_t_r_o_k_e )
(Path X_s_t_r_o_k_e X_t_h_i_r_s_t_y )
(= (Distance X_t_h_i_r_s_t_y X_s_t_r_o_k_e )13.80367)
(= (Distance X_s_t_r_o_k_e X_t_h_i_r_s_t_y )13.80367)

(Path X_t_h_i_r_s_t_y X_s_t_r_a_i_g_h_t_e_n )
(Path X_s_t_r_a_i_g_h_t_e_n X_t_h_i_r_s_t_y )
(= (Distance X_t_h_i_r_s_t_y X_s_t_r_a_i_g_h_t_e_n )28.81125)
(= (Distance X_s_t_r_a_i_g_h_t_e_n X_t_h_i_r_s_t_y )28.81125)

(Path X_c_i_g_a_r_e_t_t_e X_t_o_l_e_r_a_t_e )
(Path X_t_o_l_e_r_a_t_e X_c_i_g_a_r_e_t_t_e )
(= (Distance X_c_i_g_a_r_e_t_t_e X_t_o_l_e_r_a_t_e )49.90808)
(= (Distance X_t_o_l_e_r_a_t_e X_c_i_g_a_r_e_t_t_e )49.90808)

(Path X_c_i_g_a_r_e_t_t_e X_d_e_m_a_n_d )
(Path X_d_e_m_a_n_d X_c_i_g_a_r_e_t_t_e )
(= (Distance X_c_i_g_a_r_e_t_t_e X_d_e_m_a_n_d )18.28925)
(= (Distance X_d_e_m_a_n_d X_c_i_g_a_r_e_t_t_e )18.28925)

(Path X_c_i_g_a_r_e_t_t_e X_v_e_g_e_t_a_r_i_a_n )
(Path X_v_e_g_e_t_a_r_i_a_n X_c_i_g_a_r_e_t_t_e )
(= (Distance X_c_i_g_a_r_e_t_t_e X_v_e_g_e_t_a_r_i_a_n )38.74635)
(= (Distance X_v_e_g_e_t_a_r_i_a_n X_c_i_g_a_r_e_t_t_e )38.74635)

(Path X_b_u_f_f_e_t X_m_a_t_u_r_e )
(Path X_m_a_t_u_r_e X_b_u_f_f_e_t )
(= (Distance X_b_u_f_f_e_t X_m_a_t_u_r_e )18.15749)
(= (Distance X_m_a_t_u_r_e X_b_u_f_f_e_t )18.15749)

(Path X_b_u_f_f_e_t X_s_t_r_a_i_g_h_t_e_n )
(Path X_s_t_r_a_i_g_h_t_e_n X_b_u_f_f_e_t )
(= (Distance X_b_u_f_f_e_t X_s_t_r_a_i_g_h_t_e_n )31.01498)
(= (Distance X_s_t_r_a_i_g_h_t_e_n X_b_u_f_f_e_t )31.01498)

(Path X_a_s_s_u_m_e X_l_e_g_i_s_l_a_t_i_o_n )
(Path X_l_e_g_i_s_l_a_t_i_o_n X_a_s_s_u_m_e )
(= (Distance X_a_s_s_u_m_e X_l_e_g_i_s_l_a_t_i_o_n )33.73934)
(= (Distance X_l_e_g_i_s_l_a_t_i_o_n X_a_s_s_u_m_e )33.73934)

(Path X_a_s_s_u_m_e X_s_o_l_v_e )
(Path X_s_o_l_v_e X_a_s_s_u_m_e )
(= (Distance X_a_s_s_u_m_e X_s_o_l_v_e )35.84609)
(= (Distance X_s_o_l_v_e X_a_s_s_u_m_e )35.84609)

(Path X_a_s_s_u_m_e X_s_u_n_r_i_s_e )
(Path X_s_u_n_r_i_s_e X_a_s_s_u_m_e )
(= (Distance X_a_s_s_u_m_e X_s_u_n_r_i_s_e )28.95621)
(= (Distance X_s_u_n_r_i_s_e X_a_s_s_u_m_e )28.95621)

(Path X_m_y_s_t_e_r_y X_d_e_m_a_n_d )
(Path X_d_e_m_a_n_d X_m_y_s_t_e_r_y )
(= (Distance X_m_y_s_t_e_r_y X_d_e_m_a_n_d )33.24413)
(= (Distance X_d_e_m_a_n_d X_m_y_s_t_e_r_y )33.24413)

(Path X_m_y_s_t_e_r_y X_s_t_r_e_s_s )
(Path X_s_t_r_e_s_s X_m_y_s_t_e_r_y )
(= (Distance X_m_y_s_t_e_r_y X_s_t_r_e_s_s )20.2422)
(= (Distance X_s_t_r_e_s_s X_m_y_s_t_e_r_y )20.2422)

(Path X_m_y_s_t_e_r_y X_c_h_a_i_r )
(Path X_c_h_a_i_r X_m_y_s_t_e_r_y )
(= (Distance X_m_y_s_t_e_r_y X_c_h_a_i_r )10.86373)
(= (Distance X_c_h_a_i_r X_m_y_s_t_e_r_y )10.86373)

(Path X_a_u_t_o_n_o_m_y X_g_l_a_s_s_e_s )
(Path X_g_l_a_s_s_e_s X_a_u_t_o_n_o_m_y )
(= (Distance X_a_u_t_o_n_o_m_y X_g_l_a_s_s_e_s )26.03404)
(= (Distance X_g_l_a_s_s_e_s X_a_u_t_o_n_o_m_y )26.03404)

(Path X_j_u_d_i_c_i_a_l X_c_l_a_s_s )
(Path X_c_l_a_s_s X_j_u_d_i_c_i_a_l )
(= (Distance X_j_u_d_i_c_i_a_l X_c_l_a_s_s )20.45455)
(= (Distance X_c_l_a_s_s X_j_u_d_i_c_i_a_l )20.45455)

(Path X_j_u_d_i_c_i_a_l X_g_l_a_s_s_e_s )
(Path X_g_l_a_s_s_e_s X_j_u_d_i_c_i_a_l )
(= (Distance X_j_u_d_i_c_i_a_l X_g_l_a_s_s_e_s )7.55734)
(= (Distance X_g_l_a_s_s_e_s X_j_u_d_i_c_i_a_l )7.55734)

(Path X_j_u_d_i_c_i_a_l X_b_a_n_a_n_a )
(Path X_b_a_n_a_n_a X_j_u_d_i_c_i_a_l )
(= (Distance X_j_u_d_i_c_i_a_l X_b_a_n_a_n_a )13.05521)
(= (Distance X_b_a_n_a_n_a X_j_u_d_i_c_i_a_l )13.05521)

(Path X_j_u_d_i_c_i_a_l X_s_w_e_a_r )
(Path X_s_w_e_a_r X_j_u_d_i_c_i_a_l )
(= (Distance X_j_u_d_i_c_i_a_l X_s_w_e_a_r )43.85033)
(= (Distance X_s_w_e_a_r X_j_u_d_i_c_i_a_l )43.85033)

(Path X_i_r_o_n X_c_l_a_s_s )
(Path X_c_l_a_s_s X_i_r_o_n )
(= (Distance X_i_r_o_n X_c_l_a_s_s )23.05307)
(= (Distance X_c_l_a_s_s X_i_r_o_n )23.05307)

(Path X_i_r_o_n X_w_a_r_d )
(Path X_w_a_r_d X_i_r_o_n )
(= (Distance X_i_r_o_n X_w_a_r_d )50.50955)
(= (Distance X_w_a_r_d X_i_r_o_n )50.50955)

(Path X_i_r_o_n X_c_h_a_i_r )
(Path X_c_h_a_i_r X_i_r_o_n )
(= (Distance X_i_r_o_n X_c_h_a_i_r )41.12012)
(= (Distance X_c_h_a_i_r X_i_r_o_n )41.12012)

(Path X_r_e_s_p_e_c_t X_f_i_n_a_n_c_i_a_l )
(Path X_f_i_n_a_n_c_i_a_l X_r_e_s_p_e_c_t )
(= (Distance X_r_e_s_p_e_c_t X_f_i_n_a_n_c_i_a_l )3.45681)
(= (Distance X_f_i_n_a_n_c_i_a_l X_r_e_s_p_e_c_t )3.45681)

(Path X_r_e_s_p_e_c_t X_b_i_t_t_e_r )
(Path X_b_i_t_t_e_r X_r_e_s_p_e_c_t )
(= (Distance X_r_e_s_p_e_c_t X_b_i_t_t_e_r )5.66005)
(= (Distance X_b_i_t_t_e_r X_r_e_s_p_e_c_t )5.66005)

(Path X_r_e_s_p_e_c_t X_e_n_h_a_n_c_e )
(Path X_e_n_h_a_n_c_e X_r_e_s_p_e_c_t )
(= (Distance X_r_e_s_p_e_c_t X_e_n_h_a_n_c_e )26.30508)
(= (Distance X_e_n_h_a_n_c_e X_r_e_s_p_e_c_t )26.30508)

(Path X_r_e_s_p_e_c_t X_r_e_n_t )
(Path X_r_e_n_t X_r_e_s_p_e_c_t )
(= (Distance X_r_e_s_p_e_c_t X_r_e_n_t )44.8043)
(= (Distance X_r_e_n_t X_r_e_s_p_e_c_t )44.8043)

(Path X_r_o_m_a_n_t_i_c X_s_i_g_n )
(Path X_s_i_g_n X_r_o_m_a_n_t_i_c )
(= (Distance X_r_o_m_a_n_t_i_c X_s_i_g_n )7.71014)
(= (Distance X_s_i_g_n X_r_o_m_a_n_t_i_c )7.71014)

(Path X_r_o_m_a_n_t_i_c X_f_i_n_a_n_c_i_a_l )
(Path X_f_i_n_a_n_c_i_a_l X_r_o_m_a_n_t_i_c )
(= (Distance X_r_o_m_a_n_t_i_c X_f_i_n_a_n_c_i_a_l )35.28951)
(= (Distance X_f_i_n_a_n_c_i_a_l X_r_o_m_a_n_t_i_c )35.28951)

(Path X_r_o_m_a_n_t_i_c X_d_i_a_l_o_g_u_e )
(Path X_d_i_a_l_o_g_u_e X_r_o_m_a_n_t_i_c )
(= (Distance X_r_o_m_a_n_t_i_c X_d_i_a_l_o_g_u_e )18.92369)
(= (Distance X_d_i_a_l_o_g_u_e X_r_o_m_a_n_t_i_c )18.92369)

(Path X_r_o_m_a_n_t_i_c X_s_t_r_a_i_g_h_t_e_n )
(Path X_s_t_r_a_i_g_h_t_e_n X_r_o_m_a_n_t_i_c )
(= (Distance X_r_o_m_a_n_t_i_c X_s_t_r_a_i_g_h_t_e_n )6.37789)
(= (Distance X_s_t_r_a_i_g_h_t_e_n X_r_o_m_a_n_t_i_c )6.37789)

(Path X_t_o_l_e_r_a_t_e X_s_i_g_n )
(Path X_s_i_g_n X_t_o_l_e_r_a_t_e )
(= (Distance X_t_o_l_e_r_a_t_e X_s_i_g_n )30.78414)
(= (Distance X_s_i_g_n X_t_o_l_e_r_a_t_e )30.78414)

(Path X_t_o_l_e_r_a_t_e X_l_e_g_i_s_l_a_t_i_o_n )
(Path X_l_e_g_i_s_l_a_t_i_o_n X_t_o_l_e_r_a_t_e )
(= (Distance X_t_o_l_e_r_a_t_e X_l_e_g_i_s_l_a_t_i_o_n )44.09467)
(= (Distance X_l_e_g_i_s_l_a_t_i_o_n X_t_o_l_e_r_a_t_e )44.09467)

(Path X_t_o_l_e_r_a_t_e X_s_o_l_v_e )
(Path X_s_o_l_v_e X_t_o_l_e_r_a_t_e )
(= (Distance X_t_o_l_e_r_a_t_e X_s_o_l_v_e )17.60752)
(= (Distance X_s_o_l_v_e X_t_o_l_e_r_a_t_e )17.60752)

(Path X_t_o_l_e_r_a_t_e X_e_n_h_a_n_c_e )
(Path X_e_n_h_a_n_c_e X_t_o_l_e_r_a_t_e )
(= (Distance X_t_o_l_e_r_a_t_e X_e_n_h_a_n_c_e )47.32636)
(= (Distance X_e_n_h_a_n_c_e X_t_o_l_e_r_a_t_e )47.32636)

(Path X_s_i_g_n X_i_n_t_e_r_a_c_t_i_v_e )
(Path X_i_n_t_e_r_a_c_t_i_v_e X_s_i_g_n )
(= (Distance X_s_i_g_n X_i_n_t_e_r_a_c_t_i_v_e )47.14959)
(= (Distance X_i_n_t_e_r_a_c_t_i_v_e X_s_i_g_n )47.14959)

(Path X_s_i_g_n X_l_e_g_i_s_l_a_t_i_o_n )
(Path X_l_e_g_i_s_l_a_t_i_o_n X_s_i_g_n )
(= (Distance X_s_i_g_n X_l_e_g_i_s_l_a_t_i_o_n )13.97383)
(= (Distance X_l_e_g_i_s_l_a_t_i_o_n X_s_i_g_n )13.97383)

(Path X_s_i_g_n X_c_l_a_s_s )
(Path X_c_l_a_s_s X_s_i_g_n )
(= (Distance X_s_i_g_n X_c_l_a_s_s )32.92967)
(= (Distance X_c_l_a_s_s X_s_i_g_n )32.92967)

(Path X_s_i_g_n X_b_a_n_a_n_a )
(Path X_b_a_n_a_n_a X_s_i_g_n )
(= (Distance X_s_i_g_n X_b_a_n_a_n_a )23.52613)
(= (Distance X_b_a_n_a_n_a X_s_i_g_n )23.52613)

(Path X_p_i_g X_s_w_e_a_r )
(Path X_s_w_e_a_r X_p_i_g )
(= (Distance X_p_i_g X_s_w_e_a_r )19.68878)
(= (Distance X_s_w_e_a_r X_p_i_g )19.68878)

(Path X_p_i_g X_w_a_r_d )
(Path X_w_a_r_d X_p_i_g )
(= (Distance X_p_i_g X_w_a_r_d )26.53794)
(= (Distance X_w_a_r_d X_p_i_g )26.53794)

(Path X_p_i_g X_p_a_i_n )
(Path X_p_a_i_n X_p_i_g )
(= (Distance X_p_i_g X_p_a_i_n )13.11571)
(= (Distance X_p_a_i_n X_p_i_g )13.11571)

(Path X_p_i_g X_m_a_t_u_r_e )
(Path X_m_a_t_u_r_e X_p_i_g )
(= (Distance X_p_i_g X_m_a_t_u_r_e )10.66403)
(= (Distance X_m_a_t_u_r_e X_p_i_g )10.66403)

(Path X_f_i_n_a_n_c_i_a_l X_s_o_l_v_e )
(Path X_s_o_l_v_e X_f_i_n_a_n_c_i_a_l )
(= (Distance X_f_i_n_a_n_c_i_a_l X_s_o_l_v_e )33.27067)
(= (Distance X_s_o_l_v_e X_f_i_n_a_n_c_i_a_l )33.27067)

(Path X_f_i_n_a_n_c_i_a_l X_s_w_e_a_r )
(Path X_s_w_e_a_r X_f_i_n_a_n_c_i_a_l )
(= (Distance X_f_i_n_a_n_c_i_a_l X_s_w_e_a_r )32.06634)
(= (Distance X_s_w_e_a_r X_f_i_n_a_n_c_i_a_l )32.06634)

(Path X_f_i_n_a_n_c_i_a_l X_d_i_s_c_r_i_m_i_n_a_t_e )
(Path X_d_i_s_c_r_i_m_i_n_a_t_e X_f_i_n_a_n_c_i_a_l )
(= (Distance X_f_i_n_a_n_c_i_a_l X_d_i_s_c_r_i_m_i_n_a_t_e )18.40326)
(= (Distance X_d_i_s_c_r_i_m_i_n_a_t_e X_f_i_n_a_n_c_i_a_l )18.40326)

(Path X_l_e_g_i_s_l_a_t_i_o_n X_b_i_t_t_e_r )
(Path X_b_i_t_t_e_r X_l_e_g_i_s_l_a_t_i_o_n )
(= (Distance X_l_e_g_i_s_l_a_t_i_o_n X_b_i_t_t_e_r )35.83037)
(= (Distance X_b_i_t_t_e_r X_l_e_g_i_s_l_a_t_i_o_n )35.83037)

(Path X_l_e_g_i_s_l_a_t_i_o_n X_e_n_h_a_n_c_e )
(Path X_e_n_h_a_n_c_e X_l_e_g_i_s_l_a_t_i_o_n )
(= (Distance X_l_e_g_i_s_l_a_t_i_o_n X_e_n_h_a_n_c_e )18.53956)
(= (Distance X_e_n_h_a_n_c_e X_l_e_g_i_s_l_a_t_i_o_n )18.53956)

(Path X_c_l_a_s_s X_i_m_p_o_s_t_e_r )
(Path X_i_m_p_o_s_t_e_r X_c_l_a_s_s )
(= (Distance X_c_l_a_s_s X_i_m_p_o_s_t_e_r )40.85729)
(= (Distance X_i_m_p_o_s_t_e_r X_c_l_a_s_s )40.85729)

(Path X_c_l_a_s_s X_p_a_i_n )
(Path X_p_a_i_n X_c_l_a_s_s )
(= (Distance X_c_l_a_s_s X_p_a_i_n )23.44648)
(= (Distance X_p_a_i_n X_c_l_a_s_s )23.44648)

(Path X_c_l_a_s_s X_c_h_a_i_r )
(Path X_c_h_a_i_r X_c_l_a_s_s )
(= (Distance X_c_l_a_s_s X_c_h_a_i_r )18.07736)
(= (Distance X_c_h_a_i_r X_c_l_a_s_s )18.07736)

(Path X_g_l_a_s_s_e_s X_t_o_o_l )
(Path X_t_o_o_l X_g_l_a_s_s_e_s )
(= (Distance X_g_l_a_s_s_e_s X_t_o_o_l )17.19458)
(= (Distance X_t_o_o_l X_g_l_a_s_s_e_s )17.19458)

(Path X_g_l_a_s_s_e_s X_c_o_a_s_t )
(Path X_c_o_a_s_t X_g_l_a_s_s_e_s )
(= (Distance X_g_l_a_s_s_e_s X_c_o_a_s_t )22.67508)
(= (Distance X_c_o_a_s_t X_g_l_a_s_s_e_s )22.67508)

(Path X_t_o_o_l X_d_i_a_l_o_g_u_e )
(Path X_d_i_a_l_o_g_u_e X_t_o_o_l )
(= (Distance X_t_o_o_l X_d_i_a_l_o_g_u_e )14.01332)
(= (Distance X_d_i_a_l_o_g_u_e X_t_o_o_l )14.01332)

(Path X_t_o_o_l X_w_a_r_d )
(Path X_w_a_r_d X_t_o_o_l )
(= (Distance X_t_o_o_l X_w_a_r_d )43.33765)
(= (Distance X_w_a_r_d X_t_o_o_l )43.33765)

(Path X_l_a_k_e X_r_o_b )
(Path X_r_o_b X_l_a_k_e )
(= (Distance X_l_a_k_e X_r_o_b )25.03063)
(= (Distance X_r_o_b X_l_a_k_e )25.03063)

(Path X_l_a_k_e X_d_i_s_c_r_i_m_i_n_a_t_e )
(Path X_d_i_s_c_r_i_m_i_n_a_t_e X_l_a_k_e )
(= (Distance X_l_a_k_e X_d_i_s_c_r_i_m_i_n_a_t_e )7.09857)
(= (Distance X_d_i_s_c_r_i_m_i_n_a_t_e X_l_a_k_e )7.09857)

(Path X_f_o_r_t_u_n_e X_d_i_a_l_o_g_u_e )
(Path X_d_i_a_l_o_g_u_e X_f_o_r_t_u_n_e )
(= (Distance X_f_o_r_t_u_n_e X_d_i_a_l_o_g_u_e )40.93435)
(= (Distance X_d_i_a_l_o_g_u_e X_f_o_r_t_u_n_e )40.93435)

(Path X_f_o_r_t_u_n_e X_i_m_p_o_s_t_e_r )
(Path X_i_m_p_o_s_t_e_r X_f_o_r_t_u_n_e )
(= (Distance X_f_o_r_t_u_n_e X_i_m_p_o_s_t_e_r )10.19189)
(= (Distance X_i_m_p_o_s_t_e_r X_f_o_r_t_u_n_e )10.19189)

(Path X_s_u_n_r_i_s_e X_s_e_i_z_e )
(Path X_s_e_i_z_e X_s_u_n_r_i_s_e )
(= (Distance X_s_u_n_r_i_s_e X_s_e_i_z_e )32.42326)
(= (Distance X_s_e_i_z_e X_s_u_n_r_i_s_e )32.42326)

(Path X_s_u_n_r_i_s_e X_s_h_i_v_e_r )
(Path X_s_h_i_v_e_r X_s_u_n_r_i_s_e )
(= (Distance X_s_u_n_r_i_s_e X_s_h_i_v_e_r )41.24909)
(= (Distance X_s_h_i_v_e_r X_s_u_n_r_i_s_e )41.24909)

(Path X_l_i_n_g_e_r X_v_e_g_e_t_a_r_i_a_n )
(Path X_v_e_g_e_t_a_r_i_a_n X_l_i_n_g_e_r )
(= (Distance X_l_i_n_g_e_r X_v_e_g_e_t_a_r_i_a_n )42.99411)
(= (Distance X_v_e_g_e_t_a_r_i_a_n X_l_i_n_g_e_r )42.99411)

(Path X_l_i_n_g_e_r X_s_t_r_e_s_s )
(Path X_s_t_r_e_s_s X_l_i_n_g_e_r )
(= (Distance X_l_i_n_g_e_r X_s_t_r_e_s_s )35.64333)
(= (Distance X_s_t_r_e_s_s X_l_i_n_g_e_r )35.64333)

(Path X_l_i_n_g_e_r X_c_h_a_i_r )
(Path X_c_h_a_i_r X_l_i_n_g_e_r )
(= (Distance X_l_i_n_g_e_r X_c_h_a_i_r )39.92174)
(= (Distance X_c_h_a_i_r X_l_i_n_g_e_r )39.92174)

(Path X_r_o_b X_b_i_t_t_e_r )
(Path X_b_i_t_t_e_r X_r_o_b )
(= (Distance X_r_o_b X_b_i_t_t_e_r )20.01168)
(= (Distance X_b_i_t_t_e_r X_r_o_b )20.01168)

(Path X_r_o_b X_s_t_r_o_k_e )
(Path X_s_t_r_o_k_e X_r_o_b )
(= (Distance X_r_o_b X_s_t_r_o_k_e )23.08288)
(= (Distance X_s_t_r_o_k_e X_r_o_b )23.08288)

(Path X_g_a_l_l_o_n X_i_m_p_o_s_t_e_r )
(Path X_i_m_p_o_s_t_e_r X_g_a_l_l_o_n )
(= (Distance X_g_a_l_l_o_n X_i_m_p_o_s_t_e_r )40.8914)
(= (Distance X_i_m_p_o_s_t_e_r X_g_a_l_l_o_n )40.8914)

(Path X_s_e_i_z_e X_d_e_m_a_n_d )
(Path X_d_e_m_a_n_d X_s_e_i_z_e )
(= (Distance X_s_e_i_z_e X_d_e_m_a_n_d )42.62613)
(= (Distance X_d_e_m_a_n_d X_s_e_i_z_e )42.62613)

(Path X_s_e_i_z_e X_s_h_i_v_e_r )
(Path X_s_h_i_v_e_r X_s_e_i_z_e )
(= (Distance X_s_e_i_z_e X_s_h_i_v_e_r )33.95213)
(= (Distance X_s_h_i_v_e_r X_s_e_i_z_e )33.95213)

(Path X_s_e_i_z_e X_w_a_r_d )
(Path X_w_a_r_d X_s_e_i_z_e )
(= (Distance X_s_e_i_z_e X_w_a_r_d )32.77337)
(= (Distance X_w_a_r_d X_s_e_i_z_e )32.77337)

(Path X_s_e_i_z_e X_d_i_s_c_r_i_m_i_n_a_t_e )
(Path X_d_i_s_c_r_i_m_i_n_a_t_e X_s_e_i_z_e )
(= (Distance X_s_e_i_z_e X_d_i_s_c_r_i_m_i_n_a_t_e )36.61548)
(= (Distance X_d_i_s_c_r_i_m_i_n_a_t_e X_s_e_i_z_e )36.61548)

(Path X_s_e_i_z_e X_r_e_n_t )
(Path X_r_e_n_t X_s_e_i_z_e )
(= (Distance X_s_e_i_z_e X_r_e_n_t )18.00256)
(= (Distance X_r_e_n_t X_s_e_i_z_e )18.00256)

(Path X_f_i_g_u_r_e X_b_a_n_a_n_a )
(Path X_b_a_n_a_n_a X_f_i_g_u_r_e )
(= (Distance X_f_i_g_u_r_e X_b_a_n_a_n_a )12.5752)
(= (Distance X_b_a_n_a_n_a X_f_i_g_u_r_e )12.5752)

(Path X_s_t_r_o_k_e X_d_i_s_c_r_i_m_i_n_a_t_e )
(Path X_d_i_s_c_r_i_m_i_n_a_t_e X_s_t_r_o_k_e )
(= (Distance X_s_t_r_o_k_e X_d_i_s_c_r_i_m_i_n_a_t_e )9.59179)
(= (Distance X_d_i_s_c_r_i_m_i_n_a_t_e X_s_t_r_o_k_e )9.59179)

(Path X_s_h_y X_s_h_i_v_e_r )
(Path X_s_h_i_v_e_r X_s_h_y )
(= (Distance X_s_h_y X_s_h_i_v_e_r )34.04662)
(= (Distance X_s_h_i_v_e_r X_s_h_y )34.04662)

(Path X_d_i_p X_j_o_i_n_t )
(Path X_j_o_i_n_t X_d_i_p )
(= (Distance X_d_i_p X_j_o_i_n_t )5.33104)
(= (Distance X_j_o_i_n_t X_d_i_p )5.33104)

(Path X_d_i_p X_d_i_s_c_r_i_m_i_n_a_t_e )
(Path X_d_i_s_c_r_i_m_i_n_a_t_e X_d_i_p )
(= (Distance X_d_i_p X_d_i_s_c_r_i_m_i_n_a_t_e )20.40051)
(= (Distance X_d_i_s_c_r_i_m_i_n_a_t_e X_d_i_p )20.40051)

(Path X_i_m_p_o_s_t_e_r X_p_a_i_n )
(Path X_p_a_i_n X_i_m_p_o_s_t_e_r )
(= (Distance X_i_m_p_o_s_t_e_r X_p_a_i_n )29.78251)
(= (Distance X_p_a_i_n X_i_m_p_o_s_t_e_r )29.78251)

(Path X_i_m_p_o_s_t_e_r X_s_t_r_a_i_g_h_t_e_n )
(Path X_s_t_r_a_i_g_h_t_e_n X_i_m_p_o_s_t_e_r )
(= (Distance X_i_m_p_o_s_t_e_r X_s_t_r_a_i_g_h_t_e_n )39.5871)
(= (Distance X_s_t_r_a_i_g_h_t_e_n X_i_m_p_o_s_t_e_r )39.5871)

(Path X_d_e_m_a_n_d X_j_o_i_n_t )
(Path X_j_o_i_n_t X_d_e_m_a_n_d )
(= (Distance X_d_e_m_a_n_d X_j_o_i_n_t )14.83326)
(= (Distance X_j_o_i_n_t X_d_e_m_a_n_d )14.83326)

(Path X_d_e_m_a_n_d X_p_a_i_n )
(Path X_p_a_i_n X_d_e_m_a_n_d )
(= (Distance X_d_e_m_a_n_d X_p_a_i_n )5.67863)
(= (Distance X_p_a_i_n X_d_e_m_a_n_d )5.67863)

(Path X_e_n_h_a_n_c_e X_p_a_i_n )
(Path X_p_a_i_n X_e_n_h_a_n_c_e )
(= (Distance X_e_n_h_a_n_c_e X_p_a_i_n )30.54261)
(= (Distance X_p_a_i_n X_e_n_h_a_n_c_e )30.54261)

(Path X_e_n_h_a_n_c_e X_m_a_t_u_r_e )
(Path X_m_a_t_u_r_e X_e_n_h_a_n_c_e )
(= (Distance X_e_n_h_a_n_c_e X_m_a_t_u_r_e )28.28649)
(= (Distance X_m_a_t_u_r_e X_e_n_h_a_n_c_e )28.28649)

(Path X_s_w_e_a_r X_m_a_t_u_r_e )
(Path X_m_a_t_u_r_e X_s_w_e_a_r )
(= (Distance X_s_w_e_a_r X_m_a_t_u_r_e )30.0831)
(= (Distance X_m_a_t_u_r_e X_s_w_e_a_r )30.0831)

(Path X_s_w_e_a_r X_s_t_r_a_i_g_h_t_e_n )
(Path X_s_t_r_a_i_g_h_t_e_n X_s_w_e_a_r )
(= (Distance X_s_w_e_a_r X_s_t_r_a_i_g_h_t_e_n )27.40276)
(= (Distance X_s_t_r_a_i_g_h_t_e_n X_s_w_e_a_r )27.40276)

(Path X_j_o_i_n_t X_s_h_i_v_e_r )
(Path X_s_h_i_v_e_r X_j_o_i_n_t )
(= (Distance X_j_o_i_n_t X_s_h_i_v_e_r )7.06862)
(= (Distance X_s_h_i_v_e_r X_j_o_i_n_t )7.06862)

(Path X_s_h_i_v_e_r X_c_h_a_i_r )
(Path X_c_h_a_i_r X_s_h_i_v_e_r )
(= (Distance X_s_h_i_v_e_r X_c_h_a_i_r )29.35144)
(= (Distance X_c_h_a_i_r X_s_h_i_v_e_r )29.35144)

(Path X_p_a_i_n X_s_t_r_a_i_g_h_t_e_n )
(Path X_s_t_r_a_i_g_h_t_e_n X_p_a_i_n )
(= (Distance X_p_a_i_n X_s_t_r_a_i_g_h_t_e_n )45.98502)
(= (Distance X_s_t_r_a_i_g_h_t_e_n X_p_a_i_n )45.98502)

(Path X_c_o_a_s_t X_s_t_r_e_s_s )
(Path X_s_t_r_e_s_s X_c_o_a_s_t )
(= (Distance X_c_o_a_s_t X_s_t_r_e_s_s )15.02862)
(= (Distance X_s_t_r_e_s_s X_c_o_a_s_t )15.02862)

(Path X_s_t_r_e_s_s X_r_e_n_t )
(Path X_r_e_n_t X_s_t_r_e_s_s )
(= (Distance X_s_t_r_e_s_s X_r_e_n_t )39.63213)
(= (Distance X_r_e_n_t X_s_t_r_e_s_s )39.63213)

(EmptyHome X_s_h_y)
(EmptyHome X_s_w_e_a_r)
(EmptyHome X_d_o_u_g_h)
(EmptyHome X_p_a_i_n)
(EmptyHome X_b_u_f_f_e_t)
(EmptyHome X_l_i_n_g_e_r)
(EmptyHome X_c_i_r_c_u_l_a_t_i_o_n)
(EmptyHome X_c_l_a_s_s)
(EmptyHome X_n_a_t_i_o_n_a_l_i_s_t)
(EmptyHome X_t_o_o_l)
(EmptyHome X_h_o_n_o_r)
(EmptyHome X_p_r_i_s_o_n)
(EmptyHome X_i_m_p_o_s_t_e_r)
(EmptyHome X_g_u_a_r_a_n_t_e_e)
(EmptyHome X_e_x_c_l_u_s_i_v_e)
(EmptyHome X_o_t_h_e_r)
(EmptyHome X_r_o_b)
(EmptyHome X_s_u_n_r_i_s_e)
(EmptyHome X_v_o_i_c_e)
(EmptyHome X_w_i_n_n_e_r)
(EmptyHome X_v_e_g_e_t_a_r_i_a_n)
(EmptyHome X_t_o_l_e_r_a_t_e)
(EmptyHome X_l_a_k_e)
(EmptyHome X_h_e_a_d_l_i_n_e)
(EmptyHome X_t_h_r_o_n_e)
(EmptyHome X_s_e_i_z_e)
(EmptyHome X_g_l_a_s_s_e_s)
(EmptyHome X_p_a_p_e_r)
(EmptyHome X_t_a_b_l_e_t)
(EmptyHome X_l_e_g_i_s_l_a_t_i_o_n)
(EmptyHome X_e_n_t_e_r)
(EmptyHome X_e_n_h_a_n_c_e)
(EmptyHome X_q_u_a_l_i_t_y)
(EmptyHome X_i_n_j_u_r_y)
(EmptyHome X_b_i_t_t_e_r)
(EmptyHome X_d_i_p)
(EmptyHome X_p_a_g_e)
(EmptyHome X_m_y_s_t_e_r_y)
(EmptyHome X_f_i_g_u_r_e)
(EmptyHome X_a_u_t_o_n_o_m_y)
(EmptyHome X_l_i_k_e_l_y)
(EmptyHome X_d_e_m_a_n_d)
(EmptyHome X_o_u_t_p_u_t)
(EmptyHome X_t_h_u_m_b)
(EmptyHome X_c_i_g_a_r_e_t_t_e)
(EmptyHome X_b_r_a_k_e)
(EmptyHome X_f_i_n_a_n_c_i_a_l)
(EmptyHome X_t_i_t_l_e)
(EmptyHome X_k_i_n_g)
(EmptyHome X_s_i_g_n)
)

  ; The goal state describe what we desire to achieve
  (:goal (and
( Car_At X_p_a_c_e )
(not (EmptyHome X_s_h_y))
(not (EmptyHome X_s_w_e_a_r))
(not (EmptyHome X_d_o_u_g_h))
(not (EmptyHome X_p_a_i_n))
(not (EmptyHome X_b_u_f_f_e_t))
(not (EmptyHome X_l_i_n_g_e_r))
(not (EmptyHome X_c_i_r_c_u_l_a_t_i_o_n))
(not (EmptyHome X_c_l_a_s_s))
(not (EmptyHome X_n_a_t_i_o_n_a_l_i_s_t))
(not (EmptyHome X_t_o_o_l))
(not (EmptyHome X_h_o_n_o_r))
(not (EmptyHome X_p_r_i_s_o_n))
(not (EmptyHome X_i_m_p_o_s_t_e_r))
(not (EmptyHome X_g_u_a_r_a_n_t_e_e))
(not (EmptyHome X_e_x_c_l_u_s_i_v_e))
(not (EmptyHome X_o_t_h_e_r))
(not (EmptyHome X_r_o_b))
(not (EmptyHome X_s_u_n_r_i_s_e))
(not (EmptyHome X_v_o_i_c_e))
(not (EmptyHome X_w_i_n_n_e_r))
(not (EmptyHome X_v_e_g_e_t_a_r_i_a_n))
(not (EmptyHome X_t_o_l_e_r_a_t_e))
(not (EmptyHome X_l_a_k_e))
(not (EmptyHome X_h_e_a_d_l_i_n_e))
(not (EmptyHome X_t_h_r_o_n_e))
(not (EmptyHome X_s_e_i_z_e))
(not (EmptyHome X_g_l_a_s_s_e_s))
(not (EmptyHome X_p_a_p_e_r))
(not (EmptyHome X_t_a_b_l_e_t))
(not (EmptyHome X_l_e_g_i_s_l_a_t_i_o_n))
(not (EmptyHome X_e_n_t_e_r))
(not (EmptyHome X_e_n_h_a_n_c_e))
(not (EmptyHome X_q_u_a_l_i_t_y))
(not (EmptyHome X_i_n_j_u_r_y))
(not (EmptyHome X_b_i_t_t_e_r))
(not (EmptyHome X_d_i_p))
(not (EmptyHome X_p_a_g_e))
(not (EmptyHome X_m_y_s_t_e_r_y))
(not (EmptyHome X_f_i_g_u_r_e))
(not (EmptyHome X_a_u_t_o_n_o_m_y))
(not (EmptyHome X_l_i_k_e_l_y))
(not (EmptyHome X_d_e_m_a_n_d))
(not (EmptyHome X_o_u_t_p_u_t))
(not (EmptyHome X_t_h_u_m_b))
(not (EmptyHome X_c_i_g_a_r_e_t_t_e))
(not (EmptyHome X_b_r_a_k_e))
(not (EmptyHome X_f_i_n_a_n_c_i_a_l))
(not (EmptyHome X_t_i_t_l_e))
(not (EmptyHome X_k_i_n_g))
(not (EmptyHome X_s_i_g_n))
  ))
)